// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/UI/ArticleCategoryLabels
 * @description Localized labels and icons for every `ArticleCategory` value.
 */

import type { ArticleCategoryLabels, LanguageMap } from '../../types/index.js';
import { ArticleCategory } from '../../types/index.js';

/** Hebrew "Deep analysis" — shared across ARTICLE_TYPE_LABELS, RELATED_ANALYSIS_LABELS, and DEEP_ANALYSIS_LABELS */
export const HE_DEEP_ANALYSIS = 'ניתוח מעמיק';

export const ARTICLE_TYPE_LABELS: LanguageMap<ArticleCategoryLabels> = {
  en: {
    [ArticleCategory.WEEK_AHEAD]: 'Week Ahead',
    [ArticleCategory.MONTH_AHEAD]: 'Month Ahead',
    [ArticleCategory.QUARTER_AHEAD]: 'Quarter Ahead',
    [ArticleCategory.YEAR_AHEAD]: 'Year Ahead',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Week in Review',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Month in Review',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Quarter in Review',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Year in Review',
    [ArticleCategory.BREAKING_NEWS]: 'Breaking News',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Committee Activity',
    [ArticleCategory.MOTIONS]: 'Plenary Votes & Resolutions',
    [ArticleCategory.PROPOSITIONS]: 'Legislative Procedures',
    [ArticleCategory.TERM_OUTLOOK]: 'Term Outlook',
    [ArticleCategory.ELECTION_CYCLE]: 'Election Cycle',
    [ArticleCategory.DEEP_ANALYSIS]: 'Deep Analysis',
  },
  sv: {
    [ArticleCategory.WEEK_AHEAD]: 'Vecka Framåt',
    [ArticleCategory.MONTH_AHEAD]: 'Månad Framåt',
    [ArticleCategory.QUARTER_AHEAD]: 'Kvartal Framåt',
    [ArticleCategory.YEAR_AHEAD]: 'År Framåt',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Veckans Sammanfattning',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Månadens Sammanfattning',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Kvartalets Sammanfattning',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Årets Sammanfattning',
    [ArticleCategory.BREAKING_NEWS]: 'Senaste Nytt',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Utskottsverksamhet',
    [ArticleCategory.MOTIONS]: 'Omröstningar & Resolutioner',
    [ArticleCategory.PROPOSITIONS]: 'Lagstiftningsförfaranden',
    [ArticleCategory.TERM_OUTLOOK]: 'Mandatperiodens Utsikt',
    [ArticleCategory.ELECTION_CYCLE]: 'Valcykel',
    [ArticleCategory.DEEP_ANALYSIS]: 'Djupanalys',
  },
  da: {
    [ArticleCategory.WEEK_AHEAD]: 'Ugen Fremover',
    [ArticleCategory.MONTH_AHEAD]: 'Måneden Fremover',
    [ArticleCategory.QUARTER_AHEAD]: 'Kvartalet Fremover',
    [ArticleCategory.YEAR_AHEAD]: 'Året Fremover',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Ugens Overblik',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Månedens Overblik',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Kvartalets Overblik',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Årets Overblik',
    [ArticleCategory.BREAKING_NEWS]: 'Seneste Nyt',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Udvalgsaktivitet',
    [ArticleCategory.MOTIONS]: 'Plenar-afstemninger & Beslutninger',
    [ArticleCategory.PROPOSITIONS]: 'Lovgivningsprocedurer',
    [ArticleCategory.TERM_OUTLOOK]: 'Valgperiodens Udsigt',
    [ArticleCategory.ELECTION_CYCLE]: 'Valgcyklus',
    [ArticleCategory.DEEP_ANALYSIS]: 'Dybdeanalyse',
  },
  no: {
    [ArticleCategory.WEEK_AHEAD]: 'Uken Fremover',
    [ArticleCategory.MONTH_AHEAD]: 'Måneden Fremover',
    [ArticleCategory.QUARTER_AHEAD]: 'Kvartalet Fremover',
    [ArticleCategory.YEAR_AHEAD]: 'Året Fremover',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Ukens Oppsummering',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Månedens Oppsummering',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Kvartalets Oppsummering',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Årets Oppsummering',
    [ArticleCategory.BREAKING_NEWS]: 'Siste Nytt',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Komitéaktivitet',
    [ArticleCategory.MOTIONS]: 'Plenaravstemninger & Vedtak',
    [ArticleCategory.PROPOSITIONS]: 'Lovgivningsprosedyrer',
    [ArticleCategory.TERM_OUTLOOK]: 'Valgperiodens Utsikt',
    [ArticleCategory.ELECTION_CYCLE]: 'Valgsyklus',
    [ArticleCategory.DEEP_ANALYSIS]: 'Dybdeanalyse',
  },
  fi: {
    [ArticleCategory.WEEK_AHEAD]: 'Tuleva Viikko',
    [ArticleCategory.MONTH_AHEAD]: 'Tuleva Kuukausi',
    [ArticleCategory.QUARTER_AHEAD]: 'Tuleva Vuosineljännes',
    [ArticleCategory.YEAR_AHEAD]: 'Tuleva Vuosi',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Viikon Katsaus',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Kuukauden Katsaus',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Vuosineljänneksen Katsaus',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Vuoden Katsaus',
    [ArticleCategory.BREAKING_NEWS]: 'Uusimmat Uutiset',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Valiokuntatoiminta',
    [ArticleCategory.MOTIONS]: 'Täysistuntoäänestykset & Päätöslauselmat',
    [ArticleCategory.PROPOSITIONS]: 'Lainsäädäntömenettelyt',
    [ArticleCategory.TERM_OUTLOOK]: 'Vaalikauden Näkymät',
    [ArticleCategory.ELECTION_CYCLE]: 'Vaalisykli',
    [ArticleCategory.DEEP_ANALYSIS]: 'Syväanalyysi',
  },
  de: {
    [ArticleCategory.WEEK_AHEAD]: 'Woche Voraus',
    [ArticleCategory.MONTH_AHEAD]: 'Monat Voraus',
    [ArticleCategory.QUARTER_AHEAD]: 'Quartal Voraus',
    [ArticleCategory.YEAR_AHEAD]: 'Jahr Voraus',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Wochenrückblick',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Monatsrückblick',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Quartalsrückblick',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Jahresrückblick',
    [ArticleCategory.BREAKING_NEWS]: 'Eilmeldung',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Ausschusstätigkeit',
    [ArticleCategory.MOTIONS]: 'Plenar-Abstimmungen & Entschließungen',
    [ArticleCategory.PROPOSITIONS]: 'Gesetzgebungsverfahren',
    [ArticleCategory.TERM_OUTLOOK]: 'Wahlperioden-Ausblick',
    [ArticleCategory.ELECTION_CYCLE]: 'Wahlzyklus',
    [ArticleCategory.DEEP_ANALYSIS]: 'Tiefenanalyse',
  },
  fr: {
    [ArticleCategory.WEEK_AHEAD]: 'Semaine à Venir',
    [ArticleCategory.MONTH_AHEAD]: 'Mois à Venir',
    [ArticleCategory.QUARTER_AHEAD]: 'Trimestre à Venir',
    [ArticleCategory.YEAR_AHEAD]: 'Année à Venir',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Bilan de la Semaine',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Bilan du Mois',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Bilan du Trimestre',
    [ArticleCategory.YEAR_IN_REVIEW]: "Bilan de l'Année",
    [ArticleCategory.BREAKING_NEWS]: 'Dernières Nouvelles',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Travaux des Commissions',
    [ArticleCategory.MOTIONS]: 'Votes & Résolutions en Plénière',
    [ArticleCategory.PROPOSITIONS]: 'Procédures Législatives',
    [ArticleCategory.TERM_OUTLOOK]: 'Perspective de Législature',
    [ArticleCategory.ELECTION_CYCLE]: 'Cycle Électoral',
    [ArticleCategory.DEEP_ANALYSIS]: 'Analyse Approfondie',
  },
  es: {
    [ArticleCategory.WEEK_AHEAD]: 'Semana Próxima',
    [ArticleCategory.MONTH_AHEAD]: 'Mes Próximo',
    [ArticleCategory.QUARTER_AHEAD]: 'Trimestre Próximo',
    [ArticleCategory.YEAR_AHEAD]: 'Año Próximo',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Resumen de la Semana',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Resumen del Mes',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Resumen del Trimestre',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Resumen del Año',
    [ArticleCategory.BREAKING_NEWS]: 'Noticias de Última Hora',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Actividad de Comisiones',
    [ArticleCategory.MOTIONS]: 'Votaciones y Resoluciones Plenarias',
    [ArticleCategory.PROPOSITIONS]: 'Procedimientos Legislativos',
    [ArticleCategory.TERM_OUTLOOK]: 'Perspectiva de Legislatura',
    [ArticleCategory.ELECTION_CYCLE]: 'Ciclo Electoral',
    [ArticleCategory.DEEP_ANALYSIS]: 'Análisis Profundo',
  },
  nl: {
    [ArticleCategory.WEEK_AHEAD]: 'Week Vooruit',
    [ArticleCategory.MONTH_AHEAD]: 'Maand Vooruit',
    [ArticleCategory.QUARTER_AHEAD]: 'Kwartaal Vooruit',
    [ArticleCategory.YEAR_AHEAD]: 'Jaar Vooruit',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Weekoverzicht',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Maandoverzicht',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'Kwartaaloverzicht',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Jaaroverzicht',
    [ArticleCategory.BREAKING_NEWS]: 'Laatste Nieuws',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Commissieactiviteiten',
    [ArticleCategory.MOTIONS]: 'Plenaire Stemmingen & Resoluties',
    [ArticleCategory.PROPOSITIONS]: 'Wetgevingsprocedures',
    [ArticleCategory.TERM_OUTLOOK]: 'Zittingsperiode Vooruitzicht',
    [ArticleCategory.ELECTION_CYCLE]: 'Verkiezingscyclus',
    [ArticleCategory.DEEP_ANALYSIS]: 'Diepgaande Analyse',
  },
  ar: {
    [ArticleCategory.WEEK_AHEAD]: 'الأسبوع القادم',
    [ArticleCategory.MONTH_AHEAD]: 'الشهر القادم',
    [ArticleCategory.QUARTER_AHEAD]: 'الربع القادم',
    [ArticleCategory.YEAR_AHEAD]: 'العام القادم',
    [ArticleCategory.WEEK_IN_REVIEW]: 'مراجعة الأسبوع',
    [ArticleCategory.MONTH_IN_REVIEW]: 'مراجعة الشهر',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'مراجعة الربع',
    [ArticleCategory.YEAR_IN_REVIEW]: 'مراجعة العام',
    [ArticleCategory.BREAKING_NEWS]: 'أخبار عاجلة',
    [ArticleCategory.COMMITTEE_REPORTS]: 'نشاط اللجان',
    [ArticleCategory.MOTIONS]: 'التصويتات والقرارات العامة',
    [ArticleCategory.PROPOSITIONS]: 'الإجراءات التشريعية',
    [ArticleCategory.TERM_OUTLOOK]: 'آفاق الدورة البرلمانية',
    [ArticleCategory.ELECTION_CYCLE]: 'الدورة الانتخابية',
    [ArticleCategory.DEEP_ANALYSIS]: 'تحليل معمّق',
  },
  he: {
    [ArticleCategory.WEEK_AHEAD]: 'השבוע הקרוב',
    [ArticleCategory.MONTH_AHEAD]: 'החודש הקרוב',
    [ArticleCategory.QUARTER_AHEAD]: 'הרבעון הקרוב',
    [ArticleCategory.YEAR_AHEAD]: 'השנה הקרובה',
    [ArticleCategory.WEEK_IN_REVIEW]: 'סיכום השבוע',
    [ArticleCategory.MONTH_IN_REVIEW]: 'סיכום החודש',
    [ArticleCategory.QUARTER_IN_REVIEW]: 'סיכום הרבעון',
    [ArticleCategory.YEAR_IN_REVIEW]: 'סיכום השנה',
    [ArticleCategory.BREAKING_NEWS]: 'חדשות דחופות',
    [ArticleCategory.COMMITTEE_REPORTS]: 'פעילות ועדות',
    [ArticleCategory.MOTIONS]: 'הצבעות והחלטות מליאה',
    [ArticleCategory.PROPOSITIONS]: 'הליכי חקיקה',
    [ArticleCategory.TERM_OUTLOOK]: 'תחזית כהונה',
    [ArticleCategory.ELECTION_CYCLE]: 'מחזור בחירות',
    [ArticleCategory.DEEP_ANALYSIS]: HE_DEEP_ANALYSIS,
  },
  ja: {
    [ArticleCategory.WEEK_AHEAD]: '今週の予定',
    [ArticleCategory.MONTH_AHEAD]: '今月の予定',
    [ArticleCategory.QUARTER_AHEAD]: '四半期展望',
    [ArticleCategory.YEAR_AHEAD]: '年間展望',
    [ArticleCategory.WEEK_IN_REVIEW]: '週間レビュー',
    [ArticleCategory.MONTH_IN_REVIEW]: '月間レビュー',
    [ArticleCategory.QUARTER_IN_REVIEW]: '四半期レビュー',
    [ArticleCategory.YEAR_IN_REVIEW]: '年間レビュー',
    [ArticleCategory.BREAKING_NEWS]: '速報',
    [ArticleCategory.COMMITTEE_REPORTS]: '委員会活動',
    [ArticleCategory.MOTIONS]: '本会議投票・決議',
    [ArticleCategory.PROPOSITIONS]: '立法手続',
    [ArticleCategory.TERM_OUTLOOK]: '会期展望',
    [ArticleCategory.ELECTION_CYCLE]: '選挙サイクル',
    [ArticleCategory.DEEP_ANALYSIS]: '深層分析',
  },
  ko: {
    [ArticleCategory.WEEK_AHEAD]: '다음 주 일정',
    [ArticleCategory.MONTH_AHEAD]: '다음 달 일정',
    [ArticleCategory.QUARTER_AHEAD]: '분기 전망',
    [ArticleCategory.YEAR_AHEAD]: '연간 전망',
    [ArticleCategory.WEEK_IN_REVIEW]: '주간 리뷰',
    [ArticleCategory.MONTH_IN_REVIEW]: '월간 리뷰',
    [ArticleCategory.QUARTER_IN_REVIEW]: '분기 리뷰',
    [ArticleCategory.YEAR_IN_REVIEW]: '연간 리뷰',
    [ArticleCategory.BREAKING_NEWS]: '속보',
    [ArticleCategory.COMMITTEE_REPORTS]: '위원회 활동',
    [ArticleCategory.MOTIONS]: '본회의 투표 및 결의',
    [ArticleCategory.PROPOSITIONS]: '입법 절차',
    [ArticleCategory.TERM_OUTLOOK]: '의회 임기 전망',
    [ArticleCategory.ELECTION_CYCLE]: '선거 주기',
    [ArticleCategory.DEEP_ANALYSIS]: '심층 분석',
  },
  zh: {
    [ArticleCategory.WEEK_AHEAD]: '下周预告',
    [ArticleCategory.MONTH_AHEAD]: '下月预告',
    [ArticleCategory.QUARTER_AHEAD]: '季度展望',
    [ArticleCategory.YEAR_AHEAD]: '年度展望',
    [ArticleCategory.WEEK_IN_REVIEW]: '每周回顾',
    [ArticleCategory.MONTH_IN_REVIEW]: '每月回顾',
    [ArticleCategory.QUARTER_IN_REVIEW]: '季度回顾',
    [ArticleCategory.YEAR_IN_REVIEW]: '年度回顾',
    [ArticleCategory.BREAKING_NEWS]: '突发新闻',
    [ArticleCategory.COMMITTEE_REPORTS]: '委员会活动',
    [ArticleCategory.MOTIONS]: '全体投票与决议',
    [ArticleCategory.PROPOSITIONS]: '立法程序',
    [ArticleCategory.TERM_OUTLOOK]: '议会任期展望',
    [ArticleCategory.ELECTION_CYCLE]: '选举周期',
    [ArticleCategory.DEEP_ANALYSIS]: '深度分析',
  },
};

/** Emoji icons per article category */
export const ARTICLE_TYPE_ICONS: Readonly<Record<ArticleCategory, string>> = {
  [ArticleCategory.WEEK_AHEAD]: '📅',
  [ArticleCategory.MONTH_AHEAD]: '🗓️',
  [ArticleCategory.QUARTER_AHEAD]: '📊',
  [ArticleCategory.YEAR_AHEAD]: '🔭',
  [ArticleCategory.WEEK_IN_REVIEW]: '📋',
  [ArticleCategory.MONTH_IN_REVIEW]: '📰',
  [ArticleCategory.QUARTER_IN_REVIEW]: '📈',
  [ArticleCategory.YEAR_IN_REVIEW]: '🏛️',
  [ArticleCategory.BREAKING_NEWS]: '⚡',
  [ArticleCategory.COMMITTEE_REPORTS]: '📑',
  [ArticleCategory.MOTIONS]: '🗳️',
  [ArticleCategory.PROPOSITIONS]: '📜',
  [ArticleCategory.TERM_OUTLOOK]: '🔮',
  [ArticleCategory.ELECTION_CYCLE]: '🗳️',
  [ArticleCategory.DEEP_ANALYSIS]: '🔬',
};
