// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/* eslint-disable sonarjs/no-duplicate-string -- translations naturally repeat
   common labels (e.g., "Hjem", "Nyheter") across closely related languages
   like Norwegian / Danish; deduplicating across locales would couple them. */
// =============================================================================
// English — authoritative copy. All other locales fall back to these strings
// when a translation is not yet provided. Keep questions/answers concise so
// translation effort stays bounded and rich-result eligibility stays high.
// =============================================================================
const NEWS_INDEX_EN = {
    keywords: 'European Parliament, EU news, MEPs, plenary sessions, AI journalism, parliamentary intelligence, EU policy, Hack23',
    ogImageAlt: 'EU Parliament Monitor — AI-Disrupted Parliamentary Intelligence',
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'News',
    breadcrumbAriaLabel: 'Breadcrumb',
    faqHeading: 'Frequently asked questions',
    faqs: [
        {
            q: 'What is EU Parliament Monitor?',
            a: 'EU Parliament Monitor is an independent transparency platform that publishes daily AI-generated articles tracking the work of the European Parliament. It is built and operated by Hack23 AB and is not affiliated with the European Parliament.',
        },
        {
            q: 'Is this an official European Parliament site?',
            a: 'No. EU Parliament Monitor is independent journalism produced by Hack23 AB. Source data is fetched from the European Parliament Open Data Portal, but editorial decisions, AI prompts and analysis are wholly the responsibility of Hack23 AB.',
        },
        {
            q: 'How are the articles generated?',
            a: 'Each article is generated by a deterministic pipeline of AI agents that read EP Open Data, run analysis tools, and write a draft. Drafts are validated for factuality and accessibility before being published as static HTML on GitHub Pages.',
        },
        {
            q: 'In how many languages is the site available?',
            a: 'Articles and the site shell are available in 14 languages: English, Swedish, Danish, Norwegian, Finnish, German, French, Spanish, Dutch, Arabic, Hebrew, Japanese, Korean and Chinese.',
        },
        {
            q: 'Where does the underlying data come from?',
            a: 'All parliamentary data is fetched from the European Parliament Open Data Portal (data.europarl.europa.eu) via the open-source European Parliament MCP server published at github.com/Hack23/european-parliament-mcp.',
        },
        {
            q: 'How can I subscribe to updates?',
            a: 'A standards-compliant RSS 2.0 feed is published at rss.xml. The site is also fully static, so it can be archived, mirrored, or read offline at any time.',
        },
    ],
};
const SITEMAP_EN = {
    keywords: 'sitemap, EU Parliament Monitor, archive, news index, parliamentary articles, transparency, RSS, Hack23',
    ogImageAlt: 'EU Parliament Monitor — Site map of every published article',
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Sitemap',
    breadcrumbAriaLabel: 'Breadcrumb',
    faqHeading: 'About this sitemap',
    faqs: [
        {
            q: 'What is on this page?',
            a: 'This page lists every news article published by EU Parliament Monitor, grouped by category and topic, so that readers and search engines can find any piece of coverage in a single click.',
        },
        {
            q: 'How often is the sitemap regenerated?',
            a: 'The sitemap is rebuilt automatically every time a new article is published, which currently happens at least once per parliamentary working day.',
        },
        {
            q: 'Is there a machine-readable version?',
            a: 'Yes. A standards-compliant XML sitemap is published at sitemap.xml and a Schema.org CollectionPage with an embedded ItemList is included in this page for structured-data consumers.',
        },
        {
            q: 'Why are some articles missing in my language?',
            a: 'Every article is generated in 14 languages, but for very recent items the pipeline publishes English first and other languages within a few minutes. Refresh the page if a translation appears to be missing.',
        },
        {
            q: 'Can I link to a specific category?',
            a: 'Yes. Each category heading on this page has a stable id you can deep-link to. The sitemap.xml file additionally exposes every article URL with a lastmod timestamp for crawlers.',
        },
    ],
};
const PI_EN = {
    keywords: 'political intelligence, EU Parliament, OSINT, MEP analysis, coalition dynamics, voting patterns, EP open data, Hack23',
    ogImageAlt: 'EU Parliament Monitor — Political intelligence run archive',
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Political Intelligence',
    breadcrumbAriaLabel: 'Breadcrumb',
    faqHeading: 'About political intelligence runs',
    faqs: [
        {
            q: 'What is a political intelligence run?',
            a: 'A political intelligence run is a daily analytical workflow that pulls fresh data from the European Parliament Open Data Portal, executes a fixed set of MCP analysis tools, and produces both a markdown brief and a public news article.',
        },
        {
            q: 'Are the analyses peer-reviewed?',
            a: 'No. Analyses are produced by AI agents using deterministic prompts and published openly so that anyone can reproduce, fork, or contest the methodology. Source code, prompts and raw data are linked from every run card.',
        },
        {
            q: 'How frequently are runs executed?',
            a: 'At least once per European Parliament working day. Specialised runs (coalition fracture, MEP influence, legislative bottlenecks) execute on their own GitHub Actions schedules.',
        },
        {
            q: 'Where can I see the source code?',
            a: 'All workflow definitions, agent prompts, and analysis tooling are published at github.com/Hack23/euparliamentmonitor under the Apache 2.0 license. The MCP server itself is at github.com/Hack23/european-parliament-mcp.',
        },
        {
            q: 'Who writes the analysis?',
            a: 'The analysis is written by AI agents orchestrated by Hack23 AB. Editorial guardrails, prompts and tool whitelists are version-controlled and reviewed by humans before each release.',
        },
    ],
};
const NEWS_INDEX_OVERLAYS = {
    sv: {
        keywords: 'Europaparlamentet, EU-nyheter, ledamöter, plenarsessioner, AI-journalistik, parlamentarisk underrättelse, EU-politik, Hack23',
        breadcrumbHome: 'Hem',
        breadcrumbCurrent: 'Nyheter',
        breadcrumbAriaLabel: 'Brödsmulor',
        faqHeading: 'Vanliga frågor',
    },
    da: {
        breadcrumbHome: 'Hjem',
        breadcrumbCurrent: 'Nyheder',
        breadcrumbAriaLabel: 'Brødkrumme',
        faqHeading: 'Ofte stillede spørgsmål',
    },
    no: {
        breadcrumbHome: 'Hjem',
        breadcrumbCurrent: 'Nyheter',
        breadcrumbAriaLabel: 'Brødsmulesti',
        faqHeading: 'Ofte stilte spørsmål',
    },
    fi: {
        breadcrumbHome: 'Etusivu',
        breadcrumbCurrent: 'Uutiset',
        breadcrumbAriaLabel: 'Murupolku',
        faqHeading: 'Usein kysytyt kysymykset',
    },
    de: {
        keywords: 'Europäisches Parlament, EU-Nachrichten, Abgeordnete, Plenarsitzungen, KI-Journalismus, parlamentarische Aufklärung, EU-Politik, Hack23',
        breadcrumbHome: 'Startseite',
        breadcrumbCurrent: 'Nachrichten',
        breadcrumbAriaLabel: 'Brotkrümelnavigation',
        faqHeading: 'Häufig gestellte Fragen',
    },
    fr: {
        keywords: 'Parlement européen, actualités UE, députés européens, sessions plénières, journalisme IA, renseignement parlementaire, politique UE, Hack23',
        breadcrumbHome: 'Accueil',
        breadcrumbCurrent: 'Actualités',
        breadcrumbAriaLabel: "Fil d'Ariane",
        faqHeading: 'Questions fréquentes',
    },
    es: {
        keywords: 'Parlamento Europeo, noticias UE, eurodiputados, sesiones plenarias, periodismo con IA, inteligencia parlamentaria, política UE, Hack23',
        breadcrumbHome: 'Inicio',
        breadcrumbCurrent: 'Noticias',
        breadcrumbAriaLabel: 'Ruta de navegación',
        faqHeading: 'Preguntas frecuentes',
    },
    nl: {
        keywords: 'Europees Parlement, EU-nieuws, Europarlementariërs, plenaire vergaderingen, AI-journalistiek, parlementaire inlichtingen, EU-beleid, Hack23',
        breadcrumbHome: 'Startpagina',
        breadcrumbCurrent: 'Nieuws',
        breadcrumbAriaLabel: 'Kruimelpad',
        faqHeading: 'Veelgestelde vragen',
    },
    ar: {
        breadcrumbHome: 'الرئيسية',
        breadcrumbCurrent: 'الأخبار',
        breadcrumbAriaLabel: 'مسار التنقل',
        faqHeading: 'الأسئلة الشائعة',
    },
    he: {
        breadcrumbHome: 'דף הבית',
        breadcrumbCurrent: 'חדשות',
        breadcrumbAriaLabel: 'נתיב ניווט',
        faqHeading: 'שאלות נפוצות',
    },
    ja: {
        breadcrumbHome: 'ホーム',
        breadcrumbCurrent: 'ニュース',
        breadcrumbAriaLabel: 'パンくずリスト',
        faqHeading: 'よくある質問',
    },
    ko: {
        breadcrumbHome: '홈',
        breadcrumbCurrent: '뉴스',
        breadcrumbAriaLabel: '경로',
        faqHeading: '자주 묻는 질문',
    },
    zh: {
        breadcrumbHome: '首页',
        breadcrumbCurrent: '新闻',
        breadcrumbAriaLabel: '面包屑导航',
        faqHeading: '常见问题',
    },
};
const SITEMAP_OVERLAYS = {
    sv: {
        breadcrumbHome: 'Hem',
        breadcrumbCurrent: 'Webbplatskarta',
        breadcrumbAriaLabel: 'Brödsmulor',
        faqHeading: 'Om webbplatskartan',
    },
    da: {
        breadcrumbHome: 'Hjem',
        breadcrumbCurrent: 'Sitemap',
        breadcrumbAriaLabel: 'Brødkrumme',
        faqHeading: 'Om dette sitemap',
    },
    no: {
        breadcrumbHome: 'Hjem',
        breadcrumbCurrent: 'Nettstedskart',
        breadcrumbAriaLabel: 'Brødsmulesti',
        faqHeading: 'Om nettstedskartet',
    },
    fi: {
        breadcrumbHome: 'Etusivu',
        breadcrumbCurrent: 'Sivukartta',
        breadcrumbAriaLabel: 'Murupolku',
        faqHeading: 'Tietoa sivukartasta',
    },
    de: {
        breadcrumbHome: 'Startseite',
        breadcrumbCurrent: 'Seitenübersicht',
        breadcrumbAriaLabel: 'Brotkrümelnavigation',
        faqHeading: 'Über diese Seitenübersicht',
    },
    fr: {
        breadcrumbHome: 'Accueil',
        breadcrumbCurrent: 'Plan du site',
        breadcrumbAriaLabel: "Fil d'Ariane",
        faqHeading: 'À propos du plan du site',
    },
    es: {
        breadcrumbHome: 'Inicio',
        breadcrumbCurrent: 'Mapa del sitio',
        breadcrumbAriaLabel: 'Ruta de navegación',
        faqHeading: 'Acerca de este mapa del sitio',
    },
    nl: {
        breadcrumbHome: 'Startpagina',
        breadcrumbCurrent: 'Sitemap',
        breadcrumbAriaLabel: 'Kruimelpad',
        faqHeading: 'Over deze sitemap',
    },
    ar: {
        breadcrumbHome: 'الرئيسية',
        breadcrumbCurrent: 'خريطة الموقع',
        breadcrumbAriaLabel: 'مسار التنقل',
        faqHeading: 'حول خريطة الموقع',
    },
    he: {
        breadcrumbHome: 'דף הבית',
        breadcrumbCurrent: 'מפת אתר',
        breadcrumbAriaLabel: 'נתיב ניווט',
        faqHeading: 'אודות מפת האתר',
    },
    ja: {
        breadcrumbHome: 'ホーム',
        breadcrumbCurrent: 'サイトマップ',
        breadcrumbAriaLabel: 'パンくずリスト',
        faqHeading: 'サイトマップについて',
    },
    ko: {
        breadcrumbHome: '홈',
        breadcrumbCurrent: '사이트맵',
        breadcrumbAriaLabel: '경로',
        faqHeading: '사이트맵 안내',
    },
    zh: {
        breadcrumbHome: '首页',
        breadcrumbCurrent: '网站地图',
        breadcrumbAriaLabel: '面包屑导航',
        faqHeading: '关于本网站地图',
    },
};
const PI_OVERLAYS = {
    sv: {
        breadcrumbHome: 'Hem',
        breadcrumbCurrent: 'Politisk underrättelse',
        breadcrumbAriaLabel: 'Brödsmulor',
        faqHeading: 'Om körningarna',
    },
    da: {
        breadcrumbHome: 'Hjem',
        breadcrumbCurrent: 'Politisk efterretning',
        breadcrumbAriaLabel: 'Brødkrumme',
        faqHeading: 'Om kørslerne',
    },
    no: {
        breadcrumbHome: 'Hjem',
        breadcrumbCurrent: 'Politisk etterretning',
        breadcrumbAriaLabel: 'Brødsmulesti',
        faqHeading: 'Om kjøringene',
    },
    fi: {
        breadcrumbHome: 'Etusivu',
        breadcrumbCurrent: 'Poliittinen tiedustelu',
        breadcrumbAriaLabel: 'Murupolku',
        faqHeading: 'Tietoa ajoista',
    },
    de: {
        breadcrumbHome: 'Startseite',
        breadcrumbCurrent: 'Politische Aufklärung',
        breadcrumbAriaLabel: 'Brotkrümelnavigation',
        faqHeading: 'Über die Analyseläufe',
    },
    fr: {
        breadcrumbHome: 'Accueil',
        breadcrumbCurrent: 'Renseignement politique',
        breadcrumbAriaLabel: "Fil d'Ariane",
        faqHeading: "À propos des exécutions d'analyse",
    },
    es: {
        breadcrumbHome: 'Inicio',
        breadcrumbCurrent: 'Inteligencia política',
        breadcrumbAriaLabel: 'Ruta de navegación',
        faqHeading: 'Acerca de las ejecuciones',
    },
    nl: {
        breadcrumbHome: 'Startpagina',
        breadcrumbCurrent: 'Politieke inlichtingen',
        breadcrumbAriaLabel: 'Kruimelpad',
        faqHeading: 'Over de analyseruns',
    },
    ar: {
        breadcrumbHome: 'الرئيسية',
        breadcrumbCurrent: 'الاستخبارات السياسية',
        breadcrumbAriaLabel: 'مسار التنقل',
        faqHeading: 'حول عمليات التحليل',
    },
    he: {
        breadcrumbHome: 'דף הבית',
        breadcrumbCurrent: 'מודיעין פוליטי',
        breadcrumbAriaLabel: 'נתיב ניווט',
        faqHeading: 'אודות הרצות הניתוח',
    },
    ja: {
        breadcrumbHome: 'ホーム',
        breadcrumbCurrent: '政治インテリジェンス',
        breadcrumbAriaLabel: 'パンくずリスト',
        faqHeading: '解析実行について',
    },
    ko: {
        breadcrumbHome: '홈',
        breadcrumbCurrent: '정치 인텔리전스',
        breadcrumbAriaLabel: '경로',
        faqHeading: '분석 실행 안내',
    },
    zh: {
        breadcrumbHome: '首页',
        breadcrumbCurrent: '政治情报',
        breadcrumbAriaLabel: '面包屑导航',
        faqHeading: '关于分析运行',
    },
};
function applyOverlay(base, overlay) {
    if (!overlay)
        return base;
    return {
        keywords: overlay.keywords ?? base.keywords,
        ogImageAlt: overlay.ogImageAlt ?? base.ogImageAlt,
        breadcrumbHome: overlay.breadcrumbHome ?? base.breadcrumbHome,
        breadcrumbCurrent: overlay.breadcrumbCurrent ?? base.breadcrumbCurrent,
        breadcrumbAriaLabel: overlay.breadcrumbAriaLabel ?? base.breadcrumbAriaLabel,
        faqHeading: overlay.faqHeading ?? base.faqHeading,
        faqs: overlay.faqs ?? base.faqs,
    };
}
/**
 * Returns SEO copy for the news index page. Falls back to English.
 * @param lang - ISO 639-1 language code (e.g., `"en"`, `"de"`).
 * @returns A fully-populated {@link PageSeoCopy} record.
 */
export function getNewsIndexSeo(lang) {
    if (lang === 'en')
        return NEWS_INDEX_EN;
    return applyOverlay(NEWS_INDEX_EN, NEWS_INDEX_OVERLAYS[lang]);
}
/**
 * Returns SEO copy for the sitemap page. Falls back to English.
 * @param lang - ISO 639-1 language code (e.g., `"en"`, `"de"`).
 * @returns A fully-populated {@link PageSeoCopy} record.
 */
export function getSitemapSeo(lang) {
    if (lang === 'en')
        return SITEMAP_EN;
    return applyOverlay(SITEMAP_EN, SITEMAP_OVERLAYS[lang]);
}
/**
 * Returns SEO copy for the political-intelligence page. Falls back to English.
 * @param lang - ISO 639-1 language code (e.g., `"en"`, `"de"`).
 * @returns A fully-populated {@link PageSeoCopy} record.
 */
export function getPoliticalIntelligenceSeo(lang) {
    if (lang === 'en')
        return PI_EN;
    return applyOverlay(PI_EN, PI_OVERLAYS[lang]);
}
//# sourceMappingURL=seo-copy.js.map