// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Aggregator/ReaderGuide/RowsCore
 * @description Per-section translated reader-need / what-you'll-get rows
 * for the **core analysis sections** of the Reader Intelligence Guide —
 * Executive Brief, Synthesis, Significance, Coalitions/Voting,
 * Stakeholder Map, Economic Context, Scenarios, Risk, Actors/Forces,
 * Threat, Forward Projection, Electoral Arc. Pure data. Paired with
 * `./rows-extended.ts` (PESTLE, continuity, deep analysis,
 * supplementary intel, MCP reliability, quality reflection, and the
 * supplementary-intelligence appendix).
 */

import type { GuideRowData } from './rows-types.js';

export const READER_GUIDE_ROWS_CORE: Readonly<Record<string, GuideRowData>> = {
  'section-executive-brief': {
    need: {
      en: 'BLUF and editorial decisions',
      sv: 'BLUF och redaktionella beslut',
      da: 'BLUF og redaktionelle beslutninger',
      no: 'BLUF og redaksjonelle beslutninger',
      fi: 'BLUF ja toimitukselliset päätökset',
      de: 'BLUF und redaktionelle Entscheidungen',
      fr: 'BLUF et décisions éditoriales',
      es: 'BLUF y decisiones editoriales',
      nl: 'BLUF en redactionele beslissingen',
      ar: 'ملخص تنفيذي وقرارات تحريرية',
      he: 'תמצית ניהולית והחלטות עריכה',
      ja: 'BLUF と編集上の判断',
      ko: 'BLUF 및 편집 결정',
      zh: 'BLUF与编辑决策',
    },
    value: {
      en: 'fast answer to what happened, why it matters, who is accountable, and the next dated trigger',
      sv: 'snabbt svar på vad som hände, varför det spelar roll, vem som ansvarar och nästa daterade trigger',
      da: 'hurtigt svar på hvad der skete, hvorfor det er vigtigt, hvem der er ansvarlig, og den næste daterede trigger',
      no: 'raskt svar på hva som skjedde, hvorfor det betyr noe, hvem som er ansvarlig, og neste daterte trigger',
      fi: 'nopea vastaus siihen mitä tapahtui, miksi sillä on merkitystä, kuka on vastuussa ja seuraava päivätty laukaisin',
      de: 'schnelle Antwort auf was passiert ist, warum es wichtig ist, wer verantwortlich ist und der nächste terminierte Auslöser',
      fr: "réponse rapide à ce qui s'est passé, pourquoi c'est important, qui est responsable et le prochain déclencheur daté",
      es: 'respuesta rápida a qué sucedió, por qué importa, quién es responsable y el próximo evento programado',
      nl: 'snel antwoord op wat er gebeurde, waarom het belangrijk is, wie verantwoordelijk is en de volgende geplande trigger',
      ar: 'إجابة سريعة عما حدث، لماذا يهم، من المسؤول، والمحفز التالي المؤرخ',
      he: 'תשובה מהירה למה שקרה, למה זה חשוב, מי אחראי, והטריגר הבא',
      ja: '何が起きたか、なぜ重要か、誰が責任者か、次の予定トリガーへの即答',
      ko: '무슨 일이 있었는지, 왜 중요한지, 누가 책임지는지, 다음 예정된 트리거에 대한 빠른 답변',
      zh: '快速回答发生了什么、为何重要、谁负责以及下一个预定触发事件',
    },
  },
  'section-synthesis': {
    need: {
      en: 'Integrated thesis',
      sv: 'Integrerad tes',
      da: 'Integreret tese',
      no: 'Integrert tese',
      fi: 'Integroitu teesi',
      de: 'Integrierte These',
      fr: 'Thèse intégrée',
      es: 'Tesis integrada',
      nl: 'Geïntegreerde these',
      ar: 'أطروحة متكاملة',
      he: 'תזה משולבת',
      ja: '統合テーゼ',
      ko: '통합 논제',
      zh: '综合论点',
    },
    value: {
      en: 'the lead political reading that connects facts, actors, risks, and confidence',
      sv: 'den ledande politiska läsningen som kopplar samman fakta, aktörer, risker och förtroende',
      da: 'den ledende politiske læsning der forbinder fakta, aktører, risici og tillid',
      no: 'den ledende politiske lesningen som kobler sammen fakta, aktører, risikoer og tillit',
      fi: 'johtava poliittinen tulkinta, joka yhdistää faktat, toimijat, riskit ja luottamuksen',
      de: 'die führende politische Lesart, die Fakten, Akteure, Risiken und Vertrauen verbindet',
      fr: 'la lecture politique principale qui relie faits, acteurs, risques et confiance',
      es: 'la lectura política principal que conecta hechos, actores, riesgos y confianza',
      nl: "de leidende politieke lezing die feiten, actoren, risico's en vertrouwen verbindt",
      ar: 'القراءة السياسية الرائدة التي تربط الحقائق والفاعلين والمخاطر والثقة',
      he: 'הקריאה הפוליטית המובילה שמחברת עובדות, שחקנים, סיכונים ואמון',
      ja: '事実、アクター、リスク、信頼を結びつける主要な政治的解釈',
      ko: '사실, 행위자, 위험 및 신뢰를 연결하는 주요 정치적 해석',
      zh: '将事实、行动者、风险和信心联系起来的主要政治解读',
    },
  },
  'section-significance': {
    need: {
      en: 'Significance scoring',
      sv: 'Betydelsepoäng',
      da: 'Betydningsvurdering',
      no: 'Betydningsvurdering',
      fi: 'Merkittävyyspisteytys',
      de: 'Bedeutungsbewertung',
      fr: 'Évaluation de la signification',
      es: 'Puntuación de significancia',
      nl: 'Significantiebeoordeling',
      ar: 'تقييم الأهمية',
      he: 'ציון משמעות',
      ja: '重要度スコアリング',
      ko: '중요도 평가',
      zh: '重要性评分',
    },
    value: {
      en: 'why this story outranks or trails other same-day European Parliament signals',
      sv: 'varför denna nyhet överträffar eller underpresterar andra samma dags EU-parlamentssignaler',
      da: 'hvorfor denne historie overgår eller ligger under andre EU-parlamentssignaler fra samme dag',
      no: 'hvorfor denne saken overgår eller ligger bak andre EU-parlamentssignaler fra samme dag',
      fi: 'miksi tämä uutinen ohittaa tai jää jälkeen muista saman päivän EU-parlamentin signaaleista',
      de: 'warum diese Geschichte andere gleichzeitige EU-Parlamentssignale übertrifft oder hinterherhinkt',
      fr: "pourquoi cette histoire surpasse ou suit d'autres signaux du Parlement européen du même jour",
      es: 'por qué esta historia supera o queda detrás de otras señales del Parlamento Europeo del mismo día',
      nl: 'waarom dit verhaal andere EU-Parlementsignalen van dezelfde dag overtreft of achterblijft',
      ar: 'لماذا تتفوق هذه القصة أو تتخلف عن إشارات البرلمان الأوروبي الأخرى في نفس اليوم',
      he: 'מדוע הסיפור הזה עולה או נופל ביחס לאותות אחרים של הפרלמנט האירופי מאותו יום',
      ja: 'この記事が同日の他のEU議会シグナルを上回る/下回る理由',
      ko: '이 기사가 같은 날의 다른 EU 의회 신호보다 높은/낮은 순위인 이유',
      zh: '为何此新闻在同日欧洲议会信号中排名靠前或靠后',
    },
  },
  'section-coalitions-voting': {
    need: {
      en: 'Coalitions and voting',
      sv: 'Koalitioner och röstning',
      da: 'Koalitioner og afstemning',
      no: 'Koalisjoner og avstemning',
      fi: 'Koalitiot ja äänestys',
      de: 'Koalitionen und Abstimmungen',
      fr: 'Coalitions et votes',
      es: 'Coaliciones y votación',
      nl: 'Coalities en stemmingen',
      ar: 'التحالفات والتصويت',
      he: 'קואליציות והצבעות',
      ja: '連立と投票',
      ko: '연합 및 투표',
      zh: '联盟与投票',
    },
    value: {
      en: 'political group alignment, voting evidence, and coalition pressure points',
      sv: 'politisk gruppanpassning, röstbevis och koalitionstryckpunkter',
      da: 'politisk gruppeafstemning, stemmebevis og koalitionstrykpunkter',
      no: 'politisk gruppetilpasning, avstemningsbevis og koalisjonstrykpunkter',
      fi: 'poliittisen ryhmän linjaus, äänestystodisteet ja koalition painepisteet',
      de: 'politische Gruppenausrichtung, Abstimmungsnachweise und Koalitionsdruckpunkte',
      fr: 'alignement des groupes politiques, preuves de vote et points de pression de la coalition',
      es: 'alineamiento de grupos políticos, evidencia de votación y puntos de presión de la coalición',
      nl: 'politieke groepsafstemming, stembewijzen en coalitiepressuurpunten',
      ar: 'توافق المجموعات السياسية وأدلة التصويت ونقاط ضغط التحالف',
      he: 'התאמת קבוצות פוליטיות, ראיות הצבעה ונקודות לחץ קואליציוניות',
      ja: '政党グループの連携、投票エビデンス、連立圧力ポイント',
      ko: '정치 그룹 정렬, 투표 증거 및 연합 압력 지점',
      zh: '政治团体对齐、投票证据和联盟压力点',
    },
  },
  'section-stakeholder-map': {
    need: {
      en: 'Stakeholder impact',
      sv: 'Intressentpåverkan',
      da: 'Interessentpåvirkning',
      no: 'Interessentpåvirkning',
      fi: 'Sidosryhmävaikutus',
      de: 'Stakeholder-Auswirkungen',
      fr: 'Impact sur les parties prenantes',
      es: 'Impacto en las partes interesadas',
      nl: 'Impact op belanghebbenden',
      ar: 'تأثير أصحاب المصلحة',
      he: 'השפעה על בעלי עניין',
      ja: 'ステークホルダーへの影響',
      ko: '이해관계자 영향',
      zh: '利益相关者影响',
    },
    value: {
      en: 'who gains, who loses, and which institutions or citizens feel the policy effect',
      sv: 'vem som vinner, vem som förlorar, och vilka institutioner eller medborgare som påverkas',
      da: 'hvem vinder, hvem taber, og hvilke institutioner eller borgere der mærker politikeffekten',
      no: 'hvem som vinner, hvem som taper, og hvilke institusjoner eller borgere som merker politikkeffekten',
      fi: 'kuka voittaa, kuka häviää, ja mitkä instituutiot tai kansalaiset tuntevat politiikan vaikutuksen',
      de: 'wer gewinnt, wer verliert, und welche Institutionen oder Bürger die Politikwirkung spüren',
      fr: "qui gagne, qui perd, et quelles institutions ou citoyens ressentent l'effet de la politique",
      es: 'quién gana, quién pierde, y qué instituciones o ciudadanos sienten el efecto de la política',
      nl: 'wie wint, wie verliest, en welke instellingen of burgers het beleidseffect voelen',
      ar: 'من يكسب، من يخسر، وأي مؤسسات أو مواطنين يشعرون بتأثير السياسة',
      he: 'מי מרוויח, מי מפסיד, ואילו מוסדות או אזרחים חשים את השפעת המדיניות',
      ja: '誰が得をし、誰が損をし、どの機関や市民が政策効果を感じるか',
      ko: '누가 이익을 보고, 누가 손해를 보며, 어떤 기관이나 시민이 정책 효과를 느끼는지',
      zh: '谁受益、谁受损，哪些机构或公民感受到政策效果',
    },
  },
  'section-economic-context': {
    need: {
      en: 'IMF-backed economic context',
      sv: 'IMF-stödd ekonomisk kontext',
      da: 'IMF-støttet økonomisk kontekst',
      no: 'IMF-støttet økonomisk kontekst',
      fi: 'IMF:n tukema taloudellinen konteksti',
      de: 'IWF-gestützter wirtschaftlicher Kontext',
      fr: 'Contexte économique soutenu par le FMI',
      es: 'Contexto económico respaldado por el FMI',
      nl: 'IMF-ondersteunde economische context',
      ar: 'سياق اقتصادي مدعوم من صندوق النقد الدولي',
      he: 'הקשר כלכלי מגובה קרן המטבע',
      ja: 'IMF裏付け経済コンテキスト',
      ko: 'IMF 지원 경제 맥락',
      zh: 'IMF支持的经济背景',
    },
    value: {
      en: 'macro, fiscal, trade, or monetary evidence that changes the political interpretation',
      sv: 'makro-, finans-, handels- eller monetärbevis som förändrar den politiska tolkningen',
      da: 'makro-, finans-, handels- eller monetærbevis der ændrer den politiske fortolkning',
      no: 'makro-, finans-, handels- eller pengepolitiske bevis som endrer den politiske tolkningen',
      fi: 'makro-, finanssi-, kauppa- tai rahapoliittiset todisteet, jotka muuttavat poliittista tulkintaa',
      de: 'makroökonomische, fiskalische, Handels- oder geldpolitische Belege, die die politische Interpretation ändern',
      fr: "preuves macro, fiscales, commerciales ou monétaires qui modifient l'interprétation politique",
      es: 'evidencia macro, fiscal, comercial o monetaria que cambia la interpretación política',
      nl: 'macro-, fiscaal, handels- of monetair bewijs dat de politieke interpretatie verandert',
      ar: 'أدلة كلية أو مالية أو تجارية أو نقدية تغير التفسير السياسي',
      he: 'ראיות מקרו, פיסקליות, מסחריות או מוניטריות שמשנות את הפרשנות הפוליטית',
      ja: '政治的解釈を変えるマクロ、財政、貿易、金融エビデンス',
      ko: '정치적 해석을 바꾸는 거시, 재정, 무역 또는 통화 증거',
      zh: '改变政治解读的宏观、财政、贸易或货币证据',
    },
  },
  'section-scenarios': {
    need: {
      en: 'Forward indicators',
      sv: 'Framåtblickande indikatorer',
      da: 'Fremadrettede indikatorer',
      no: 'Fremoverpekende indikatorer',
      fi: 'Tulevaisuuden indikaattorit',
      de: 'Vorausschauende Indikatoren',
      fr: 'Indicateurs prospectifs',
      es: 'Indicadores prospectivos',
      nl: 'Vooruitkijkende indicatoren',
      ar: 'مؤشرات استشرافية',
      he: 'אינדיקטורים קדימה',
      ja: '先行指標',
      ko: '전망 지표',
      zh: '前瞻性指标',
    },
    value: {
      en: 'dated watch items that let readers verify or falsify the assessment later',
      sv: 'daterade bevakningspunkter som låter läsare verifiera eller falsifiera bedömningen senare',
      da: 'daterede overvågningspunkter der lader læsere verificere eller falsificere vurderingen senere',
      no: 'daterte overvåkningspunkter som lar lesere verifisere eller falsifisere vurderingen senere',
      fi: 'päivätyt seurantakohteet, joiden avulla lukijat voivat myöhemmin vahvistaa tai kumota arvion',
      de: 'datierte Beobachtungspunkte, mit denen Leser die Bewertung später verifizieren oder falsifizieren können',
      fr: "éléments de surveillance datés permettant aux lecteurs de vérifier ou d'infirmer l'évaluation ultérieurement",
      es: 'elementos de vigilancia fechados que permiten a los lectores verificar o refutar la evaluación posteriormente',
      nl: 'gedateerde bewakingspunten waarmee lezers de beoordeling later kunnen verifiëren of weerleggen',
      ar: 'عناصر مراقبة مؤرخة تتيح للقراء التحقق من التقييم أو دحضه لاحقاً',
      he: 'פריטי מעקב מתוארכים שמאפשרים לקוראים לאמת או להפריך את ההערכה בהמשך',
      ja: '読者が後で評価を検証または反証できる日付入り監視項目',
      ko: '독자가 나중에 평가를 검증하거나 반증할 수 있는 날짜가 지정된 감시 항목',
      zh: '让读者日后验证或证伪评估的标注日期监测项目',
    },
  },
  'section-risk': {
    need: {
      en: 'Risk assessment',
      sv: 'Riskbedömning',
      da: 'Risikovurdering',
      no: 'Risikovurdering',
      fi: 'Riskiarviointi',
      de: 'Risikobewertung',
      fr: 'Évaluation des risques',
      es: 'Evaluación de riesgos',
      nl: 'Risicobeoordeling',
      ar: 'تقييم المخاطر',
      he: 'הערכת סיכונים',
      ja: 'リスク評価',
      ko: '위험 평가',
      zh: '风险评估',
    },
    value: {
      en: 'policy, institutional, coalition, communications, and implementation risk register',
      sv: 'policy-, institutions-, koalitions-, kommunikations- och genomföranderiskregister',
      da: 'politik-, institutions-, koalitions-, kommunikations- og implementeringsrisikoregister',
      no: 'politikk-, institusjons-, koalisjons-, kommunikasjons- og gjennomføringsrisikoregister',
      fi: 'politiikka-, instituutio-, koalitio-, viestintä- ja toteutusriskien rekisteri',
      de: 'Risikoverzeichnis für Politik, Institutionen, Koalitionen, Kommunikation und Umsetzung',
      fr: 'registre des risques politiques, institutionnels, de coalition, de communication et de mise en œuvre',
      es: 'registro de riesgos políticos, institucionales, de coalición, de comunicación y de implementación',
      nl: 'risicoregister voor beleid, instellingen, coalities, communicatie en implementatie',
      ar: 'سجل مخاطر السياسات والمؤسسات والتحالفات والاتصالات والتنفيذ',
      he: 'מרשם סיכוני מדיניות, מוסדות, קואליציות, תקשורת ויישום',
      ja: '政策、制度、連立、コミュニケーション、実施のリスクレジスター',
      ko: '정책, 기관, 연합, 커뮤니케이션 및 이행 위험 등록부',
      zh: '政策、机构、联盟、沟通和执行风险登记册',
    },
  },
  'section-actors-forces': {
    need: {
      en: 'Actors & forces',
      sv: 'Aktörer & krafter',
      da: 'Aktører & kræfter',
      no: 'Aktører & krefter',
      fi: 'Toimijat & voimat',
      de: 'Akteure & Kräfte',
      fr: 'Acteurs & forces',
      es: 'Actores & fuerzas',
      nl: 'Actoren & krachten',
      ar: 'الفاعلون والقوى',
      he: 'שחקנים וכוחות',
      ja: 'アクターと力学',
      ko: '행위자 & 세력',
      zh: '行动者与力量',
    },
    value: {
      en: 'who is driving the story, what political forces line up behind them, and which institutional levers they can pull',
      sv: 'vem som driver händelsen, vilka politiska krafter står bakom och vilka institutionella spakar de kan dra',
      da: 'hvem der driver historien, hvilke politiske kræfter står bag, og hvilke institutionelle håndtag de kan trække',
      no: 'hvem som driver saken, hvilke politiske krefter står bak, og hvilke institusjonelle spaker de kan trekke',
      fi: 'kuka ohjaa tarinaa, mitkä poliittiset voimat ovat takana ja mitä institutionaalisia vipuja he voivat käyttää',
      de: 'wer die Geschichte vorantreibt, welche politischen Kräfte dahinterstehen und welche institutionellen Hebel sie ziehen können',
      fr: "qui pilote l'histoire, quelles forces politiques sont alignées derrière, et quels leviers institutionnels ils peuvent actionner",
      es: 'quién impulsa la historia, qué fuerzas políticas están detrás y qué palancas institucionales pueden accionar',
      nl: 'wie het verhaal aandrijft, welke politieke krachten erachter staan en welke institutionele hefbomen ze kunnen overhalen',
      ar: 'من يقود القصة، وما القوى السياسية المصطفة خلفه، وأي روافع مؤسسية يمكنهم تحريكها',
      he: 'מי מניע את הסיפור, אילו כוחות פוליטיים מאחוריו, ואילו מנופים מוסדיים הם יכולים להפעיל',
      ja: 'ストーリーを動かしているのは誰か、その背後にある政治的勢力、そして彼らが引ける制度的レバー',
      ko: '누가 이야기를 주도하는지, 그 뒤에 어떤 정치적 세력이 있는지, 그리고 어떤 제도적 지렛대를 당길 수 있는지',
      zh: '谁在推动故事、哪些政治力量在其背后、以及他们可以拉动哪些制度杠杆',
    },
  },
  'section-threat': {
    need: {
      en: 'Threat landscape',
      sv: 'Hotlandskap',
      da: 'Trussellandskab',
      no: 'Trussellandskap',
      fi: 'Uhkamaisema',
      de: 'Bedrohungslandschaft',
      fr: 'Paysage des menaces',
      es: 'Panorama de amenazas',
      nl: 'Dreigingslandschap',
      ar: 'مشهد التهديدات',
      he: 'נוף האיומים',
      ja: '脅威ランドスケープ',
      ko: '위협 환경',
      zh: '威胁态势',
    },
    value: {
      en: 'hostile actors, attack vectors, consequence trees, and the legislative-disruption pathways the article tracks',
      sv: 'fientliga aktörer, attackvektorer, konsekvensträd och de lagstiftningsstörningsvägar artikeln spårar',
      da: 'fjendtlige aktører, angrebsvektorer, konsekvenstræer og de lovgivningsforstyrrelsesveje artiklen følger',
      no: 'fiendtlige aktører, angrepsvektorer, konsekvenstrær og lovgivningsforstyrrelsesveiene artikkelen sporer',
      fi: 'vihamieliset toimijat, hyökkäysvektorit, seurauspuut ja lainsäädännön häiriöpolut, joita artikkeli seuraa',
      de: 'feindliche Akteure, Angriffsvektoren, Konsequenzbäume und die Gesetzgebungsstörungspfade, die der Artikel verfolgt',
      fr: "acteurs hostiles, vecteurs d'attaque, arbres de conséquences et voies de perturbation législative que l'article suit",
      es: 'actores hostiles, vectores de ataque, árboles de consecuencias y las vías de disrupción legislativa que sigue el artículo',
      nl: 'vijandige actoren, aanvalsvectoren, gevolgenbomen en de wetgevingsverstoringspaden die het artikel volgt',
      ar: 'الجهات المعادية وناقلات الهجوم وأشجار العواقب ومسارات التعطيل التشريعي التي يتتبعها المقال',
      he: 'שחקנים עוינים, ווקטורי תקיפה, עצי השלכה ונתיבי שיבוש החקיקה שהמאמר עוקב אחריהם',
      ja: '敵対的アクター、攻撃ベクトル、結果ツリー、および記事が追跡する立法阻害経路',
      ko: '적대적 행위자, 공격 벡터, 결과 트리, 그리고 기사가 추적하는 입법 교란 경로',
      zh: '敌对行为者、攻击向量、后果树以及文章追踪的立法干扰路径',
    },
  },
  'section-forward-projection': {
    need: {
      en: 'What to watch',
      sv: 'Vad att bevaka',
      da: 'Hvad man skal følge',
      no: 'Hva å følge med på',
      fi: 'Mitä seurata',
      de: 'Was zu beobachten ist',
      fr: 'À surveiller',
      es: 'Qué vigilar',
      nl: 'Wat te volgen',
      ar: 'ما يجب مراقبته',
      he: 'מה לעקוב אחריו',
      ja: '注目ポイント',
      ko: '주목할 사항',
      zh: '关注要点',
    },
    value: {
      en: 'dated trigger events, parliamentary-calendar dependencies, and the legislative-pipeline forecast',
      sv: 'daterade triggers, beroenden i parlamentskalendern och prognosen för lagstiftningspipelinen',
      da: 'daterede triggers, parlamentskalender-afhængigheder og prognosen for lovgivningspipelinen',
      no: 'daterte triggers, parlamentskalender-avhengigheter og prognosen for lovgivningspipelinen',
      fi: 'päivätyt laukaisimet, parlamentin kalenterin riippuvuudet ja lainsäädäntöputken ennuste',
      de: 'datierte Auslöseereignisse, Abhängigkeiten vom Parlamentskalender und die Prognose der Gesetzgebungspipeline',
      fr: 'événements déclencheurs datés, dépendances du calendrier parlementaire et prévision du pipeline législatif',
      es: 'eventos desencadenantes fechados, dependencias del calendario parlamentario y previsión del pipeline legislativo',
      nl: 'gedateerde triggergebeurtenissen, afhankelijkheden van de parlementaire agenda en de voorspelling van de wetgevingspijplijn',
      ar: 'أحداث محفزة مؤرخة، تبعيات الجدول البرلماني، وتوقعات خط الأنابيب التشريعي',
      he: 'אירועי טריגר מתוארכים, תלויות לוח הפרלמנט ותחזית צינור החקיקה',
      ja: '日付付きのトリガーイベント、議会カレンダーの依存関係、立法パイプラインの予測',
      ko: '날짜가 지정된 트리거 이벤트, 의회 일정 의존성, 입법 파이프라인 예측',
      zh: '标注日期的触发事件、议会日历依赖关系以及立法流程预测',
    },
  },
  'section-electoral-arc': {
    need: {
      en: 'Electoral arc & mandate',
      sv: 'Valbåge & mandat',
      da: 'Valgbue & mandat',
      no: 'Valgbue & mandat',
      fi: 'Vaalikaari & mandaatti',
      de: 'Wahlbogen & Mandat',
      fr: 'Arc électoral & mandat',
      es: 'Arco electoral & mandato',
      nl: 'Verkiezingsboog & mandaat',
      ar: 'القوس الانتخابي والتفويض',
      he: 'קשת בחירות ומנדט',
      ja: '選挙アークとマンデート',
      ko: '선거 아크 & 위임',
      zh: '选举弧线与任期',
    },
    value: {
      en: 'where in the term the story sits, mandate-fulfilment scoring, seat projection, and the presidency-trio context',
      sv: 'var i mandatperioden händelsen befinner sig, mandatuppfyllelsescoring, mandatprojektion och ordförandetrio-kontexten',
      da: 'hvor i valgperioden historien ligger, mandatopfyldelsesscoring, mandatprojektion og formandstrio-konteksten',
      no: 'hvor i valgperioden saken ligger, mandatoppfyllelsesscoring, mandatprojeksjon og formannskapstrio-konteksten',
      fi: 'mihin kohtaan kautta tarina sijoittuu, mandaatin täyttymisen pisteytys, paikkaennuste ja puheenjohtajatrion konteksti',
      de: 'wo im Mandat die Geschichte liegt, Mandatserfüllungs-Scoring, Sitzprojektion und Präsidentschaftstrio-Kontext',
      fr: "où en est l'histoire dans le mandat, notation de l'exécution du mandat, projection des sièges et contexte du trio présidentiel",
      es: 'dónde se sitúa la historia en el mandato, puntuación de cumplimiento del mandato, proyección de escaños y contexto del trío presidencial',
      nl: 'waar het verhaal zich in het mandaat bevindt, scoring mandaatuitvoering, zetelprojectie en context van de voorzittersdrieluik',
      ar: 'موقع القصة في الولاية، تقييم تنفيذ التفويض، توقعات المقاعد، وسياق الترويكا الرئاسية',
      he: 'איפה בכהונה הסיפור ממוקם, ניקוד מילוי המנדט, תחזית מושבים, והקשר של שלישיית הנשיאות',
      ja: '物語が任期のどこに位置するか、マンデート遂行スコア、議席予測、議長トリオの文脈',
      ko: '이야기가 임기의 어디에 위치하는지, 위임 이행 점수, 의석 예측, 의장 트리오 맥락',
      zh: '故事在任期中所处的位置、任期履行评分、席位预测以及主席三人组的背景',
    },
  },
};
