// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/DA
 * @description DA deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** DA deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_DA: DeepAnalysisStrings = {
  sectionHeading: 'Dybdegående Politisk Analyse',
  whatHeading: 'Hvad Skete',
  whoHeading: 'Nøgleaktører',
  whenHeading: 'Tidslinje',
  whyHeading: 'Hvorfor Det Betyder Noget — Grundårsager',
  stakeholderHeading: 'Vindere & Tabere',
  winnerLabel: 'Vinder',
  loserLabel: 'Taber',
  neutralLabel: 'Neutral',
  impactHeading: 'Konsekvensvurdering',
  politicalLabel: 'Politisk',
  economicLabel: 'Økonomisk',
  socialLabel: 'Social',
  legalLabel: 'Juridisk',
  geopoliticalLabel: 'Geopolitisk',
  consequencesHeading: 'Handlinger → Konsekvenser',
  actionLabel: 'Handling',
  consequenceLabel: 'Konsekvens',
  severityColumnLabel: 'Alvorlighed',
  mistakesHeading: 'Fejlvurderinger & Forpassede Muligheder',
  alternativeLabel: 'Burde have',
  outlookHeading: 'Strategisk Udsigt',
  severityLow: 'Lav',
  severityMedium: 'Middel',
  severityHigh: 'Høj',
  severityCritical: 'Kritisk',
  executiveSummaryHeading: 'Resumé',
  confidenceHigh: 'Høj Tillid',
  confidenceMedium: 'Middel Tillid',
  confidenceLow: 'Lav Tillid',
  evidenceRefsHeading: 'Beviser',
  counterArgumentsHeading: 'Modargumenter',
  conclusionLabel: 'Konklusion:',
  premiseLabel: 'Præmis:',
  inferenceLabel: 'Slutning:',
  reasoningChainsHeading: 'Ræsonnementskæder',
  scenarioPlanningHeading: 'Scenarieplanlægning',
  bestCaseLabel: 'Bedste Scenarie',
  worstCaseLabel: 'Værste Scenarie',
  mostLikelyLabel: 'Mest Sandsynligt',
  wildcardsLabel: 'Jokere',
  probabilityLabel: 'Sandsynlighed',
  triggersLabel: 'Udløsere',
  impliedImpactsLabel: 'Forventede Konsekvenser',
  timelineLabel: 'Tidslinje',
  analysisMethodologyHeading: 'Analysemetodik',
  iterationCountLabel: 'Iterationer',
  evidenceStrengthLabel: 'Bevisstyrke',
  evidenceStrong: 'Stærk',
  evidenceModerate: 'Moderat',
  evidenceWeak: 'Svag',
  iterationInitial: 'Indledende Vurdering',
  iterationStakeholderChallenge: 'Interessentudfordring',
  iterationEvidenceValidation: 'Bevisvalidering',
  iterationSynthesis: 'Syntese',
  overallConfidenceLabel: 'Samlet Tillid',
  pendingNotice:
    'Analyse afventer — denne sektion vil blive udfyldt af det redaktionelle analyse-workflow.',
  perspectivesHeading: 'Interessentperspektiver',
  outcomeMatrixHeading: 'Interessentresultatmatrix',
  confidenceLabel: 'Konfidens',
  politicalGroupsLabel: 'Politiske grupper',
  civilSocietyLabel: 'Civilsamfund',
  industryLabel: 'Industri',
  nationalGovtsLabel: 'Nationale regeringer',
  citizensLabel: 'Borgere',
  euInstitutionsLabel: 'EU-institutioner',
  positiveLabel: 'Positiv',
  negativeLabel: 'Negativ',
  mixedLabel: 'Blandet',
};
