// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/DE
 * @description DE deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** DE deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_DE: DeepAnalysisStrings = {
  sectionHeading: 'Vertiefte Politische Analyse',
  whatHeading: 'Was Geschah',
  whoHeading: 'Schlüsselakteure',
  whenHeading: 'Zeitachse',
  whyHeading: 'Warum Es Wichtig Ist — Grundursachen',
  stakeholderHeading: 'Gewinner & Verlierer',
  winnerLabel: 'Gewinner',
  loserLabel: 'Verlierer',
  neutralLabel: 'Neutral',
  impactHeading: 'Folgenabschätzung',
  politicalLabel: 'Politisch',
  economicLabel: 'Wirtschaftlich',
  socialLabel: 'Sozial',
  legalLabel: 'Rechtlich',
  geopoliticalLabel: 'Geopolitisch',
  consequencesHeading: 'Handlungen → Konsequenzen',
  actionLabel: 'Handlung',
  consequenceLabel: 'Konsequenz',
  severityColumnLabel: 'Schweregrad',
  mistakesHeading: 'Fehleinschätzungen & Verpasste Chancen',
  alternativeLabel: 'Hätte sollen',
  outlookHeading: 'Strategischer Ausblick',
  severityLow: 'Niedrig',
  severityMedium: 'Mittel',
  severityHigh: 'Hoch',
  severityCritical: 'Kritisch',
  executiveSummaryHeading: 'Zusammenfassung',
  confidenceHigh: 'Hohe Konfidenz',
  confidenceMedium: 'Mittlere Konfidenz',
  confidenceLow: 'Niedrige Konfidenz',
  evidenceRefsHeading: 'Belege',
  counterArgumentsHeading: 'Gegenargumente',
  conclusionLabel: 'Schlussfolgerung:',
  premiseLabel: 'Prämisse:',
  inferenceLabel: 'Ableitung:',
  reasoningChainsHeading: 'Argumentationsketten',
  scenarioPlanningHeading: 'Szenarioplanung',
  bestCaseLabel: 'Bester Fall',
  worstCaseLabel: 'Schlimmster Fall',
  mostLikelyLabel: 'Wahrscheinlichster Fall',
  wildcardsLabel: 'Unbekannte Faktoren',
  probabilityLabel: 'Wahrscheinlichkeit',
  triggersLabel: 'Auslöser',
  impliedImpactsLabel: 'Erwartete Auswirkungen',
  timelineLabel: 'Zeitachse',
  analysisMethodologyHeading: 'Analysemethodik',
  iterationCountLabel: 'Iterationen',
  evidenceStrengthLabel: 'Beweisstärke',
  evidenceStrong: 'Stark',
  evidenceModerate: 'Mäßig',
  evidenceWeak: 'Schwach',
  iterationInitial: 'Erstbewertung',
  iterationStakeholderChallenge: 'Stakeholder-Herausforderung',
  iterationEvidenceValidation: 'Beweisvalidierung',
  iterationSynthesis: 'Synthese',
  overallConfidenceLabel: 'Gesamtkonfidenz',
  pendingNotice:
    'Analyse ausstehend — dieser Abschnitt wird durch den redaktionellen Analyse-Workflow vervollständigt.',
  perspectivesHeading: 'Stakeholder-Perspektiven',
  outcomeMatrixHeading: 'Stakeholder-Ergebnismatrix',
  confidenceLabel: 'Konfidenz',
  politicalGroupsLabel: 'Politische Fraktionen',
  civilSocietyLabel: 'Zivilgesellschaft',
  industryLabel: 'Industrie',
  nationalGovtsLabel: 'Nationale Regierungen',
  citizensLabel: 'Bürger',
  euInstitutionsLabel: 'EU-Institutionen',
  positiveLabel: 'Positiv',
  negativeLabel: 'Negativ',
  mixedLabel: 'Gemischt',
};
