// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/EN
 * @description EN deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** EN deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_EN: DeepAnalysisStrings = {
  sectionHeading: 'Deep Political Analysis',
  whatHeading: 'What Happened',
  whoHeading: 'Key Actors',
  whenHeading: 'Timeline',
  whyHeading: 'Why It Matters — Root Causes',
  stakeholderHeading: 'Winners & Losers',
  winnerLabel: 'Winner',
  loserLabel: 'Loser',
  neutralLabel: 'Neutral',
  impactHeading: 'Impact Assessment',
  politicalLabel: 'Political',
  economicLabel: 'Economic',
  socialLabel: 'Social',
  legalLabel: 'Legal',
  geopoliticalLabel: 'Geopolitical',
  consequencesHeading: 'Actions → Consequences',
  actionLabel: 'Action',
  consequenceLabel: 'Consequence',
  severityColumnLabel: 'Severity',
  mistakesHeading: 'Miscalculations & Missed Opportunities',
  alternativeLabel: 'Should have',
  outlookHeading: 'Strategic Outlook',
  severityLow: 'Low',
  severityMedium: 'Medium',
  severityHigh: 'High',
  severityCritical: 'Critical',

  executiveSummaryHeading: 'Executive Summary',
  confidenceHigh: 'High Confidence',
  confidenceMedium: 'Medium Confidence',
  confidenceLow: 'Low Confidence',
  evidenceRefsHeading: 'Evidence',
  counterArgumentsHeading: 'Counter-arguments',
  conclusionLabel: 'Conclusion:',
  premiseLabel: 'Premise:',
  inferenceLabel: 'Inference:',
  reasoningChainsHeading: 'Reasoning Chains',
  scenarioPlanningHeading: 'Scenario Planning',
  bestCaseLabel: 'Best Case',
  worstCaseLabel: 'Worst Case',
  mostLikelyLabel: 'Most Likely',
  wildcardsLabel: 'Wildcards',
  probabilityLabel: 'Probability',
  triggersLabel: 'Triggers',
  impliedImpactsLabel: 'Implied Impacts',
  timelineLabel: 'Timeline',
  analysisMethodologyHeading: 'Analysis Methodology',
  iterationCountLabel: 'Iterations',
  evidenceStrengthLabel: 'Evidence Strength',
  evidenceStrong: 'Strong',
  evidenceModerate: 'Moderate',
  evidenceWeak: 'Weak',
  iterationInitial: 'Initial Assessment',
  iterationStakeholderChallenge: 'Stakeholder Challenge',
  iterationEvidenceValidation: 'Evidence Validation',
  iterationSynthesis: 'Synthesis',
  overallConfidenceLabel: 'Overall Confidence',
  pendingNotice:
    'Analysis pending — this section will be completed by the editorial intelligence workflow.',
  perspectivesHeading: 'Multi-Stakeholder Perspectives',
  outcomeMatrixHeading: 'Stakeholder Outcome Matrix',
  confidenceLabel: 'Confidence',
  politicalGroupsLabel: 'Political Groups',
  civilSocietyLabel: 'Civil Society',
  industryLabel: 'Industry',
  nationalGovtsLabel: 'National Governments',
  citizensLabel: 'Citizens',
  euInstitutionsLabel: 'EU Institutions',
  positiveLabel: 'Positive',
  negativeLabel: 'Negative',
  mixedLabel: 'Mixed',
};
