// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/ES
 * @description ES deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** ES deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_ES: DeepAnalysisStrings = {
  sectionHeading: 'Análisis Político Profundo',
  whatHeading: 'Qué Ocurrió',
  whoHeading: 'Actores Clave',
  whenHeading: 'Cronología',
  whyHeading: 'Por Qué Importa — Causas Raíz',
  stakeholderHeading: 'Ganadores & Perdedores',
  winnerLabel: 'Ganador',
  loserLabel: 'Perdedor',
  neutralLabel: 'Neutral',
  impactHeading: 'Evaluación de Impacto',
  politicalLabel: 'Político',
  economicLabel: 'Económico',
  socialLabel: 'Social',
  legalLabel: 'Jurídico',
  geopoliticalLabel: 'Geopolítico',
  consequencesHeading: 'Acciones → Consecuencias',
  actionLabel: 'Acción',
  consequenceLabel: 'Consecuencia',
  severityColumnLabel: 'Gravedad',
  mistakesHeading: 'Errores de Cálculo & Oportunidades Perdidas',
  alternativeLabel: 'Debería haber',
  outlookHeading: 'Perspectivas Estratégicas',
  severityLow: 'Bajo',
  severityMedium: 'Medio',
  severityHigh: 'Alto',
  severityCritical: 'Crítico',
  executiveSummaryHeading: 'Resumen Ejecutivo',
  confidenceHigh: 'Confianza Alta',
  confidenceMedium: 'Confianza Media',
  confidenceLow: 'Confianza Baja',
  evidenceRefsHeading: 'Evidencias',
  counterArgumentsHeading: 'Contraargumentos',
  conclusionLabel: 'Conclusión:',
  premiseLabel: 'Premisa:',
  inferenceLabel: 'Inferencia:',
  reasoningChainsHeading: 'Cadenas de Razonamiento',
  scenarioPlanningHeading: 'Planificación de Escenarios',
  bestCaseLabel: 'Mejor Escenario',
  worstCaseLabel: 'Peor Escenario',
  mostLikelyLabel: 'Más Probable',
  wildcardsLabel: 'Factores Imprevistos',
  probabilityLabel: 'Probabilidad',
  triggersLabel: 'Desencadenantes',
  impliedImpactsLabel: 'Impactos Previstos',
  timelineLabel: 'Cronología',
  analysisMethodologyHeading: 'Metodología de Análisis',
  iterationCountLabel: 'Iteraciones',
  evidenceStrengthLabel: 'Fuerza de la Evidencia',
  evidenceStrong: 'Fuerte',
  evidenceModerate: 'Moderada',
  evidenceWeak: 'Débil',
  iterationInitial: 'Evaluación Inicial',
  iterationStakeholderChallenge: 'Desafío de Partes Interesadas',
  iterationEvidenceValidation: 'Validación de Evidencia',
  iterationSynthesis: 'Síntesis',
  overallConfidenceLabel: 'Confianza Global',
  pendingNotice:
    'Análisis pendiente — esta sección será completada por el flujo de trabajo de análisis editorial.',
  perspectivesHeading: 'Perspectivas de las Partes Interesadas',
  outcomeMatrixHeading: 'Matriz de Resultados de Partes Interesadas',
  confidenceLabel: 'Confianza',
  politicalGroupsLabel: 'Grupos políticos',
  civilSocietyLabel: 'Sociedad civil',
  industryLabel: 'Industria',
  nationalGovtsLabel: 'Gobiernos nacionales',
  citizensLabel: 'Ciudadanos',
  euInstitutionsLabel: 'Instituciones de la UE',
  positiveLabel: 'Positivo',
  negativeLabel: 'Negativo',
  mixedLabel: 'Mixto',
};
