// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/JA
 * @description JA deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** JA deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_JA: DeepAnalysisStrings = {
  sectionHeading: '深層政治分析',
  whatHeading: '何が起きたか',
  whoHeading: '主要関係者',
  whenHeading: 'タイムライン',
  whyHeading: 'なぜ重要か — 根本原因',
  stakeholderHeading: '勝者と敗者',
  winnerLabel: '勝者',
  loserLabel: '敗者',
  neutralLabel: '中立',
  impactHeading: '影響評価',
  politicalLabel: '政治的',
  economicLabel: '経済的',
  socialLabel: '社会的',
  legalLabel: '法的',
  geopoliticalLabel: '地政学的',
  consequencesHeading: '行動 → 結果',
  actionLabel: '行動',
  consequenceLabel: '結果',
  severityColumnLabel: '重大度',
  mistakesHeading: '誤算と逃した機会',
  alternativeLabel: 'すべきだった',
  outlookHeading: '戦略的展望',
  severityLow: '低',
  severityMedium: '中',
  severityHigh: '高',
  severityCritical: '重大',
  executiveSummaryHeading: 'エグゼクティブサマリー',
  confidenceHigh: '高い信頼度',
  confidenceMedium: '中程度の信頼度',
  confidenceLow: '低い信頼度',
  evidenceRefsHeading: '証拠',
  counterArgumentsHeading: '反論',
  conclusionLabel: '結論:',
  premiseLabel: '前提:',
  inferenceLabel: '推論:',
  reasoningChainsHeading: '推論チェーン',
  scenarioPlanningHeading: 'シナリオプランニング',
  bestCaseLabel: '最良シナリオ',
  worstCaseLabel: '最悪シナリオ',
  mostLikelyLabel: '最も可能性が高い',
  wildcardsLabel: '不確定要素',
  probabilityLabel: '確率',
  triggersLabel: 'トリガー',
  impliedImpactsLabel: '予想される影響',
  timelineLabel: 'タイムライン',
  analysisMethodologyHeading: '分析手法',
  iterationCountLabel: 'イテレーション',
  evidenceStrengthLabel: '証拠の強度',
  evidenceStrong: '強い',
  evidenceModerate: '中程度',
  evidenceWeak: '弱い',
  iterationInitial: '初期評価',
  iterationStakeholderChallenge: 'ステークホルダーの検証',
  iterationEvidenceValidation: '証拠の検証',
  iterationSynthesis: '総合',
  overallConfidenceLabel: '総合信頼度',
  pendingNotice: '分析保留中 — このセクションは編集分析ワークフローによって完了されます。',
  perspectivesHeading: 'ステークホルダーの視点',
  outcomeMatrixHeading: 'ステークホルダー結果マトリックス',
  confidenceLabel: '信頼度',
  politicalGroupsLabel: '政治グループ',
  civilSocietyLabel: '市民社会',
  industryLabel: '産業界',
  nationalGovtsLabel: '各国政府',
  citizensLabel: '市民',
  euInstitutionsLabel: 'EU機関',
  positiveLabel: '肯定的',
  negativeLabel: '否定的',
  mixedLabel: '混合',
};
