// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/KO
 * @description KO deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** KO deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_KO: DeepAnalysisStrings = {
  sectionHeading: '심층 정치 분석',
  whatHeading: '무엇이 일어났는가',
  whoHeading: '주요 행위자',
  whenHeading: '타임라인',
  whyHeading: '왜 중요한가 — 근본 원인',
  stakeholderHeading: '승자와 패자',
  winnerLabel: '승자',
  loserLabel: '패자',
  neutralLabel: '중립',
  impactHeading: '영향 평가',
  politicalLabel: '정치적',
  economicLabel: '경제적',
  socialLabel: '사회적',
  legalLabel: '법적',
  geopoliticalLabel: '지정학적',
  consequencesHeading: '행동 → 결과',
  actionLabel: '행동',
  consequenceLabel: '결과',
  severityColumnLabel: '심각도',
  mistakesHeading: '오판과 놓친 기회',
  alternativeLabel: '했어야 했다',
  outlookHeading: '전략적 전망',
  severityLow: '낮음',
  severityMedium: '보통',
  severityHigh: '높음',
  severityCritical: '위기',
  executiveSummaryHeading: '핵심 요약',
  confidenceHigh: '높은 신뢰도',
  confidenceMedium: '중간 신뢰도',
  confidenceLow: '낮은 신뢰도',
  evidenceRefsHeading: '증거',
  counterArgumentsHeading: '반론',
  conclusionLabel: '결론:',
  premiseLabel: '전제:',
  inferenceLabel: '추론:',
  reasoningChainsHeading: '추론 체인',
  scenarioPlanningHeading: '시나리오 계획',
  bestCaseLabel: '최선 시나리오',
  worstCaseLabel: '최악 시나리오',
  mostLikelyLabel: '가장 가능성 높은',
  wildcardsLabel: '불확실 요소',
  probabilityLabel: '확률',
  triggersLabel: '촉발 요인',
  impliedImpactsLabel: '예상 영향',
  timelineLabel: '타임라인',
  analysisMethodologyHeading: '분석 방법론',
  iterationCountLabel: '반복',
  evidenceStrengthLabel: '증거 강도',
  evidenceStrong: '강함',
  evidenceModerate: '보통',
  evidenceWeak: '약함',
  iterationInitial: '초기 평가',
  iterationStakeholderChallenge: '이해관계자 검증',
  iterationEvidenceValidation: '증거 검증',
  iterationSynthesis: '종합',
  overallConfidenceLabel: '종합 신뢰도',
  pendingNotice: '분석 대기 중 — 이 섹션은 편집 분석 워크플로에 의해 완성됩니다.',
  perspectivesHeading: '이해관계자 관점',
  outcomeMatrixHeading: '이해관계자 결과 매트릭스',
  confidenceLabel: '신뢰도',
  politicalGroupsLabel: '정치 그룹',
  civilSocietyLabel: '시민사회',
  industryLabel: '산업계',
  nationalGovtsLabel: '각국 정부',
  citizensLabel: '시민',
  euInstitutionsLabel: 'EU 기관',
  positiveLabel: '긍정적',
  negativeLabel: '부정적',
  mixedLabel: '혼합',
};
