// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/SV
 * @description SV deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** SV deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_SV: DeepAnalysisStrings = {
  sectionHeading: 'Fördjupad Politisk Analys',
  whatHeading: 'Vad Hände',
  whoHeading: 'Nyckelaktörer',
  whenHeading: 'Tidslinje',
  whyHeading: 'Varför Det Spelar Roll — Grundorsaker',
  stakeholderHeading: 'Vinnare & Förlorare',
  winnerLabel: 'Vinnare',
  loserLabel: 'Förlorare',
  neutralLabel: 'Neutral',
  impactHeading: 'Konsekvensbedömning',
  politicalLabel: 'Politisk',
  economicLabel: 'Ekonomisk',
  socialLabel: 'Social',
  legalLabel: 'Juridisk',
  geopoliticalLabel: 'Geopolitisk',
  consequencesHeading: 'Åtgärder → Konsekvenser',
  actionLabel: 'Åtgärd',
  consequenceLabel: 'Konsekvens',
  severityColumnLabel: 'Allvarlighetsgrad',
  mistakesHeading: 'Felbedömningar & Missade Möjligheter',
  alternativeLabel: 'Borde ha',
  outlookHeading: 'Strategisk Utsikt',
  severityLow: 'Låg',
  severityMedium: 'Medel',
  severityHigh: 'Hög',
  severityCritical: 'Kritisk',
  executiveSummaryHeading: 'Sammanfattning',
  confidenceHigh: 'Hög Tillförlitlighet',
  confidenceMedium: 'Medel Tillförlitlighet',
  confidenceLow: 'Låg Tillförlitlighet',
  evidenceRefsHeading: 'Bevisning',
  counterArgumentsHeading: 'Motargument',
  conclusionLabel: 'Slutsats:',
  premiseLabel: 'Premiss:',
  inferenceLabel: 'Slutledning:',
  reasoningChainsHeading: 'Resonemangskedjor',
  scenarioPlanningHeading: 'Scenarioplanering',
  bestCaseLabel: 'Bästa Scenario',
  worstCaseLabel: 'Värsta Scenario',
  mostLikelyLabel: 'Mest Troligt',
  wildcardsLabel: 'Jokerkort',
  probabilityLabel: 'Sannolikhet',
  triggersLabel: 'Utlösare',
  impliedImpactsLabel: 'Förväntade Effekter',
  timelineLabel: 'Tidslinje',
  analysisMethodologyHeading: 'Analysmetodik',
  iterationCountLabel: 'Iterationer',
  evidenceStrengthLabel: 'Bevisstyrka',
  evidenceStrong: 'Stark',
  evidenceModerate: 'Måttlig',
  evidenceWeak: 'Svag',
  iterationInitial: 'Inledande Bedömning',
  iterationStakeholderChallenge: 'Intressentutmaning',
  iterationEvidenceValidation: 'Bevisvalidering',
  iterationSynthesis: 'Syntes',
  overallConfidenceLabel: 'Övergripande Tillförlitlighet',
  pendingNotice:
    'Analys väntar — denna sektion kommer att slutföras av det redaktionella analysarbetsflödet.',
  perspectivesHeading: 'Intressentperspektiv',
  outcomeMatrixHeading: 'Intressentutfallsmatris',
  confidenceLabel: 'Konfidens',
  politicalGroupsLabel: 'Politiska grupper',
  civilSocietyLabel: 'Civilsamhälle',
  industryLabel: 'Industri',
  nationalGovtsLabel: 'Nationella regeringar',
  citizensLabel: 'Medborgare',
  euInstitutionsLabel: 'EU-institutioner',
  positiveLabel: 'Positiv',
  negativeLabel: 'Negativ',
  mixedLabel: 'Blandad',
};
