// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis/ZH
 * @description ZH deep-analysis strings.
 */

import type { DeepAnalysisStrings } from '../../../types/index.js';

/** ZH deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_ZH: DeepAnalysisStrings = {
  sectionHeading: '深度政治分析',
  whatHeading: '发生了什么',
  whoHeading: '关键参与者',
  whenHeading: '时间线',
  whyHeading: '为何重要 — 根本原因',
  stakeholderHeading: '赢家与输家',
  winnerLabel: '赢家',
  loserLabel: '输家',
  neutralLabel: '中立',
  impactHeading: '影响评估',
  politicalLabel: '政治',
  economicLabel: '经济',
  socialLabel: '社会',
  legalLabel: '法律',
  geopoliticalLabel: '地缘政治',
  consequencesHeading: '行动 → 后果',
  actionLabel: '行动',
  consequenceLabel: '后果',
  severityColumnLabel: '严重程度',
  mistakesHeading: '误判与错失机会',
  alternativeLabel: '本应',
  outlookHeading: '战略展望',
  severityLow: '低',
  severityMedium: '中',
  severityHigh: '高',
  severityCritical: '严重',
  executiveSummaryHeading: '执行摘要',
  confidenceHigh: '高置信度',
  confidenceMedium: '中等置信度',
  confidenceLow: '低置信度',
  evidenceRefsHeading: '证据',
  counterArgumentsHeading: '反驳论点',
  conclusionLabel: '结论：',
  premiseLabel: '前提：',
  inferenceLabel: '推理：',
  reasoningChainsHeading: '推理链',
  scenarioPlanningHeading: '情景规划',
  bestCaseLabel: '最佳情景',
  worstCaseLabel: '最坏情景',
  mostLikelyLabel: '最可能情景',
  wildcardsLabel: '不确定因素',
  probabilityLabel: '概率',
  triggersLabel: '触发因素',
  impliedImpactsLabel: '预期影响',
  timelineLabel: '时间线',
  analysisMethodologyHeading: '分析方法论',
  iterationCountLabel: '迭代次数',
  evidenceStrengthLabel: '证据强度',
  evidenceStrong: '强',
  evidenceModerate: '中等',
  evidenceWeak: '弱',
  iterationInitial: '初始评估',
  iterationStakeholderChallenge: '利益相关方审查',
  iterationEvidenceValidation: '证据验证',
  iterationSynthesis: '综合',
  overallConfidenceLabel: '整体置信度',
  pendingNotice: '分析待定 — 本节将由编辑分析工作流完成。',

  perspectivesHeading: '利益相关方视角',
  outcomeMatrixHeading: '利益相关方结果矩阵',
  confidenceLabel: '置信度',
  politicalGroupsLabel: '政治团体',
  civilSocietyLabel: '公民社会',
  industryLabel: '工商界',
  nationalGovtsLabel: '各国政府',
  citizensLabel: '公民',
  euInstitutionsLabel: '欧盟机构',
  positiveLabel: '积极',
  negativeLabel: '消极',
  mixedLabel: '混合',
};
