# SPDX-FileCopyrightText: 2024-2026 Hack23 AB
# SPDX-License-Identifier: Apache-2.0
# Analyze only source code
sonar.sources=src,scripts

# Analyze only tests
sonar.tests=test

# Source encoding
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
docs,\
analysis,\
data,\
images,\
dist,\
build
