// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
//
// PurgeCSS configuration for the static site.
//
// Scans every HTML page that ships to S3/CloudFront — root pages
// (index*.html, sitemap*.html, political-intelligence_*.html, offline.html)
// AND every news article under news/*.html — plus all client-side JS that
// can attach classes at runtime, then drops every selector in styles.css
// that is not referenced. Output overwrites styles.css in place so the
// deploy pipeline preserves filenames and paths.
//
// Run with `npm run optimize-css` (devDependency `purgecss`) — invoked
// from `.github/workflows/deploy-s3.yml` after prebuild generation and
// before the `npm run minify-assets` step.
//
// Safelist rationale: the runtime tone-coder in js/article-runtime.js
// adds `intel-tone-{critical,high,medium,low,source}` and
// `article-intel-table` to nodes that match content patterns; the
// chart/network/treemap helpers add `d3-{treemap,network,swot-chart}-wrapper`;
// mermaid-init adds `mermaid` / `mermaid--error` to error spans; theme
// toggle adds `is-active`; filter UI toggles `active`. None of these
// classes appear in the source HTML so PurgeCSS would otherwise
// (correctly, by its own model) treat them as unused. Keep this list in
// sync with the JS sources cited above.

module.exports = {
  content: [
    // Root pages (committed + generated by `npm run prebuild`).
    './*.html',
    // News article archive — 4400+ rendered articles with diverse content
    // shapes; PurgeCSS scans all of them so any class used by ANY article
    // survives the purge.
    './news/*.html',
    // Service worker template carries cache-list class names.
    './sw.js.template',
    // Client-side bundles that mutate classList at runtime.
    './js/**/*.js',
    // Build-time HTML/section template emitters — class names appear in
    // string literals here before they ever reach a rendered HTML file.
    './scripts/templates/**/*.js',
    './scripts/generators/**/*.js',
  ],
  css: ['./styles.css'],
  // Overwrite styles.css in place — keeps the existing filename and the
  // <link rel="stylesheet" href="styles.css"> reference in every page.
  output: './styles.css',
  // Variables: keep CSS custom properties so the theme system keeps working
  // even if a variable is only consumed by an inline style or a JS
  // computed-style read.
  variables: true,
  // Keyframes: drop @keyframes that aren't referenced by any surviving rule.
  keyframes: true,
  // Font-face: keep all @font-face rules (fontFace: false disables pruning).
  // We ship system fonts only, so no custom @font-face declarations exist in
  // styles.css today, but retaining the rules guards against accidental purges
  // if a web-font is added in future.
  fontFace: false,
  safelist: {
    standard: [
      // Runtime-toggled state classes.
      'active',
      'is-active',
      // Article-runtime tone coder (js/article-runtime.js:109-145).
      'intel-tone-critical',
      'intel-tone-high',
      'intel-tone-medium',
      'intel-tone-low',
      'intel-tone-source',
      'article-intel-table',
      // Chart wrappers added by D3 helpers.
      'd3-treemap-wrapper',
      'd3-network-wrapper',
      'd3-swot-chart-wrapper',
      // Mermaid runtime (js/mermaid-init.js).
      'mermaid',
      'mermaid--error',
    ],
    deep: [
      // Mermaid emits SVGs with classes like `flowchart`, `node`, `edgePath`,
      // `cluster` — keep anything under a .mermaid container intact.
      /^mermaid/,
      // Chart.js / D3 helpers may add deep descendants.
      /^d3-/,
      // Article tone coder cascades may target descendants of toned blocks.
      /^intel-tone-/,
    ],
    greedy: [
      // Theme system — html[data-theme='light'|'dark'] selectors targeting
      // any class. Without this, the purger drops selectors whose ONLY
      // ancestor is the theme attribute selector.
      /\[data-theme=/,
    ],
  },
};
