// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** AR dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_AR = {
    votingOverview: 'نظرة عامة على التصويت',
    totalVotes: 'إجمالي الأصوات',
    adopted: 'معتمدة',
    rejected: 'مرفوضة',
    anomalies: 'شذوذات',
    politicalGroupCohesion: 'تماسك المجموعات السياسية',
    groupCohesionRates: 'معدلات تماسك المجموعات',
    cohesionPct: 'التماسك %',
    scheduledActivity: 'النشاط المجدول',
    plenaryEvents: 'فعاليات الجلسة العامة',
    committeeMeetings: 'اجتماعات اللجان',
    documents: 'الوثائق',
    pipelineProcedures: 'إجراءات خط الأنابيب',
    parliamentaryQuestions: 'الأسئلة البرلمانية',
    questionsFiled: 'الأسئلة المقدمة',
    bottleneckProcedures: 'إجراءات الاختناق',
    feedActivity: 'نشاط التغذية',
    adoptedTexts: 'النصوص المعتمدة',
    events: 'الفعاليات',
    procedures: 'الإجراءات',
    mepUpdates: 'تحديثات الأعضاء',
    activitySummary: 'ملخص النشاط',
    totalItems: 'إجمالي العناصر',
    feedBreakdown: 'توزيع التغذية',
    items: 'العناصر',
    pipelineHealth: 'صحة خط الأنابيب',
    healthScore: 'درجة الصحة',
    throughput: 'معدل الإنتاجية',
    status: 'الحالة',
    pipelineStrong: 'قوي',
    pipelineModerate: 'معتدل',
    pipelineWeak: 'ضعيف',
    committeeOverview: 'نظرة عامة على اللجان',
    totalCommittees: 'إجمالي اللجان',
    activeCommittees: 'اللجان النشطة',
    activityRate: 'معدل النشاط',
    documentsProduced: 'الوثائق المنتجة',
    documentOutputByCommittee: 'إنتاج الوثائق حسب اللجنة',
    documentsPerCommittee: 'الوثائق لكل لجنة',
    coalitionAlignment: 'توافق التحالف',
    alignmentScore: 'درجة التوافق',
    votingBlocs: 'كتل التصويت',
    coalitionShift: 'تحول التحالف',
    coalitionStrengthening: 'تعزيز',
    coalitionWeakening: 'إضعاف',
    coalitionStable: 'مستقر',
    coalitionRadarChart: 'رادار التحالف',
    pipelineStatus: 'حالة الإجراءات',
    onTrack: 'في المسار',
    delayed: 'متأخر',
    blocked: 'محظور',
    fastTracked: 'مسار سريع',
    pipelineStatusChart: 'مخطط حالة الإجراءات',
    trendAnalysis: 'تحليل الاتجاهات',
    weekOverWeek: 'أسبوع إلى أسبوع',
    monthOverMonth: 'شهر إلى شهر',
    trendImproving: 'تحسن',
    trendDeclining: 'تراجع',
    trendStableLabel: 'مستقر',
    activityTrendChart: 'اتجاه النشاط',
    stakeholderImpact: 'تأثير أصحاب المصلحة',
    impactScore: 'درجة التأثير',
    impactPositive: 'إيجابي',
    impactNegative: 'سلبي',
    impactNeutral: 'محايد',
};
//# sourceMappingURL=ar.js.map