// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** EN dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_EN = {
    votingOverview: 'Voting Overview',
    totalVotes: 'Total Votes',
    adopted: 'Adopted',
    rejected: 'Rejected',
    anomalies: 'Anomalies',
    politicalGroupCohesion: 'Political Group Cohesion',
    groupCohesionRates: 'Group Cohesion Rates',
    cohesionPct: 'Cohesion %',
    scheduledActivity: 'Scheduled Activity',
    plenaryEvents: 'Plenary Events',
    committeeMeetings: 'Committee Meetings',
    documents: 'Documents',
    pipelineProcedures: 'Pipeline Procedures',
    parliamentaryQuestions: 'Parliamentary Questions',
    questionsFiled: 'Questions Filed',
    bottleneckProcedures: 'Bottleneck Procedures',
    feedActivity: 'Feed Activity',
    adoptedTexts: 'Adopted Texts',
    events: 'Events',
    procedures: 'Procedures',
    mepUpdates: 'MEP Updates',
    activitySummary: 'Activity Summary',
    totalItems: 'Total Items',
    feedBreakdown: 'Feed Breakdown',
    items: 'Items',
    pipelineHealth: 'Pipeline Health',
    healthScore: 'Health Score',
    throughput: 'Throughput',
    status: 'Status',
    pipelineStrong: 'Strong',
    pipelineModerate: 'Moderate',
    pipelineWeak: 'Weak',
    committeeOverview: 'Committee Overview',
    totalCommittees: 'Total Committees',
    activeCommittees: 'Active Committees',
    activityRate: 'Activity Rate',
    documentsProduced: 'Documents Produced',
    documentOutputByCommittee: 'Document Output by Committee',
    documentsPerCommittee: 'Documents per Committee',
    coalitionAlignment: 'Coalition Alignment',
    alignmentScore: 'Alignment Score',
    votingBlocs: 'Voting Blocs',
    coalitionShift: 'Coalition Shift',
    coalitionStrengthening: 'Strengthening',
    coalitionWeakening: 'Weakening',
    coalitionStable: 'Stable',
    coalitionRadarChart: 'Coalition Radar',
    pipelineStatus: 'Pipeline Status',
    onTrack: 'On Track',
    delayed: 'Delayed',
    blocked: 'Blocked',
    fastTracked: 'Fast-Tracked',
    pipelineStatusChart: 'Pipeline Status Chart',
    trendAnalysis: 'Trend Analysis',
    weekOverWeek: 'Week-over-Week',
    monthOverMonth: 'Month-over-Month',
    trendImproving: 'Improving',
    trendDeclining: 'Declining',
    trendStableLabel: 'Stable',
    activityTrendChart: 'Activity Trend',
    stakeholderImpact: 'Stakeholder Impact',
    impactScore: 'Impact Score',
    impactPositive: 'Positive',
    impactNegative: 'Negative',
    impactNeutral: 'Neutral',
};
//# sourceMappingURL=en.js.map