// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** NO dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_NO = {
    votingOverview: 'Avstemningsoversikt',
    totalVotes: 'Totale stemmer',
    adopted: 'Vedtatt',
    rejected: 'Avvist',
    anomalies: 'Avvik',
    politicalGroupCohesion: 'Politisk gruppesamhold',
    groupCohesionRates: 'Gruppesamhold',
    cohesionPct: 'Samhold %',
    scheduledActivity: 'Planlagt aktivitet',
    plenaryEvents: 'Plenarmøter',
    committeeMeetings: 'Komitémøter',
    documents: 'Dokumenter',
    pipelineProcedures: 'Pipeline-prosedyrer',
    parliamentaryQuestions: 'Parlamentariske spørsmål',
    questionsFiled: 'Innsendte spørsmål',
    bottleneckProcedures: 'Flaskehalsprosedyrer',
    feedActivity: 'Feed-aktivitet',
    adoptedTexts: 'Vedtatte tekster',
    events: 'Hendelser',
    procedures: 'Prosedyrer',
    mepUpdates: 'MEP-oppdateringer',
    activitySummary: 'Aktivitetssammendrag',
    totalItems: 'Totale elementer',
    feedBreakdown: 'Feed-fordeling',
    items: 'Elementer',
    pipelineHealth: 'Pipeline-helse',
    healthScore: 'Helsescore',
    throughput: 'Gjennomstrømning',
    status: 'Status',
    pipelineStrong: 'Sterk',
    pipelineModerate: 'Moderat',
    pipelineWeak: 'Svak',
    committeeOverview: 'Komitéoversikt',
    totalCommittees: 'Totale komiteer',
    activeCommittees: 'Aktive komiteer',
    activityRate: 'Aktivitetsrate',
    documentsProduced: 'Produserte dokumenter',
    documentOutputByCommittee: 'Dokumentproduksjon per komité',
    documentsPerCommittee: 'Dokumenter per komité',
    coalitionAlignment: 'Koalisjonsretting',
    alignmentScore: 'Retningsscore',
    votingBlocs: 'Stemmeblokker',
    coalitionShift: 'Koalisjonsskifte',
    coalitionStrengthening: 'Styrking',
    coalitionWeakening: 'Svekkelse',
    coalitionStable: 'Stabil',
    coalitionRadarChart: 'Koalisjonsradar',
    pipelineStatus: 'Pipeline-status',
    onTrack: 'På rett spor',
    delayed: 'Forsinket',
    blocked: 'Blokkert',
    fastTracked: 'Hurtigspor',
    pipelineStatusChart: 'Pipeline-statusdiagram',
    trendAnalysis: 'Trendanalyse',
    weekOverWeek: 'Uke-til-uke',
    monthOverMonth: 'Måned-til-måned',
    trendImproving: 'Forbedring',
    trendDeclining: 'Nedgang',
    trendStableLabel: 'Stabil',
    activityTrendChart: 'Aktivitetstrend',
    stakeholderImpact: 'Interessentpåvirkning',
    impactScore: 'Påvirkningsscore',
    impactPositive: 'Positiv',
    impactNegative: 'Negativ',
    impactNeutral: 'Nøytral',
};
//# sourceMappingURL=no.js.map