// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Generators/PoliticalIntelligence/Descriptions/RunTypesDescriptions
 * @description Per-language descriptions for each canonical daily-analysis
 * run type. Split out of the monolithic
 * `political-intelligence-descriptions.ts` (Refactor 8/8).
 */

import type { LanguageCode } from '../../../types/index.js';

/** Per-language descriptions for each canonical run type. */
export const RUN_TYPE_DESCRIPTIONS: Readonly<Record<string, Record<LanguageCode, string>>> = {
  breaking: {
    en: 'Fast-turnaround breaking-news analysis of a single European Parliament event — classification, stakeholder map, SWOT, risk scoring and scenario forecast produced within hours.',
    sv: 'Snabb analys av en enskild Europaparlamentshändelse — klassificering, intressentkarta, SWOT, riskpoängsättning och scenarioprognos producerad inom timmar.',
    da: 'Hurtig analyse af en enkelt Europa-Parlament-hændelse — klassificering, interessentkort, SWOT, risikoscoring og scenarieprognose produceret inden for timer.',
    no: 'Rask analyse av en enkelt EP-hendelse — klassifisering, interessentkart, SWOT, risikoscoring og scenarioprognose produsert innen timer.',
    fi: 'Nopea analyysi yksittäisestä Euroopan parlamentin tapahtumasta — luokittelu, sidosryhmäkartta, SWOT, riskipisteytys ja skenaarioennuste muutamassa tunnissa.',
    de: 'Schnellanalyse eines einzelnen EP-Ereignisses — Klassifikation, Stakeholder-Karte, SWOT, Risikobewertung und Szenario­prognose innerhalb weniger Stunden.',
    fr: 'Analyse rapide d’un événement unique du Parlement européen — classification, cartographie des parties prenantes, SWOT, notation des risques et prévision de scénarios en quelques heures.',
    es: 'Análisis rápido de un único evento del Parlamento Europeo — clasificación, mapa de partes interesadas, SWOT, puntuación de riesgo y pronóstico de escenarios en horas.',
    nl: 'Snelle analyse van één enkele EP-gebeurtenis — classificatie, stakeholder-kaart, SWOT, risicoscoring en scenarioprognose binnen enkele uren.',
    ar: 'تحليل سريع لحدث واحد في البرلمان الأوروبي — تصنيف، خريطة أصحاب المصلحة، SWOT، تسجيل المخاطر وتوقّع السيناريوهات خلال ساعات.',
    he: 'ניתוח מהיר של אירוע יחיד בפרלמנט האירופי — סיווג, מפת בעלי עניין, SWOT, ציוני סיכון ותחזית תרחישים תוך שעות.',
    ja: '欧州議会の単一事象に対する迅速分析 — 分類、ステークホルダー・マップ、SWOT、リスクスコア、シナリオ予測を数時間で提供。',
    ko: '유럽의회 단일 사건에 대한 신속 분석 — 분류·이해관계자 지도·SWOT·위험 점수·시나리오 예측을 수 시간 내 제공.',
    zh: '欧洲议会单一事件的快速分析 — 在数小时内产出分类、利益相关者图谱、SWOT、风险评分与情景预测。',
  },
  'week-in-review': {
    en: 'Weekly retrospective: the past seven days of European Parliament activity distilled into coalition trends, vote tallies, SWOT synthesis and forward indicators.',
    sv: 'Veckoretrospektiv: Europaparlamentets senaste sju dagar destillerade till koalitionstrender, röstsummor, SWOT-syntes och framåtriktade indikatorer.',
    da: 'Ugentlig tilbageskuelse: syv dages Europa-Parlamentsaktivitet destilleret til koalitionstendenser, stemmetællinger, SWOT-syntese og fremadrettede indikatorer.',
    no: 'Ukentlig tilbakeblikk: syv dager med EP-aktivitet destillert til koalisjonstrender, stemmesummer, SWOT-syntese og fremoverrettede indikatorer.',
    fi: 'Viikkokatsaus: Euroopan parlamentin seitsemän päivän toiminta tiivistettynä koalitiotrendeiksi, äänitaulukoiksi, SWOT-synteesiksi ja ennakoiviksi indikaattoreiksi.',
    de: 'Wochenrückblick: Sieben Tage EP-Aktivität destilliert zu Koalitionstrends, Abstimmungs­tableaus, SWOT-Synthese und vorausschauenden Indikatoren.',
    fr: 'Rétrospective hebdomadaire : sept jours d’activité du Parlement européen distillés en tendances de coalition, décomptes de votes, synthèse SWOT et indicateurs prospectifs.',
    es: 'Retrospectiva semanal: siete días de actividad del Parlamento Europeo destilados en tendencias de coalición, recuentos de votos, síntesis SWOT e indicadores prospectivos.',
    nl: 'Wekelijkse terugblik: zeven dagen EP-activiteit samengevat in coalitietrends, stemtellingen, SWOT-synthese en vooruitblikkende indicatoren.',
    ar: 'استعراض أسبوعي: سبعة أيام من نشاط البرلمان الأوروبي مركّزة في اتجاهات تحالف، إحصاءات تصويت، تركيب SWOT ومؤشرات استشرافية.',
    he: 'סיכום שבועי: שבעה ימי פעילות בפרלמנט האירופי מזוקקים למגמות קואליציה, ספירת הצבעות, סינתזת SWOT ומדדים צופי־פני־עתיד.',
    ja: '週次振り返り：欧州議会の直近7日間を連立傾向・投票集計・SWOT 統合・先行指標へ凝縮。',
    ko: '주간 회고: 유럽의회의 지난 7일간 활동을 연정 동향·표결 집계·SWOT 종합·선행 지표로 압축.',
    zh: '每周回顾：将欧洲议会过去七天的活动凝练为联盟趋势、投票统计、SWOT 综合与前瞻指标。',
  },
  'month-in-review': {
    en: 'Monthly retrospective: a four-week synthesis of EP legislative flow, coalition stability, anomalous votes and cumulative political-risk delta versus the prior month.',
    sv: 'Månadsretrospektiv: en fyraveckorssyntes av EP:s lagstiftningsflöde, koalitionsstabilitet, avvikande röster och kumulativ politisk-risk-delta jämfört med föregående månad.',
    da: 'Månedlig tilbageskuelse: en fire-ugers syntese af EP’s lovgivningsflow, koalitionsstabilitet, afvigende stemmer og kumulativt politisk risikodelta mod forrige måned.',
    no: 'Månedlig tilbakeblikk: en fire-ukers syntese av EPs lovgivningsflyt, koalisjonsstabilitet, avvikende stemmer og kumulativt politisk risikodelta mot forrige måned.',
    fi: 'Kuukausikatsaus: EU-parlamentin neljän viikon lainsäädäntövirran, koalition vakauden, poikkeavien äänestysten ja kumulatiivisen poliittisen riskin delta edelliseen kuukauteen nähden.',
    de: 'Monatsrückblick: vierwöchige Synthese des EP-Gesetzgebungsflusses, der Koalitionsstabilität, anomaler Abstimmungen und des kumulativen Politikrisiko-Deltas gegenüber dem Vormonat.',
    fr: 'Rétrospective mensuelle : synthèse sur quatre semaines du flux législatif du PE, stabilité des coalitions, votes atypiques et delta cumulatif du risque politique par rapport au mois précédent.',
    es: 'Retrospectiva mensual: síntesis de cuatro semanas del flujo legislativo del PE, estabilidad de coaliciones, votos anómalos y delta acumulado de riesgo político frente al mes anterior.',
    nl: 'Maandelijks overzicht: een vierwekelijkse synthese van EP-wetgevingsstroom, coalitiestabiliteit, afwijkende stemmingen en cumulatieve politieke-risico-delta t.o.v. de vorige maand.',
    ar: 'استعراض شهري: تركيب أربعة أسابيع من تدفّق التشريع في البرلمان الأوروبي، استقرار التحالفات، الأصوات الشاذّة، ودلتا المخاطر السياسية التراكمية مقابل الشهر السابق.',
    he: 'סיכום חודשי: סינתזה של ארבעה שבועות מזרימה חקיקתית בפרלמנט האירופי, יציבות קואליציה, הצבעות חריגות ודלתת סיכון פוליטי מצטברת מול החודש הקודם.',
    ja: '月次振り返り：欧州議会の 4 週間分の立法フロー・連立安定性・異常投票・前月比の累積政治リスク差分を統合。',
    ko: '월간 회고: 유럽의회의 4주간 입법 흐름·연정 안정성·이상 표결·전월 대비 누적 정치 위험 델타를 종합.',
    zh: '月度回顾：将欧洲议会四周的立法流、联盟稳定性、异常投票以及相对上月的累计政治风险增量整合为综合分析。',
  },
  'week-ahead': {
    en: 'Forward-looking weekly brief: the next seven days of scheduled plenary, committee and trilogue activity, with risk scoring and coalition stress indicators.',
    sv: 'Framåtblickande veckobrief: de kommande sju dagarnas plenar-, utskotts- och trilogaktiviteter, med riskpoängsättning och indikatorer på koalitionsstress.',
    da: 'Fremadrettet ugebrief: de kommende syv dages plenar-, udvalgs- og trilog-aktiviteter med risikoscoring og indikatorer for koalitionspres.',
    no: 'Fremoverrettet ukebrief: de neste syv dagers plenum-, komité- og trilogaktivitet med risikoscoring og indikatorer for koalisjonspress.',
    fi: 'Ennakoiva viikkokatsaus: seuraavien seitsemän päivän täysistunto-, valiokunta- ja trilogiatoiminta, riskipisteytykset ja koalitiokuormaindikaattorit.',
    de: 'Vorausschauende Wochenvorschau: die nächsten sieben Tage geplanter Plenar-, Ausschuss- und Trilog-Aktivität mit Risikobewertung und Koalitionsstress-Indikatoren.',
    fr: 'Note hebdomadaire prospective : les sept prochains jours d’activité plénière, en commission et en trilogue, avec notation des risques et indicateurs de tension de coalition.',
    es: 'Nota semanal prospectiva: los próximos siete días de actividad plenaria, de comisión y de trílogo, con puntuación de riesgo e indicadores de tensión de coalición.',
    nl: 'Vooruitkijkend weekoverzicht: de komende zeven dagen plenaire, commissie- en trilo­og-activiteit, met risicoscoring en indicatoren voor coalitiedruk.',
    ar: 'ملخص أسبوعي استشرافي: الأيام السبعة المقبلة من أنشطة الجلسة العامة واللجان والترايلوج، مع تسجيل المخاطر ومؤشرات إجهاد التحالف.',
    he: 'תקציר שבועי צופה פני עתיד: שבעת הימים הקרובים של פעילות מליאה, ועדות וטרילוג, עם ציוני סיכון ומדדי מתח קואליציוני.',
    ja: '先行週次ブリーフ：今後 7 日間の本会議・委員会・トリローグの予定を、リスクスコアと連立ストレス指標付きで提示。',
    ko: '선행 주간 브리프: 향후 7일의 본회의·위원회·삼자협의 일정에 위험 점수와 연정 스트레스 지표를 결합.',
    zh: '前瞻周报：未来七天的全体会议、委员会与三方谈判议程，附风险评分与联盟压力指标。',
  },
  'month-ahead': {
    en: 'Forward-looking monthly brief: the next four weeks of EP scheduled activity, dossier pipeline, anticipated votes and strategic inflection points.',
    sv: 'Framåtblickande månadsbrief: de kommande fyra veckornas schemalagda EP-aktiviteter, dossierflöde, förväntade röster och strategiska vändpunkter.',
    da: 'Fremadrettet månedsbrief: de kommende fire ugers EP-aktiviteter, dossierpipeline, forventede afstemninger og strategiske vendepunkter.',
    no: 'Fremoverrettet månedsbrief: de neste fire ukenes planlagte EP-aktivitet, dossierløp, forventede stemmer og strategiske vendepunkter.',
    fi: 'Ennakoiva kuukausikatsaus: seuraavien neljän viikon EP-aktiviteetit, asiakokonaisuuksien putki, odotetut äänestykset ja strategiset taitepisteet.',
    de: 'Vorausschauende Monatsvorschau: die nächsten vier Wochen geplanter EP-Aktivität, Dossier-Pipeline, erwartete Abstimmungen und strategische Wendepunkte.',
    fr: 'Note mensuelle prospective : les quatre prochaines semaines d’activité programmée du PE, pipeline de dossiers, votes anticipés et points d’inflexion stratégiques.',
    es: 'Nota mensual prospectiva: las próximas cuatro semanas de actividad programada del PE, cartera de expedientes, votaciones previstas y puntos de inflexión estratégicos.',
    nl: 'Vooruitkijkend maandoverzicht: de komende vier weken geplande EP-activiteit, dossier­pipeline, verwachte stemmingen en strategische kantelpunten.',
    ar: 'ملخص شهري استشرافي: الأسابيع الأربعة القادمة من نشاط البرلمان الأوروبي، خط سير الملفات، التصويتات المتوقعة ونقاط التحوّل الاستراتيجية.',
    he: 'תקציר חודשי צופה פני עתיד: ארבעת השבועות הקרובים בפעילות הפרלמנט האירופי, קו תיקים, הצבעות צפויות ונקודות מפנה אסטרטגיות.',
    ja: '先行月次ブリーフ：今後 4 週間の欧州議会予定、法案パイプライン、予定された投票、戦略的転換点を提示。',
    ko: '선행 월간 브리프: 향후 4주간의 유럽의회 일정·법안 파이프라인·예정 표결·전략적 전환점을 제시.',
    zh: '前瞻月报：欧洲议会未来四周的日程、议题流水线、预期投票与战略拐点。',
  },
  'year-ahead': {
    en: 'Forward-looking annual brief: the next twelve months of EP agenda, legislative priorities and strategic risk surfaces.',
    sv: 'Framåtblickande årsbrief: EP:s agenda, lagstiftnings­prioriteringar och strategiska riskytor de kommande tolv månaderna.',
    da: 'Fremadrettet årsbrief: EP-dagsorden, lovgivnings­prioriteter og strategiske risikoflader de kommende tolv måneder.',
    no: 'Fremoverrettet årsbrief: EPs agenda, lovgivnings­prioriteringer og strategiske risikoflater de neste tolv månedene.',
    fi: 'Ennakoiva vuosikatsaus: EP:n asialista, lainsäädäntö­prioriteetit ja strategiset riskipinnat tulevina kahtenatoista kuukautena.',
    de: 'Vorausschauende Jahres­vorschau: EP-Agenda, Gesetzgebungs­prioritäten und strategische Risikoflächen der nächsten zwölf Monate.',
    fr: 'Note annuelle prospective : agenda du PE, priorités législatives et surfaces de risque stratégique des douze prochains mois.',
    es: 'Nota anual prospectiva: agenda del PE, prioridades legislativas y superficies de riesgo estratégico de los próximos doce meses.',
    nl: 'Vooruitkijkend jaaroverzicht: EP-agenda, wetgevings­prioriteiten en strategische risico­vlakken voor de komende twaalf maanden.',
    ar: 'ملخص سنوي استشرافي: جدول أعمال البرلمان الأوروبي، الأولويات التشريعية وأسطح المخاطر الاستراتيجية للأشهر الاثني عشر المقبلة.',
    he: 'תקציר שנתי צופה פני עתיד: סדר היום של הפרלמנט האירופי, סדרי עדיפויות חקיקתיים ומשטחי סיכון אסטרטגיים בשנה הקרובה.',
    ja: '先行年次ブリーフ：今後 12 か月の欧州議会アジェンダ・立法優先事項・戦略リスク面を提示。',
    ko: '선행 연간 브리프: 향후 12개월의 유럽의회 의제·입법 우선순위·전략적 위험 표면을 제시.',
    zh: '前瞻年报：欧洲议会未来十二个月的议程、立法优先事项与战略风险面。',
  },
  'year-in-review': {
    en: 'Annual retrospective: twelve months of EP activity synthesized into coalition maps, dossier throughput, major inflection points and cumulative political-risk trajectory.',
    sv: 'Årsretrospektiv: tolv månaders EP-aktivitet sammanställd till koalitions­kartor, dossiergenomströmning, större vändpunkter och kumulativ politisk-risk-bana.',
    da: 'Årlig tilbageskuelse: tolv måneders EP-aktivitet syntetiseret til koalitionskort, dossiergennemløb, større vendepunkter og kumulativt politisk risikoforløb.',
    no: 'Årlig tilbakeblikk: tolv måneders EP-aktivitet syntetisert til koalisjonskart, dossiergjennomstrømning, store vendepunkter og kumulativ politisk risikobane.',
    fi: 'Vuosikatsaus: kahdentoista kuukauden EP-toiminta tiivistettynä koalitio­kartoiksi, asiakokonaisuuksien läpivirtaukseksi, taitepisteiksi ja kumulatiiviseksi poliittiseksi riskipoluksi.',
    de: 'Jahresrückblick: zwölf Monate EP-Aktivität synthetisiert zu Koalitions­karten, Dossier-Durchsatz, wichtigen Wendepunkten und kumulativer Politikrisiko-Trajektorie.',
    fr: 'Rétrospective annuelle : douze mois d’activité du PE synthétisés en cartes de coalitions, débit des dossiers, principaux points d’inflexion et trajectoire cumulative du risque politique.',
    es: 'Retrospectiva anual: doce meses de actividad del PE sintetizados en mapas de coaliciones, rendimiento de expedientes, principales puntos de inflexión y trayectoria acumulada de riesgo político.',
    nl: 'Jaaroverzicht: twaalf maanden EP-activiteit samengevat in coalitie­kaarten, dossier­doorstroom, belangrijke kantelpunten en cumulatieve politieke-risico­traject.',
    ar: 'استعراض سنوي: اثنا عشر شهرًا من نشاط البرلمان الأوروبي مركّزة في خرائط تحالف، إنتاجية ملفات، نقاط تحوّل كبرى ومسار مخاطر سياسية تراكمي.',
    he: 'סיכום שנתי: שנים־עשר חודשי פעילות בפרלמנט האירופי בסינתזה של מפות קואליציה, תפוקת תיקים, נקודות מפנה מרכזיות ומסלול סיכון פוליטי מצטבר.',
    ja: '年間振り返り：12 か月の欧州議会活動を連立マップ、法案スループット、主要転換点、累積政治リスク軌道に統合。',
    ko: '연간 회고: 12개월간의 유럽의회 활동을 연정 지도·법안 처리량·주요 전환점·누적 정치 위험 궤적으로 종합.',
    zh: '年度回顾：将欧洲议会十二个月的活动综合为联盟图谱、议题吞吐量、主要拐点和累计政治风险轨迹。',
  },
  'quarter-ahead': {
    en: 'Forward-looking quarterly brief: the next ~90 days (≈3 plenary sessions) of EP scheduled activity, dossier pipeline, anticipated votes, Council Presidency overlay and strategic inflection points.',
    sv: 'Framåtblickande kvartalsbrief: de kommande ~90 dagarnas (≈3 plenarmöten) EP-aktiviteter, dossierflöde, förväntade röster, ordförandeskap och strategiska vändpunkter.',
    da: 'Fremadrettet kvartalsbrief: de kommende ~90 dages (≈3 plenar­møder) EP-aktivitet, dossierpipeline, forventede afstemninger, formandskabs­overlay og strategiske vendepunkter.',
    no: 'Fremoverrettet kvartalsbrief: de neste ~90 dagene (≈3 plenum) med EP-aktivitet, dossierløp, forventede stemmer, formannskapsoverlegg og strategiske vendepunkter.',
    fi: 'Ennakoiva neljännesvuosikatsaus: seuraavien ~90 päivän (≈3 täysistuntoa) EP-aktiviteetit, asiakokonaisuuksien putki, odotetut äänestykset, puheenjohtajakauden konteksti ja strategiset taitepisteet.',
    de: 'Vorausschauende Quartalsvorschau: die nächsten ~90 Tage (≈3 Plenar­tagungen) geplanter EP-Aktivität, Dossier-Pipeline, erwartete Abstimmungen, Ratspräsidentschafts-Overlay und strategische Wendepunkte.',
    fr: 'Note trimestrielle prospective : les ~90 prochains jours (≈3 sessions plénières) d’activité programmée du PE, pipeline de dossiers, votes anticipés, contexte de Présidence du Conseil et points d’inflexion stratégiques.',
    es: 'Nota trimestral prospectiva: los próximos ~90 días (≈3 sesiones plenarias) de actividad programada del PE, cartera de expedientes, votaciones previstas, contexto de Presidencia y puntos de inflexión estratégicos.',
    nl: 'Vooruitkijkend kwartaalbrief: de komende ~90 dagen (≈3 plenaire sessies) geplande EP-activiteit, dossierpipeline, verwachte stemmingen, voorzitterschapscontext en strategische kantelpunten.',
    ar: 'ملخص ربعي استشرافي: الـ 90 يومًا القادمة (≈3 جلسات عامة) من نشاط البرلمان الأوروبي، خط سير الملفات، التصويتات المتوقعة، سياق رئاسة المجلس ونقاط التحوّل الاستراتيجية.',
    he: 'תקציר רבעוני צופה פני עתיד: ~90 הימים הקרובים (≈3 מליאות) בפעילות הפרלמנט האירופי, קו תיקים, הצבעות צפויות, רקע נשיאות המועצה ונקודות מפנה אסטרטגיות.',
    ja: '先行四半期ブリーフ：今後 ~90 日 (≈3 本会議) の欧州議会予定、法案パイプライン、予定投票、理事会議長国コンテキスト、戦略的転換点を提示。',
    ko: '선행 분기 브리프: 향후 ~90일 (≈3회 본회의) 유럽의회 일정·법안 파이프라인·예정 표결·이사회 의장국 맥락·전략적 전환점을 제시.',
    zh: '前瞻季报：欧洲议会未来约 90 天（≈3 次全体会议）的日程、议题流水线、预期投票、理事会主席国背景与战略拐点。',
  },
  'quarter-in-review': {
    en: 'Quarterly retrospective: ≈90 days of EP activity synthesized into coalition trajectory, dossier throughput delta, anomalous votes and rolling political-risk trend versus the prior quarter.',
    sv: 'Kvartalsretrospektiv: ≈90 dagars EP-aktivitet sammanställd till koalitionsbana, dossierflödesdelta, avvikande röster och rullande politisk-risk-trend mot föregående kvartal.',
    da: 'Kvartalstilbageblik: ≈90 dages EP-aktivitet syntetiseret til koalitionsbane, dossier­gennemløbs­delta, afvigende afstemninger og rullende politisk risikotrend mod forrige kvartal.',
    no: 'Kvartalstilbakeblikk: ≈90 dagers EP-aktivitet syntetisert til koalisjonsbane, dossiergjennomstrømnings­delta, avvikende stemmer og rullende politisk risikotrend mot forrige kvartal.',
    fi: 'Neljännes­vuosi­katsaus: ≈90 päivän EP-toiminta tiivistettynä koalitio­kehitykseksi, asiakokonaisuuksien läpivirtauksen muutokseksi, poikkeaviksi äänestyksiksi ja rullaavaksi poliittiseksi riskitrendiksi edelliseen neljännekseen verrattuna.',
    de: 'Quartalsrückblick: ≈90 Tage EP-Aktivität synthetisiert zu Koalitions­trajektorie, Dossier-Durchsatzdelta, anomalen Abstimmungen und rollender Politikrisiko-Tendenz gegenüber dem Vorquartal.',
    fr: 'Rétrospective trimestrielle : ≈90 jours d’activité du PE synthétisés en trajectoire de coalition, delta de débit des dossiers, votes atypiques et tendance glissante du risque politique par rapport au trimestre précédent.',
    es: 'Retrospectiva trimestral: ≈90 días de actividad del PE sintetizados en trayectoria de coalición, delta de rendimiento de expedientes, votos anómalos y tendencia rodante de riesgo político frente al trimestre anterior.',
    nl: 'Kwartaalterugblik: ≈90 dagen EP-activiteit samengevat in coalitietraject, dossier­doorstroomdelta, afwijkende stemmingen en rolling politieke-risicotrend t.o.v. het vorige kwartaal.',
    ar: 'استعراض ربعي: ≈90 يومًا من نشاط البرلمان الأوروبي مركّزة في مسار التحالف، فارق إنتاجية الملفات، الأصوات الشاذّة، واتجاه مخاطر سياسية متحرك مقابل الربع السابق.',
    he: 'סיכום רבעוני: ≈90 ימי פעילות בפרלמנט האירופי בסינתזה של מסלול קואליציה, דלתת תפוקת תיקים, הצבעות חריגות ומגמת סיכון פוליטי מתגלגלת מול הרבעון הקודם.',
    ja: '四半期振り返り：≈90 日分の欧州議会活動を連立軌道、法案スループット差分、異常投票、前四半期比のローリング政治リスク傾向へ統合。',
    ko: '분기 회고: ≈90일간의 유럽의회 활동을 연정 궤적·법안 처리량 델타·이상 표결·전분기 대비 롤링 정치 위험 추세로 종합.',
    zh: '季度回顾：将欧洲议会约 90 天的活动综合为联盟轨迹、议题吞吐量增量、异常投票，以及相对上季度的滚动政治风险趋势。',
  },
  'term-outlook': {
    en: 'Multi-year electoral outlook spanning today through the next EP election: coalition trajectory, mandate delivery progress, Spitzenkandidaten signals and seat-projection bands at 6/12/24/36 months.',
    sv: 'Flerårig valutsikt från idag fram till nästa EP-val: koalitionsbana, mandatleverans, Spitzenkandidaten-signaler och mandatprognosband vid 6/12/24/36 månader.',
    da: 'Flerårig valgudsigt fra i dag til næste EP-valg: koalitionsbane, mandat­leverance, Spitzenkandidaten-signaler og mandatprognose­bånd ved 6/12/24/36 måneder.',
    no: 'Flerårig valgutsikt fra i dag til neste EP-valg: koalisjonsbane, mandatlevering, Spitzenkandidaten-signaler og mandatprognose­bånd ved 6/12/24/36 måneder.',
    fi: 'Monivuotinen vaalinäkymä tästä päivästä seuraaviin EP-vaaleihin: koalitiokehitys, mandaatin toteutuminen, Spitzenkandidaten-signaalit ja paikkaennustekaistat 6/12/24/36 kuukauden horisontilla.',
    de: 'Mehrjähriger Wahlausblick von heute bis zur nächsten EP-Wahl: Koalitions­trajektorie, Mandats­fortschritt, Spitzenkandidaten-Signale und Sitz­projektions­bänder bei 6/12/24/36 Monaten.',
    fr: 'Perspective électorale pluriannuelle de l’aujourd’hui jusqu’à la prochaine élection du PE : trajectoire de coalition, livraison du mandat, signaux Spitzenkandidaten et fourchettes de projection de sièges à 6/12/24/36 mois.',
    es: 'Perspectiva electoral plurianual desde hoy hasta la próxima elección del PE: trayectoria de coalición, cumplimiento del mandato, señales Spitzenkandidaten y bandas de proyección de escaños a 6/12/24/36 meses.',
    nl: 'Meerjarig verkiezings­vooruitzicht van vandaag tot de volgende EP-verkiezing: coalitietraject, mandaat­voortgang, Spitzenkandidaten-signalen en zetelprojectie­banden op 6/12/24/36 maanden.',
    ar: 'آفاق انتخابية متعدّدة السنوات من اليوم حتى الانتخابات الأوروبية المقبلة: مسار التحالف، تقدّم تنفيذ التفويض، إشارات المرشّحين الرئيسيين، ونطاقات إسقاط المقاعد عند 6/12/24/36 شهرًا.',
    he: 'תחזית רב־שנתית בחירות מהיום ועד הבחירות הבאות לפרלמנט האירופי: מסלול קואליציה, מימוש מנדט, סיגנלים מועמדי־צמרת וטווחי תחזית מושבים ב־6/12/24/36 חודשים.',
    ja: '次期欧州議会選挙までの複数年選挙アウトルック：連立軌道、公約実現進捗、Spitzenkandidaten シグナル、6/12/24/36 か月の議席投影帯。',
    ko: '다음 유럽의회 선거까지 다년간 전망: 연정 궤적, 공약 이행 진척, Spitzenkandidaten 시그널, 6/12/24/36개월 의석 투영 구간.',
    zh: '面向下届欧洲议会选举的多年期电选展望：联盟轨迹、政纲履行进度、Spitzenkandidaten 信号以及 6/12/24/36 个月的议席投射区间。',
  },
  'election-cycle': {
    en: 'Electoral-cycle dual brief: EP-term retrospective scorecard (vote-share delta, mandate fulfilment, defection-flow map) paired with forward seat projections, coalition viability matrix and Spitzenkandidaten arithmetic.',
    sv: 'Valcykel-dubbelbrief: EP-mandatperiodens retrospektiva poäng­tavla (röst­andels­delta, mandatuppfyllelse, defektions­flöde) parad med framåtblickande mandatprognoser, koalitions­livskrafts­matris och Spitzenkandidaten-aritmetik.',
    da: 'Valgcyklus dobbelt-brief: EP-valgperiodens retrospektive score­kort (stemme­andels­delta, mandat­opfyldelse, defektionsflow) parret med fremad­rettede mandatprojektioner, koalitions­levedygtigheds­matrix og Spitzenkandidaten-aritmetik.',
    no: 'Valgsyklus-dobbeltbrief: EP-valgperiodens retrospektive scorekort (stemmeandelsdelta, mandat­oppfyllelse, defeksjons­flyt) sammen med fremoverrettede mandatprojeksjoner, koalisjonslevedyktighets­matrise og Spitzenkandidaten-aritmetikk.',
    fi: 'Vaalisyklin kaksoisbrief: EP-vaalikauden retrospektiivinen tulostaulu (ääniosuus­muutos, mandaatin täyttyminen, defektio­virrat) yhdistettynä eteenpäin katsoviin paikka­ennusteisiin, koalition elinkelpoisuus­matriisiin ja Spitzenkandidaten-aritmetiikkaan.',
    de: 'Wahlzyklus-Doppel­brief: EP-Wahlperioden-Retrospektiv-Scorecard (Stimmen­anteilsdelta, Mandats­erfüllung, Defektions­fluss) gepaart mit Sitz­prognosen, Koalitions­tragfähigkeits­matrix und Spitzenkandidaten-Arithmetik.',
    fr: 'Note duale du cycle électoral : tableau de bord rétrospectif de la mandature européenne (delta de part de voix, accomplissement du mandat, flux de défections) combiné aux projections de sièges, à la matrice de viabilité des coalitions et à l’arithmétique des Spitzenkandidaten.',
    es: 'Nota dual del ciclo electoral: cuadro de mando retrospectivo de la legislatura del PE (delta de cuota de voto, cumplimiento del mandato, flujo de deserciones) emparejado con proyecciones de escaños, matriz de viabilidad de coaliciones y aritmética Spitzenkandidaten.',
    nl: 'Dubbel verkiezingscyclus-brief: retrospectief EP-zittingsperiodescorebord (stemaandeel-delta, mandaatvervulling, defectie­stroom) gekoppeld aan vooruit­blikkende zetelprojecties, coalitie­levensvatbaarheidsmatrix en Spitzenkandidaten-rekenkunde.',
    ar: 'ملخّص مزدوج للدورة الانتخابية: لوحة استعراض رجعية لدورة البرلمان الأوروبي (دلتا حصة الأصوات، تنفيذ التفويض، خريطة الانشقاقات) مرفقة بإسقاطات مقاعد مستقبلية ومصفوفة جدوى التحالفات وحساب المرشحين الرئيسيين.',
    he: 'תקציר כפול של מחזור בחירות: לוח־בקרה רטרוספקטיבי לכהונת הפרלמנט האירופי (דלתת חלק קולות, מימוש מנדט, מפת עריקות) במשולב עם תחזיות מושבים, מטריצת כדאיות קואליציה וחשבון מועמדי־צמרת.',
    ja: '選挙サイクル二部構成ブリーフ：欧州議会会期の振り返り (得票率差分・公約実現・離反フロー) と、議席投影・連立可行性マトリクス・Spitzenkandidaten 算術を併記。',
    ko: '선거 주기 이중 브리프: 유럽의회 임기 회고 (득표율 델타·공약 이행·이탈 흐름)와 의석 투영·연정 실현가능성 매트릭스·Spitzenkandidaten 산술을 결합.',
    zh: '选举周期双重简报：欧洲议会任期回顾计分卡（得票率增量、政纲履行、倒戈流向）与未来议席投射、联盟可行性矩阵及 Spitzenkandidaten 算术并列。',
  },
  'committee-reports': {
    en: 'Dedicated analysis of EP committee reports — rapporteur attribution, amendment tracking, coalition mathematics and projected plenary outcome.',
    sv: 'Dedikerad analys av EP-utskottsrapporter — föredragande­attribuering, ändringsförslags­spårning, koalitions­matematik och prognostiserat plenar­utfall.',
    da: 'Dedikeret analyse af EP-udvalgs­rapporter — ordfører­attribution, ændrings­sporing, koalitions­matematik og forventet plenarresultat.',
    no: 'Dedikert analyse av EP-komitérapporter — ordfører­attribusjon, endrings­sporing, koalisjons­matematikk og forventet plenumsresultat.',
    fi: 'EP:n valiokunta­raporttien kohdennettu analyysi — esittelijän attribuointi, muutosehdotusten seuranta, koalitio­matematiikka ja ennustettu täysistunto­tulos.',
    de: 'Gezielte Analyse der EP-Ausschussberichte — Berichterstatter­zuordnung, Änderungs­verfolgung, Koalitions­mathematik und prognostiziertes Plenar­ergebnis.',
    fr: 'Analyse dédiée des rapports des commissions du PE — attribution du rapporteur, suivi des amendements, mathématiques de coalition et résultat plénier anticipé.',
    es: 'Análisis dedicado de los informes de comisión del PE — atribución de ponente, seguimiento de enmiendas, matemáticas de coalición y resultado plenario previsto.',
    nl: 'Toegewijde analyse van EP-commissieverslagen — rapporteur­attributie, amendements­opvolging, coalitie­wiskunde en verwachte plenaire uitkomst.',
    ar: 'تحليل مكرّس لتقارير لجان البرلمان الأوروبي — إسناد المقرر، تتبع التعديلات، رياضيات التحالف، والنتيجة المتوقعة للجلسة العامة.',
    he: 'ניתוח ייעודי של דוחות ועדות הפרלמנט האירופי — ייחוס דוברי הוועדה, מעקב תיקונים, מתמטיקת קואליציות ותוצאה צפויה במליאה.',
    ja: '欧州議会委員会報告の専門分析 — 報告者の帰属、修正追跡、連立算術、本会議での予測結果。',
    ko: '유럽의회 위원회 보고서에 대한 전용 분석 — 보고위원 귀속, 수정안 추적, 연정 산술, 본회의 예측 결과.',
    zh: '欧洲议会委员会报告的专门分析 — 报告员归属、修正案追踪、联盟数学与全体会议预期结果。',
  },
  motions: {
    en: 'Analysis of motions for resolution — sponsor coalition, signatory threshold, SWOT, amendment risk and comparative historical votes.',
    sv: 'Analys av resolutions­motioner — sponsor­koalition, underskrifts­tröskel, SWOT, ändrings­risk och jämförande historiska röster.',
    da: 'Analyse af beslutnings­forslag — sponsorkoalition, underskriftstærskel, SWOT, ændringsrisiko og sammenlignelige historiske afstemninger.',
    no: 'Analyse av resolusjonsforslag — sponsorkoalisjon, underskriftsterskel, SWOT, endringsrisiko og sammenlignbare historiske stemmer.',
    fi: 'Päätöslauselma­aloitteiden analyysi — esittäjäkoalitio, allekirjoitus­kynnys, SWOT, muutosriski ja vertailevat historialliset äänestykset.',
    de: 'Analyse von Entschließungs­anträgen — Einreicher-Koalition, Unterschriften­schwelle, SWOT, Änderungs­risiko und vergleichbare historische Abstimmungen.',
    fr: 'Analyse des propositions de résolution — coalition de signataires, seuil de signatures, SWOT, risque d’amendement et votes historiques comparables.',
    es: 'Análisis de propuestas de resolución — coalición de proponentes, umbral de firmas, SWOT, riesgo de enmienda y votaciones históricas comparables.',
    nl: 'Analyse van ontwerp­resoluties — coalitie van ondertekenaars, ondertekenings­drempel, SWOT, amendementrisico en vergelijkbare historische stemmingen.',
    ar: 'تحليل مقترحات القرارات — تحالف المقدّمين، عتبة التوقيع، SWOT، مخاطر التعديلات والتصويتات التاريخية المقارنة.',
    he: 'ניתוח הצעות החלטה — קואליציית יוזמים, סף חתימות, SWOT, סיכון תיקונים והצבעות היסטוריות משוות.',
    ja: '決議動議の分析 — 提出者連立、署名閾値、SWOT、修正リスク、比較可能な歴史的投票。',
    ko: '결의안 동의안 분석 — 발의자 연정, 서명 임계값, SWOT, 수정안 위험 및 비교 가능한 과거 표결.',
    zh: '决议动议分析 — 提案联盟、联署门槛、SWOT、修正风险与可比的历史投票。',
  },
  propositions: {
    en: 'Analysis of legislative propositions — rapporteur, co-decision pathway, impact assessment, industry stakeholder map and trilogue risk.',
    sv: 'Analys av lagstiftnings­propositioner — föredragande, medbeslutande­väg, konsekvens­bedömning, branschens intressentkarta och trilogrisk.',
    da: 'Analyse af lovforslag — ordfører, fælles­beslutnings­vej, konsekvens­vurdering, interessentkort for branchen og trilog-risiko.',
    no: 'Analyse av lovforslag — ordfører, medbesluttende­løp, konsekvensvurdering, bransjens interessentkart og trilog-risiko.',
    fi: 'Lakiehdotusten analyysi — esittelijä, yhteispäätös­menettelyn polku, vaikutus­arvio, toimialan sidosryhmä­kartta ja trilogia­riski.',
    de: 'Analyse von Gesetzes­vorschlägen — Berichterstatter, Mitentscheidungs­weg, Folgen­abschätzung, Stakeholder-Karte der Industrie und Trilog-Risiko.',
    fr: 'Analyse des propositions législatives — rapporteur, parcours de codécision, évaluation d’impact, cartographie des parties prenantes sectorielles et risque de trilogue.',
    es: 'Análisis de propuestas legislativas — ponente, vía de codecisión, evaluación de impacto, mapa de partes interesadas del sector y riesgo de trílogo.',
    nl: 'Analyse van wetsvoorstellen — rapporteur, medebeslissings­traject, impact­beoordeling, stakeholder-kaart van de sector en triloog­risico.',
    ar: 'تحليل المقترحات التشريعية — المقرر، مسار التقرير المشترك، تقييم الأثر، خريطة أصحاب المصلحة القطاعيين ومخاطر الترايلوج.',
    he: 'ניתוח הצעות חקיקה — דובר הוועדה, מסלול ההחלטה המשותפת, הערכת השפעה, מפת בעלי עניין ענפיים וסיכון טרילוג.',
    ja: '立法提案の分析 — 報告者、共同決定経路、影響評価、業界ステークホルダー・マップ、トリローグリスク。',
    ko: '입법 제안 분석 — 보고위원, 공동결정 경로, 영향 평가, 산업 이해관계자 지도 및 삼자협의 위험.',
    zh: '立法提案分析 — 报告员、共同决定路径、影响评估、行业利益相关者图谱与三方谈判风险。',
  },
  translate: {
    en: 'Translation run: one published article rendered into all 13 non-English supported languages with per-language quality gates.',
    sv: 'Översättnings­körning: en publicerad artikel översatt till alla 13 icke-engelska språk med kvalitets­portar per språk.',
    da: 'Oversættelses­kørsel: én udgivet artikel oversat til alle 13 ikke-engelske sprog med kvalitetsporte pr. sprog.',
    no: 'Oversettelses­kjøring: én publisert artikkel oversatt til alle 13 ikke-engelske språk med kvalitetsporter per språk.',
    fi: 'Käännösajo: yksi julkaistu artikkeli käännettynä kaikille 13 ei-englanninkieliselle tuetulle kielelle kielikohtaisin laatuportein.',
    de: 'Übersetzungslauf: ein veröffentlichter Artikel in alle 13 nicht-englischen unterstützten Sprachen übertragen, mit sprach­spezifischen Qualitäts­gates.',
    fr: 'Exécution de traduction : un article publié rendu dans les 13 langues prises en charge autres que l’anglais, avec des portes qualité par langue.',
    es: 'Ejecución de traducción: un artículo publicado traducido a los 13 idiomas admitidos distintos del inglés, con puertas de calidad por idioma.',
    nl: 'Vertaalronde: één gepubliceerd artikel weergegeven in alle 13 niet-Engelse ondersteunde talen met kwaliteitspoorten per taal.',
    ar: 'تشغيل الترجمة: مقال منشور يُترجَم إلى جميع اللغات الـ 13 المدعومة غير الإنجليزية مع بوابات جودة لكل لغة.',
    he: 'הרצת תרגום: מאמר אחד שפורסם מתורגם לכל 13 השפות הנתמכות שאינן אנגלית, עם שערי איכות לכל שפה.',
    ja: '翻訳ラン：公開された 1 記事を、英語以外のサポート言語 13 種すべてに言語ごとの品質ゲート付きで翻訳。',
    ko: '번역 실행: 게시된 기사 1건을 영어를 제외한 지원 언어 13개로 언어별 품질 게이트와 함께 번역.',
    zh: '翻译运行：将一篇已发布的文章翻译为除英语外的全部 13 种受支持语言，按语言执行质量门。',
  },
  deep: {
    en: 'Deep-dive multi-stage analysis: extended artifact set, cross-run synthesis and long-horizon scenario forecasting for a single strategic topic.',
    sv: 'Fördjupad flerstegs­analys: utökad artefaktuppsättning, tvärkörnings­syntes och lång­horisonts­scenarioprognos för ett enskilt strategiskt ämne.',
    da: 'Dybdegående analyse i flere trin: udvidet artefaktsæt, tværkørselssyntese og langhorisonts-scenarieprognose for et enkelt strategisk emne.',
    no: 'Dyp flerstegsanalyse: utvidet artefaktsett, tverrkjøringssyntese og langhorisonts-scenarioprognose for ett enkelt strategisk tema.',
    fi: 'Monivaiheinen syväanalyysi: laajennettu artefakti­setti, ajojen välinen synteesi ja pitkän aikavälin skenaario­ennuste yhdestä strategisesta aiheesta.',
    de: 'Mehrstufige Tiefen­analyse: erweitertes Artefakt-Set, Cross-Run-Synthese und Langzeit-Szenario­prognose für ein einzelnes strategisches Thema.',
    fr: 'Analyse approfondie multi-étapes : ensemble d’artefacts étendu, synthèse inter-exécutions et prévision de scénarios à long horizon pour un sujet stratégique unique.',
    es: 'Análisis multietapa en profundidad: conjunto extendido de artefactos, síntesis entre ejecuciones y pronóstico de escenarios a largo horizonte para un único tema estratégico.',
    nl: 'Meerfasige diepgaande analyse: uitgebreide artefactset, cross-run-synthese en scenarioprognose op lange horizon voor één strategisch onderwerp.',
    ar: 'تحليل معمّق متعدد المراحل: مجموعة قطع موسّعة، تركيب عبر الجلسات وتوقّع سيناريوهات طويل الأمد لموضوع استراتيجي واحد.',
    he: 'ניתוח מעמיק רב־שלבי: מערך ארטיפקטים מורחב, סינתזה בין־הרצות ותחזית תרחישים באופק ארוך לנושא אסטרטגי יחיד.',
    ja: '多段階ディープダイブ分析：拡張成果物セット、ラン間シンセシス、単一戦略テーマの長期シナリオ予測。',
    ko: '다단계 심층 분석: 확장 산출물 세트, 런 간 시너지스, 단일 전략 주제에 대한 장기 시나리오 예측.',
    zh: '多阶段深度分析：扩展的产物集、跨运行综合以及针对单一战略主题的长视野情景预测。',
  },
};
