// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Generators/PoliticalIntelligence/Descriptions/RunTypesTitles
 * @description Per-language titles for each canonical daily-analysis run
 * type (breaking, week-in-review, motions, …). Split out of the
 * monolithic `political-intelligence-descriptions.ts` (Refactor 8/8).
 */

import type { LanguageCode } from '../../../types/index.js';

/** Per-language titles for each canonical run type. */
export const RUN_TYPE_TITLES: Readonly<Record<string, Record<LanguageCode, string>>> = {
  breaking: {
    en: 'Breaking Analysis',
    sv: 'Analys av aktuella nyheter',
    da: 'Analyse af aktuelle nyheder',
    no: 'Analyse av aktuelle nyheter',
    fi: 'Ajankohtaisanalyysi',
    de: 'Aktuelle Analyse',
    fr: 'Analyse d’actualité',
    es: 'Análisis de última hora',
    nl: 'Analyse actueel nieuws',
    ar: 'تحليل عاجل',
    he: 'ניתוח מבזק',
    ja: '速報分析',
    ko: '속보 분석',
    zh: '突发新闻分析',
  },
  'week-in-review': {
    en: 'Week in Review',
    sv: 'Veckan i återblick',
    da: 'Ugen i tilbageblik',
    no: 'Uken i tilbakeblikk',
    fi: 'Viikko katsauksessa',
    de: 'Wochenrückblick',
    fr: 'La semaine en revue',
    es: 'Semana en revisión',
    nl: 'Week in terugblik',
    ar: 'الأسبوع في مراجعة',
    he: 'סיכום השבוע',
    ja: '今週のまとめ',
    ko: '주간 리뷰',
    zh: '本周回顾',
  },
  'month-in-review': {
    en: 'Month in Review',
    sv: 'Månaden i återblick',
    da: 'Måneden i tilbageblik',
    no: 'Måneden i tilbakeblikk',
    fi: 'Kuukausi katsauksessa',
    de: 'Monatsrückblick',
    fr: 'Le mois en revue',
    es: 'Mes en revisión',
    nl: 'Maand in terugblik',
    ar: 'الشهر في مراجعة',
    he: 'סיכום החודש',
    ja: '今月のまとめ',
    ko: '월간 리뷰',
    zh: '本月回顾',
  },
  'week-ahead': {
    en: 'Week Ahead',
    sv: 'Veckan framöver',
    da: 'Ugen forude',
    no: 'Uken fremover',
    fi: 'Tuleva viikko',
    de: 'Kommende Woche',
    fr: 'La semaine à venir',
    es: 'Semana por delante',
    nl: 'Komende week',
    ar: 'الأسبوع القادم',
    he: 'השבוע הקרוב',
    ja: '来週の展望',
    ko: '다가오는 주',
    zh: '下周前瞻',
  },
  'month-ahead': {
    en: 'Month Ahead',
    sv: 'Månaden framöver',
    da: 'Måneden forude',
    no: 'Måneden fremover',
    fi: 'Tuleva kuukausi',
    de: 'Kommender Monat',
    fr: 'Le mois à venir',
    es: 'Mes por delante',
    nl: 'Komende maand',
    ar: 'الشهر القادم',
    he: 'החודש הקרוב',
    ja: '来月の展望',
    ko: '다가오는 달',
    zh: '下月前瞻',
  },
  'year-ahead': {
    en: 'Year Ahead',
    sv: 'Året framöver',
    da: 'Året forude',
    no: 'Året fremover',
    fi: 'Tuleva vuosi',
    de: 'Kommendes Jahr',
    fr: 'L’année à venir',
    es: 'Año por delante',
    nl: 'Komend jaar',
    ar: 'السنة القادمة',
    he: 'השנה הקרובה',
    ja: '来年の展望',
    ko: '다가오는 해',
    zh: '来年前瞻',
  },
  'year-in-review': {
    en: 'Year in Review',
    sv: 'Året i återblick',
    da: 'Året i tilbageblik',
    no: 'Året i tilbakeblikk',
    fi: 'Vuosi katsauksessa',
    de: 'Jahresrückblick',
    fr: 'L’année en revue',
    es: 'Año en revisión',
    nl: 'Jaar in terugblik',
    ar: 'السنة في مراجعة',
    he: 'סיכום השנה',
    ja: '年間総括',
    ko: '연간 리뷰',
    zh: '年度回顾',
  },
  'quarter-ahead': {
    en: 'Quarter Ahead',
    sv: 'Kvartalet framöver',
    da: 'Kvartalet forude',
    no: 'Kvartalet fremover',
    fi: 'Tuleva neljännes',
    de: 'Kommendes Quartal',
    fr: 'Le trimestre à venir',
    es: 'Trimestre por delante',
    nl: 'Komend kwartaal',
    ar: 'الربع القادم',
    he: 'הרבעון הקרוב',
    ja: '来四半期の展望',
    ko: '다가오는 분기',
    zh: '下季前瞻',
  },
  'quarter-in-review': {
    en: 'Quarter in Review',
    sv: 'Kvartalet i återblick',
    da: 'Kvartalet i tilbageblik',
    no: 'Kvartalet i tilbakeblikk',
    fi: 'Neljännes katsauksessa',
    de: 'Quartalsrückblick',
    fr: 'Le trimestre en revue',
    es: 'Trimestre en revisión',
    nl: 'Kwartaal in terugblik',
    ar: 'الربع في مراجعة',
    he: 'סיכום הרבעון',
    ja: '四半期総括',
    ko: '분기 리뷰',
    zh: '季度回顾',
  },
  'term-outlook': {
    en: 'Term Outlook',
    sv: 'Mandatperiodens utsikt',
    da: 'Valgperiodens udsigt',
    no: 'Valgperiodens utsikt',
    fi: 'Vaalikauden näkymä',
    de: 'Wahlperioden-Ausblick',
    fr: 'Perspective de législature',
    es: 'Perspectiva de legislatura',
    nl: 'Zittingsperiode-vooruitzicht',
    ar: 'آفاق الدورة البرلمانية',
    he: 'תחזית כהונה',
    ja: '会期展望',
    ko: '의회 임기 전망',
    zh: '议会任期展望',
  },
  'election-cycle': {
    en: 'Election Cycle',
    sv: 'Valcykel',
    da: 'Valgcyklus',
    no: 'Valgsyklus',
    fi: 'Vaalisykli',
    de: 'Wahlzyklus',
    fr: 'Cycle électoral',
    es: 'Ciclo electoral',
    nl: 'Verkiezingscyclus',
    ar: 'الدورة الانتخابية',
    he: 'מחזור בחירות',
    ja: '選挙サイクル',
    ko: '선거 주기',
    zh: '选举周期',
  },
  'committee-reports': {
    en: 'Committee Reports',
    sv: 'Utskottsrapporter',
    da: 'Udvalgsrapporter',
    no: 'Komitérapporter',
    fi: 'Valiokuntaraportit',
    de: 'Ausschussberichte',
    fr: 'Rapports de commission',
    es: 'Informes de comisión',
    nl: 'Commissieverslagen',
    ar: 'تقارير اللجان',
    he: 'דוחות ועדה',
    ja: '委員会報告',
    ko: '위원회 보고서',
    zh: '委员会报告',
  },
  motions: {
    en: 'Motions',
    sv: 'Motioner',
    da: 'Beslutningsforslag',
    no: 'Forslag',
    fi: 'Aloitteet',
    de: 'Entschließungsanträge',
    fr: 'Propositions de résolution',
    es: 'Mociones',
    nl: 'Moties',
    ar: 'مقترحات',
    he: 'הצעות החלטה',
    ja: '動議',
    ko: '동의안',
    zh: '动议',
  },
  propositions: {
    en: 'Propositions',
    sv: 'Propositioner',
    da: 'Lovforslag',
    no: 'Lovforslag',
    fi: 'Lakiehdotukset',
    de: 'Gesetzesvorschläge',
    fr: 'Propositions législatives',
    es: 'Propuestas legislativas',
    nl: 'Wetsvoorstellen',
    ar: 'مقترحات تشريعية',
    he: 'הצעות חקיקה',
    ja: '法案',
    ko: '법안',
    zh: '立法提案',
  },
  translate: {
    en: 'Translation Run',
    sv: 'Översättningskörning',
    da: 'Oversættelseskørsel',
    no: 'Oversettelseskjøring',
    fi: 'Käännösajo',
    de: 'Übersetzungslauf',
    fr: 'Exécution de traduction',
    es: 'Ejecución de traducción',
    nl: 'Vertaalronde',
    ar: 'تشغيل الترجمة',
    he: 'הרצת תרגום',
    ja: '翻訳ラン',
    ko: '번역 실행',
    zh: '翻译运行',
  },
  deep: {
    en: 'Deep Analysis',
    sv: 'Djupanalys',
    da: 'Dybdeanalyse',
    no: 'Dybdeanalyse',
    fi: 'Syväanalyysi',
    de: 'Tiefenanalyse',
    fr: 'Analyse approfondie',
    es: 'Análisis profundo',
    nl: 'Diepteanalyse',
    ar: 'تحليل متعمق',
    he: 'ניתוח מעמיק',
    ja: '詳細分析',
    ko: '심층 분석',
    zh: '深度分析',
  },
};
