// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Generators/PoliticalIntelligence/Descriptions/TitlesTemplatesA
 * @description Curated per-language titles for `analysis/templates/*.md`
 * (first half — README through `mcp-reliability-audit.md`). Split out of
 * the monolithic `political-intelligence-descriptions.ts` (Refactor 8/8)
 * so contributors editing one half don't collide with the other.
 */

import type { TextI18n } from './types.js';

export const TEMPLATE_TITLES_A: Readonly<Record<string, TextI18n>> = {
  'analysis/templates/README.md': {
    en: 'Analysis Template Library Index',
    sv: 'Analysmallbibliotek — index',
    da: 'Analyseskabelonbibliotek — indeks',
    no: 'Analysemalsbibliotek — indeks',
    fi: 'Analyysimallikirjasto — hakemisto',
    de: 'Analyse-Vorlagen-Bibliothek — Index',
    fr: 'Bibliothèque de modèles d’analyse — index',
    es: 'Biblioteca de plantillas de análisis — índice',
    nl: 'Analysesjabloonbibliotheek — index',
    ar: 'فهرس مكتبة قوالب التحليل',
    he: 'אינדקס ספריית תבניות הניתוח',
    ja: '分析テンプレートライブラリ索引',
    ko: '분석 템플릿 라이브러리 색인',
    zh: '分析模板库索引',
  },
  'analysis/templates/actor-mapping.md': {
    en: 'Actor Mapping',
    sv: 'Aktörskartläggning',
    da: 'Aktørmapping',
    no: 'Aktørkartlegging',
    fi: 'Toimijoiden kartoitus',
    de: 'Akteurs-Mapping',
    fr: 'Cartographie des acteurs',
    es: 'Mapeo de actores',
    nl: 'Actor-mapping',
    ar: 'رسم خرائط الفاعلين',
    he: 'מיפוי שחקנים',
    ja: 'アクターマッピング',
    ko: '행위자 매핑',
    zh: '参与者映射',
  },
  'analysis/templates/actor-threat-profiles.md': {
    en: 'Actor Threat Profiles',
    sv: 'Aktörshotprofiler',
    da: 'Aktørtrusselprofiler',
    no: 'Aktørtrusselprofiler',
    fi: 'Toimijoiden uhkaprofiilit',
    de: 'Akteurs-Bedrohungsprofile',
    fr: 'Profils de menace des acteurs',
    es: 'Perfiles de amenaza de actores',
    nl: 'Dreigingsprofielen van actoren',
    ar: 'ملفات تعريف تهديد الفاعلين',
    he: 'פרופילי איום של שחקנים',
    ja: 'アクター脅威プロファイル',
    ko: '행위자 위협 프로필',
    zh: '参与者威胁画像',
  },
  'analysis/templates/analysis-index.md': {
    en: 'Analysis Index (Run Artifact Navigator)',
    sv: 'Analysindex (artefaktnavigator för körning)',
    da: 'Analyseindeks (kørselsartefaktnavigator)',
    no: 'Analyseindeks (kjøringsartefaktnavigator)',
    fi: 'Analyysihakemisto (ajo­artefaktien navigaattori)',
    de: 'Analyseindex (Run-Artefakt-Navigator)',
    fr: 'Index d’analyse (navigateur d’artefacts d’exécution)',
    es: 'Índice de análisis (navegador de artefactos de ejecución)',
    nl: 'Analyse-index (run-artefactnavigator)',
    ar: 'فهرس التحليل (متنقل قطع التشغيل)',
    he: 'אינדקס ניתוח (ניווט ארטיפקטי ריצה)',
    ja: '分析索引(ラン成果物ナビゲータ)',
    ko: '분석 색인(실행 산출물 내비게이터)',
    zh: '分析索引（运行工件导航器）',
  },
  'analysis/templates/coalition-dynamics.md': {
    en: 'Coalition Dynamics',
    sv: 'Koalitionsdynamik',
    da: 'Koalitionsdynamik',
    no: 'Koalisjonsdynamikk',
    fi: 'Koalitiodynamiikka',
    de: 'Koalitionsdynamik',
    fr: 'Dynamique des coalitions',
    es: 'Dinámica de coaliciones',
    nl: 'Coalitiedynamiek',
    ar: 'ديناميكيات التحالف',
    he: 'דינמיקת קואליציות',
    ja: '連立ダイナミクス',
    ko: '연정 역학',
    zh: '联盟动态',
  },
  'analysis/templates/coalition-mathematics.md': {
    en: 'Coalition Mathematics',
    sv: 'Koalitionsmatematik',
    da: 'Koalitionsmatematik',
    no: 'Koalisjonsmatematikk',
    fi: 'Koalitiomatematiikka',
    de: 'Koalitionsmathematik',
    fr: 'Mathématiques des coalitions',
    es: 'Matemáticas de coaliciones',
    nl: 'Coalitiewiskunde',
    ar: 'رياضيات التحالف',
    he: 'מתמטיקה של קואליציות',
    ja: '連立数学',
    ko: '연정 수학',
    zh: '联盟数学',
  },
  'analysis/templates/comparative-international.md': {
    en: 'Comparative International Analysis',
    sv: 'Jämförande internationell analys',
    da: 'Komparativ international analyse',
    no: 'Komparativ internasjonal analyse',
    fi: 'Vertaileva kansainvälinen analyysi',
    de: 'Vergleichende internationale Analyse',
    fr: 'Analyse internationale comparative',
    es: 'Análisis internacional comparado',
    nl: 'Vergelijkende internationale analyse',
    ar: 'التحليل الدولي المقارن',
    he: 'ניתוח בינלאומי השוואתי',
    ja: '比較国際分析',
    ko: '비교 국제 분석',
    zh: '比较国际分析',
  },
  'analysis/templates/consequence-trees.md': {
    en: 'Consequence Trees',
    sv: 'Konsekvensträd',
    da: 'Konsekvenstræer',
    no: 'Konsekvenstrær',
    fi: 'Seurauspuut',
    de: 'Konsequenzbäume',
    fr: 'Arbres des conséquences',
    es: 'Árboles de consecuencias',
    nl: 'Gevolgenbomen',
    ar: 'أشجار العواقب',
    he: 'עצי השלכה',
    ja: '帰結ツリー',
    ko: '결과 트리',
    zh: '后果树',
  },
  'analysis/templates/cross-reference-map.md': {
    en: 'Cross-Reference Map',
    sv: 'Korsreferenskarta',
    da: 'Krydshenvisningskort',
    no: 'Kryssreferansekart',
    fi: 'Ristiviittauskartta',
    de: 'Querverweiskarte',
    fr: 'Carte de références croisées',
    es: 'Mapa de referencias cruzadas',
    nl: 'Kruisverwijzingskaart',
    ar: 'خريطة الإحالات المتقاطعة',
    he: 'מפת הפניות צולבות',
    ja: 'クロスリファレンスマップ',
    ko: '교차 참조 지도',
    zh: '交叉引用地图',
  },
  'analysis/templates/cross-run-diff.md': {
    en: 'Cross-Run Diff (Bayesian Delta)',
    sv: 'Diff mellan körningar (bayesiansk delta)',
    da: 'Kørselsdiff (Bayesiansk delta)',
    no: 'Kjøringsdiff (Bayesiansk delta)',
    fi: 'Ajojen välinen diff (Bayesin delta)',
    de: 'Cross-Run-Diff (Bayesianisches Delta)',
    fr: 'Diff entre exécutions (delta bayésien)',
    es: 'Diff entre ejecuciones (delta bayesiano)',
    nl: 'Cross-run-diff (Bayesiaanse delta)',
    ar: 'فرق عبر التشغيلات (دلتا بايزية)',
    he: 'דיף בין ריצות (דלתא בייסיאנית)',
    ja: 'ラン間差分(ベイジアンデルタ)',
    ko: '실행 간 차분(베이지안 델타)',
    zh: '跨运行差异（贝叶斯增量）',
  },
  'analysis/templates/cross-session-intelligence.md': {
    en: 'Cross-Session Intelligence',
    sv: 'Sessionsövergripande underrättelse',
    da: 'Sessionsovergribende efterretning',
    no: 'Sesjonsovergripende etterretning',
    fi: 'Istuntojen välinen tiedustelu',
    de: 'Sitzungsübergreifende Aufklärung',
    fr: 'Renseignement inter-sessions',
    es: 'Inteligencia entre sesiones',
    nl: 'Intersessionele inlichtingen',
    ar: 'استخبارات عبر الجلسات',
    he: 'מודיעין בין-מושבי',
    ja: 'セッション横断インテリジェンス',
    ko: '세션 간 정보',
    zh: '跨会议情报',
  },
  'analysis/templates/data-download-manifest.md': {
    en: 'Data Download Manifest',
    sv: 'Datanedladdningsmanifest',
    da: 'Datadownloadmanifest',
    no: 'Datanedlastingsmanifest',
    fi: 'Datan latausmanifesti',
    de: 'Daten-Download-Manifest',
    fr: 'Manifeste de téléchargement de données',
    es: 'Manifiesto de descarga de datos',
    nl: 'Datadownload-manifest',
    ar: 'بيان تنزيل البيانات',
    he: 'מניפסט הורדת נתונים',
    ja: 'データダウンロード・マニフェスト',
    ko: '데이터 다운로드 매니페스트',
    zh: '数据下载清单',
  },
  'analysis/templates/deep-analysis.md': {
    en: 'Deep Political Analysis (Long-Form)',
    sv: 'Djup politisk analys (långformat)',
    da: 'Dyb politisk analyse (langform)',
    no: 'Dyp politisk analyse (langform)',
    fi: 'Syvä poliittinen analyysi (pitkä muoto)',
    de: 'Tiefgehende politische Analyse (Langform)',
    fr: 'Analyse politique approfondie (format long)',
    es: 'Análisis político profundo (formato largo)',
    nl: 'Diepe politieke analyse (langvorm)',
    ar: 'تحليل سياسي معمق (شكل مطول)',
    he: 'ניתוח פוליטי מעמיק (פורמט ארוך)',
    ja: '深い政治分析(ロングフォーム)',
    ko: '심층 정치 분석(롱폼)',
    zh: '深度政治分析（长篇）',
  },
  'analysis/templates/devils-advocate-analysis.md': {
    en: 'Devil’s Advocate Analysis',
    sv: 'Djävulens advokat-analys',
    da: 'Djævlens advokat-analyse',
    no: 'Djevelens advokat-analyse',
    fi: 'Paholaisen asianajajan analyysi',
    de: 'Advocatus-Diaboli-Analyse',
    fr: 'Analyse de l’avocat du diable',
    es: 'Análisis del abogado del diablo',
    nl: 'Advocaat-van-de-duivel-analyse',
    ar: 'تحليل محامي الشيطان',
    he: 'ניתוח פרקליט השטן',
    ja: '悪魔の代弁者分析',
    ko: '악마의 대변인 분석',
    zh: '魔鬼代言人分析',
  },
  'analysis/templates/economic-context.md': {
    en: 'Economic Context (World Bank & IMF)',
    sv: 'Ekonomisk kontext (Världsbanken & IMF)',
    da: 'Økonomisk kontekst (Verdensbanken & IMF)',
    no: 'Økonomisk kontekst (Verdensbanken & IMF)',
    fi: 'Taloudellinen konteksti (Maailmanpankki & IMF)',
    de: 'Wirtschaftlicher Kontext (Weltbank & IWF)',
    fr: 'Contexte économique (Banque mondiale & FMI)',
    es: 'Contexto económico (Banco Mundial y FMI)',
    nl: 'Economische context (Wereldbank & IMF)',
    ar: 'السياق الاقتصادي (البنك الدولي وصندوق النقد)',
    he: 'הקשר כלכלי (הבנק העולמי וקרן המטבע)',
    ja: '経済コンテキスト(世界銀行・IMF)',
    ko: '경제 컨텍스트(세계은행·IMF)',
    zh: '经济背景（世界银行与 IMF）',
  },
  'analysis/templates/executive-brief.md': {
    en: 'Executive Brief',
    sv: 'Ledningsbrief',
    da: 'Lederbriefing',
    no: 'Ledelsesbrief',
    fi: 'Johdon tiivistelmä',
    de: 'Executive Brief',
    fr: 'Note exécutive',
    es: 'Informe ejecutivo',
    nl: 'Executive briefing',
    ar: 'موجز تنفيذي',
    he: 'תדריך ניהולי',
    ja: 'エグゼクティブ・ブリーフ',
    ko: '경영진 브리프',
    zh: '高管简报',
  },
  'analysis/templates/forces-analysis.md': {
    en: 'Forces Analysis (Lewin Force-Field)',
    sv: 'Kraftanalys (Lewins kraftfält)',
    da: 'Kraftanalyse (Lewins kraftfelt)',
    no: 'Kraftanalyse (Lewins kraftfelt)',
    fi: 'Voima-analyysi (Lewinin voima­kenttä)',
    de: 'Kräfteanalyse (Lewin-Kraftfeld)',
    fr: 'Analyse des forces (champ de forces de Lewin)',
    es: 'Análisis de fuerzas (campo de fuerzas de Lewin)',
    nl: 'Krachtenanalyse (Lewin-krachtenveld)',
    ar: 'تحليل القوى (حقل قوى ليفين)',
    he: 'ניתוח כוחות (שדה כוחות לוין)',
    ja: '勢力分析(レヴィン力場)',
    ko: '세력 분석(레빈 역장)',
    zh: '力场分析（勒温力场）',
  },
  'analysis/templates/forward-indicators.md': {
    en: 'Forward Indicators',
    sv: 'Framåtblickande indikatorer',
    da: 'Fremadrettede indikatorer',
    no: 'Fremoverrettede indikatorer',
    fi: 'Ennakoivat indikaattorit',
    de: 'Vorlaufindikatoren',
    fr: 'Indicateurs avancés',
    es: 'Indicadores adelantados',
    nl: 'Voorlopende indicatoren',
    ar: 'المؤشرات الاستباقية',
    he: 'מדדים צופים פני עתיד',
    ja: '先行指標',
    ko: '선행 지표',
    zh: '前瞻指标',
  },
  'analysis/templates/historical-baseline.md': {
    en: 'Historical Baseline',
    sv: 'Historisk baslinje',
    da: 'Historisk basislinje',
    no: 'Historisk grunnlinje',
    fi: 'Historiallinen lähtötaso',
    de: 'Historische Basislinie',
    fr: 'Référence historique',
    es: 'Línea base histórica',
    nl: 'Historische basislijn',
    ar: 'خط الأساس التاريخي',
    he: 'קו בסיס היסטורי',
    ja: '歴史的ベースライン',
    ko: '역사적 기준선',
    zh: '历史基线',
  },
  'analysis/templates/historical-parallels.md': {
    en: 'Historical Parallels',
    sv: 'Historiska paralleller',
    da: 'Historiske paralleller',
    no: 'Historiske paralleller',
    fi: 'Historialliset rinnakkaistapaukset',
    de: 'Historische Parallelen',
    fr: 'Parallèles historiques',
    es: 'Paralelos históricos',
    nl: 'Historische parallellen',
    ar: 'التوازيات التاريخية',
    he: 'הקבלות היסטוריות',
    ja: '歴史的類似例',
    ko: '역사적 유사 사례',
    zh: '历史类比',
  },
  'analysis/templates/impact-matrix.md': {
    en: 'Impact Matrix (Event × Stakeholder)',
    sv: 'Effektmatris (händelse × intressent)',
    da: 'Effektmatrix (begivenhed × interessent)',
    no: 'Effektmatrise (hendelse × interessent)',
    fi: 'Vaikutusmatriisi (tapahtuma × sidosryhmä)',
    de: 'Auswirkungsmatrix (Ereignis × Stakeholder)',
    fr: 'Matrice d’impact (événement × partie prenante)',
    es: 'Matriz de impacto (evento × interesado)',
    nl: 'Impactmatrix (gebeurtenis × belanghebbende)',
    ar: 'مصفوفة التأثير (حدث × أصحاب مصلحة)',
    he: 'מטריצת השפעה (אירוע × בעלי עניין)',
    ja: '影響マトリクス(事象×ステークホルダー)',
    ko: '영향 매트릭스(이벤트×이해관계자)',
    zh: '影响矩阵（事件×利益相关方）',
  },
  'analysis/templates/implementation-feasibility.md': {
    en: 'Implementation Feasibility',
    sv: 'Genomförbarhet av implementering',
    da: 'Implementeringsgennemførlighed',
    no: 'Gjennomførbarhet av implementering',
    fi: 'Toteutettavuus',
    de: 'Umsetzbarkeit der Implementierung',
    fr: 'Faisabilité de mise en œuvre',
    es: 'Viabilidad de implementación',
    nl: 'Implementeerbaarheid',
    ar: 'جدوى التنفيذ',
    he: 'היתכנות יישום',
    ja: '実装実行可能性',
    ko: '구현 실현 가능성',
    zh: '实施可行性',
  },
  'analysis/templates/intelligence-assessment.md': {
    en: 'Intelligence Assessment',
    sv: 'Underrättelsebedömning',
    da: 'Efterretningsvurdering',
    no: 'Etterretningsvurdering',
    fi: 'Tiedusteluarvio',
    de: 'Aufklärungsbewertung',
    fr: 'Évaluation du renseignement',
    es: 'Evaluación de inteligencia',
    nl: 'Inlichtingenbeoordeling',
    ar: 'تقييم استخباراتي',
    he: 'הערכה מודיעינית',
    ja: 'インテリジェンス評価',
    ko: '정보 평가',
    zh: '情报评估',
  },
  'analysis/templates/legislative-disruption.md': {
    en: 'Legislative Disruption',
    sv: 'Lagstiftningsstörning',
    da: 'Lovgivningsforstyrrelse',
    no: 'Lovgivningsforstyrrelse',
    fi: 'Lainsäädännön häiriö',
    de: 'Gesetzgebungsunterbrechung',
    fr: 'Perturbation législative',
    es: 'Disrupción legislativa',
    nl: 'Wetgevingsverstoring',
    ar: 'اضطراب تشريعي',
    he: 'שיבוש חקיקתי',
    ja: '立法撹乱',
    ko: '입법 교란',
    zh: '立法干扰',
  },
  'analysis/templates/legislative-velocity-risk.md': {
    en: 'Legislative Velocity Risk',
    sv: 'Risk för lagstiftningshastighet',
    da: 'Risiko for lovgivningshastighed',
    no: 'Risiko for lovgivningshastighet',
    fi: 'Lainsäädännön nopeuden riski',
    de: 'Risiko der Gesetzgebungsgeschwindigkeit',
    fr: 'Risque lié à la vélocité législative',
    es: 'Riesgo de velocidad legislativa',
    nl: 'Risico van wetgevingssnelheid',
    ar: 'مخاطر سرعة التشريع',
    he: 'סיכון מהירות חקיקה',
    ja: '立法速度リスク',
    ko: '입법 속도 리스크',
    zh: '立法速度风险',
  },
  'analysis/templates/mcp-reliability-audit.md': {
    en: 'MCP Reliability Audit',
    sv: 'MCP-tillförlitlighetsrevision',
    da: 'MCP-pålidelighedsrevision',
    no: 'MCP-pålitelighetsrevisjon',
    fi: 'MCP-luotettavuustarkastus',
    de: 'MCP-Zuverlässigkeitsaudit',
    fr: 'Audit de fiabilité MCP',
    es: 'Auditoría de fiabilidad MCP',
    nl: 'MCP-betrouwbaarheidsaudit',
    ar: 'تدقيق موثوقية MCP',
    he: 'ביקורת אמינות MCP',
    ja: 'MCP信頼性監査',
    ko: 'MCP 신뢰성 감사',
    zh: 'MCP 可靠性审计',
  },
};
