// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Generators/PoliticalIntelligence/Descriptions/TitlesMethodologies
 * @description Curated per-language titles for `analysis/methodologies/*.md`.
 * Split out of the monolithic `political-intelligence-descriptions.ts`
 * (Refactor 8/8).
 */

import type { TextI18n } from './types.js';

export const METHODOLOGY_TITLES: Readonly<Record<string, TextI18n>> = {
  /* eslint-disable sonarjs/no-duplicate-string --
     Title translations across closely-related languages (Scandinavian
     sv/da/no, or English-borrowed technical terms like "TOWS", "IMF",
     "MCP") legitimately coincide. Extracting a shared constant would
     obscure the per-language intent and make later divergence harder. */
  // ========================================================================
  'analysis/methodologies/README.md': {
    en: 'Methodology Library Index',
    sv: 'Metodologibibliotek — index',
    da: 'Metodebibliotek — indeks',
    no: 'Metodebibliotek — indeks',
    fi: 'Metodologiakirjasto — hakemisto',
    de: 'Methodologie-Bibliothek — Index',
    fr: 'Bibliothèque des méthodologies — index',
    es: 'Biblioteca de metodologías — índice',
    nl: 'Methodologiebibliotheek — index',
    ar: 'فهرس مكتبة المنهجيات',
    he: 'אינדקס ספריית המתודולוגיות',
    ja: '方法論ライブラリ索引',
    ko: '방법론 라이브러리 색인',
    zh: '方法论库索引',
  },
  'analysis/methodologies/ai-driven-analysis-guide.md': {
    en: 'AI-Driven Analysis Guide',
    sv: 'AI-driven analysguide',
    da: 'AI-drevet analyseguide',
    no: 'AI-drevet analyseveiledning',
    fi: 'Tekoälypohjainen analyysiopas',
    de: 'KI-gesteuerter Analyseleitfaden',
    fr: 'Guide d’analyse pilotée par IA',
    es: 'Guía de análisis impulsado por IA',
    nl: 'AI-gedreven analysegids',
    ar: 'دليل التحليل المدفوع بالذكاء الاصطناعي',
    he: 'מדריך ניתוח מבוסס בינה מלאכותית',
    ja: 'AI駆動分析ガイド',
    ko: 'AI 기반 분석 가이드',
    zh: 'AI 驱动分析指南',
  },
  'analysis/methodologies/artifact-catalog.md': {
    en: 'Analysis Artifact Catalog',
    sv: 'Katalog över analysartefakter',
    da: 'Katalog over analyseartefakter',
    no: 'Katalog over analyseartefakter',
    fi: 'Analyysiartefaktien luettelo',
    de: 'Katalog der Analyse-Artefakte',
    fr: 'Catalogue des artefacts d’analyse',
    es: 'Catálogo de artefactos de análisis',
    nl: 'Catalogus van analyse-artefacten',
    ar: 'كتالوج القطع التحليلية',
    he: 'קטלוג ארטיפקטי הניתוח',
    ja: '分析成果物カタログ',
    ko: '분석 산출물 카탈로그',
    zh: '分析工件目录',
  },
  'analysis/methodologies/electoral-domain-methodology.md': {
    en: 'Electoral Domain Methodology',
    sv: 'Valdomänmetodologi',
    da: 'Valgdomænemetode',
    no: 'Valgdomenemetodikk',
    fi: 'Vaalialueen metodologia',
    de: 'Wahldomänen-Methodologie',
    fr: 'Méthodologie du domaine électoral',
    es: 'Metodología del dominio electoral',
    nl: 'Methodologie voor het kiesdomein',
    ar: 'منهجية المجال الانتخابي',
    he: 'מתודולוגיית תחום הבחירות',
    ja: '選挙領域方法論',
    ko: '선거 도메인 방법론',
    zh: '选举领域方法论',
  },
  'analysis/methodologies/imf-indicator-mapping.md': {
    en: 'IMF Indicator → Article-Type Mapping',
    sv: 'IMF-indikator → artikeltypmappning',
    da: 'IMF-indikator → artikeltypemapping',
    no: 'IMF-indikator → artikkeltypekobling',
    fi: 'IMF-indikaattori → artikkelityypin kartoitus',
    de: 'IWF-Indikator → Artikeltyp-Zuordnung',
    fr: 'Indicateur FMI → Mappage par type d’article',
    es: 'Indicador del FMI → Asignación por tipo de artículo',
    nl: 'IMF-indicator → toewijzing artikeltype',
    ar: 'مؤشر صندوق النقد الدولي → خريطة نوع المقال',
    he: 'מיפוי מדד קרן המטבע → סוג מאמר',
    ja: 'IMF指標 → 記事タイプマッピング',
    ko: 'IMF 지표 → 기사 유형 매핑',
    zh: 'IMF 指标 → 文章类型映射',
  },
  'analysis/methodologies/osint-tradecraft-standards.md': {
    en: 'OSINT Tradecraft Standards',
    sv: 'OSINT-tradecraft-standarder',
    da: 'OSINT-tradecraft-standarder',
    no: 'OSINT-håndverksstandarder',
    fi: 'OSINT-tradecraft-standardit',
    de: 'OSINT-Tradecraft-Standards',
    fr: 'Normes de savoir-faire OSINT',
    es: 'Estándares de oficio OSINT',
    nl: 'OSINT-vakstandaarden',
    ar: 'معايير حرفة الاستخبارات المفتوحة',
    he: 'תקני מלאכת מודיעין פתוח',
    ja: 'OSINT トレードクラフト標準',
    ko: 'OSINT 트레이드크래프트 표준',
    zh: 'OSINT 情报工艺标准',
  },
  'analysis/methodologies/per-artifact-methodologies.md': {
    en: 'Per-Artifact Methodologies',
    sv: 'Per-artefakt-metodologier',
    da: 'Pr.-artefakt-metoder',
    no: 'Per-artefakt-metodikker',
    fi: 'Artefaktikohtaiset metodologiat',
    de: 'Methodologien pro Artefakt',
    fr: 'Méthodologies par artefact',
    es: 'Metodologías por artefacto',
    nl: 'Methodologieën per artefact',
    ar: 'منهجيات لكل قطعة أثرية',
    he: 'מתודולוגיות לפי ארטיפקט',
    ja: '成果物別方法論',
    ko: '산출물별 방법론',
    zh: '分工件方法论',
  },
  'analysis/methodologies/per-document-methodology.md': {
    en: 'Per-Document Analysis Methodology',
    sv: 'Per-dokument-analysmetodologi',
    da: 'Pr.-dokument analysemetode',
    no: 'Per-dokument analysemetodikk',
    fi: 'Asiakirja­kohtainen analyysimetodologia',
    de: 'Dokumentspezifische Analysemethodologie',
    fr: 'Méthodologie d’analyse par document',
    es: 'Metodología de análisis por documento',
    nl: 'Analysemethodologie per document',
    ar: 'منهجية التحليل لكل وثيقة',
    he: 'מתודולוגיית ניתוח למסמך בודד',
    ja: '文書別分析方法論',
    ko: '문서별 분석 방법론',
    zh: '按文档分析方法论',
  },
  'analysis/methodologies/political-classification-guide.md': {
    en: 'Political Event Classification Guide',
    sv: 'Guide för klassificering av politiska händelser',
    da: 'Vejledning i klassifikation af politiske begivenheder',
    no: 'Veiledning for klassifisering av politiske hendelser',
    fi: 'Poliittisten tapahtumien luokitteluopas',
    de: 'Leitfaden zur Klassifizierung politischer Ereignisse',
    fr: 'Guide de classification des événements politiques',
    es: 'Guía de clasificación de eventos políticos',
    nl: 'Gids voor classificatie van politieke gebeurtenissen',
    ar: 'دليل تصنيف الأحداث السياسية',
    he: 'מדריך סיווג אירועים פוליטיים',
    ja: '政治イベント分類ガイド',
    ko: '정치 이벤트 분류 가이드',
    zh: '政治事件分类指南',
  },
  'analysis/methodologies/political-risk-methodology.md': {
    en: 'Political Risk Methodology',
    sv: 'Politisk riskmetodologi',
    da: 'Politisk risikometode',
    no: 'Politisk risikometodikk',
    fi: 'Poliittisen riskin metodologia',
    de: 'Methodologie für politische Risiken',
    fr: 'Méthodologie des risques politiques',
    es: 'Metodología de riesgos políticos',
    nl: 'Methodologie voor politieke risico’s',
    ar: 'منهجية المخاطر السياسية',
    he: 'מתודולוגיית סיכון פוליטי',
    ja: '政治リスク方法論',
    ko: '정치 리스크 방법론',
    zh: '政治风险方法论',
  },
  'analysis/methodologies/political-style-guide.md': {
    en: 'Political Style Guide',
    sv: 'Politisk stilguide',
    da: 'Politisk stilguide',
    no: 'Politisk stilguide',
    fi: 'Poliittinen tyyliopas',
    de: 'Politischer Stilleitfaden',
    fr: 'Guide de style politique',
    es: 'Guía de estilo político',
    nl: 'Politieke stijlgids',
    ar: 'دليل الأسلوب السياسي',
    he: 'מדריך סגנון פוליטי',
    ja: '政治スタイルガイド',
    ko: '정치 스타일 가이드',
    zh: '政治风格指南',
  },
  'analysis/methodologies/political-swot-framework.md': {
    en: 'Political SWOT Framework',
    sv: 'Politiskt SWOT-ramverk',
    da: 'Politisk SWOT-ramme',
    no: 'Politisk SWOT-rammeverk',
    fi: 'Poliittinen SWOT-viitekehys',
    de: 'Politisches SWOT-Rahmenwerk',
    fr: 'Cadre SWOT politique',
    es: 'Marco SWOT político',
    nl: 'Politiek SWOT-raamwerk',
    ar: 'إطار SWOT السياسي',
    he: 'מסגרת SWOT פוליטית',
    ja: '政治SWOTフレームワーク',
    ko: '정치 SWOT 프레임워크',
    zh: '政治 SWOT 框架',
  },
  'analysis/methodologies/political-threat-framework.md': {
    en: 'Political Threat Framework',
    sv: 'Politiskt hotramverk',
    da: 'Politisk trusselramme',
    no: 'Politisk trusselrammeverk',
    fi: 'Poliittinen uhkaviitekehys',
    de: 'Politisches Bedrohungsrahmenwerk',
    fr: 'Cadre des menaces politiques',
    es: 'Marco de amenazas políticas',
    nl: 'Politiek dreigingsraamwerk',
    ar: 'إطار التهديدات السياسية',
    he: 'מסגרת איומים פוליטיים',
    ja: '政治脅威フレームワーク',
    ko: '정치 위협 프레임워크',
    zh: '政治威胁框架',
  },
  'analysis/methodologies/strategic-extensions-methodology.md': {
    en: 'Strategic Extensions Methodology',
    sv: 'Metodologi för strategiska utvidgningar',
    da: 'Metode for strategiske udvidelser',
    no: 'Metodikk for strategiske utvidelser',
    fi: 'Strategisten laajennusten metodologia',
    de: 'Methodologie strategischer Erweiterungen',
    fr: 'Méthodologie des extensions stratégiques',
    es: 'Metodología de extensiones estratégicas',
    nl: 'Methodologie voor strategische uitbreidingen',
    ar: 'منهجية الامتدادات الاستراتيجية',
    he: 'מתודולוגיית הרחבות אסטרטגיות',
    ja: '戦略的拡張方法論',
    ko: '전략적 확장 방법론',
    zh: '战略扩展方法论',
  },
  'analysis/methodologies/structural-metadata-methodology.md': {
    en: 'Structural Metadata Methodology',
    sv: 'Metodologi för strukturell metadata',
    da: 'Metode for strukturel metadata',
    no: 'Metodikk for strukturell metadata',
    fi: 'Rakenteellisen metatiedon metodologia',
    de: 'Methodologie struktureller Metadaten',
    fr: 'Méthodologie des métadonnées structurelles',
    es: 'Metodología de metadatos estructurales',
    nl: 'Methodologie voor structurele metadata',
    ar: 'منهجية البيانات الوصفية الهيكلية',
    he: 'מתודולוגיית מטא-נתונים מבניים',
    ja: '構造メタデータ方法論',
    ko: '구조 메타데이터 방법론',
    zh: '结构化元数据方法论',
  },
  'analysis/methodologies/synthesis-methodology.md': {
    en: 'Synthesis Methodology',
    sv: 'Syntesmetodologi',
    da: 'Syntesemetode',
    no: 'Syntesemetodikk',
    fi: 'Synteesin metodologia',
    de: 'Synthese-Methodologie',
    fr: 'Méthodologie de synthèse',
    es: 'Metodología de síntesis',
    nl: 'Synthesemethodologie',
    ar: 'منهجية التوليف',
    he: 'מתודולוגיית סינתזה',
    ja: '総合方法論',
    ko: '종합 방법론',
    zh: '综合方法论',
  },
  'analysis/methodologies/worldbank-indicator-mapping.md': {
    en: 'World Bank Indicator → Article-Type Mapping',
    sv: 'Världsbanken-indikator → artikeltypmappning',
    da: 'Verdensbank-indikator → artikeltypemapping',
    no: 'Verdensbank-indikator → artikkeltypekobling',
    fi: 'Maailmanpankin indikaattori → artikkelityypin kartoitus',
    de: 'Weltbank-Indikator → Artikeltyp-Zuordnung',
    fr: 'Indicateur Banque mondiale → Mappage par type d’article',
    es: 'Indicador del Banco Mundial → Asignación por tipo de artículo',
    nl: 'Wereldbank-indicator → toewijzing artikeltype',
    ar: 'مؤشر البنك الدولي → خريطة نوع المقال',
    he: 'מיפוי מדד הבנק העולמי → סוג מאמר',
    ja: '世界銀行指標 → 記事タイプマッピング',
    ko: '세계은행 지표 → 기사 유형 매핑',
    zh: '世界银行指标 → 文章类型映射',
  },
};
