// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Generators/PoliticalIntelligence/Descriptions/TitlesReferences
 * @description Curated per-language titles for `analysis/reference/*.md`,
 * IMF and World Bank data-pipeline catalog files. Split out of the
 * monolithic `political-intelligence-descriptions.ts` (Refactor 8/8).
 */

import type { TextI18n } from './types.js';

export const REFERENCE_TITLES: Readonly<Record<string, TextI18n>> = {
  /* eslint-disable sonarjs/no-duplicate-string --
     Title translations across closely-related languages (Scandinavian
     sv/da/no, or English-borrowed technical terms like "TOWS", "IMF",
     "MCP") legitimately coincide. Extracting a shared constant would
     obscure the per-language intent and make later divergence harder. */
  'analysis/reference/isms-classification-adaptation.md': {
    en: 'ISMS Classification Adaptation',
    sv: 'ISMS-klassificeringsanpassning',
    da: 'ISMS-klassifikationstilpasning',
    no: 'ISMS-klassifiseringstilpasning',
    fi: 'ISMS-luokittelun sovellus',
    de: 'ISMS-Klassifizierungsanpassung',
    fr: 'Adaptation de classification ISMS',
    es: 'Adaptación de clasificación ISMS',
    nl: 'ISMS-classificatieaanpassing',
    ar: 'تكييف تصنيف ISMS',
    he: 'התאמת סיווג ISMS',
    ja: 'ISMS分類適応',
    ko: 'ISMS 분류 적응',
    zh: 'ISMS 分类适配',
  },
  'analysis/reference/isms-risk-assessment-adaptation.md': {
    en: 'ISMS Risk-Assessment Adaptation',
    sv: 'ISMS-riskbedömningsanpassning',
    da: 'ISMS-risikovurderingstilpasning',
    no: 'ISMS-risikovurderingstilpasning',
    fi: 'ISMS-riskiarvioinnin sovellus',
    de: 'ISMS-Risikobewertungsanpassung',
    fr: 'Adaptation d’évaluation des risques ISMS',
    es: 'Adaptación de evaluación de riesgos ISMS',
    nl: 'ISMS-risicobeoordelingsaanpassing',
    ar: 'تكييف تقييم مخاطر ISMS',
    he: 'התאמת הערכת סיכונים ISMS',
    ja: 'ISMSリスク評価適応',
    ko: 'ISMS 리스크 평가 적응',
    zh: 'ISMS 风险评估适配',
  },
  'analysis/reference/isms-style-guide-adaptation.md': {
    en: 'ISMS Style-Guide Adaptation',
    sv: 'ISMS-stilguideanpassning',
    da: 'ISMS-stilguidetilpasning',
    no: 'ISMS-stilveiledningstilpasning',
    fi: 'ISMS-tyylioppaan sovellus',
    de: 'ISMS-Stilleitfaden-Anpassung',
    fr: 'Adaptation du guide de style ISMS',
    es: 'Adaptación de la guía de estilo ISMS',
    nl: 'ISMS-stijlgidsaanpassing',
    ar: 'تكييف دليل أسلوب ISMS',
    he: 'התאמת מדריך סגנון ISMS',
    ja: 'ISMSスタイルガイド適応',
    ko: 'ISMS 스타일 가이드 적응',
    zh: 'ISMS 风格指南适配',
  },
  'analysis/reference/isms-threat-modeling-adaptation.md': {
    en: 'ISMS Threat-Modeling Adaptation',
    sv: 'ISMS-hotmodelleringsanpassning',
    da: 'ISMS-trusselsmodelleringstilpasning',
    no: 'ISMS-trusselmodelleringstilpasning',
    fi: 'ISMS-uhkamallinnuksen sovellus',
    de: 'ISMS-Bedrohungsmodellierungsanpassung',
    fr: 'Adaptation de modélisation des menaces ISMS',
    es: 'Adaptación del modelado de amenazas ISMS',
    nl: 'ISMS-dreigingsmodelleringsaanpassing',
    ar: 'تكييف نمذجة التهديدات ISMS',
    he: 'התאמת מידול איומים ISMS',
    ja: 'ISMS脅威モデリング適応',
    ko: 'ISMS 위협 모델링 적응',
    zh: 'ISMS 威胁建模适配',
  },

  // ========================================================================
  // IMF Data (5)
  // ========================================================================
  'analysis/imf/README.md': {
    en: 'IMF Data Integration — Overview',
    sv: 'IMF-dataintegration — översikt',
    da: 'IMF-dataintegration — oversigt',
    no: 'IMF-dataintegrasjon — oversikt',
    fi: 'IMF-datan integrointi — yleiskatsaus',
    de: 'IWF-Datenintegration — Überblick',
    fr: 'Intégration des données FMI — aperçu',
    es: 'Integración de datos del FMI — visión general',
    nl: 'IMF-data-integratie — overzicht',
    ar: 'دمج بيانات صندوق النقد الدولي — نظرة عامة',
    he: 'שילוב נתוני קרן המטבע — סקירה',
    ja: 'IMFデータ統合 — 概要',
    ko: 'IMF 데이터 통합 — 개요',
    zh: 'IMF 数据集成 — 概览',
  },
  'analysis/imf/chart-integration-guide.md': {
    en: 'IMF Chart Integration Guide',
    sv: 'IMF-diagramintegrationsguide',
    da: 'IMF-diagramintegrationsvejledning',
    no: 'IMF-diagramintegrasjonsveiledning',
    fi: 'IMF-kaavioiden integrointiopas',
    de: 'IWF-Diagrammintegrationsleitfaden',
    fr: 'Guide d’intégration des graphiques FMI',
    es: 'Guía de integración de gráficos del FMI',
    nl: 'IMF-grafiekintegratiegids',
    ar: 'دليل دمج مخططات صندوق النقد الدولي',
    he: 'מדריך שילוב תרשימי קרן המטבע',
    ja: 'IMFチャート統合ガイド',
    ko: 'IMF 차트 통합 가이드',
    zh: 'IMF 图表集成指南',
  },
  'analysis/imf/eu-country-mapping.md': {
    en: 'IMF EU Country & Aggregation Codes',
    sv: 'IMF EU-land- och aggregatkoder',
    da: 'IMF EU-lande- og aggregationskoder',
    no: 'IMF EU-land- og aggregeringskoder',
    fi: 'IMF EU-maa- ja aggregaattikoodit',
    de: 'IWF EU-Länder- und Aggregationscodes',
    fr: 'Codes pays & agrégations FMI UE',
    es: 'Códigos de países y agregaciones FMI UE',
    nl: 'IMF EU-land- en aggregatiecodes',
    ar: 'رموز دول وتجميعات صندوق النقد الدولي للاتحاد الأوروبي',
    he: 'קודי מדינות ואגרגציה של קרן המטבע לאיחוד האירופי',
    ja: 'IMF EU 国・集計コード',
    ko: 'IMF EU 국가 및 집계 코드',
    zh: 'IMF 欧盟国家与聚合代码',
  },
  'analysis/imf/indicator-catalog.md': {
    en: 'IMF Indicator Catalog',
    sv: 'IMF-indikatorkatalog',
    da: 'IMF-indikatorkatalog',
    no: 'IMF-indikatorkatalog',
    fi: 'IMF-indikaattorien luettelo',
    de: 'IWF-Indikatorkatalog',
    fr: 'Catalogue des indicateurs FMI',
    es: 'Catálogo de indicadores del FMI',
    nl: 'IMF-indicatorcatalogus',
    ar: 'كتالوج مؤشرات صندوق النقد الدولي',
    he: 'קטלוג מדדי קרן המטבע',
    ja: 'IMF指標カタログ',
    ko: 'IMF 지표 카탈로그',
    zh: 'IMF 指标目录',
  },
  'analysis/imf/use-cases.md': {
    en: 'IMF Data Use Cases',
    sv: 'Användningsfall för IMF-data',
    da: 'Use cases for IMF-data',
    no: 'Brukstilfeller for IMF-data',
    fi: 'IMF-datan käyttötapaukset',
    de: 'IWF-Daten — Anwendungsfälle',
    fr: 'Cas d’utilisation des données FMI',
    es: 'Casos de uso de datos del FMI',
    nl: 'Gebruiksgevallen voor IMF-data',
    ar: 'حالات استخدام بيانات صندوق النقد الدولي',
    he: 'תרחישי שימוש בנתוני קרן המטבע',
    ja: 'IMFデータのユースケース',
    ko: 'IMF 데이터 활용 사례',
    zh: 'IMF 数据使用案例',
  },

  // ========================================================================
  // World Bank Data (5)
  // ========================================================================
  'analysis/worldbank/README.md': {
    en: 'World Bank Indicator Integration — Overview',
    sv: 'Världsbankens indikatorintegration — översikt',
    da: 'Verdensbankens indikatorintegration — oversigt',
    no: 'Verdensbankens indikatorintegrasjon — oversikt',
    fi: 'Maailmanpankin indikaattorien integrointi — yleiskatsaus',
    de: 'Weltbank-Indikatorintegration — Überblick',
    fr: 'Intégration des indicateurs Banque mondiale — aperçu',
    es: 'Integración de indicadores del Banco Mundial — visión general',
    nl: 'Wereldbank-indicatorintegratie — overzicht',
    ar: 'دمج مؤشرات البنك الدولي — نظرة عامة',
    he: 'שילוב מדדי הבנק העולמי — סקירה',
    ja: '世界銀行指標統合 — 概要',
    ko: '세계은행 지표 통합 — 개요',
    zh: '世界银行指标集成 — 概览',
  },
  'analysis/worldbank/chart-integration-guide.md': {
    en: 'World Bank Chart Integration Guide',
    sv: 'Världsbankens diagramintegrationsguide',
    da: 'Verdensbankens diagramintegrationsvejledning',
    no: 'Verdensbankens diagramintegrasjonsveiledning',
    fi: 'Maailmanpankin kaavioiden integrointiopas',
    de: 'Weltbank-Diagrammintegrationsleitfaden',
    fr: 'Guide d’intégration des graphiques Banque mondiale',
    es: 'Guía de integración de gráficos del Banco Mundial',
    nl: 'Wereldbank-grafiekintegratiegids',
    ar: 'دليل دمج مخططات البنك الدولي',
    he: 'מדריך שילוב תרשימי הבנק העולמי',
    ja: '世界銀行チャート統合ガイド',
    ko: '세계은행 차트 통합 가이드',
    zh: '世界银行图表集成指南',
  },
  'analysis/worldbank/eu-country-mapping.md': {
    en: 'EU-27 → World Bank Country-Code Mapping',
    sv: 'EU-27 → Världsbankens landskodsmappning',
    da: 'EU-27 → Verdensbankens landekodesmapping',
    no: 'EU-27 → Verdensbankens landskodekobling',
    fi: 'EU-27 → Maailmanpankin maakoodien kartoitus',
    de: 'EU-27 → Weltbank-Ländercode-Zuordnung',
    fr: 'EU-27 → Mappage des codes pays Banque mondiale',
    es: 'EU-27 → Asignación de códigos de país del Banco Mundial',
    nl: 'EU-27 → Wereldbank-landcodetoewijzing',
    ar: 'EU-27 → ربط رموز دول البنك الدولي',
    he: 'EU-27 → מיפוי קודי מדינות הבנק העולמי',
    ja: 'EU-27 → 世界銀行国コードマッピング',
    ko: 'EU-27 → 세계은행 국가 코드 매핑',
    zh: 'EU-27 → 世界银行国家代码映射',
  },
  'analysis/worldbank/indicator-catalog.md': {
    en: 'World Bank Indicator Catalog',
    sv: 'Världsbanken-indikatorkatalog',
    da: 'Verdensbank-indikatorkatalog',
    no: 'Verdensbank-indikatorkatalog',
    fi: 'Maailmanpankin indikaattorien luettelo',
    de: 'Weltbank-Indikatorkatalog',
    fr: 'Catalogue des indicateurs Banque mondiale',
    es: 'Catálogo de indicadores del Banco Mundial',
    nl: 'Wereldbank-indicatorcatalogus',
    ar: 'كتالوج مؤشرات البنك الدولي',
    he: 'קטלוג מדדי הבנק העולמי',
    ja: '世界銀行指標カタログ',
    ko: '세계은행 지표 카탈로그',
    zh: '世界银行指标目录',
  },
  'analysis/worldbank/use-cases.md': {
    en: 'World Bank Indicator Use Cases',
    sv: 'Användningsfall för Världsbanken-indikatorer',
    da: 'Use cases for Verdensbank-indikatorer',
    no: 'Brukstilfeller for Verdensbank-indikatorer',
    fi: 'Maailmanpankin indikaattorien käyttötapaukset',
    de: 'Weltbank-Indikatoren — Anwendungsfälle',
    fr: 'Cas d’utilisation des indicateurs Banque mondiale',
    es: 'Casos de uso de indicadores del Banco Mundial',
    nl: 'Gebruiksgevallen voor Wereldbank-indicatoren',
    ar: 'حالات استخدام مؤشرات البنك الدولي',
    he: 'תרחישי שימוש במדדי הבנק העולמי',
    ja: '世界銀行指標のユースケース',
    ko: '세계은행 지표 활용 사례',
    zh: '世界银行指标使用案例',
  },
};
