// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
export const DE_COPY = {
    title: 'Politische Aufklärung',
    intro: 'Jede auf dieser Website veröffentlichte politische Analyse wird durch eine transparente Kette von Methodologien, Artefaktvorlagen und laufbezogenen Analysedaten gestützt. Diese Seite bietet einen einzigen, vollständig verlinkten Index aller Handwerkskunst, die zur Produktion der Nachrichten verwendet wird.',
    heroSubtitle: 'Methodologien, Vorlagen und tägliche Analyse-Transparenz',
    home: 'Startseite',
    breadcrumbCurrent: 'Politische Aufklärung',
    breadcrumbLabel: 'Breadcrumb',
    methodologiesHeading: 'Methodologien',
    methodologiesDescription: 'Autoritative Tradecraft-Leitfäden — Risikorahmen, Stilstandards und das 10-Schritte-KI-gestützte Analyseprotokoll.',
    templatesHeading: 'Analysevorlagen',
    templatesDescription: 'Der Katalog der Artefaktvorlagen, die in jedem täglichen Analyselauf erstellt werden — SWOT, PESTLE, Bedrohungsmatrizen, Koalitionsdynamik und Konsequenzbäume.',
    referenceHeading: 'Referenzen und Datenquellen',
    referenceDescription: 'ISMS-Referenzanpassungen, Indikatorkataloge, EU-Länderzuordnungen und Diagramm-Integrationsleitfäden hinter jeder IMF- und Weltbank-Quelle.',
    statReferenceLabel: 'Referenzen',
    dailyHeading: 'Tägliche Analyseläufe',
    dailyDescription: 'Jeder veröffentlichte Analyselauf, nach Datum gruppiert und neueste zuerst sortiert. Jeder Lauf verlinkt auf den vollständigen GitHub-Baum.',
    statMethodologiesLabel: 'Methodologien',
    statTemplatesLabel: 'Vorlagen',
    statRunsLabel: 'Analyseläufe',
    statArtifactsLabel: 'Artefakte',
    viewOnGitHub: 'Auf GitHub ansehen',
    artifactCountLabel: '{count} Artefakte',
    artifactCountLabelSingular: '1 Artefakt',
    runsCountLabel: '{count} Läufe',
    runsCountLabelSingular: '1 Lauf',
    artifactsToggleLabel: 'Alle {count} Artefaktdateien anzeigen',
    artifactsToggleLabelSingular: '1 Artefaktdatei anzeigen',
    sourceInEnglishNote: 'Die Quellmaterialien (Methodologien, Vorlagen und tägliche Analyseartefakte) werden auf Englisch veröffentlicht. Titel und Dateipfade sind daher auf Englisch — nur die Seitennavigation und Beschreibungen sind übersetzt.',
    seoKeywords: 'Europäisches Parlament, politische Aufklärung, OSINT, SWOT-Analyse, PESTLE-Analyse, Methodologie, Artefaktvorlagen, Koalitionsmathematik, Risikobewertung, Bedrohungsmodell, Transparenz, EU',
};
export const FR_COPY = {
    title: 'Intelligence politique',
    intro: "Chaque analyse politique publiée sur ce site s'appuie sur une chaîne transparente de méthodologies, de modèles d'artefacts et de données d'analyse par exécution. Cette page vous offre un index unique, entièrement lié, vers tout le savoir-faire utilisé pour produire les actualités.",
    heroSubtitle: 'Méthodologies, modèles et transparence des analyses quotidiennes',
    home: 'Accueil',
    breadcrumbCurrent: 'Intelligence politique',
    breadcrumbLabel: "Fil d'Ariane",
    methodologiesHeading: 'Méthodologies',
    methodologiesDescription: "Guides de savoir-faire faisant autorité — cadres de risque, normes de style et le protocole d'analyse en 10 étapes piloté par IA.",
    templatesHeading: "Modèles d'analyse",
    templatesDescription: "Catalogue des modèles d'artefacts produits dans chaque exécution d'analyse quotidienne — SWOT, PESTLE, matrices de menaces, dynamiques de coalition et arbres de conséquences.",
    referenceHeading: 'Références et sources de données',
    referenceDescription: "Adaptations de référence ISMS, catalogues d'indicateurs, mappages des pays de l'UE et guides d'intégration de graphiques derrière chaque source FMI et Banque mondiale.",
    statReferenceLabel: 'Références',
    dailyHeading: 'Exécutions d\u2019analyse quotidiennes',
    dailyDescription: "Chaque exécution d'analyse publiée, regroupée par date et triée du plus récent au plus ancien. Chaque exécution renvoie à l'arbre GitHub complet.",
    statMethodologiesLabel: 'Méthodologies',
    statTemplatesLabel: 'Modèles',
    statRunsLabel: 'Analyses',
    statArtifactsLabel: 'Artefacts',
    viewOnGitHub: 'Voir sur GitHub',
    artifactCountLabel: '{count} artefacts',
    artifactCountLabelSingular: '1 artefact',
    runsCountLabel: '{count} exécutions',
    runsCountLabelSingular: '1 exécution',
    artifactsToggleLabel: 'Afficher les {count} fichiers d\u2019artefacts',
    artifactsToggleLabelSingular: 'Afficher le fichier d\u2019artefact',
    sourceInEnglishNote: "Les documents sources (méthodologies, modèles et artefacts d'analyse quotidiens) sont publiés en anglais. Les titres et chemins de fichiers sont donc en anglais — seuls la navigation et les descriptions de la page sont traduits.",
    seoKeywords: 'Parlement européen, renseignement politique, OSINT, analyse SWOT, analyse PESTLE, méthodologie, modèles d’artefacts, mathématiques de coalition, évaluation des risques, modèle de menace, transparence, UE',
};
export const ES_COPY = {
    title: 'Inteligencia política',
    intro: 'Cada análisis político publicado en este sitio se respalda con una cadena transparente de metodologías, plantillas de artefactos y datos de análisis por ejecución. Esta página proporciona un único índice totalmente enlazado con todo el oficio empleado para producir las noticias.',
    heroSubtitle: 'Metodologías, plantillas y transparencia del análisis diario',
    home: 'Inicio',
    breadcrumbCurrent: 'Inteligencia política',
    breadcrumbLabel: 'Ruta de navegación',
    methodologiesHeading: 'Metodologías',
    methodologiesDescription: 'Guías autorizadas de oficio — marcos de riesgo, estándares de estilo y el protocolo de análisis impulsado por IA de 10 pasos.',
    templatesHeading: 'Plantillas de análisis',
    templatesDescription: 'Catálogo de plantillas de artefactos producidas en cada ejecución diaria — SWOT, PESTLE, matrices de amenazas, dinámicas de coalición y árboles de consecuencias.',
    referenceHeading: 'Referencias y fuentes de datos',
    referenceDescription: 'Adaptaciones de referencia ISMS, catálogos de indicadores, mapeos de países de la UE y guías de integración de gráficos detrás de cada fuente del FMI y del Banco Mundial.',
    statReferenceLabel: 'Referencias',
    dailyHeading: 'Ejecuciones de análisis diarias',
    dailyDescription: 'Cada ejecución de análisis publicada, agrupada por fecha y ordenada de más reciente a más antigua. Cada ejecución enlaza al árbol completo de GitHub.',
    statMethodologiesLabel: 'Metodologías',
    statTemplatesLabel: 'Plantillas',
    statRunsLabel: 'Ejecuciones',
    statArtifactsLabel: 'Artefactos',
    viewOnGitHub: 'Ver en GitHub',
    artifactCountLabel: '{count} artefactos',
    artifactCountLabelSingular: '1 artefacto',
    runsCountLabel: '{count} ejecuciones',
    runsCountLabelSingular: '1 ejecución',
    artifactsToggleLabel: 'Mostrar los {count} archivos de artefactos',
    artifactsToggleLabelSingular: 'Mostrar el archivo de artefacto',
    sourceInEnglishNote: 'Los materiales fuente (metodologías, plantillas y artefactos de análisis diarios) se publican en inglés. Los títulos y las rutas de archivo están, por tanto, en inglés — solo la navegación y las descripciones de la página están traducidas.',
    seoKeywords: 'Parlamento Europeo, inteligencia política, OSINT, análisis SWOT, análisis PESTLE, metodología, plantillas de artefactos, matemáticas de coaliciones, evaluación de riesgos, modelo de amenazas, transparencia, UE',
};
export const NL_COPY = {
    title: 'Politieke intelligentie',
    intro: 'Elke politieke analyse op deze website wordt ondersteund door een transparante keten van methodologieën, artefactsjablonen en analysegegevens per uitvoering. Deze pagina biedt een enkele, volledig gekoppelde index naar al het vakmanschap dat wordt gebruikt om het nieuws te produceren.',
    heroSubtitle: 'Methodologieën, sjablonen en dagelijkse analysetransparantie',
    home: 'Home',
    breadcrumbCurrent: 'Politieke intelligentie',
    breadcrumbLabel: 'Broodkruimelpad',
    methodologiesHeading: 'Methodologieën',
    methodologiesDescription: 'Gezaghebbende vakhandboeken — risicoframeworks, stijlstandaarden en het 10-staps AI-gedreven analyseprotocol.',
    templatesHeading: 'Analysesjablonen',
    templatesDescription: 'De catalogus met artefactsjablonen die in elke dagelijkse analyse-uitvoering worden geproduceerd — SWOT, PESTLE, dreigingsmatrices, coalitiedynamiek en consequentiebomen.',
    referenceHeading: 'Referenties en gegevensbronnen',
    referenceDescription: 'ISMS-referentieadaptaties, indicatorcatalogi, EU-landmappings en grafiekintegratiegidsen achter elke IMF- en Wereldbank-bron.',
    statReferenceLabel: 'Referenties',
    dailyHeading: 'Dagelijkse analyse-uitvoeringen',
    dailyDescription: 'Elke gepubliceerde analyse-uitvoering, gegroepeerd op datum en gesorteerd van nieuwste naar oudste. Elke uitvoering linkt naar de volledige GitHub-boom.',
    statMethodologiesLabel: 'Methodologieën',
    statTemplatesLabel: 'Sjablonen',
    statRunsLabel: 'Uitvoeringen',
    statArtifactsLabel: 'Artefacten',
    viewOnGitHub: 'Op GitHub bekijken',
    artifactCountLabel: '{count} artefacten',
    artifactCountLabelSingular: '1 artefact',
    runsCountLabel: '{count} uitvoeringen',
    runsCountLabelSingular: '1 uitvoering',
    artifactsToggleLabel: 'Alle {count} artefactbestanden tonen',
    artifactsToggleLabelSingular: '1 artefactbestand tonen',
    sourceInEnglishNote: 'De bronmaterialen (methodologieën, sjablonen en dagelijkse analyse-artefacten) worden in het Engels gepubliceerd. Titels en bestandspaden staan daarom in het Engels — alleen de paginanavigatie en beschrijvingen zijn vertaald.',
    seoKeywords: 'Europees Parlement, politieke inlichtingen, OSINT, SWOT-analyse, PESTLE-analyse, methodologie, artefactsjablonen, coalitiewiskunde, risicobeoordeling, dreigingsmodel, transparantie, EU',
};
//# sourceMappingURL=eu-core.js.map