// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/AnalysisConstants
 * @description Shared constants for the analysis pipeline. Kept in a standalone
 * module (outside generators/ and utils/) so that both `analysis-builders.ts`
 * and `intelligence-analysis.ts` can import it without introducing circular
 * ESM dependencies.
 */

/**
 * Marker for fields that require AI-generated political intelligence analysis.
 *
 * Scripts construct the structural scaffolding from data (what/who/when,
 * counts, identifiers, Mermaid charts) and may also derive some neutral,
 * factual descriptions directly from parliamentary data.
 *
 * Any narrative or interpretive analysis text (for example: why, outlook,
 * impact assessments, stakeholder reasoning, or mistake/consequence
 * explanations) that is LEFT AS THIS MARKER is expected to be generated by
 * the AI agent (Opus 4.6) in the agentic workflow, not by code.
 */
export const AI_MARKER = '[AI_ANALYSIS_REQUIRED]';

/**
 * Check whether a text value is the AI analysis placeholder marker.
 *
 * Used by rendering functions to detect unfilled AI analysis fields and
 * display a user-friendly "analysis pending" notice rather than the raw
 * marker string. Also catches the legacy `[REQUIRED]` format.
 *
 * @param text - Text to test
 * @returns `true` when the text is the AI placeholder marker
 */
export function isAiMarker(text: string | null | undefined): boolean {
  if (!text) return false;
  const trimmed = text.trim();
  return trimmed === AI_MARKER || trimmed === '[REQUIRED]' || trimmed === '[?]';
}

/**
 * CSS class applied to sections rendered with pending AI analysis content.
 * Used to visually indicate that the section awaits AI completion.
 */
export const AI_PENDING_CLASS = 'ai-analysis-pending';
