// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/LanguageUI
 * @description UI-facing localized strings — page titles, descriptions, section headings,
 * accessibility labels, article type labels, and read-time formatters.
 */

import type { LanguageMap, ArticleCategoryLabels } from '../types/index.js';
import { ArticleCategory } from '../types/index.js';

/** Page titles per language */
export const PAGE_TITLES: LanguageMap = {
  en: 'EU Parliament Monitor - News',
  sv: 'EU-parlamentsmonitor - Nyheter',
  da: 'EU-parlamentsmonitor - Nyheder',
  no: 'EU-parlamentsmonitor - Nyheter',
  fi: 'EU-parlamentin seuranta - Uutiset',
  de: 'EU-Parlamentsmonitor - Nachrichten',
  fr: 'Moniteur du Parlement UE - Actualités',
  es: 'Monitor del Parlamento UE - Noticias',
  nl: 'EU Parlementsmonitor - Nieuws',
  ar: 'مراقب البرلمان الأوروبي - أخبار',
  he: 'מוניטור הפרלמנט האירופי - חדשות',
  ja: 'EU議会モニター - ニュース',
  ko: 'EU 의회 모니터 - 뉴스',
  zh: 'EU议会监测 - 新闻',
};

/** Page descriptions per language */
export const PAGE_DESCRIPTIONS: LanguageMap = {
  en: 'Latest news and analysis about European Parliament activities',
  sv: 'Senaste nyheterna och analyser om Europaparlamentets verksamhet',
  da: 'Seneste nyheder og analyser om Europa-Parlamentets aktiviteter',
  no: 'Siste nytt og analyser om Europaparlamentets aktiviteter',
  fi: 'Viimeisimmät uutiset ja analyysit Euroopan parlamentin toiminnasta',
  de: 'Neueste Nachrichten und Analysen zu den Aktivitäten des Europäischen Parlaments',
  fr: 'Dernières nouvelles et analyses sur les activités du Parlement européen',
  es: 'Últimas noticias y análisis sobre las actividades del Parlamento Europeo',
  nl: 'Laatste nieuws en analyses over activiteiten van het Europees Parlement',
  ar: 'آخر الأخبار والتحليلات حول أنشطة البرلمان الأوروبي',
  he: 'חדשות ואנליזות עדכניות על פעילויות הפרלמנט האירופי',
  ja: '欧州議会活動に関する最新ニュースと分析',
  ko: '유럽 의회 활동에 관한 최신 뉴스 및 분석',
  zh: '关于欧洲议会活动的最新新闻和分析',
};

/** Section headings per language */
export const SECTION_HEADINGS: LanguageMap = {
  en: 'Latest News',
  sv: 'Senaste Nyheterna',
  da: 'Seneste Nyheder',
  no: 'Siste Nytt',
  fi: 'Viimeisimmät Uutiset',
  de: 'Neueste Nachrichten',
  fr: 'Dernières Actualités',
  es: 'Últimas Noticias',
  nl: 'Laatste Nieuws',
  ar: 'آخر الأخبار',
  he: 'חדשות אחרונות',
  ja: '最新ニュース',
  ko: '최신 뉴스',
  zh: '最新新闻',
};

/** "No articles" messages per language */
export const NO_ARTICLES_MESSAGES: LanguageMap = {
  en: 'No articles available yet.',
  sv: 'Inga artiklar tillgängliga ännu.',
  da: 'Ingen artikler tilgængelige endnu.',
  no: 'Ingen artikler tilgjengelige ennå.',
  fi: 'Ei vielä saatavilla olevia artikkeleita.',
  de: 'Noch keine Artikel verfügbar.',
  fr: 'Aucun article disponible pour le moment.',
  es: 'Aún no hay artículos disponibles.',
  nl: 'Nog geen artikelen beschikbaar.',
  ar: 'لا توجد مقالات متاحة بعد.',
  he: 'אין עדיין מאמרים זמינים.',
  ja: 'まだ記事がありません。',
  ko: '아직 이용 가능한 기사가 없습니다.',
  zh: '暂无文章。',
};

/** Skip link text per language */
export const SKIP_LINK_TEXTS: LanguageMap = {
  en: 'Skip to main content',
  sv: 'Hoppa till huvudinnehåll',
  da: 'Spring til hovedindhold',
  no: 'Hopp til hovedinnhold',
  fi: 'Siirry pääsisältöön',
  de: 'Zum Hauptinhalt springen',
  fr: 'Aller au contenu principal',
  es: 'Ir al contenido principal',
  nl: 'Ga naar hoofdinhoud',
  ar: 'انتقل إلى المحتوى الرئيسي',
  he: 'דלג לתוכן הראשי',
  ja: 'メインコンテンツへスキップ',
  ko: '본문으로 건너뛰기',
  zh: '跳至主要内容',
};

/** Article category labels per language — covers all ArticleCategory values */
export const ARTICLE_TYPE_LABELS: LanguageMap<ArticleCategoryLabels> = {
  en: {
    [ArticleCategory.WEEK_AHEAD]: 'Week Ahead',
    [ArticleCategory.MONTH_AHEAD]: 'Month Ahead',
    [ArticleCategory.YEAR_AHEAD]: 'Year Ahead',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Week in Review',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Month in Review',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Year in Review',
    [ArticleCategory.BREAKING_NEWS]: 'Breaking News',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Committee Reports',
    [ArticleCategory.MOTIONS]: 'Parliamentary Motions',
    [ArticleCategory.PROPOSITIONS]: 'Legislative Proposals',
    [ArticleCategory.DEEP_ANALYSIS]: 'Deep Analysis',
  },
  sv: {
    [ArticleCategory.WEEK_AHEAD]: 'Vecka Framåt',
    [ArticleCategory.MONTH_AHEAD]: 'Månad Framåt',
    [ArticleCategory.YEAR_AHEAD]: 'År Framåt',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Veckans Sammanfattning',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Månadens Sammanfattning',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Årets Sammanfattning',
    [ArticleCategory.BREAKING_NEWS]: 'Senaste Nytt',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Utskottsrapporter',
    [ArticleCategory.MOTIONS]: 'Parlamentariska Motioner',
    [ArticleCategory.PROPOSITIONS]: 'Lagstiftningsförslag',
    [ArticleCategory.DEEP_ANALYSIS]: 'Djupanalys',
  },
  da: {
    [ArticleCategory.WEEK_AHEAD]: 'Ugen Fremover',
    [ArticleCategory.MONTH_AHEAD]: 'Måneden Fremover',
    [ArticleCategory.YEAR_AHEAD]: 'Året Fremover',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Ugens Overblik',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Månedens Overblik',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Årets Overblik',
    [ArticleCategory.BREAKING_NEWS]: 'Seneste Nyt',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Udvalgsrapporter',
    [ArticleCategory.MOTIONS]: 'Parlamentariske Motioner',
    [ArticleCategory.PROPOSITIONS]: 'Lovgivningsforslag',
    [ArticleCategory.DEEP_ANALYSIS]: 'Dybdeanalyse',
  },
  no: {
    [ArticleCategory.WEEK_AHEAD]: 'Uken Fremover',
    [ArticleCategory.MONTH_AHEAD]: 'Måneden Fremover',
    [ArticleCategory.YEAR_AHEAD]: 'Året Fremover',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Ukens Oppsummering',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Månedens Oppsummering',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Årets Oppsummering',
    [ArticleCategory.BREAKING_NEWS]: 'Siste Nytt',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Komitérapporter',
    [ArticleCategory.MOTIONS]: 'Parlamentariske Forslag',
    [ArticleCategory.PROPOSITIONS]: 'Lovgivningsforslag',
    [ArticleCategory.DEEP_ANALYSIS]: 'Dybdeanalyse',
  },
  fi: {
    [ArticleCategory.WEEK_AHEAD]: 'Tuleva Viikko',
    [ArticleCategory.MONTH_AHEAD]: 'Tuleva Kuukausi',
    [ArticleCategory.YEAR_AHEAD]: 'Tuleva Vuosi',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Viikon Katsaus',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Kuukauden Katsaus',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Vuoden Katsaus',
    [ArticleCategory.BREAKING_NEWS]: 'Uusimmat Uutiset',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Valiokuntaraportit',
    [ArticleCategory.MOTIONS]: 'Parlamentaariset Esitykset',
    [ArticleCategory.PROPOSITIONS]: 'Lainsäädäntöehdotukset',
    [ArticleCategory.DEEP_ANALYSIS]: 'Syväanalyysi',
  },
  de: {
    [ArticleCategory.WEEK_AHEAD]: 'Woche Voraus',
    [ArticleCategory.MONTH_AHEAD]: 'Monat Voraus',
    [ArticleCategory.YEAR_AHEAD]: 'Jahr Voraus',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Wochenrückblick',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Monatsrückblick',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Jahresrückblick',
    [ArticleCategory.BREAKING_NEWS]: 'Eilmeldung',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Ausschussberichte',
    [ArticleCategory.MOTIONS]: 'Parlamentarische Anträge',
    [ArticleCategory.PROPOSITIONS]: 'Gesetzgebungsvorschläge',
    [ArticleCategory.DEEP_ANALYSIS]: 'Tiefenanalyse',
  },
  fr: {
    [ArticleCategory.WEEK_AHEAD]: 'Semaine à Venir',
    [ArticleCategory.MONTH_AHEAD]: 'Mois à Venir',
    [ArticleCategory.YEAR_AHEAD]: 'Année à Venir',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Bilan de la Semaine',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Bilan du Mois',
    [ArticleCategory.YEAR_IN_REVIEW]: "Bilan de l'Année",
    [ArticleCategory.BREAKING_NEWS]: 'Dernières Nouvelles',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Rapports de Commission',
    [ArticleCategory.MOTIONS]: 'Motions Parlementaires',
    [ArticleCategory.PROPOSITIONS]: 'Propositions Législatives',
    [ArticleCategory.DEEP_ANALYSIS]: 'Analyse Approfondie',
  },
  es: {
    [ArticleCategory.WEEK_AHEAD]: 'Semana Próxima',
    [ArticleCategory.MONTH_AHEAD]: 'Mes Próximo',
    [ArticleCategory.YEAR_AHEAD]: 'Año Próximo',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Resumen de la Semana',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Resumen del Mes',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Resumen del Año',
    [ArticleCategory.BREAKING_NEWS]: 'Noticias de Última Hora',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Informes de Comisión',
    [ArticleCategory.MOTIONS]: 'Mociones Parlamentarias',
    [ArticleCategory.PROPOSITIONS]: 'Propuestas Legislativas',
    [ArticleCategory.DEEP_ANALYSIS]: 'Análisis Profundo',
  },
  nl: {
    [ArticleCategory.WEEK_AHEAD]: 'Week Vooruit',
    [ArticleCategory.MONTH_AHEAD]: 'Maand Vooruit',
    [ArticleCategory.YEAR_AHEAD]: 'Jaar Vooruit',
    [ArticleCategory.WEEK_IN_REVIEW]: 'Weekoverzicht',
    [ArticleCategory.MONTH_IN_REVIEW]: 'Maandoverzicht',
    [ArticleCategory.YEAR_IN_REVIEW]: 'Jaaroverzicht',
    [ArticleCategory.BREAKING_NEWS]: 'Laatste Nieuws',
    [ArticleCategory.COMMITTEE_REPORTS]: 'Commissierapporten',
    [ArticleCategory.MOTIONS]: 'Parlementaire Moties',
    [ArticleCategory.PROPOSITIONS]: 'Wetgevingsvoorstellen',
    [ArticleCategory.DEEP_ANALYSIS]: 'Diepgaande Analyse',
  },
  ar: {
    [ArticleCategory.WEEK_AHEAD]: 'الأسبوع القادم',
    [ArticleCategory.MONTH_AHEAD]: 'الشهر القادم',
    [ArticleCategory.YEAR_AHEAD]: 'العام القادم',
    [ArticleCategory.WEEK_IN_REVIEW]: 'مراجعة الأسبوع',
    [ArticleCategory.MONTH_IN_REVIEW]: 'مراجعة الشهر',
    [ArticleCategory.YEAR_IN_REVIEW]: 'مراجعة العام',
    [ArticleCategory.BREAKING_NEWS]: 'أخبار عاجلة',
    [ArticleCategory.COMMITTEE_REPORTS]: 'تقارير اللجان',
    [ArticleCategory.MOTIONS]: 'اقتراحات برلمانية',
    [ArticleCategory.PROPOSITIONS]: 'مقترحات تشريعية',
    [ArticleCategory.DEEP_ANALYSIS]: 'تحليل معمّق',
  },
  he: {
    [ArticleCategory.WEEK_AHEAD]: 'השבוע הקרוב',
    [ArticleCategory.MONTH_AHEAD]: 'החודש הקרוב',
    [ArticleCategory.YEAR_AHEAD]: 'השנה הקרובה',
    [ArticleCategory.WEEK_IN_REVIEW]: 'סיכום השבוע',
    [ArticleCategory.MONTH_IN_REVIEW]: 'סיכום החודש',
    [ArticleCategory.YEAR_IN_REVIEW]: 'סיכום השנה',
    [ArticleCategory.BREAKING_NEWS]: 'חדשות דחופות',
    [ArticleCategory.COMMITTEE_REPORTS]: 'דוחות ועדות',
    [ArticleCategory.MOTIONS]: 'הצעות פרלמנטריות',
    [ArticleCategory.PROPOSITIONS]: 'הצעות חקיקה',
    [ArticleCategory.DEEP_ANALYSIS]: 'ניתוח מעמיק',
  },
  ja: {
    [ArticleCategory.WEEK_AHEAD]: '今週の予定',
    [ArticleCategory.MONTH_AHEAD]: '今月の予定',
    [ArticleCategory.YEAR_AHEAD]: '年間展望',
    [ArticleCategory.WEEK_IN_REVIEW]: '週間レビュー',
    [ArticleCategory.MONTH_IN_REVIEW]: '月間レビュー',
    [ArticleCategory.YEAR_IN_REVIEW]: '年間レビュー',
    [ArticleCategory.BREAKING_NEWS]: '速報',
    [ArticleCategory.COMMITTEE_REPORTS]: '委員会報告',
    [ArticleCategory.MOTIONS]: '議会動議',
    [ArticleCategory.PROPOSITIONS]: '法案提案',
    [ArticleCategory.DEEP_ANALYSIS]: '深層分析',
  },
  ko: {
    [ArticleCategory.WEEK_AHEAD]: '다음 주 일정',
    [ArticleCategory.MONTH_AHEAD]: '다음 달 일정',
    [ArticleCategory.YEAR_AHEAD]: '연간 전망',
    [ArticleCategory.WEEK_IN_REVIEW]: '주간 리뷰',
    [ArticleCategory.MONTH_IN_REVIEW]: '월간 리뷰',
    [ArticleCategory.YEAR_IN_REVIEW]: '연간 리뷰',
    [ArticleCategory.BREAKING_NEWS]: '속보',
    [ArticleCategory.COMMITTEE_REPORTS]: '위원회 보고서',
    [ArticleCategory.MOTIONS]: '의회 동의안',
    [ArticleCategory.PROPOSITIONS]: '입법 제안',
    [ArticleCategory.DEEP_ANALYSIS]: '심층 분석',
  },
  zh: {
    [ArticleCategory.WEEK_AHEAD]: '下周预告',
    [ArticleCategory.MONTH_AHEAD]: '下月预告',
    [ArticleCategory.YEAR_AHEAD]: '年度展望',
    [ArticleCategory.WEEK_IN_REVIEW]: '每周回顾',
    [ArticleCategory.MONTH_IN_REVIEW]: '每月回顾',
    [ArticleCategory.YEAR_IN_REVIEW]: '年度回顾',
    [ArticleCategory.BREAKING_NEWS]: '突发新闻',
    [ArticleCategory.COMMITTEE_REPORTS]: '委员会报告',
    [ArticleCategory.MOTIONS]: '议会动议',
    [ArticleCategory.PROPOSITIONS]: '立法提案',
    [ArticleCategory.DEEP_ANALYSIS]: '深度分析',
  },
};

/** Read time label formatters per language */
export const READ_TIME_LABELS: LanguageMap<(time: number) => string> = {
  en: (time: number) => `${time} min read`,
  sv: (time: number) => `${time} min läsning`,
  da: (time: number) => `${time} min læsetid`,
  no: (time: number) => `${time} min lesetid`,
  fi: (time: number) => `${time} min lukuaika`,
  de: (time: number) => `${time} Min. Lesezeit`,
  fr: (time: number) => `${time} min de lecture`,
  es: (time: number) => `${time} min de lectura`,
  nl: (time: number) => `${time} min leestijd`,
  ar: (time: number) => `${time} دقائق قراءة`,
  he: (time: number) => `${time} דקות קריאה`,
  ja: (time: number) => `${time}分で読了`,
  ko: (time: number) => `${time}분 읽기`,
  zh: (time: number) => `${time}分钟阅读`,
};

/** Back to news link labels per language */
export const BACK_TO_NEWS_LABELS: LanguageMap = {
  en: '← Back to News',
  sv: '← Tillbaka till Nyheter',
  da: '← Tilbage til Nyheder',
  no: '← Tilbake til Nyheter',
  fi: '← Takaisin Uutisiin',
  de: '← Zurück zu Nachrichten',
  fr: '← Retour aux Actualités',
  es: '← Volver a Noticias',
  nl: '← Terug naar Nieuws',
  ar: '→ العودة إلى الأخبار',
  he: '→ חזרה לחדשות',
  ja: '← ニュースに戻る',
  ko: '← 뉴스로 돌아가기',
  zh: '← 返回新闻',
};

/** Article navigation aria-label per language */
export const ARTICLE_NAV_LABELS: LanguageMap = {
  en: 'Article navigation',
  sv: 'Artikelnavigering',
  da: 'Artikelnavigation',
  no: 'Artikkelnavigasjon',
  fi: 'Artikkelin navigointi',
  de: 'Artikelnavigation',
  fr: 'Navigation de l\'article',
  es: 'Navegación del artículo',
  nl: 'Artikelnavigatie',
  ar: 'التنقل في المقالة',
  he: 'ניווט מאמר',
  ja: '記事ナビゲーション',
  ko: '기사 탐색',
  zh: '文章导航',
};
