// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** AR deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_AR = {
    sectionHeading: 'تحليل سياسي معمّق',
    whatHeading: 'ماذا حدث',
    whoHeading: 'الجهات الفاعلة الرئيسية',
    whenHeading: 'الجدول الزمني',
    whyHeading: 'لماذا هذا مهم — الأسباب الجذرية',
    stakeholderHeading: 'الرابحون والخاسرون',
    winnerLabel: 'رابح',
    loserLabel: 'خاسر',
    neutralLabel: 'محايد',
    impactHeading: 'تقييم الأثر',
    politicalLabel: 'سياسي',
    economicLabel: 'اقتصادي',
    socialLabel: 'اجتماعي',
    legalLabel: 'قانوني',
    geopoliticalLabel: 'جيوسياسي',
    consequencesHeading: 'إجراءات ← عواقب',
    actionLabel: 'إجراء',
    consequenceLabel: 'عاقبة',
    severityColumnLabel: 'شدة',
    mistakesHeading: 'أخطاء في الحسابات وفرص ضائعة',
    alternativeLabel: 'كان ينبغي',
    outlookHeading: 'النظرة الاستراتيجية',
    severityLow: 'منخفض',
    severityMedium: 'متوسط',
    severityHigh: 'مرتفع',
    severityCritical: 'حرج',
    executiveSummaryHeading: 'ملخص تنفيذي',
    confidenceHigh: 'ثقة عالية',
    confidenceMedium: 'ثقة متوسطة',
    confidenceLow: 'ثقة منخفضة',
    evidenceRefsHeading: 'الأدلة',
    counterArgumentsHeading: 'حجج مضادة',
    conclusionLabel: 'استنتاج:',
    premiseLabel: 'مقدمة:',
    inferenceLabel: 'استدلال:',
    reasoningChainsHeading: 'سلاسل الاستدلال',
    scenarioPlanningHeading: 'تخطيط السيناريوهات',
    bestCaseLabel: 'أفضل سيناريو',
    worstCaseLabel: 'أسوأ سيناريو',
    mostLikelyLabel: 'الأكثر احتمالاً',
    wildcardsLabel: 'عوامل غير متوقعة',
    probabilityLabel: 'الاحتمالية',
    triggersLabel: 'المحفزات',
    impliedImpactsLabel: 'التأثيرات المتوقعة',
    timelineLabel: 'الجدول الزمني',
    analysisMethodologyHeading: 'منهجية التحليل',
    iterationCountLabel: 'التكرارات',
    evidenceStrengthLabel: 'قوة الأدلة',
    evidenceStrong: 'قوي',
    evidenceModerate: 'معتدل',
    evidenceWeak: 'ضعيف',
    iterationInitial: 'التقييم الأولي',
    iterationStakeholderChallenge: 'تحدي أصحاب المصلحة',
    iterationEvidenceValidation: 'التحقق من الأدلة',
    iterationSynthesis: 'التوليف',
    overallConfidenceLabel: 'الثقة الإجمالية',
    pendingNotice: 'التحليل معلق — سيتم استكمال هذا القسم بواسطة سير العمل التحريري التحليلي.',
    perspectivesHeading: 'وجهات نظر أصحاب المصلحة',
    outcomeMatrixHeading: 'مصفوفة نتائج أصحاب المصلحة',
    confidenceLabel: 'الثقة',
    politicalGroupsLabel: 'المجموعات السياسية',
    civilSocietyLabel: 'المجتمع المدني',
    industryLabel: 'الصناعة',
    nationalGovtsLabel: 'الحكومات الوطنية',
    citizensLabel: 'المواطنون',
    euInstitutionsLabel: 'مؤسسات الاتحاد الأوروبي',
    positiveLabel: 'إيجابي',
    negativeLabel: 'سلبي',
    mixedLabel: 'مختلط',
};
//# sourceMappingURL=ar.js.map