// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** FI deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_FI = {
    sectionHeading: 'Syvällinen Poliittinen Analyysi',
    whatHeading: 'Mitä Tapahtui',
    whoHeading: 'Keskeiset Toimijat',
    whenHeading: 'Aikajana',
    whyHeading: 'Miksi Sillä On Merkitystä — Juurisyyt',
    stakeholderHeading: 'Voittajat & Häviäjät',
    winnerLabel: 'Voittaja',
    loserLabel: 'Häviäjä',
    neutralLabel: 'Neutraali',
    impactHeading: 'Vaikutusarviointi',
    politicalLabel: 'Poliittinen',
    economicLabel: 'Taloudellinen',
    socialLabel: 'Sosiaalinen',
    legalLabel: 'Oikeudellinen',
    geopoliticalLabel: 'Geopoliittinen',
    consequencesHeading: 'Toimet → Seuraukset',
    actionLabel: 'Toimi',
    consequenceLabel: 'Seuraus',
    severityColumnLabel: 'Vakavuus',
    mistakesHeading: 'Virhearvioinnit & Menetetyt Mahdollisuudet',
    alternativeLabel: 'Olisi pitänyt',
    outlookHeading: 'Strategiset Näkymät',
    severityLow: 'Matala',
    severityMedium: 'Keskitaso',
    severityHigh: 'Korkea',
    severityCritical: 'Kriittinen',
    executiveSummaryHeading: 'Yhteenveto',
    confidenceHigh: 'Korkea Luotettavuus',
    confidenceMedium: 'Keskitason Luotettavuus',
    confidenceLow: 'Matala Luotettavuus',
    evidenceRefsHeading: 'Todisteet',
    counterArgumentsHeading: 'Vasta-argumentit',
    conclusionLabel: 'Johtopäätös:',
    premiseLabel: 'Lähtökohta:',
    inferenceLabel: 'Päätelmä:',
    reasoningChainsHeading: 'Päättelyketjut',
    scenarioPlanningHeading: 'Skenaarion Suunnittelu',
    bestCaseLabel: 'Paras Skenaario',
    worstCaseLabel: 'Pahin Skenaario',
    mostLikelyLabel: 'Todennäköisin',
    wildcardsLabel: 'Jokerikortit',
    probabilityLabel: 'Todennäköisyys',
    triggersLabel: 'Laukaisijat',
    impliedImpactsLabel: 'Odotetut Vaikutukset',
    timelineLabel: 'Aikajana',
    analysisMethodologyHeading: 'Analyysimenetelmä',
    iterationCountLabel: 'Iteraatiot',
    evidenceStrengthLabel: 'Todistusvoima',
    evidenceStrong: 'Vahva',
    evidenceModerate: 'Kohtalainen',
    evidenceWeak: 'Heikko',
    iterationInitial: 'Alustava Arviointi',
    iterationStakeholderChallenge: 'Sidosryhmähaaste',
    iterationEvidenceValidation: 'Todisteiden Validointi',
    iterationSynthesis: 'Synteesi',
    overallConfidenceLabel: 'Kokonaisluotettavuus',
    pendingNotice: 'Analyysi odottaa — tämä osio täydennetään toimituksellisen analyysin työnkulussa.',
    perspectivesHeading: 'Sidosryhmänäkökulmat',
    outcomeMatrixHeading: 'Sidosryhmätulosmatriisi',
    confidenceLabel: 'Luotettavuus',
    politicalGroupsLabel: 'Poliittiset ryhmät',
    civilSocietyLabel: 'Kansalaisyhteiskunta',
    industryLabel: 'Teollisuus',
    nationalGovtsLabel: 'Kansalliset hallitukset',
    citizensLabel: 'Kansalaiset',
    euInstitutionsLabel: 'EU:n toimielimet',
    positiveLabel: 'Positiivinen',
    negativeLabel: 'Negatiivinen',
    mixedLabel: 'Sekalainen',
};
//# sourceMappingURL=fi.js.map