// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** FR deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_FR = {
    sectionHeading: 'Analyse Politique Approfondie',
    whatHeading: "Ce Qui S'est Passé",
    whoHeading: 'Acteurs Clés',
    whenHeading: 'Chronologie',
    whyHeading: "Pourquoi C'est Important — Causes Profondes",
    stakeholderHeading: 'Gagnants & Perdants',
    winnerLabel: 'Gagnant',
    loserLabel: 'Perdant',
    neutralLabel: 'Neutre',
    impactHeading: "Évaluation d'Impact",
    politicalLabel: 'Politique',
    economicLabel: 'Économique',
    socialLabel: 'Social',
    legalLabel: 'Juridique',
    geopoliticalLabel: 'Géopolitique',
    consequencesHeading: 'Actions → Conséquences',
    actionLabel: 'Action',
    consequenceLabel: 'Conséquence',
    severityColumnLabel: 'Gravité',
    mistakesHeading: 'Erreurs de Calcul & Opportunités Manquées',
    alternativeLabel: 'Aurait dû',
    outlookHeading: 'Perspectives Stratégiques',
    severityLow: 'Faible',
    severityMedium: 'Moyen',
    severityHigh: 'Élevé',
    severityCritical: 'Critique',
    executiveSummaryHeading: 'Synthèse',
    confidenceHigh: 'Confiance Élevée',
    confidenceMedium: 'Confiance Moyenne',
    confidenceLow: 'Confiance Faible',
    evidenceRefsHeading: 'Preuves',
    counterArgumentsHeading: 'Contre-arguments',
    conclusionLabel: 'Conclusion :',
    premiseLabel: 'Prémisse :',
    inferenceLabel: 'Inférence :',
    reasoningChainsHeading: 'Chaînes de Raisonnement',
    scenarioPlanningHeading: 'Planification de Scénarios',
    bestCaseLabel: 'Meilleur Scénario',
    worstCaseLabel: 'Pire Scénario',
    mostLikelyLabel: 'Plus Probable',
    wildcardsLabel: 'Imprévus',
    probabilityLabel: 'Probabilité',
    triggersLabel: 'Déclencheurs',
    impliedImpactsLabel: 'Impacts Attendus',
    timelineLabel: 'Chronologie',
    analysisMethodologyHeading: "Méthodologie d'Analyse",
    iterationCountLabel: 'Itérations',
    evidenceStrengthLabel: 'Force des Preuves',
    evidenceStrong: 'Fort',
    evidenceModerate: 'Modéré',
    evidenceWeak: 'Faible',
    iterationInitial: 'Évaluation Initiale',
    iterationStakeholderChallenge: 'Défi des Parties Prenantes',
    iterationEvidenceValidation: 'Validation des Preuves',
    iterationSynthesis: 'Synthèse',
    overallConfidenceLabel: 'Confiance Globale',
    pendingNotice: "Analyse en attente — cette section sera complétée par le flux de travail d'analyse éditoriale.",
    perspectivesHeading: 'Perspectives des Parties Prenantes',
    outcomeMatrixHeading: 'Matrice des Résultats des Parties Prenantes',
    confidenceLabel: 'Confiance',
    politicalGroupsLabel: 'Groupes politiques',
    civilSocietyLabel: 'Société civile',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Gouvernements nationaux',
    citizensLabel: 'Citoyens',
    euInstitutionsLabel: "Institutions de l'UE",
    positiveLabel: 'Positif',
    negativeLabel: 'Négatif',
    mixedLabel: 'Mixte',
};
//# sourceMappingURL=fr.js.map