// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** HE deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_HE = {
    sectionHeading: 'ניתוח פוליטי מעמיק',
    whatHeading: 'מה קרה',
    whoHeading: 'שחקנים מרכזיים',
    whenHeading: 'ציר זמן',
    whyHeading: 'מדוע זה חשוב — סיבות שורש',
    stakeholderHeading: 'מרוויחים ומפסידים',
    winnerLabel: 'מרוויח',
    loserLabel: 'מפסיד',
    neutralLabel: 'ניטרלי',
    impactHeading: 'הערכת השפעה',
    politicalLabel: 'פוליטי',
    economicLabel: 'כלכלי',
    socialLabel: 'חברתי',
    legalLabel: 'משפטי',
    geopoliticalLabel: 'גיאופוליטי',
    consequencesHeading: 'פעולות ← השלכות',
    actionLabel: 'פעולה',
    consequenceLabel: 'השלכה',
    severityColumnLabel: 'חומרה',
    mistakesHeading: 'טעויות חישוב והזדמנויות שהוחמצו',
    alternativeLabel: 'היה צריך',
    outlookHeading: 'תחזית אסטרטגית',
    severityLow: 'נמוך',
    severityMedium: 'בינוני',
    severityHigh: 'גבוה',
    severityCritical: 'קריטי',
    executiveSummaryHeading: 'תקציר מנהלים',
    confidenceHigh: 'ביטחון גבוה',
    confidenceMedium: 'ביטחון בינוני',
    confidenceLow: 'ביטחון נמוך',
    evidenceRefsHeading: 'ראיות',
    counterArgumentsHeading: 'טענות נגד',
    conclusionLabel: 'מסקנה:',
    premiseLabel: 'הנחה:',
    inferenceLabel: 'היסק:',
    reasoningChainsHeading: 'שרשראות היסק',
    scenarioPlanningHeading: 'תכנון תרחישים',
    bestCaseLabel: 'תרחיש אופטימי',
    worstCaseLabel: 'תרחיש גרוע',
    mostLikelyLabel: 'הסביר ביותר',
    wildcardsLabel: 'גורמים בלתי צפויים',
    probabilityLabel: 'הסתברות',
    triggersLabel: 'טריגרים',
    impliedImpactsLabel: 'השפעות צפויות',
    timelineLabel: 'ציר זמן',
    analysisMethodologyHeading: 'מתודולוגיית ניתוח',
    iterationCountLabel: 'איטרציות',
    evidenceStrengthLabel: 'עוצמת הראיות',
    evidenceStrong: 'חזק',
    evidenceModerate: 'בינוני',
    evidenceWeak: 'חלש',
    iterationInitial: 'הערכה ראשונית',
    iterationStakeholderChallenge: 'אתגר בעלי עניין',
    iterationEvidenceValidation: 'אימות ראיות',
    iterationSynthesis: 'סינתזה',
    overallConfidenceLabel: 'ביטחון כולל',
    pendingNotice: 'ניתוח ממתין — חלק זה יושלם על ידי תהליך העבודה של הניתוח העורכי.',
    perspectivesHeading: 'נקודות מבט של בעלי עניין',
    outcomeMatrixHeading: 'מטריצת תוצאות בעלי עניין',
    confidenceLabel: 'ביטחון',
    politicalGroupsLabel: 'קבוצות פוליטיות',
    civilSocietyLabel: 'חברה אזרחית',
    industryLabel: 'תעשייה',
    nationalGovtsLabel: 'ממשלות לאומיות',
    citizensLabel: 'אזרחים',
    euInstitutionsLabel: 'מוסדות האיחוד האירופי',
    positiveLabel: 'חיובי',
    negativeLabel: 'שלילי',
    mixedLabel: 'מעורב',
};
//# sourceMappingURL=he.js.map