// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** NL deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_NL = {
    sectionHeading: 'Diepgaande Politieke Analyse',
    whatHeading: 'Wat er Gebeurde',
    whoHeading: 'Belangrijkste Actoren',
    whenHeading: 'Tijdlijn',
    whyHeading: 'Waarom Het Belangrijk Is — Grondoorzaken',
    stakeholderHeading: 'Winnaars & Verliezers',
    winnerLabel: 'Winnaar',
    loserLabel: 'Verliezer',
    neutralLabel: 'Neutraal',
    impactHeading: 'Impactbeoordeling',
    politicalLabel: 'Politiek',
    economicLabel: 'Economisch',
    socialLabel: 'Sociaal',
    legalLabel: 'Juridisch',
    geopoliticalLabel: 'Geopolitiek',
    consequencesHeading: 'Acties → Gevolgen',
    actionLabel: 'Actie',
    consequenceLabel: 'Gevolg',
    severityColumnLabel: 'Ernst',
    mistakesHeading: 'Misrekeningen & Gemiste Kansen',
    alternativeLabel: 'Had moeten',
    outlookHeading: 'Strategisch Vooruitzicht',
    severityLow: 'Laag',
    severityMedium: 'Gemiddeld',
    severityHigh: 'Hoog',
    severityCritical: 'Kritiek',
    executiveSummaryHeading: 'Samenvatting',
    confidenceHigh: 'Hoog Vertrouwen',
    confidenceMedium: 'Gemiddeld Vertrouwen',
    confidenceLow: 'Laag Vertrouwen',
    evidenceRefsHeading: 'Bewijs',
    counterArgumentsHeading: 'Tegenargumenten',
    conclusionLabel: 'Conclusie:',
    premiseLabel: 'Premisse:',
    inferenceLabel: 'Gevolgtrekking:',
    reasoningChainsHeading: 'Redeneerketens',
    scenarioPlanningHeading: 'Scenarioplanning',
    bestCaseLabel: 'Beste Scenario',
    worstCaseLabel: 'Slechtste Scenario',
    mostLikelyLabel: 'Meest Waarschijnlijk',
    wildcardsLabel: 'Onverwachte Factoren',
    probabilityLabel: 'Waarschijnlijkheid',
    triggersLabel: 'Triggers',
    impliedImpactsLabel: 'Verwachte Effecten',
    timelineLabel: 'Tijdlijn',
    analysisMethodologyHeading: 'Analysemethodologie',
    iterationCountLabel: 'Iteraties',
    evidenceStrengthLabel: 'Bewijskracht',
    evidenceStrong: 'Sterk',
    evidenceModerate: 'Matig',
    evidenceWeak: 'Zwak',
    iterationInitial: 'Eerste Beoordeling',
    iterationStakeholderChallenge: 'Stakeholderuitdaging',
    iterationEvidenceValidation: 'Bewijsvalidatie',
    iterationSynthesis: 'Synthese',
    overallConfidenceLabel: 'Algeheel Vertrouwen',
    pendingNotice: 'Analyse in afwachting — deze sectie wordt aangevuld door de redactionele analyse-workflow.',
    perspectivesHeading: 'Stakeholdersperspectieven',
    outcomeMatrixHeading: 'Stakeholdersresultaatmatrix',
    confidenceLabel: 'Vertrouwen',
    politicalGroupsLabel: 'Politieke fracties',
    civilSocietyLabel: 'Maatschappelijk middenveld',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Nationale regeringen',
    citizensLabel: 'Burgers',
    euInstitutionsLabel: 'EU-instellingen',
    positiveLabel: 'Positief',
    negativeLabel: 'Negatief',
    mixedLabel: 'Gemengd',
};
//# sourceMappingURL=nl.js.map