// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** NO deep-analysis strings */
export const DEEP_ANALYSIS_STRINGS_NO = {
    sectionHeading: 'Dyptgående Politisk Analyse',
    whatHeading: 'Hva Skjedde',
    whoHeading: 'Nøkkelaktører',
    whenHeading: 'Tidslinje',
    whyHeading: 'Hvorfor Det Betyr Noe — Grunnårsaker',
    stakeholderHeading: 'Vinnere & Tapere',
    winnerLabel: 'Vinner',
    loserLabel: 'Taper',
    neutralLabel: 'Nøytral',
    impactHeading: 'Konsekvensutredning',
    politicalLabel: 'Politisk',
    economicLabel: 'Økonomisk',
    socialLabel: 'Sosial',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Handlinger → Konsekvenser',
    actionLabel: 'Handling',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Alvorlighetsgrad',
    mistakesHeading: 'Feilberegninger & Tapte Muligheter',
    alternativeLabel: 'Burde ha',
    outlookHeading: 'Strategisk Utsikt',
    severityLow: 'Lav',
    severityMedium: 'Middels',
    severityHigh: 'Høy',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Sammendrag',
    confidenceHigh: 'Høy Tillit',
    confidenceMedium: 'Middels Tillit',
    confidenceLow: 'Lav Tillit',
    evidenceRefsHeading: 'Bevis',
    counterArgumentsHeading: 'Motargumenter',
    conclusionLabel: 'Konklusjon:',
    premiseLabel: 'Premiss:',
    inferenceLabel: 'Slutning:',
    reasoningChainsHeading: 'Resonnementsrekker',
    scenarioPlanningHeading: 'Scenarioplanlegging',
    bestCaseLabel: 'Beste Scenario',
    worstCaseLabel: 'Verste Scenario',
    mostLikelyLabel: 'Mest Sannsynlig',
    wildcardsLabel: 'Jokere',
    probabilityLabel: 'Sannsynlighet',
    triggersLabel: 'Utløsere',
    impliedImpactsLabel: 'Forventede Konsekvenser',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysemetodikk',
    iterationCountLabel: 'Iterasjoner',
    evidenceStrengthLabel: 'Bevisstyrke',
    evidenceStrong: 'Sterk',
    evidenceModerate: 'Moderat',
    evidenceWeak: 'Svak',
    iterationInitial: 'Innledende Vurdering',
    iterationStakeholderChallenge: 'Interessentutfordring',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntese',
    overallConfidenceLabel: 'Samlet Tillit',
    pendingNotice: 'Analyse avventer — denne seksjonen vil bli fullført av den redaksjonelle analyse-arbeidsflyten.',
    perspectivesHeading: 'Interessentperspektiver',
    outcomeMatrixHeading: 'Interessentutfallsmatrise',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiske grupper',
    civilSocietyLabel: 'Sivilsamfunn',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nasjonale regjeringer',
    citizensLabel: 'Borgere',
    euInstitutionsLabel: 'EU-institusjoner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandet',
};
//# sourceMappingURL=no.js.map