// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
import { BRK_WHY_ANOMALIES, BRK_WHY_NORMAL, BRK_NEUTRAL_REASON, BRK_LEGAL_CONSEQUENCE, BRK_PROC_CONSEQUENCE, BRK_IMPACT_ECONOMIC, BRK_IMPACT_SOCIAL, BRK_IMPACT_GEO_COALITION, BRK_IMPACT_GEO_NORMAL, BRK_MISTAKE_DESC, BRK_MISTAKE_ALT, } from './_shared.js';
export const BREAKING_NEWS_TITLES = {
    en: (date) => ({
        title: `Breaking: Significant Parliamentary Developments — ${date}`,
        subtitle: 'Intelligence analysis of voting anomalies, coalition shifts, and key MEP activities',
    }),
    sv: (date) => ({
        title: `Senaste Nytt: Betydande Parlamentariska Händelser — ${date}`,
        subtitle: 'Underrättelseanalys av röstningsanomalier, koalitionsförändringar och viktig MEP-aktivitet',
    }),
    da: (date) => ({
        title: `Seneste Nyt: Betydelige Parlamentariske Udviklinger — ${date}`,
        subtitle: 'Efterretningsanalyse af afstemningsanomalier, koalitionsforskydninger og centrale MEP-aktiviteter',
    }),
    no: (date) => ({
        title: `Siste Nytt: Betydelige Parlamentariske Hendelser — ${date}`,
        subtitle: 'Etterretningsanalyse av avstemningsavvik, koalisjonsendringer og viktige MEP-aktiviteter',
    }),
    fi: (date) => ({
        title: `Uusimmat Uutiset: Merkittäviä Parlamentaarisia Kehityksiä — ${date}`,
        subtitle: 'Tiedusteluanalyysi äänestyspoikkeamista, koalitiomuutoksista ja keskeisistä MEP-toimista',
    }),
    de: (date) => ({
        title: `Eilmeldung: Bedeutende Parlamentarische Entwicklungen — ${date}`,
        subtitle: 'Analyse von Abstimmungsanomalien, Koalitionsverschiebungen und wichtigen MEP-Aktivitäten',
    }),
    fr: (date) => ({
        title: `Dernières Nouvelles: Développements Parlementaires Significatifs — ${date}`,
        subtitle: 'Analyse des anomalies de vote, des évolutions des coalitions et des activités clés des eurodéputés',
    }),
    es: (date) => ({
        title: `Última Hora: Desarrollos Parlamentarios Significativos — ${date}`,
        subtitle: 'Análisis de anomalías en votaciones, cambios en coaliciones y actividades clave de eurodiputados',
    }),
    nl: (date) => ({
        title: `Laatste Nieuws: Significante Parlementaire Ontwikkelingen — ${date}`,
        subtitle: 'Analyse van stemanomalieën, coalitieverschuivingen en belangrijke MEP-activiteiten',
    }),
    ar: (date) => ({
        title: `عاجل: تطورات برلمانية هامة — ${date}`,
        subtitle: 'تحليل استخباراتي لشذوذ التصويت وتحولات التحالفات وأنشطة النواب الرئيسية',
    }),
    he: (date) => ({
        title: `חדשות דחופות: התפתחויות פרלמנטריות משמעותיות — ${date}`,
        subtitle: 'ניתוח מודיעיני של חריגות הצבעה, שינויי קואליציה ופעילויות חברי פרלמנט מרכזיות',
    }),
    ja: (date) => ({
        title: `速報: 重要な議会の動き — ${date}`,
        subtitle: '投票異常、連立変動、主要MEP活動の分析',
    }),
    ko: (date) => ({
        title: `속보: 중요한 의회 동향 — ${date}`,
        subtitle: '투표 이상, 연합 변화 및 주요 MEP 활동 분석',
    }),
    zh: (date) => ({
        title: `突发: 重大议会进展 — ${date}`,
        subtitle: '投票异常、联盟变化和关键MEP活动的情报分析',
    }),
};
/** Committee reports titles per language */
export const BREAKING_STRINGS = {
    en: {
        breakingBanner: '⚡ BREAKING',
        votingAnomalyIntel: 'Voting Anomaly Intelligence',
        coalitionDynamics: 'Coalition Dynamics Assessment',
        analyticalReport: 'Analytical Report',
        keyMEPInfluence: 'Key MEP Influence Analysis',
        intelligenceBriefing: 'Intelligence Briefing',
        votingAnomalyAlert: 'Voting Anomaly Alert',
        coalitionDynamicsSection: 'Coalition Dynamics',
        keyPlayers: 'Key Parliamentary Players',
        placeholderNotice: 'This is placeholder content generated while the European Parliament MCP Server is unavailable. Live intelligence data will appear here when the server is connected.',
        placeholderLede: 'Significant parliamentary developments are being monitored. Connect the European Parliament MCP Server to receive real-time intelligence on voting anomalies, coalition shifts, and MEP activities.',
        lede: 'Intelligence analysis from the European Parliament MCP Server has identified significant parliamentary developments requiring immediate attention',
        feedLede: 'The latest European Parliament feed data highlights recent parliamentary activity',
        adoptedTextsHeading: 'Recently Adopted Texts',
        recentEventsHeading: 'Recent Parliamentary Events',
        procedureUpdatesHeading: 'Legislative Procedure Updates',
        mepUpdatesHeading: 'MEP Updates',
        noFeedDataNotice: 'No recent feed data available from the European Parliament.',
        asOf: 'as of',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Breaking developments on ${date}: ${adopted} newly adopted texts, ${events} events, ${procedures} procedure updates, ${meps} MEP changes.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Legislative Majority',
        breakingWinnerReasonFn: (count) => `${count} legislative texts have been advanced through the parliamentary process.`,
        breakingNeutralActor: 'Opposition Groups',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Political Group Whips',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Adopted:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: 'Detailed voting anomaly analysis is currently unavailable due to technical limitations in the source data.',
        coalitionUnavailable: 'Detailed coalition dynamics assessment cannot be displayed at this time as the necessary underlying data is temporarily unavailable.',
        adoptedTextTypeLabel: 'Adopted text',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Showing ${shown} of ${total}`,
    },
    sv: {
        breakingBanner: '⚡ SENASTE NYTT',
        votingAnomalyIntel: 'Röstningsanomalier — Underrättelseanalys',
        coalitionDynamics: 'Bedömning av Koalitionsdynamik',
        analyticalReport: 'Analytisk Rapport',
        keyMEPInfluence: 'Analys av Viktiga MEP-Inflytanden',
        intelligenceBriefing: 'Underrättelserapport',
        votingAnomalyAlert: 'Varning för Röstningsanomalier',
        coalitionDynamicsSection: 'Koalitionsdynamik',
        keyPlayers: 'Parlamentariska Nyckelaktörer',
        placeholderNotice: 'Detta är platshållarinnehåll genererat medan EU-parlamentets MCP-server är otillgänglig.',
        placeholderLede: 'Betydande parlamentariska händelser övervakas. Anslut EU-parlamentets MCP-server för att ta emot realtidsinformation.',
        lede: 'Underrättelseanalys från EU-parlamentets MCP-server har identifierat betydande parlamentariska händelser som kräver omedelbar uppmärksamhet',
        feedLede: 'De senaste flödena från Europaparlamentet belyser aktuell parlamentarisk verksamhet',
        adoptedTextsHeading: 'Nyligen Antagna Texter',
        recentEventsHeading: 'Senaste Parlamentariska Händelser',
        procedureUpdatesHeading: 'Uppdateringar av Lagstiftningsförfaranden',
        mepUpdatesHeading: 'Uppdateringar om Ledamöter',
        noFeedDataNotice: 'Inga nya flödesdata tillgängliga från Europaparlamentet.',
        asOf: 'per',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Senaste händelserna ${date}: ${adopted} nyligen antagna texter, ${events} händelser, ${procedures} proceduruppdateringar, ${meps} MEP-ändringar.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Lagstiftande majoritet',
        breakingWinnerReasonFn: (count) => `${count} lagstiftningstexter har drivits fram i den parlamentariska processen.`,
        breakingNeutralActor: 'Oppositionsgrupper',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Partigruppernas piskare',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Antagen:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: 'Detaljerad analys av möjliga röstningsavvikelser är för närvarande inte tillgänglig på grund av tekniska begränsningar i källdatan.',
        coalitionUnavailable: 'Fördjupad bedömning av koalitionsdynamik kan inte visas just nu eftersom nödvändiga underlagsdata tillfälligt saknas.',
        adoptedTextTypeLabel: 'Antagen text',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Visar ${shown} av ${total}`,
    },
    da: {
        breakingBanner: '⚡ SENESTE NYT',
        votingAnomalyIntel: 'Afstemningsanomali — Efterretningsanalyse',
        coalitionDynamics: 'Vurdering af Koalitionsdynamik',
        analyticalReport: 'Analytisk Rapport',
        keyMEPInfluence: 'Analyse af Vigtige MEP-Indflydelse',
        intelligenceBriefing: 'Efterretningsbriefing',
        votingAnomalyAlert: 'Advarsel om Afstemningsanomalier',
        coalitionDynamicsSection: 'Koalitionsdynamik',
        keyPlayers: 'Parlamentariske Nøgleaktører',
        placeholderNotice: 'Dette er pladsholderindhold genereret mens Europa-Parlamentets MCP-server er utilgængelig.',
        placeholderLede: 'Betydelige parlamentariske udviklinger overvåges. Tilslut Europa-Parlamentets MCP-server for at modtage realtidsintelligens.',
        lede: 'Efterretningsanalyse fra Europa-Parlamentets MCP-server har identificeret betydelige parlamentariske udviklinger der kræver øjeblikkelig opmærksomhed',
        feedLede: 'De seneste feeds fra Europa-Parlamentet fremhæver aktuel parlamentarisk aktivitet',
        adoptedTextsHeading: 'Nyligt Vedtagne Tekster',
        recentEventsHeading: 'Seneste Parlamentariske Begivenheder',
        procedureUpdatesHeading: 'Opdateringer af Lovgivningsprocedurer',
        mepUpdatesHeading: 'MEP-Opdateringer',
        noFeedDataNotice: 'Ingen nye feeddata tilgængelige fra Europa-Parlamentet.',
        asOf: 'pr.',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Seneste begivenheder den ${date}: ${adopted} nyvedtagne tekster, ${events} begivenheder, ${procedures} procedureopdateringer, ${meps} MEP-ændringer.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Lovgivningsmæssigt flertal',
        breakingWinnerReasonFn: (count) => `${count} lovgivningstekster er ført frem i den parlamentariske proces.`,
        breakingNeutralActor: 'Oppositionsgrupper',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Partigruppernes piskere',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Vedtaget:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: 'Detaljeret analyse af afstemningsanomalier er i øjeblikket ikke tilgængelig på grund af tekniske begrænsninger i kildedata.',
        coalitionUnavailable: 'Detaljeret vurdering af koalitionsdynamik kan ikke vises i øjeblikket, da de nødvendige underliggende data midlertidigt mangler.',
        adoptedTextTypeLabel: 'Vedtaget tekst',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Viser ${shown} af ${total}`,
    },
    no: {
        breakingBanner: '⚡ SISTE NYTT',
        votingAnomalyIntel: 'Avstemningsavvik — Etterretningsanalyse',
        coalitionDynamics: 'Vurdering av Koalisjonsdynamikk',
        analyticalReport: 'Analytisk Rapportering',
        keyMEPInfluence: 'Analyse av Viktige MEP-Innflytelse',
        intelligenceBriefing: 'Etterretningsbriefing',
        votingAnomalyAlert: 'Advarsel om Avstemningsavvik',
        coalitionDynamicsSection: 'Koalisjonsdynamikk',
        keyPlayers: 'Parlamentariske Nøkkelaktører',
        placeholderNotice: 'Dette er plassholder-innhold generert mens Europaparlamentets MCP-server er utilgjengelig.',
        placeholderLede: 'Betydelige parlamentariske hendelser overvåkes. Koble til Europaparlamentets MCP-server for å motta sanntidsinformasjon.',
        lede: 'Etterretningsanalyse fra Europaparlamentets MCP-server har identifisert betydelige parlamentariske hendelser som krever umiddelbar oppmerksomhet',
        feedLede: 'De siste feedene fra Europaparlamentet belyser nylig parlamentarisk aktivitet',
        adoptedTextsHeading: 'Nylig Vedtatte Tekster',
        recentEventsHeading: 'Siste Parlamentariske Hendelser',
        procedureUpdatesHeading: 'Oppdateringer av Lovgivningsprosedyrer',
        mepUpdatesHeading: 'MEP-Oppdateringer',
        noFeedDataNotice: 'Ingen nye feeddata tilgjengelige fra Europaparlamentet.',
        asOf: 'per',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Siste hendelser ${date}: ${adopted} nylig vedtatte tekster, ${events} hendelser, ${procedures} prosedyreoppdateringer, ${meps} MEP-endringer.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Lovgivningsmessig flertall',
        breakingWinnerReasonFn: (count) => `${count} lovgivningstekster er fremmet i den parlamentariske prosessen.`,
        breakingNeutralActor: 'Opposisjonsgrupper',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Partigruppers innpisker',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Vedtatt:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: 'Detaljert analyse av mulige avstemningsavvik er for øyeblikket ikke tilgjengelig på grunn av tekniske begrensninger i kildedataene.',
        coalitionUnavailable: 'Detaljert vurdering av koalisjonsdynamikk kan ikke vises for øyeblikket siden de nødvendige underliggende dataene midlertidig mangler.',
        adoptedTextTypeLabel: 'Vedtatt tekst',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Viser ${shown} av ${total}`,
    },
    fi: {
        breakingBanner: '⚡ TUOREET UUTISET',
        votingAnomalyIntel: 'Äänestyspoikkeamat — Tiedusteluanalyysi',
        coalitionDynamics: 'Koalitiodynamiikan Arviointi',
        analyticalReport: 'Analyyttinen Raportti',
        keyMEPInfluence: 'Avain-MEP-vaikutusanalyysi',
        intelligenceBriefing: 'Tiedusteluraportti',
        votingAnomalyAlert: 'Äänestyspoikkeamavaroitus',
        coalitionDynamicsSection: 'Koalitiodynamiikka',
        keyPlayers: 'Parlamentaariset Avainpelaajat',
        placeholderNotice: 'Tämä on paikkamerkkisisältö, joka on luotu EU-parlamentin MCP-palvelimen ollessa pois käytöstä.',
        placeholderLede: 'Merkittäviä parlamentaarisia tapahtumia seurataan. Yhdistä EU-parlamentin MCP-palvelimeen reaaliaikaisen tiedon vastaanottamiseksi.',
        lede: 'EU-parlamentin MCP-palvelimen tiedusteluanalyysi on tunnistanut merkittäviä parlamentaarisia tapahtumia, jotka vaativat välitöntä huomiota',
        feedLede: 'Euroopan parlamentin uusimmat syötetiedot korostavat viimeaikaista parlamentaarista toimintaa',
        adoptedTextsHeading: 'Äskettäin Hyväksytyt Tekstit',
        recentEventsHeading: 'Viimeisimmät Parlamentaariset Tapahtumat',
        procedureUpdatesHeading: 'Lainsäädäntömenettelyjen Päivitykset',
        mepUpdatesHeading: 'MEP-Päivitykset',
        noFeedDataNotice: 'Ei uusia syötetietoja saatavilla Euroopan parlamentista.',
        asOf: 'tilanne',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Uusimmat tapahtumat ${date}: ${adopted} äskettäin hyväksyttyä tekstiä, ${events} tapahtumaa, ${procedures} menettelypäivitystä, ${meps} MEP-muutosta.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Lainsäädännöllinen enemmistö',
        breakingWinnerReasonFn: (count) => `${count} lainsäädäntötekstiä on edistetty parlamentaarisessa prosessissa.`,
        breakingNeutralActor: 'Oppositioryhmät',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Ryhmien parlamenttipiiskurit',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Hyväksytty:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: 'Äänestyspoikkeamien yksityiskohtainen analyysi ei ole tällä hetkellä saatavilla lähdetietojen teknisten rajoitusten vuoksi.',
        coalitionUnavailable: 'Koalitiodynamiikan yksityiskohtaista arviointia ei voida näyttää tällä hetkellä, koska tarvittavat taustatiedot ovat tilapäisesti poissa.',
        adoptedTextTypeLabel: 'Hyväksytty teksti',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Näytetään ${shown} / ${total}`,
    },
    de: {
        breakingBanner: '⚡ EILMELDUNG',
        votingAnomalyIntel: 'Abstimmungsanomalien — Nachrichtendienstanalyse',
        coalitionDynamics: 'Bewertung der Koalitionsdynamik',
        analyticalReport: 'Analytischer Bericht',
        keyMEPInfluence: 'Analyse des Einflusses wichtiger MdEPs',
        intelligenceBriefing: 'Nachrichtendienstbriefing',
        votingAnomalyAlert: 'Warnung vor Abstimmungsanomalien',
        coalitionDynamicsSection: 'Koalitionsdynamik',
        keyPlayers: 'Parlamentarische Schlüsselfiguren',
        placeholderNotice: 'Dies ist Platzhalterinhalt, der generiert wurde, während der MCP-Server des EU-Parlaments nicht verfügbar ist.',
        placeholderLede: 'Bedeutende parlamentarische Entwicklungen werden überwacht. Verbinden Sie den MCP-Server des EU-Parlaments für Echtzeit-Informationen.',
        lede: 'Die Nachrichtendienstanalyse des MCP-Servers des EU-Parlaments hat bedeutende parlamentarische Entwicklungen identifiziert, die sofortige Aufmerksamkeit erfordern',
        feedLede: 'Die neuesten Feeds des Europäischen Parlaments beleuchten aktuelle parlamentarische Aktivitäten',
        adoptedTextsHeading: 'Kürzlich Angenommene Texte',
        recentEventsHeading: 'Aktuelle Parlamentarische Ereignisse',
        procedureUpdatesHeading: 'Aktualisierungen der Gesetzgebungsverfahren',
        mepUpdatesHeading: 'MdEP-Aktualisierungen',
        noFeedDataNotice: 'Keine neuen Feeddaten vom Europäischen Parlament verfügbar.',
        asOf: 'zum',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Neueste Entwicklungen am ${date}: ${adopted} neu angenommene Texte, ${events} Ereignisse, ${procedures} Verfahrensupdates, ${meps} MdEP-Änderungen.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Gesetzgebende Mehrheit',
        breakingWinnerReasonFn: (count) => `${count} Gesetzestexte wurden im parlamentarischen Verfahren vorangebracht.`,
        breakingNeutralActor: 'Oppositionsgruppen',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Fraktionsgeschäftsführer',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Angenommen:',
        breakingMEPPrefix: 'MdEP:',
        anomalyUnavailable: 'Detaillierte Analyse von Abstimmungsanomalien ist aufgrund technischer Einschränkungen der Quelldaten derzeit nicht verfügbar.',
        coalitionUnavailable: 'Eine detaillierte Bewertung der Koalitionsdynamik kann derzeit nicht angezeigt werden, da die erforderlichen Grundlagendaten vorübergehend fehlen.',
        adoptedTextTypeLabel: 'Angenommener Text',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `${shown} von ${total} angezeigt`,
    },
    fr: {
        breakingBanner: '⚡ DERNIÈRES NOUVELLES',
        votingAnomalyIntel: 'Anomalies de Vote — Analyse de Renseignement',
        coalitionDynamics: 'Évaluation des Dynamiques de Coalition',
        analyticalReport: 'Rapport Analytique',
        keyMEPInfluence: "Analyse de l'Influence des Eurodéputés Clés",
        intelligenceBriefing: 'Briefing de Renseignement',
        votingAnomalyAlert: 'Alerte Anomalie de Vote',
        coalitionDynamicsSection: 'Dynamiques de Coalition',
        keyPlayers: 'Acteurs Parlementaires Clés',
        placeholderNotice: 'Ceci est un contenu indicatif généré pendant que le serveur MCP du Parlement européen est indisponible.',
        placeholderLede: 'Des développements parlementaires importants sont surveillés. Connectez le serveur MCP du Parlement européen pour recevoir des renseignements en temps réel.',
        lede: "L'analyse de renseignement du serveur MCP du Parlement européen a identifié des développements parlementaires significatifs nécessitant une attention immédiate",
        feedLede: 'Les dernières données du Parlement européen mettent en lumière les activités parlementaires récentes',
        adoptedTextsHeading: 'Textes Récemment Adoptés',
        recentEventsHeading: 'Événements Parlementaires Récents',
        procedureUpdatesHeading: 'Mises à Jour des Procédures Législatives',
        mepUpdatesHeading: 'Mises à Jour des Eurodéputés',
        noFeedDataNotice: 'Aucune donnée de flux récente disponible du Parlement européen.',
        asOf: 'au',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Dernières évolutions au ${date}\u00a0: ${adopted} textes nouvellement adoptés, ${events} événements, ${procedures} mises à jour procédurales, ${meps} changements de députés.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Majorité législative',
        breakingWinnerReasonFn: (count) => `${count} textes législatifs ont été avancés dans le cadre du processus parlementaire.`,
        breakingNeutralActor: "Groupes d'opposition",
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Chefs de file des groupes politiques',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Adopté\u00a0:',
        breakingMEPPrefix: 'Député\u00a0:',
        anomalyUnavailable: "L'analyse détaillée des anomalies de vote n'est pas disponible pour le moment en raison de limitations techniques des données sources.",
        coalitionUnavailable: "L'évaluation détaillée de la dynamique de coalition ne peut pas être affichée pour le moment, car les données sous-jacentes nécessaires sont temporairement indisponibles.",
        adoptedTextTypeLabel: 'Texte adopté',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Affichage de ${shown} sur ${total}`,
    },
    es: {
        breakingBanner: '⚡ ÚLTIMA HORA',
        votingAnomalyIntel: 'Anomalías de Votación — Análisis de Inteligencia',
        coalitionDynamics: 'Evaluación de Dinámicas de Coalición',
        analyticalReport: 'Informe Analítico',
        keyMEPInfluence: 'Análisis de Influencia de Eurodiputados Clave',
        intelligenceBriefing: 'Informe de Inteligencia',
        votingAnomalyAlert: 'Alerta de Anomalía de Votación',
        coalitionDynamicsSection: 'Dinámicas de Coalición',
        keyPlayers: 'Actores Parlamentarios Clave',
        placeholderNotice: 'Este es contenido de marcador de posición generado mientras el servidor MCP del Parlamento Europeo no está disponible.',
        placeholderLede: 'Se están monitoreando desarrollos parlamentarios significativos. Conecte el servidor MCP del Parlamento Europeo para recibir inteligencia en tiempo real.',
        lede: 'El análisis de inteligencia del servidor MCP del Parlamento Europeo ha identificado desarrollos parlamentarios significativos que requieren atención inmediata',
        feedLede: 'Los últimos datos del Parlamento Europeo destacan la actividad parlamentaria reciente',
        adoptedTextsHeading: 'Textos Recientemente Adoptados',
        recentEventsHeading: 'Eventos Parlamentarios Recientes',
        procedureUpdatesHeading: 'Actualizaciones de Procedimientos Legislativos',
        mepUpdatesHeading: 'Actualizaciones de Eurodiputados',
        noFeedDataNotice: 'No hay datos de feeds recientes disponibles del Parlamento Europeo.',
        asOf: 'a',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Últimas novedades el ${date}: ${adopted} textos recién adoptados, ${events} eventos, ${procedures} actualizaciones de procedimientos, ${meps} cambios de eurodiputados.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Mayoría legislativa',
        breakingWinnerReasonFn: (count) => `${count} textos legislativos han sido avanzados en el proceso parlamentario.`,
        breakingNeutralActor: 'Grupos de oposición',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Jefes de delegación de grupos políticos',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Adoptado:',
        breakingMEPPrefix: 'Eurodiputado:',
        anomalyUnavailable: 'El análisis detallado de anomalías de votación no está disponible actualmente debido a limitaciones técnicas en los datos fuente.',
        coalitionUnavailable: 'La evaluación detallada de la dinámica de coalición no se puede mostrar en este momento, ya que los datos subyacentes necesarios no están disponibles temporalmente.',
        adoptedTextTypeLabel: 'Texto aprobado',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `Mostrando ${shown} de ${total}`,
    },
    nl: {
        breakingBanner: '⚡ LAATSTE NIEUWS',
        votingAnomalyIntel: 'Stemanomalieën — Inlichtingenanalyse',
        coalitionDynamics: 'Beoordeling van Coalitiedynamiek',
        analyticalReport: 'Analytisch Rapport',
        keyMEPInfluence: 'Analyse van Invloed Belangrijke Europarlementsleden',
        intelligenceBriefing: 'Inlichtingenbriefing',
        votingAnomalyAlert: 'Waarschuwing Stemanomalieën',
        coalitionDynamicsSection: 'Coalitiedynamiek',
        keyPlayers: 'Parlementaire Sleutelfiguren',
        placeholderNotice: 'Dit is tijdelijke inhoud gegenereerd terwijl de MCP-server van het Europees Parlement niet beschikbaar is.',
        placeholderLede: 'Significante parlementaire ontwikkelingen worden gemonitord. Verbind de MCP-server van het Europees Parlement voor realtime-informatie.',
        lede: 'Inlichtingenanalyse van de MCP-server van het Europees Parlement heeft significante parlementaire ontwikkelingen geïdentificeerd die onmiddellijke aandacht vereisen',
        feedLede: 'De nieuwste gegevens van het Europees Parlement belichten recente parlementaire activiteiten',
        adoptedTextsHeading: 'Recent Aangenomen Teksten',
        recentEventsHeading: 'Recente Parlementaire Evenementen',
        procedureUpdatesHeading: 'Updates van Wetgevingsprocedures',
        mepUpdatesHeading: 'Updates van Europarlementsleden',
        noFeedDataNotice: 'Geen recente feedgegevens beschikbaar van het Europees Parlement.',
        asOf: 'per',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `Laatste ontwikkelingen op ${date}: ${adopted} nieuw aangenomen teksten, ${events} evenementen, ${procedures} procedurebijwerkingen, ${meps} MEP-wijzigingen.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'Wetgevende meerderheid',
        breakingWinnerReasonFn: (count) => `${count} wetgevingsteksten zijn gevorderd in het parlementaire proces.`,
        breakingNeutralActor: 'Oppositiegroepen',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'Fractiedisciplineurs',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'Aangenomen:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: 'Gedetailleerde analyse van stemanomalieën is momenteel niet beschikbaar vanwege technische beperkingen in de brondata.',
        coalitionUnavailable: 'Gedetailleerde beoordeling van coalitiedynamiek kan momenteel niet worden weergegeven, omdat de benodigde onderliggende gegevens tijdelijk niet beschikbaar zijn.',
        adoptedTextTypeLabel: 'Aangenomen tekst',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `${shown} van ${total} weergegeven`,
    },
    ar: {
        breakingBanner: '⚡ عاجل',
        votingAnomalyIntel: 'شذوذ التصويت — تحليل استخباراتي',
        coalitionDynamics: 'تقييم ديناميات التحالف',
        analyticalReport: 'تقرير تحليلي',
        keyMEPInfluence: 'تحليل تأثير النواب الرئيسيين',
        intelligenceBriefing: 'ملخص استخباراتي',
        votingAnomalyAlert: 'تنبيه شذوذ التصويت',
        coalitionDynamicsSection: 'ديناميات التحالف',
        keyPlayers: 'اللاعبون البرلمانيون الرئيسيون',
        placeholderNotice: 'هذا محتوى مؤقت تم إنشاؤه أثناء عدم توفر خادم MCP للبرلمان الأوروبي.',
        placeholderLede: 'تتم مراقبة تطورات برلمانية مهمة. قم بتوصيل خادم MCP للبرلمان الأوروبي لتلقي معلومات استخبارية في الوقت الفعلي.',
        lede: 'حدد التحليل الاستخباراتي لخادم MCP للبرلمان الأوروبي تطورات برلمانية مهمة تتطلب اهتماماً فورياً',
        feedLede: 'تسلط أحدث بيانات البرلمان الأوروبي الضوء على النشاط البرلماني الأخير',
        adoptedTextsHeading: 'النصوص المعتمدة مؤخراً',
        recentEventsHeading: 'أحداث برلمانية حديثة',
        procedureUpdatesHeading: 'تحديثات الإجراءات التشريعية',
        mepUpdatesHeading: 'تحديثات أعضاء البرلمان',
        noFeedDataNotice: 'لا تتوفر بيانات تغذية حديثة من البرلمان الأوروبي.',
        asOf: 'اعتباراً من',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `آخر التطورات في ${date}: ${adopted} نصًا معتمدًا حديثًا، ${events} أحداث، ${procedures} تحديثات إجراءات، ${meps} تغييرات في أعضاء البرلمان.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'الأغلبية التشريعية',
        breakingWinnerReasonFn: (count) => `تم تقديم ${count} نصًا تشريعيًا في العملية البرلمانية.`,
        breakingNeutralActor: 'مجموعات المعارضة',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'مسؤولو الانضباط الحزبي',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'معتمد:',
        breakingMEPPrefix: 'عضو البرلمان:',
        anomalyUnavailable: 'تحليل شذوذات التصويت التفصيلي غير متاح حاليًا بسبب قيود تقنية في بيانات المصدر.',
        coalitionUnavailable: 'لا يمكن عرض التقييم التفصيلي لديناميات الائتلاف في الوقت الحالي نظرًا لعدم توفر البيانات الأساسية اللازمة مؤقتًا.',
        adoptedTextTypeLabel: 'نص معتمد',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `عرض ${shown} من ${total}`,
    },
    he: {
        breakingBanner: '⚡ חדשות דחופות',
        votingAnomalyIntel: 'חריגות הצבעה — ניתוח מודיעיני',
        coalitionDynamics: 'הערכת דינמיקת קואליציה',
        analyticalReport: 'דוח אנליטי',
        keyMEPInfluence: 'ניתוח השפעת חברי פרלמנט מרכזיים',
        intelligenceBriefing: 'תדרוך מודיעיני',
        votingAnomalyAlert: 'התראת חריגות הצבעה',
        coalitionDynamicsSection: 'דינמיקת קואליציה',
        keyPlayers: 'שחקני מפתח פרלמנטריים',
        placeholderNotice: 'זהו תוכן מציין מיקום שנוצר בזמן ששרת MCP של הפרלמנט האירופי אינו זמין.',
        placeholderLede: 'מתבצע ניטור של התפתחויות פרלמנטריות משמעותיות. חבר את שרת MCP של הפרלמנט האירופי לקבלת מודיעין בזמן אמת.',
        lede: 'ניתוח מודיעיני משרת MCP של הפרלמנט האירופי זיהה התפתחויות פרלמנטריות משמעותיות הדורשות תשומת לב מיידית',
        feedLede: 'נתוני ההזנה האחרונים של הפרלמנט האירופי מדגישים פעילות פרלמנטרית עדכנית',
        adoptedTextsHeading: 'טקסטים שאומצו לאחרונה',
        recentEventsHeading: 'אירועים פרלמנטריים אחרונים',
        procedureUpdatesHeading: 'עדכוני הליכי חקיקה',
        mepUpdatesHeading: 'עדכוני חברי פרלמנט',
        noFeedDataNotice: 'אין נתוני הזנה עדכניים זמינים מהפרלמנט האירופי.',
        asOf: 'נכון ל-',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `ההתפתחויות האחרונות ב-${date}: ${adopted} טקסטים שאומצו לאחרונה, ${events} אירועים, ${procedures} עדכוני הליכים, ${meps} שינויים בחברי פרלמנט.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: 'הרוב החקיקתי',
        breakingWinnerReasonFn: (count) => `${count} טקסטים חקיקתיים קודמו בתהליך הפרלמנטרי.`,
        breakingNeutralActor: 'קבוצות האופוזיציה',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: 'מנהיגי הסיעות',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: 'אומץ:',
        breakingMEPPrefix: 'חבר פרלמנט:',
        anomalyUnavailable: 'ניתוח מפורט של חריגות הצבעה אינו זמין כעת עקב מגבלות טכניות בנתוני המקור.',
        coalitionUnavailable: 'הערכה מפורטת של דינמיקת הקואליציה אינה יכולה להיות מוצגת כעת, מכיוון שנתוני הבסיס הנחוצים אינם זמינים זמנית.',
        adoptedTextTypeLabel: 'טקסט שאומץ',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `מציג ${shown} מתוך ${total}`,
    },
    ja: {
        breakingBanner: '⚡ 速報',
        votingAnomalyIntel: '投票異常 — 情報分析',
        coalitionDynamics: '連立動態評価',
        analyticalReport: '分析レポート',
        keyMEPInfluence: '主要MEP影響力分析',
        intelligenceBriefing: 'インテリジェンスブリーフィング',
        votingAnomalyAlert: '投票異常警報',
        coalitionDynamicsSection: '連立動態',
        keyPlayers: '議会の主要人物',
        placeholderNotice: 'これは欧州議会MCPサーバーが利用できない間に生成されたプレースホルダーコンテンツです。',
        placeholderLede: '重大な議会の動きを監視しています。リアルタイムの情報を受信するには、欧州議会MCPサーバーに接続してください。',
        lede: '欧州議会MCPサーバーの情報分析により、即座の注意を要する重大な議会の動きが特定されました',
        feedLede: '欧州議会の最新フィードデータが最近の議会活動を紹介しています',
        adoptedTextsHeading: '最近採択されたテキスト',
        recentEventsHeading: '最近の議会イベント',
        procedureUpdatesHeading: '立法手続きの更新',
        mepUpdatesHeading: 'MEPの更新',
        noFeedDataNotice: '欧州議会からの最新フィードデータはありません。',
        asOf: '現在',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `${date}の最新動向：新たに採択されたテキスト${adopted}件、イベント${events}件、手続き更新${procedures}件、MEP変更${meps}件。`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: '立法多数派',
        breakingWinnerReasonFn: (count) => `${count}件の立法テキストが議会プロセスで進められました。`,
        breakingNeutralActor: '野党グループ',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: '会派院内幹事',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: '採択：',
        breakingMEPPrefix: 'MEP：',
        anomalyUnavailable: '投票異常の詳細分析は、ソースデータの技術的な制限により現在利用できません。',
        coalitionUnavailable: '連立力学の詳細な評価は、必要な基礎データが一時的に利用できないため、現時点では表示できません。',
        adoptedTextTypeLabel: '採択テキスト',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `${total}件中${shown}件を表示`,
    },
    ko: {
        breakingBanner: '⚡ 속보',
        votingAnomalyIntel: '투표 이상 — 정보 분석',
        coalitionDynamics: '연합 역학 평가',
        analyticalReport: '분석 보고서',
        keyMEPInfluence: '주요 MEP 영향력 분석',
        intelligenceBriefing: '정보 브리핑',
        votingAnomalyAlert: '투표 이상 경보',
        coalitionDynamicsSection: '연합 역학',
        keyPlayers: '의회 핵심 인물',
        placeholderNotice: '유럽 의회 MCP 서버를 사용할 수 없는 동안 생성된 자리 표시자 콘텐츠입니다.',
        placeholderLede: '중요한 의회 동향이 모니터링되고 있습니다. 실시간 정보를 수신하려면 유럽 의회 MCP 서버에 연결하세요.',
        lede: '유럽 의회 MCP 서버의 정보 분석에서 즉각적인 주의가 필요한 중요한 의회 동향이 확인되었습니다',
        feedLede: '유럽 의회의 최신 피드 데이터가 최근 의회 활동을 조명합니다',
        adoptedTextsHeading: '최근 채택된 텍스트',
        recentEventsHeading: '최근 의회 이벤트',
        procedureUpdatesHeading: '입법 절차 업데이트',
        mepUpdatesHeading: 'MEP 업데이트',
        noFeedDataNotice: '유럽 의회의 최신 피드 데이터가 없습니다.',
        asOf: '기준',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `${date} 최신 동향: 새로 채택된 텍스트 ${adopted}건, 이벤트 ${events}건, 절차 업데이트 ${procedures}건, MEP 변경 ${meps}건.`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: '입법 다수파',
        breakingWinnerReasonFn: (count) => `${count}건의 입법 텍스트가 의회 절차를 통해 진행되었습니다.`,
        breakingNeutralActor: '야당 그룹',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: '정치 그룹 원내총무',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: '채택:',
        breakingMEPPrefix: 'MEP:',
        anomalyUnavailable: '투표 이상의 상세 분석은 소스 데이터의 기술적 제한으로 현재 이용할 수 없습니다.',
        coalitionUnavailable: '연합 역학의 상세 평가는 필요한 기본 데이터가 일시적으로 이용 불가능하여 현재 표시할 수 없습니다.',
        adoptedTextTypeLabel: '채택 문서',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `총 ${total}개 중 ${shown}개 표시`,
    },
    zh: {
        breakingBanner: '⚡ 突发',
        votingAnomalyIntel: '投票异常 — 情报分析',
        coalitionDynamics: '联盟动态评估',
        analyticalReport: '分析报告',
        keyMEPInfluence: '关键MEP影响力分析',
        intelligenceBriefing: '情报简报',
        votingAnomalyAlert: '投票异常警报',
        coalitionDynamicsSection: '联盟动态',
        keyPlayers: '议会关键人物',
        placeholderNotice: '这是在欧洲议会MCP服务器不可用时生成的占位符内容。',
        placeholderLede: '正在监控重大议会动态。请连接欧洲议会MCP服务器以接收实时情报。',
        lede: '欧洲议会MCP服务器的情报分析已确定需要立即关注的重大议会动态',
        feedLede: '欧洲议会的最新数据动态展示了近期议会活动',
        adoptedTextsHeading: '最近通过的文本',
        recentEventsHeading: '近期议会活动',
        procedureUpdatesHeading: '立法程序更新',
        mepUpdatesHeading: 'MEP更新',
        noFeedDataNotice: '没有来自欧洲议会的最新订阅数据。',
        asOf: '截至',
        breakingWhatFn: (date, adopted, events, procedures, meps) => `${date}最新动态：${adopted}项新通过文本，${events}项活动，${procedures}项程序更新，${meps}项议员变更。`,
        breakingWhyAnomalies: BRK_WHY_ANOMALIES,
        breakingWhyNormal: BRK_WHY_NORMAL,
        breakingWinnerActor: '立法多数派',
        breakingWinnerReasonFn: (count) => `${count}项立法文本已通过议会程序推进。`,
        breakingNeutralActor: '反对派团体',
        breakingNeutralReason: BRK_NEUTRAL_REASON,
        breakingOutlookActiveFn: (date) => `session_date=${date}`,
        breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
        breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
        breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
        breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
        breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
        breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
        breakingImpactSocial: BRK_IMPACT_SOCIAL,
        breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
        breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
        breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
        breakingMistakeActor: '政治团体党鞭',
        breakingMistakeDescription: BRK_MISTAKE_DESC,
        breakingMistakeAlternative: BRK_MISTAKE_ALT,
        breakingAdoptedPrefix: '通过：',
        breakingMEPPrefix: '议员：',
        anomalyUnavailable: '由于源数据存在技术限制，投票异常的详细分析目前不可用。',
        coalitionUnavailable: '目前无法显示联盟动态的详细评估，因为所需的基础数据暂时不可用。',
        adoptedTextTypeLabel: '通过文本',
        adoptedTextItemLabelFn: (label) => label,
        showingXofNFn: (shown, total) => `显示 ${shown} / ${total}`,
    },
};
/** Localized body-text strings for the committee-analysis deep-analysis section */
//# sourceMappingURL=breaking.js.map