// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** Shared Scandinavian/Dutch SWOT heading */
const SWOT_ANALYSE = 'SWOT-analyse';
export const SWOT_STRINGS = {
    en: {
        sectionHeading: 'SWOT Analysis',
        strengthsLabel: 'Strengths',
        weaknessesLabel: 'Weaknesses',
        opportunitiesLabel: 'Opportunities',
        threatsLabel: 'Threats',
        strengthsDesc: 'Internal positive factors',
        weaknessesDesc: 'Internal negative factors',
        opportunitiesDesc: 'External positive factors',
        threatsDesc: 'External negative factors',
        internalLabel: 'Internal',
        externalLabel: 'External',
    },
    sv: {
        sectionHeading: 'SWOT-analys',
        strengthsLabel: 'Styrkor',
        weaknessesLabel: 'Svagheter',
        opportunitiesLabel: 'Möjligheter',
        threatsLabel: 'Hot',
        strengthsDesc: 'Interna positiva faktorer',
        weaknessesDesc: 'Interna negativa faktorer',
        opportunitiesDesc: 'Externa positiva faktorer',
        threatsDesc: 'Externa negativa faktorer',
        internalLabel: 'Internt',
        externalLabel: 'Externt',
    },
    da: {
        sectionHeading: SWOT_ANALYSE,
        strengthsLabel: 'Styrker',
        weaknessesLabel: 'Svagheder',
        opportunitiesLabel: 'Muligheder',
        threatsLabel: 'Trusler',
        strengthsDesc: 'Interne positive faktorer',
        weaknessesDesc: 'Interne negative faktorer',
        opportunitiesDesc: 'Eksterne positive faktorer',
        threatsDesc: 'Eksterne negative faktorer',
        internalLabel: 'Internt',
        externalLabel: 'Eksternt',
    },
    no: {
        sectionHeading: SWOT_ANALYSE,
        strengthsLabel: 'Styrker',
        weaknessesLabel: 'Svakheter',
        opportunitiesLabel: 'Muligheter',
        threatsLabel: 'Trusler',
        strengthsDesc: 'Interne positive faktorer',
        weaknessesDesc: 'Interne negative faktorer',
        opportunitiesDesc: 'Eksterne positive faktorer',
        threatsDesc: 'Eksterne negative faktorer',
        internalLabel: 'Internt',
        externalLabel: 'Eksternt',
    },
    fi: {
        sectionHeading: 'SWOT-analyysi',
        strengthsLabel: 'Vahvuudet',
        weaknessesLabel: 'Heikkoudet',
        opportunitiesLabel: 'Mahdollisuudet',
        threatsLabel: 'Uhat',
        strengthsDesc: 'Sisäiset positiiviset tekijät',
        weaknessesDesc: 'Sisäiset negatiiviset tekijät',
        opportunitiesDesc: 'Ulkoiset positiiviset tekijät',
        threatsDesc: 'Ulkoiset negatiiviset tekijät',
        internalLabel: 'Sisäinen',
        externalLabel: 'Ulkoinen',
    },
    de: {
        sectionHeading: 'SWOT-Analyse',
        strengthsLabel: 'Stärken',
        weaknessesLabel: 'Schwächen',
        opportunitiesLabel: 'Chancen',
        threatsLabel: 'Risiken',
        strengthsDesc: 'Interne positive Faktoren',
        weaknessesDesc: 'Interne negative Faktoren',
        opportunitiesDesc: 'Externe positive Faktoren',
        threatsDesc: 'Externe negative Faktoren',
        internalLabel: 'Intern',
        externalLabel: 'Extern',
    },
    fr: {
        sectionHeading: 'Analyse SWOT',
        strengthsLabel: 'Forces',
        weaknessesLabel: 'Faiblesses',
        opportunitiesLabel: 'Opportunités',
        threatsLabel: 'Menaces',
        strengthsDesc: 'Facteurs positifs internes',
        weaknessesDesc: 'Facteurs négatifs internes',
        opportunitiesDesc: 'Facteurs positifs externes',
        threatsDesc: 'Facteurs négatifs externes',
        internalLabel: 'Interne',
        externalLabel: 'Externe',
    },
    es: {
        sectionHeading: 'Análisis DAFO',
        strengthsLabel: 'Fortalezas',
        weaknessesLabel: 'Debilidades',
        opportunitiesLabel: 'Oportunidades',
        threatsLabel: 'Amenazas',
        strengthsDesc: 'Factores positivos internos',
        weaknessesDesc: 'Factores negativos internos',
        opportunitiesDesc: 'Factores positivos externos',
        threatsDesc: 'Factores negativos externos',
        internalLabel: 'Interno',
        externalLabel: 'Externo',
    },
    nl: {
        sectionHeading: SWOT_ANALYSE,
        strengthsLabel: 'Sterktes',
        weaknessesLabel: 'Zwaktes',
        opportunitiesLabel: 'Kansen',
        threatsLabel: 'Bedreigingen',
        strengthsDesc: 'Interne positieve factoren',
        weaknessesDesc: 'Interne negatieve factoren',
        opportunitiesDesc: 'Externe positieve factoren',
        threatsDesc: 'Externe negatieve factoren',
        internalLabel: 'Intern',
        externalLabel: 'Extern',
    },
    ar: {
        sectionHeading: 'تحليل SWOT',
        strengthsLabel: 'نقاط القوة',
        weaknessesLabel: 'نقاط الضعف',
        opportunitiesLabel: 'الفرص',
        threatsLabel: 'التهديدات',
        strengthsDesc: 'العوامل الإيجابية الداخلية',
        weaknessesDesc: 'العوامل السلبية الداخلية',
        opportunitiesDesc: 'العوامل الإيجابية الخارجية',
        threatsDesc: 'العوامل السلبية الخارجية',
        internalLabel: 'داخلي',
        externalLabel: 'خارجي',
    },
    he: {
        sectionHeading: 'ניתוח SWOT',
        strengthsLabel: 'חוזקות',
        weaknessesLabel: 'חולשות',
        opportunitiesLabel: 'הזדמנויות',
        threatsLabel: 'איומים',
        strengthsDesc: 'גורמים פנימיים חיוביים',
        weaknessesDesc: 'גורמים פנימיים שליליים',
        opportunitiesDesc: 'גורמים חיצוניים חיוביים',
        threatsDesc: 'גורמים חיצוניים שליליים',
        internalLabel: 'פנימי',
        externalLabel: 'חיצוני',
    },
    ja: {
        sectionHeading: 'SWOT分析',
        strengthsLabel: '強み',
        weaknessesLabel: '弱み',
        opportunitiesLabel: '機会',
        threatsLabel: '脅威',
        strengthsDesc: '内部のプラス要因',
        weaknessesDesc: '内部のマイナス要因',
        opportunitiesDesc: '外部のプラス要因',
        threatsDesc: '外部のマイナス要因',
        internalLabel: '内部',
        externalLabel: '外部',
    },
    ko: {
        sectionHeading: 'SWOT 분석',
        strengthsLabel: '강점',
        weaknessesLabel: '약점',
        opportunitiesLabel: '기회',
        threatsLabel: '위협',
        strengthsDesc: '내부 긍정적 요인',
        weaknessesDesc: '내부 부정적 요인',
        opportunitiesDesc: '외부 긍정적 요인',
        threatsDesc: '외부 부정적 요인',
        internalLabel: '내부',
        externalLabel: '외부',
    },
    zh: {
        sectionHeading: 'SWOT分析',
        strengthsLabel: '优势',
        weaknessesLabel: '劣势',
        opportunitiesLabel: '机会',
        threatsLabel: '威胁',
        strengthsDesc: '内部积极因素',
        weaknessesDesc: '内部消极因素',
        opportunitiesDesc: '外部积极因素',
        threatsDesc: '外部消极因素',
        internalLabel: '内部',
        externalLabel: '外部',
    },
};
// ─── Dashboard localization strings ──────────────────────────────────────────
/**
 * Localized dashboard heading and chart-label strings indexed by ISO 639-1
 * language code. Consumed by the dashboard builder when rendering Chart.js
 * widgets in each of the 14 supported article languages.
 */
import { SWOT_BUILDER_STRINGS_EU } from './swot-builder-eu.js';
import { SWOT_BUILDER_STRINGS_GLOBAL } from './swot-builder-global.js';
export const SWOT_BUILDER_STRINGS = {
    ...SWOT_BUILDER_STRINGS_EU,
    ...SWOT_BUILDER_STRINGS_GLOBAL,
};
// ─── Dashboard Builder Strings ───────────────────────────────────────────────
/**
 * Localized strings used by the 5 Dashboard builder functions in analysis-builders.
 * Panel titles, metric labels, and chart labels.
 */
//# sourceMappingURL=swot.js.map