// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0
/** Shared Scandinavian/Dutch SWOT heading */
const SWOT_ANALYSE = 'SWOT-analyse';
export const SWOT_STRINGS = {
    en: {
        sectionHeading: 'SWOT Analysis',
        strengthsLabel: 'Strengths',
        weaknessesLabel: 'Weaknesses',
        opportunitiesLabel: 'Opportunities',
        threatsLabel: 'Threats',
        strengthsDesc: 'Internal positive factors',
        weaknessesDesc: 'Internal negative factors',
        opportunitiesDesc: 'External positive factors',
        threatsDesc: 'External negative factors',
        internalLabel: 'Internal',
        externalLabel: 'External',
    },
    sv: {
        sectionHeading: 'SWOT-analys',
        strengthsLabel: 'Styrkor',
        weaknessesLabel: 'Svagheter',
        opportunitiesLabel: 'Möjligheter',
        threatsLabel: 'Hot',
        strengthsDesc: 'Interna positiva faktorer',
        weaknessesDesc: 'Interna negativa faktorer',
        opportunitiesDesc: 'Externa positiva faktorer',
        threatsDesc: 'Externa negativa faktorer',
        internalLabel: 'Internt',
        externalLabel: 'Externt',
    },
    da: {
        sectionHeading: SWOT_ANALYSE,
        strengthsLabel: 'Styrker',
        weaknessesLabel: 'Svagheder',
        opportunitiesLabel: 'Muligheder',
        threatsLabel: 'Trusler',
        strengthsDesc: 'Interne positive faktorer',
        weaknessesDesc: 'Interne negative faktorer',
        opportunitiesDesc: 'Eksterne positive faktorer',
        threatsDesc: 'Eksterne negative faktorer',
        internalLabel: 'Internt',
        externalLabel: 'Eksternt',
    },
    no: {
        sectionHeading: SWOT_ANALYSE,
        strengthsLabel: 'Styrker',
        weaknessesLabel: 'Svakheter',
        opportunitiesLabel: 'Muligheter',
        threatsLabel: 'Trusler',
        strengthsDesc: 'Interne positive faktorer',
        weaknessesDesc: 'Interne negative faktorer',
        opportunitiesDesc: 'Eksterne positive faktorer',
        threatsDesc: 'Eksterne negative faktorer',
        internalLabel: 'Internt',
        externalLabel: 'Eksternt',
    },
    fi: {
        sectionHeading: 'SWOT-analyysi',
        strengthsLabel: 'Vahvuudet',
        weaknessesLabel: 'Heikkoudet',
        opportunitiesLabel: 'Mahdollisuudet',
        threatsLabel: 'Uhat',
        strengthsDesc: 'Sisäiset positiiviset tekijät',
        weaknessesDesc: 'Sisäiset negatiiviset tekijät',
        opportunitiesDesc: 'Ulkoiset positiiviset tekijät',
        threatsDesc: 'Ulkoiset negatiiviset tekijät',
        internalLabel: 'Sisäinen',
        externalLabel: 'Ulkoinen',
    },
    de: {
        sectionHeading: 'SWOT-Analyse',
        strengthsLabel: 'Stärken',
        weaknessesLabel: 'Schwächen',
        opportunitiesLabel: 'Chancen',
        threatsLabel: 'Risiken',
        strengthsDesc: 'Interne positive Faktoren',
        weaknessesDesc: 'Interne negative Faktoren',
        opportunitiesDesc: 'Externe positive Faktoren',
        threatsDesc: 'Externe negative Faktoren',
        internalLabel: 'Intern',
        externalLabel: 'Extern',
    },
    fr: {
        sectionHeading: 'Analyse SWOT',
        strengthsLabel: 'Forces',
        weaknessesLabel: 'Faiblesses',
        opportunitiesLabel: 'Opportunités',
        threatsLabel: 'Menaces',
        strengthsDesc: 'Facteurs positifs internes',
        weaknessesDesc: 'Facteurs négatifs internes',
        opportunitiesDesc: 'Facteurs positifs externes',
        threatsDesc: 'Facteurs négatifs externes',
        internalLabel: 'Interne',
        externalLabel: 'Externe',
    },
    es: {
        sectionHeading: 'Análisis DAFO',
        strengthsLabel: 'Fortalezas',
        weaknessesLabel: 'Debilidades',
        opportunitiesLabel: 'Oportunidades',
        threatsLabel: 'Amenazas',
        strengthsDesc: 'Factores positivos internos',
        weaknessesDesc: 'Factores negativos internos',
        opportunitiesDesc: 'Factores positivos externos',
        threatsDesc: 'Factores negativos externos',
        internalLabel: 'Interno',
        externalLabel: 'Externo',
    },
    nl: {
        sectionHeading: SWOT_ANALYSE,
        strengthsLabel: 'Sterktes',
        weaknessesLabel: 'Zwaktes',
        opportunitiesLabel: 'Kansen',
        threatsLabel: 'Bedreigingen',
        strengthsDesc: 'Interne positieve factoren',
        weaknessesDesc: 'Interne negatieve factoren',
        opportunitiesDesc: 'Externe positieve factoren',
        threatsDesc: 'Externe negatieve factoren',
        internalLabel: 'Intern',
        externalLabel: 'Extern',
    },
    ar: {
        sectionHeading: 'تحليل SWOT',
        strengthsLabel: 'نقاط القوة',
        weaknessesLabel: 'نقاط الضعف',
        opportunitiesLabel: 'الفرص',
        threatsLabel: 'التهديدات',
        strengthsDesc: 'العوامل الإيجابية الداخلية',
        weaknessesDesc: 'العوامل السلبية الداخلية',
        opportunitiesDesc: 'العوامل الإيجابية الخارجية',
        threatsDesc: 'العوامل السلبية الخارجية',
        internalLabel: 'داخلي',
        externalLabel: 'خارجي',
    },
    he: {
        sectionHeading: 'ניתוח SWOT',
        strengthsLabel: 'חוזקות',
        weaknessesLabel: 'חולשות',
        opportunitiesLabel: 'הזדמנויות',
        threatsLabel: 'איומים',
        strengthsDesc: 'גורמים פנימיים חיוביים',
        weaknessesDesc: 'גורמים פנימיים שליליים',
        opportunitiesDesc: 'גורמים חיצוניים חיוביים',
        threatsDesc: 'גורמים חיצוניים שליליים',
        internalLabel: 'פנימי',
        externalLabel: 'חיצוני',
    },
    ja: {
        sectionHeading: 'SWOT分析',
        strengthsLabel: '強み',
        weaknessesLabel: '弱み',
        opportunitiesLabel: '機会',
        threatsLabel: '脅威',
        strengthsDesc: '内部のプラス要因',
        weaknessesDesc: '内部のマイナス要因',
        opportunitiesDesc: '外部のプラス要因',
        threatsDesc: '外部のマイナス要因',
        internalLabel: '内部',
        externalLabel: '外部',
    },
    ko: {
        sectionHeading: 'SWOT 분석',
        strengthsLabel: '강점',
        weaknessesLabel: '약점',
        opportunitiesLabel: '기회',
        threatsLabel: '위협',
        strengthsDesc: '내부 긍정적 요인',
        weaknessesDesc: '내부 부정적 요인',
        opportunitiesDesc: '외부 긍정적 요인',
        threatsDesc: '외부 부정적 요인',
        internalLabel: '내부',
        externalLabel: '외부',
    },
    zh: {
        sectionHeading: 'SWOT分析',
        strengthsLabel: '优势',
        weaknessesLabel: '劣势',
        opportunitiesLabel: '机会',
        threatsLabel: '威胁',
        strengthsDesc: '内部积极因素',
        weaknessesDesc: '内部消极因素',
        opportunitiesDesc: '外部积极因素',
        threatsDesc: '外部消极因素',
        internalLabel: '内部',
        externalLabel: '外部',
    },
};
// ─── Dashboard localization strings ──────────────────────────────────────────
/**
 * Localized dashboard heading and chart-label strings indexed by ISO 639-1
 * language code. Consumed by the dashboard builder when rendering Chart.js
 * widgets in each of the 14 supported article languages.
 */
export const SWOT_BUILDER_STRINGS = {
    en: {
        votingHighCohesion: (n) => `${n} political groups with cohesion above 80% — disciplined voting blocs`,
        votingAdopted: (n) => `${n} texts adopted — demonstrates legislative productivity`,
        votingActiveVotes: (n) => `${n} votes recorded — active plenary engagement`,
        votingLowCohesion: (n) => `${n} groups with cohesion below 50% — internal divisions weaken bargaining power`,
        votingAnomalies: (n) => `${n} voting anomalies detected — signals unpredictable coalition behaviour`,
        votingCrossParty: 'Cross-party alliances on specific legislation can build broader consensus',
        votingDiverseGroups: (n) => `${n} active political groups — diverse coalition formation possibilities`,
        votingHighSeverity: (n) => `${n} high-severity anomalies — risk of coalition fragmentation`,
        votingShiftingAlliances: 'Shifting alliances may delay legislative progress on key files',
        prospectiveEvents: (n) => `${n} plenary events scheduled — active legislative agenda`,
        prospectiveCommittees: (n) => `${n} committee meetings — broad policy engagement`,
        prospectiveBottlenecks: (n) => `${n} legislative procedures facing bottleneck risks`,
        prospectiveHighDensity: (n) => `High event density (${n}) risks compressed debate time`,
        prospectiveDocuments: (n) => `${n} documents under consideration — legislative momentum`,
        prospectiveQuestions: (n) => `${n} parliamentary questions — MEP engagement with citizen concerns`,
        prospectiveBottleneckRisk: 'Bottleneck procedures may force procedural shortcuts or defer key files',
        prospectiveSchedulingRisk: 'Scheduling density increases risk of last-minute amendments',
        breakingAdopted: (n) => `${n} texts adopted — Parliament demonstrating legislative capacity`,
        breakingEvents: (n) => `${n} parliamentary events — active institutional engagement`,
        breakingAnomalyWeakness: 'Voting anomalies detected — potential coalition instability',
        breakingNoProcedures: 'No new legislative procedures — limited pipeline momentum',
        breakingProceduresActive: (n) => `${n} procedures advancing — legislative pipeline active`,
        breakingCoalitionOpportunity: 'Coalition dynamics shifting — new alliance opportunities emerging',
        breakingAnomalyThreat: 'Detected anomalies may signal deeper political realignment',
        breakingRapidEvents: 'Rapidly evolving events may outpace legislative response capacity',
        propositionsHealthStrong: (pct) => `Pipeline health at ${pct}% — strong legislative management`,
        propositionsThroughputGood: (n) => `Throughput rate ${n} — healthy processing pace`,
        propositionsHealthWeak: (pct) => `Pipeline health at ${pct}% — legislative congestion risk`,
        propositionsThroughputLow: (n) => `Low throughput (${n}) — slow processing delays policy implementation`,
        propositionsPrioritisation: 'Prioritisation of flagship files can improve pipeline efficiency',
        propositionsTrilogueAcceleration: 'Trilogue acceleration on mature files can boost throughput',
        propositionsCriticalCongestion: 'Critical pipeline congestion may force legislative file abandonment',
        propositionsOverlapping: 'Overlapping implementation timelines strain member state transposition capacity',
        committeeActive: (active, total) => `${active} of ${total} committees actively producing documents`,
        committeeDocuments: (n) => `${n} documents produced — strong legislative output`,
        committeeInactive: (n) => `${n} committees with no recent document activity`,
        committeeCrossCollaboration: 'Cross-committee collaboration on horizontal policy files can increase impact',
        committeeHearings: 'Committee hearings provide platform for expert stakeholder engagement',
        committeeLowActivity: 'Low committee activity risks legislative bottlenecks downstream',
        committeeCompetingPriorities: 'Competing policy priorities may dilute committee focus',
    },
    sv: {
        votingHighCohesion: (n) => `${n} politiska grupper med sammanhållning över 80 % — disciplinerade röstningsblock`,
        votingAdopted: (n) => `${n} texter antagna — visar lagstiftande produktivitet`,
        votingActiveVotes: (n) => `${n} röster registrerade — aktivt plenarengagemang`,
        votingLowCohesion: (n) => `${n} grupper med sammanhållning under 50 % — interna splittringar försvagar förhandlingskraft`,
        votingAnomalies: (n) => `${n} röstningsanomalier upptäckta — signalerar oförutsägbart koalitionsbeteende`,
        votingCrossParty: 'Tvärgruppsallianser kring specifik lagstiftning kan bygga bredare samförstånd',
        votingDiverseGroups: (n) => `${n} aktiva politiska grupper — mångsidiga koalitionsmöjligheter`,
        votingHighSeverity: (n) => `${n} allvarliga anomalier — risk för koalitionsfragmentering`,
        votingShiftingAlliances: 'Skiftande allianser kan fördröja lagstiftningsframsteg i viktiga ärenden',
        prospectiveEvents: (n) => `${n} plenarsessioner planerade — aktiv lagstiftningsagenda`,
        prospectiveCommittees: (n) => `${n} utskottsmöten — brett politiskt engagemang`,
        prospectiveBottlenecks: (n) => `${n} lagstiftningsförfaranden med flaskhalsrisk`,
        prospectiveHighDensity: (n) => `Hög händelsetäthet (${n}) riskerar komprimerad debattid`,
        prospectiveDocuments: (n) => `${n} dokument under behandling — lagstiftande momentum`,
        prospectiveQuestions: (n) => `${n} parlamentariska frågor — MEP-engagemang för medborgarfrågor`,
        prospectiveBottleneckRisk: 'Flaskhalsförfaranden kan tvinga fram genvägar eller skjuta upp viktiga ärenden',
        prospectiveSchedulingRisk: 'Hög schemaläggningstäthet ökar risken för ändringsförslag i sista minuten',
        breakingAdopted: (n) => `${n} texter antagna — parlamentet visar lagstiftningskapacitet`,
        breakingEvents: (n) => `${n} parlamentariska händelser — aktivt institutionellt engagemang`,
        breakingAnomalyWeakness: 'Röstningsanomalier upptäckta — potentiell koalitionsinstabilitet',
        breakingNoProcedures: 'Inga nya lagstiftningsförfaranden — begränsat pipelinemomentum',
        breakingProceduresActive: (n) => `${n} förfaranden framskrider — lagstiftningspipelinen aktiv`,
        breakingCoalitionOpportunity: 'Koalitionsdynamiken förändras — nya alliansmöjligheter uppstår',
        breakingAnomalyThreat: 'Upptäckta anomalier kan signalera djupare politisk omgruppering',
        breakingRapidEvents: 'Snabbt utvecklande händelser kan överskrida lagstiftningskapaciteten',
        propositionsHealthStrong: (pct) => `Pipelinehälsa på ${pct} % — stark lagstiftningshantering`,
        propositionsThroughputGood: (n) => `Genomströmning ${n} — hälsosam behandlingstakt`,
        propositionsHealthWeak: (pct) => `Pipelinehälsa på ${pct} % — risk för lagstiftningsträngsel`,
        propositionsThroughputLow: (n) => `Låg genomströmning (${n}) — långsam behandling fördröjer politiska åtgärder`,
        propositionsPrioritisation: 'Prioritering av flaggskeppsfiler kan förbättra pipelineeffektiviteten',
        propositionsTrilogueAcceleration: 'Trilogacceleration av mogna ärenden kan öka genomströmningen',
        propositionsCriticalCongestion: 'Kritisk pipelineträngsel kan tvinga fram att lagstiftningsfiler överges',
        propositionsOverlapping: 'Överlappande genomförandetidslinjer belastar medlemsstaternas införlivandekapacitet',
        committeeActive: (active, total) => `${active} av ${total} utskott producerar aktivt dokument`,
        committeeDocuments: (n) => `${n} dokument producerade — stark lagstiftande produktion`,
        committeeInactive: (n) => `${n} utskott utan nylig dokumentaktivitet`,
        committeeCrossCollaboration: 'Samarbete mellan utskott kring horisontella policyfiler kan öka genomslaget',
        committeeHearings: 'Utskottsutfrågningar ger plattform för expertintressenters engagemang',
        committeeLowActivity: 'Låg utskottsaktivitet riskerar lagstiftningsflaskhalsar nedströms',
        committeeCompetingPriorities: 'Konkurrerande politiska prioriteringar kan späda ut utskottens fokus',
    },
    da: {
        votingHighCohesion: (n) => `${n} politiske grupper med samhørighed over 80 % — disciplinerede stemmeblokke`,
        votingAdopted: (n) => `${n} tekster vedtaget — viser lovgivningsmæssig produktivitet`,
        votingActiveVotes: (n) => `${n} afstemninger registreret — aktivt plenarengagement`,
        votingLowCohesion: (n) => `${n} grupper med samhørighed under 50 % — interne splittelser svækker forhandlingskraft`,
        votingAnomalies: (n) => `${n} stemmeanomalier opdaget — signalerer uforudsigeligt koalitionsadfærd`,
        votingCrossParty: 'Tværpolitiske alliancer om specifik lovgivning kan skabe bredere konsensus',
        votingDiverseGroups: (n) => `${n} aktive politiske grupper — mangfoldige koalitionsmuligheder`,
        votingHighSeverity: (n) => `${n} alvorlige anomalier — risiko for koalitionsfragmentering`,
        votingShiftingAlliances: 'Skiftende alliancer kan forsinke lovgivningsfremskridt i vigtige sager',
        prospectiveEvents: (n) => `${n} plenarmøder planlagt — aktiv lovgivningsdagsorden`,
        prospectiveCommittees: (n) => `${n} udvalgsmøder — bredt politisk engagement`,
        prospectiveBottlenecks: (n) => `${n} lovgivningsprocedurer med flaskehalsrisiko`,
        prospectiveHighDensity: (n) => `Høj begivenhedstæthed (${n}) risikerer komprimeret debattid`,
        prospectiveDocuments: (n) => `${n} dokumenter til behandling — lovgivningsmæssigt momentum`,
        prospectiveQuestions: (n) => `${n} parlamentariske spørgsmål — MEP-engagement med borgerbekymringer`,
        prospectiveBottleneckRisk: 'Flaskehalsprocedurer kan fremtvinge proceduremæssige genveje eller udskyde vigtige sager',
        prospectiveSchedulingRisk: 'Planlægningstæthed øger risikoen for ændringsforslag i sidste øjeblik',
        breakingAdopted: (n) => `${n} tekster vedtaget — parlamentet demonstrerer lovgivningskapacitet`,
        breakingEvents: (n) => `${n} parlamentariske begivenheder — aktivt institutionelt engagement`,
        breakingAnomalyWeakness: 'Stemmeanomalier opdaget — potentiel koalitionsinstabilitet',
        breakingNoProcedures: 'Ingen nye lovgivningsprocedurer — begrænset pipeline-momentum',
        breakingProceduresActive: (n) => `${n} procedurer fremskrider — lovgivningspipeline aktiv`,
        breakingCoalitionOpportunity: 'Koalitionsdynamikken skifter — nye alliancemuligheder opstår',
        breakingAnomalyThreat: 'Opdagede anomalier kan signalere dybere politisk omgruppering',
        breakingRapidEvents: 'Hurtigt udviklende begivenheder kan overskride lovgivningskapaciteten',
        propositionsHealthStrong: (pct) => `Pipeline-sundhed på ${pct} % — stærk lovgivningsforvaltning`,
        propositionsThroughputGood: (n) => `Gennemløb ${n} — sundt behandlingstempo`,
        propositionsHealthWeak: (pct) => `Pipeline-sundhed på ${pct} % — risiko for lovgivningsmæssig trængsel`,
        propositionsThroughputLow: (n) => `Lavt gennemløb (${n}) — langsom behandling forsinker politiske tiltag`,
        propositionsPrioritisation: 'Prioritering af flagskibsfiler kan forbedre pipeline-effektiviteten',
        propositionsTrilogueAcceleration: 'Trilogacceleration af modne sager kan øge gennemløbet',
        propositionsCriticalCongestion: 'Kritisk pipeline-trængsel kan tvinge lovgivningsfiler til at blive opgivet',
        propositionsOverlapping: 'Overlappende implementeringstidslinjer belaster medlemsstaternes gennemførelseskapacitet',
        committeeActive: (active, total) => `${active} af ${total} udvalg producerer aktivt dokumenter`,
        committeeDocuments: (n) => `${n} dokumenter produceret — stærk lovgivningsmæssig produktion`,
        committeeInactive: (n) => `${n} udvalg uden nylig dokumentaktivitet`,
        committeeCrossCollaboration: 'Samarbejde på tværs af udvalg om horisontale politikfiler kan øge gennemslagskraften',
        committeeHearings: 'Udvalgshøringer giver platform for ekspertinteressenters engagement',
        committeeLowActivity: 'Lav udvalgsaktivitet risikerer lovgivningsmæssige flaskehalse nedstrøms',
        committeeCompetingPriorities: 'Konkurrerende politiske prioriteter kan udvande udvalgets fokus',
    },
    no: {
        votingHighCohesion: (n) => `${n} politiske grupper med samhold over 80 % — disiplinerte stemmeblokker`,
        votingAdopted: (n) => `${n} tekster vedtatt — viser lovgivende produktivitet`,
        votingActiveVotes: (n) => `${n} avstemninger registrert — aktivt plenaraktivitet`,
        votingLowCohesion: (n) => `${n} grupper med samhold under 50 % — interne splittelser svekker forhandlingskraft`,
        votingAnomalies: (n) => `${n} stemmeavvik oppdaget — signaliserer uforutsigbar koalisjonsadferd`,
        votingCrossParty: 'Tverrpolitiske allianser om spesifikk lovgivning kan bygge bredere konsensus',
        votingDiverseGroups: (n) => `${n} aktive politiske grupper — mangfoldige koalisjonsmuligheter`,
        votingHighSeverity: (n) => `${n} alvorlige avvik — risiko for koalisjonsfragmentering`,
        votingShiftingAlliances: 'Skiftende allianser kan forsinke lovgivningsframgang i viktige saker',
        prospectiveEvents: (n) => `${n} plenarmøter planlagt — aktiv lovgivningsdagsorden`,
        prospectiveCommittees: (n) => `${n} komitémøter — bredt politisk engasjement`,
        prospectiveBottlenecks: (n) => `${n} lovgivningsprosedyrer med flaskehalsrisiko`,
        prospectiveHighDensity: (n) => `Høy hendelsestetthet (${n}) risikerer komprimert debattid`,
        prospectiveDocuments: (n) => `${n} dokumenter til behandling — lovgivende momentum`,
        prospectiveQuestions: (n) => `${n} parlamentariske spørsmål — MEP-engasjement for borgernes bekymringer`,
        prospectiveBottleneckRisk: 'Flaskehalsprosedyrer kan tvinge frem snarveier eller utsette viktige saker',
        prospectiveSchedulingRisk: 'Planleggingstetthet øker risikoen for endringsforslag i siste liten',
        breakingAdopted: (n) => `${n} tekster vedtatt — parlamentet demonstrerer lovgivningskapasitet`,
        breakingEvents: (n) => `${n} parlamentariske hendelser — aktivt institusjonelt engasjement`,
        breakingAnomalyWeakness: 'Stemmeavvik oppdaget — potensiell koalisjonsinstabilitet',
        breakingNoProcedures: 'Ingen nye lovgivningsprosedyrer — begrenset pipeline-momentum',
        breakingProceduresActive: (n) => `${n} prosedyrer fremskrider — lovgivningspipeline aktiv`,
        breakingCoalitionOpportunity: 'Koalisjonsdynamikken skifter — nye alliansmuligheter oppstår',
        breakingAnomalyThreat: 'Oppdagede avvik kan signalisere dypere politisk omgruppering',
        breakingRapidEvents: 'Raskt utviklende hendelser kan overskride lovgivningskapasiteten',
        propositionsHealthStrong: (pct) => `Pipeline-helse på ${pct} % — sterk lovgivningsforvaltning`,
        propositionsThroughputGood: (n) => `Gjennomstrømning ${n} — sunt behandlingstempo`,
        propositionsHealthWeak: (pct) => `Pipeline-helse på ${pct} % — risiko for lovgivningsmessig trengsel`,
        propositionsThroughputLow: (n) => `Lav gjennomstrømning (${n}) — treg behandling forsinker politiske tiltak`,
        propositionsPrioritisation: 'Prioritering av flaggskipfiler kan forbedre pipeline-effektiviteten',
        propositionsTrilogueAcceleration: 'Trilogakselerasjon av modne saker kan øke gjennomstrømningen',
        propositionsCriticalCongestion: 'Kritisk pipeline-trengsel kan tvinge lovgivningsfiler til å bli forlatt',
        propositionsOverlapping: 'Overlappende implementeringstidslinjer belaster medlemsstatenes gjennomføringskapasitet',
        committeeActive: (active, total) => `${active} av ${total} komiteer produserer aktivt dokumenter`,
        committeeDocuments: (n) => `${n} dokumenter produsert — sterk lovgivende produksjon`,
        committeeInactive: (n) => `${n} komiteer uten nylig dokumentaktivitet`,
        committeeCrossCollaboration: 'Samarbeid på tvers av komiteer om horisontale policyfiler kan øke gjennomslaget',
        committeeHearings: 'Komitéhøringer gir plattform for ekspertinteressenters engasjement',
        committeeLowActivity: 'Lav komitéaktivitet risikerer lovgivningsmessige flaskehalser nedstrøms',
        committeeCompetingPriorities: 'Konkurrerende politiske prioriteringer kan utvanne komitéens fokus',
    },
    fi: {
        votingHighCohesion: (n) => `${n} poliittista ryhmää yhtenäisyydellä yli 80 % — kurinalaiset äänestyslohkot`,
        votingAdopted: (n) => `${n} tekstiä hyväksytty — osoittaa lainsäädännöllistä tuottavuutta`,
        votingActiveVotes: (n) => `${n} äänestystä kirjattu — aktiivinen täysistuntoaktiivisuus`,
        votingLowCohesion: (n) => `${n} ryhmää yhtenäisyydellä alle 50 % — sisäiset jakolinjat heikentävät neuvotteluvoimaa`,
        votingAnomalies: (n) => `${n} äänestyspoikkeamaa havaittu — viestii ennakoimattomasta koalitiokäyttäytymisestä`,
        votingCrossParty: 'Puoluerajat ylittävät liittoutumat voivat rakentaa laajempaa yhteisymmärrystä',
        votingDiverseGroups: (n) => `${n} aktiivista poliittista ryhmää — monipuoliset koalitiomahdollisuudet`,
        votingHighSeverity: (n) => `${n} vakavaa poikkeamaa — koalition pirstoutumisen riski`,
        votingShiftingAlliances: 'Muuttuvat liittoutumat voivat viivästyttää lainsäädäntötyötä keskeisissä asioissa',
        prospectiveEvents: (n) => `${n} täysistuntotapahtumaa aikataulutettu — aktiivinen lainsäädäntöagenda`,
        prospectiveCommittees: (n) => `${n} valiokuntakokousta — laaja poliittinen sitoutuminen`,
        prospectiveBottlenecks: (n) => `${n} lainsäädäntömenettelyä pullonkaulauhalla`,
        prospectiveHighDensity: (n) => `Korkea tapahtumatiheys (${n}) uhkaa tiivistettyä keskusteluaikaa`,
        prospectiveDocuments: (n) => `${n} asiakirjaa käsittelyssä — lainsäädännöllinen vauhti`,
        prospectiveQuestions: (n) => `${n} parlamentaarista kysymystä — MEP-sitoutuminen kansalaisten huoliin`,
        prospectiveBottleneckRisk: 'Pullonkaulamenettelyt voivat pakottaa menettelylliset oikotiet tai lykätä keskeisiä asioita',
        prospectiveSchedulingRisk: 'Aikataulutiheys lisää viime hetken muutosehdotusten riskiä',
        breakingAdopted: (n) => `${n} tekstiä hyväksytty — parlamentti osoittaa lainsäädäntökapasiteettia`,
        breakingEvents: (n) => `${n} parlamentaarista tapahtumaa — aktiivinen institutionaalinen sitoutuminen`,
        breakingAnomalyWeakness: 'Äänestyspoikkeamia havaittu — mahdollinen koalition epävakaus',
        breakingNoProcedures: 'Ei uusia lainsäädäntömenettelyjä — rajallinen pipeline-vauhti',
        breakingProceduresActive: (n) => `${n} menettelyä edistyy — lainsäädäntöpipeline aktiivinen`,
        breakingCoalitionOpportunity: 'Koalitiodynamiikka muuttuu — uusia liittoutumamahdollisuuksia syntyy',
        breakingAnomalyThreat: 'Havaitut poikkeamat voivat viestittää syvemmästä poliittisesta uudelleenjärjestelystä',
        breakingRapidEvents: 'Nopeasti kehittyvät tapahtumat voivat ylittää lainsäädännöllisen reagointikyvyn',
        propositionsHealthStrong: (pct) => `Pipeline-terveys ${pct} % — vahva lainsäädännön hallinta`,
        propositionsThroughputGood: (n) => `Läpäisyaste ${n} — terve käsittelytahti`,
        propositionsHealthWeak: (pct) => `Pipeline-terveys ${pct} % — lainsäädännöllisen ruuhkautumisen riski`,
        propositionsThroughputLow: (n) => `Matala läpäisyaste (${n}) — hidas käsittely viivästyttää politiikkatoimia`,
        propositionsPrioritisation: 'Lippulaiva-asiakirjojen priorisointi voi parantaa pipeline-tehokkuutta',
        propositionsTrilogueAcceleration: 'Trilogikiihdytys kypsille asioille voi kasvattaa läpäisyastetta',
        propositionsCriticalCongestion: 'Kriittinen pipeline-ruuhka voi pakottaa lainsäädäntöasiakirjojen hylkäämisen',
        propositionsOverlapping: 'Päällekkäiset toteutusaikataulut rasittavat jäsenvaltioiden täytäntöönpanokapasiteettia',
        committeeActive: (active, total) => `${active} / ${total} valiokuntaa tuottaa aktiivisesti asiakirjoja`,
        committeeDocuments: (n) => `${n} asiakirjaa tuotettu — vahva lainsäädännöllinen tuotanto`,
        committeeInactive: (n) => `${n} valiokuntaa ilman viimeaikaista asiakirja-aktiivisuutta`,
        committeeCrossCollaboration: 'Valiokuntien välinen yhteistyö horisontaalisissa politiikka-asioissa voi lisätä vaikuttavuutta',
        committeeHearings: 'Valiokuntakuulemiset tarjoavat alustan asiantuntijasidosryhmien osallistumiselle',
        committeeLowActivity: 'Matala valiokuntatoiminta uhkaa lainsäädännöllisiä pullonkauloja jatkovaiheessa',
        committeeCompetingPriorities: 'Kilpailevat poliittiset prioriteetit voivat laimentaa valiokunnan fokusta',
    },
    de: {
        votingHighCohesion: (n) => `${n} Fraktionen mit Kohäsion über 80 % — disziplinierte Abstimmungsblöcke`,
        votingAdopted: (n) => `${n} Texte angenommen — zeigt gesetzgeberische Produktivität`,
        votingActiveVotes: (n) => `${n} Abstimmungen erfasst — aktives Plenarengagement`,
        votingLowCohesion: (n) => `${n} Fraktionen mit Kohäsion unter 50 % — interne Spaltungen schwächen Verhandlungsmacht`,
        votingAnomalies: (n) => `${n} Abstimmungsanomalien erkannt — signalisiert unvorhersehbares Koalitionsverhalten`,
        votingCrossParty: 'Fraktionsübergreifende Allianzen bei spezifischer Gesetzgebung können breiteren Konsens schaffen',
        votingDiverseGroups: (n) => `${n} aktive Fraktionen — vielfältige Koalitionsbildungsmöglichkeiten`,
        votingHighSeverity: (n) => `${n} schwerwiegende Anomalien — Risiko der Koalitionsfragmentierung`,
        votingShiftingAlliances: 'Wechselnde Allianzen können den Gesetzgebungsfortschritt bei wichtigen Dossiers verzögern',
        prospectiveEvents: (n) => `${n} Plenarveranstaltungen geplant — aktive Gesetzgebungsagenda`,
        prospectiveCommittees: (n) => `${n} Ausschusssitzungen — breites politisches Engagement`,
        prospectiveBottlenecks: (n) => `${n} Gesetzgebungsverfahren mit Engpassrisiko`,
        prospectiveHighDensity: (n) => `Hohe Veranstaltungsdichte (${n}) birgt Risiko komprimierter Debattenzeit`,
        prospectiveDocuments: (n) => `${n} Dokumente in Beratung — gesetzgeberisches Momentum`,
        prospectiveQuestions: (n) => `${n} parlamentarische Anfragen — MdEP-Engagement für Bürgeranliegen`,
        prospectiveBottleneckRisk: 'Engpassverfahren können zu Verfahrensabkürzungen zwingen oder wichtige Dossiers verzögern',
        prospectiveSchedulingRisk: 'Terminierungsdichte erhöht das Risiko von Last-Minute-Änderungsanträgen',
        breakingAdopted: (n) => `${n} Texte angenommen — Parlament demonstriert Gesetzgebungskapazität`,
        breakingEvents: (n) => `${n} parlamentarische Veranstaltungen — aktives institutionelles Engagement`,
        breakingAnomalyWeakness: 'Abstimmungsanomalien erkannt — potenzielle Koalitionsinstabilität',
        breakingNoProcedures: 'Keine neuen Gesetzgebungsverfahren — begrenztes Pipeline-Momentum',
        breakingProceduresActive: (n) => `${n} Verfahren schreiten voran — Gesetzgebungspipeline aktiv`,
        breakingCoalitionOpportunity: 'Koalitionsdynamik verschiebt sich — neue Allianzmöglichkeiten entstehen',
        breakingAnomalyThreat: 'Erkannte Anomalien könnten tiefere politische Neuausrichtung signalisieren',
        breakingRapidEvents: 'Sich schnell entwickelnde Ereignisse könnten die Gesetzgebungskapazität übersteigen',
        propositionsHealthStrong: (pct) => `Pipeline-Gesundheit bei ${pct} % — starkes Gesetzgebungsmanagement`,
        propositionsThroughputGood: (n) => `Durchsatz ${n} — gesundes Verarbeitungstempo`,
        propositionsHealthWeak: (pct) => `Pipeline-Gesundheit bei ${pct} % — Risiko gesetzgeberischer Stauung`,
        propositionsThroughputLow: (n) => `Niedriger Durchsatz (${n}) — langsame Verarbeitung verzögert politische Maßnahmen`,
        propositionsPrioritisation: 'Priorisierung von Leuchtturm-Dossiers kann die Pipeline-Effizienz verbessern',
        propositionsTrilogueAcceleration: 'Trilog-Beschleunigung reifer Dossiers kann den Durchsatz steigern',
        propositionsCriticalCongestion: 'Kritische Pipeline-Stauung kann zum Aufgeben von Gesetzgebungsdossiers führen',
        propositionsOverlapping: 'Überlappende Umsetzungszeitpläne belasten die Umsetzungskapazität der Mitgliedstaaten',
        committeeActive: (active, total) => `${active} von ${total} Ausschüssen produzieren aktiv Dokumente`,
        committeeDocuments: (n) => `${n} Dokumente produziert — starke gesetzgeberische Produktion`,
        committeeInactive: (n) => `${n} Ausschüsse ohne jüngste Dokumentenaktivität`,
        committeeCrossCollaboration: 'Ausschussübergreifende Zusammenarbeit bei horizontalen Politikdossiers kann die Wirkung erhöhen',
        committeeHearings: 'Ausschussanhörungen bieten Plattform für Experten-Stakeholder-Engagement',
        committeeLowActivity: 'Niedrige Ausschussaktivität birgt Risiko gesetzgeberischer Engpässe im weiteren Verlauf',
        committeeCompetingPriorities: 'Konkurrierende politische Prioritäten können den Ausschussfokus verwässern',
    },
    fr: {
        votingHighCohesion: (n) => `${n} groupes politiques avec cohésion supérieure à 80 % — blocs de vote disciplinés`,
        votingAdopted: (n) => `${n} textes adoptés — démontre la productivité législative`,
        votingActiveVotes: (n) => `${n} votes enregistrés — engagement actif en plénière`,
        votingLowCohesion: (n) => `${n} groupes avec cohésion inférieure à 50 % — divisions internes affaiblissent le pouvoir de négociation`,
        votingAnomalies: (n) => `${n} anomalies de vote détectées — signale un comportement de coalition imprévisible`,
        votingCrossParty: 'Les alliances transpartisanes sur des législations spécifiques peuvent construire un consensus plus large',
        votingDiverseGroups: (n) => `${n} groupes politiques actifs — possibilités diverses de formation de coalition`,
        votingHighSeverity: (n) => `${n} anomalies de haute gravité — risque de fragmentation de la coalition`,
        votingShiftingAlliances: 'Les alliances mouvantes peuvent retarder les progrès législatifs sur les dossiers clés',
        prospectiveEvents: (n) => `${n} événements pléniers programmés — agenda législatif actif`,
        prospectiveCommittees: (n) => `${n} réunions de commission — large engagement politique`,
        prospectiveBottlenecks: (n) => `${n} procédures législatives confrontées à des risques de goulot d'étranglement`,
        prospectiveHighDensity: (n) => `Haute densité d'événements (${n}) risque de comprimer le temps de débat`,
        prospectiveDocuments: (n) => `${n} documents en examen — momentum législatif`,
        prospectiveQuestions: (n) => `${n} questions parlementaires — engagement des députés envers les préoccupations citoyennes`,
        prospectiveBottleneckRisk: "Les procédures en goulot d'étranglement peuvent forcer des raccourcis ou reporter des dossiers clés",
        prospectiveSchedulingRisk: "La densité de programmation augmente le risque d'amendements de dernière minute",
        breakingAdopted: (n) => `${n} textes adoptés — le Parlement démontre sa capacité législative`,
        breakingEvents: (n) => `${n} événements parlementaires — engagement institutionnel actif`,
        breakingAnomalyWeakness: 'Anomalies de vote détectées — instabilité potentielle de la coalition',
        breakingNoProcedures: 'Pas de nouvelles procédures législatives — momentum limité du pipeline',
        breakingProceduresActive: (n) => `${n} procédures en cours — pipeline législatif actif`,
        breakingCoalitionOpportunity: "La dynamique de coalition évolue — de nouvelles opportunités d'alliance émergent",
        breakingAnomalyThreat: 'Les anomalies détectées peuvent signaler un réalignement politique plus profond',
        breakingRapidEvents: 'Les événements à évolution rapide peuvent dépasser la capacité de réponse législative',
        propositionsHealthStrong: (pct) => `Santé du pipeline à ${pct} % — gestion législative solide`,
        propositionsThroughputGood: (n) => `Débit ${n} — rythme de traitement sain`,
        propositionsHealthWeak: (pct) => `Santé du pipeline à ${pct} % — risque de congestion législative`,
        propositionsThroughputLow: (n) => `Faible débit (${n}) — le traitement lent retarde la mise en œuvre des politiques`,
        propositionsPrioritisation: "La priorisation des dossiers phares peut améliorer l'efficacité du pipeline",
        propositionsTrilogueAcceleration: "L'accélération des trilogues sur les dossiers mûrs peut augmenter le débit",
        propositionsCriticalCongestion: "Une congestion critique du pipeline peut forcer l'abandon de dossiers législatifs",
        propositionsOverlapping: 'Les calendriers de mise en œuvre qui se chevauchent mettent à rude épreuve la capacité de transposition des États membres',
        committeeActive: (active, total) => `${active} sur ${total} commissions produisent activement des documents`,
        committeeDocuments: (n) => `${n} documents produits — forte production législative`,
        committeeInactive: (n) => `${n} commissions sans activité documentaire récente`,
        committeeCrossCollaboration: "La collaboration inter-commissions sur les dossiers politiques horizontaux peut accroître l'impact",
        committeeHearings: "Les auditions en commission offrent une plateforme pour l'engagement des parties prenantes expertes",
        committeeLowActivity: "Une faible activité des commissions risque de créer des goulots d'étranglement législatifs en aval",
        committeeCompetingPriorities: 'Les priorités politiques concurrentes peuvent diluer la concentration des commissions',
    },
    es: {
        votingHighCohesion: (n) => `${n} grupos políticos con cohesión superior al 80 % — bloques de voto disciplinados`,
        votingAdopted: (n) => `${n} textos adoptados — demuestra productividad legislativa`,
        votingActiveVotes: (n) => `${n} votos registrados — participación activa en plenario`,
        votingLowCohesion: (n) => `${n} grupos con cohesión inferior al 50 % — divisiones internas debilitan el poder de negociación`,
        votingAnomalies: (n) => `${n} anomalías de votación detectadas — señala comportamiento de coalición impredecible`,
        votingCrossParty: 'Las alianzas transversales en legislación específica pueden construir un consenso más amplio',
        votingDiverseGroups: (n) => `${n} grupos políticos activos — diversas posibilidades de formación de coalición`,
        votingHighSeverity: (n) => `${n} anomalías de alta gravedad — riesgo de fragmentación de la coalición`,
        votingShiftingAlliances: 'Las alianzas cambiantes pueden retrasar el progreso legislativo en expedientes clave',
        prospectiveEvents: (n) => `${n} eventos plenarios programados — agenda legislativa activa`,
        prospectiveCommittees: (n) => `${n} reuniones de comisión — amplio compromiso político`,
        prospectiveBottlenecks: (n) => `${n} procedimientos legislativos con riesgo de cuello de botella`,
        prospectiveHighDensity: (n) => `Alta densidad de eventos (${n}) arriesga tiempo de debate comprimido`,
        prospectiveDocuments: (n) => `${n} documentos en consideración — impulso legislativo`,
        prospectiveQuestions: (n) => `${n} preguntas parlamentarias — compromiso de los eurodiputados con las preocupaciones ciudadanas`,
        prospectiveBottleneckRisk: 'Los procedimientos con cuello de botella pueden forzar atajos o aplazar expedientes clave',
        prospectiveSchedulingRisk: 'La densidad de programación aumenta el riesgo de enmiendas de último momento',
        breakingAdopted: (n) => `${n} textos adoptados — el Parlamento demuestra capacidad legislativa`,
        breakingEvents: (n) => `${n} eventos parlamentarios — compromiso institucional activo`,
        breakingAnomalyWeakness: 'Anomalías de votación detectadas — potencial inestabilidad de la coalición',
        breakingNoProcedures: 'Sin nuevos procedimientos legislativos — impulso limitado del pipeline',
        breakingProceduresActive: (n) => `${n} procedimientos avanzando — pipeline legislativo activo`,
        breakingCoalitionOpportunity: 'La dinámica de coalición está cambiando — surgen nuevas oportunidades de alianza',
        breakingAnomalyThreat: 'Las anomalías detectadas pueden señalar un realineamiento político más profundo',
        breakingRapidEvents: 'Los eventos en rápida evolución pueden superar la capacidad de respuesta legislativa',
        propositionsHealthStrong: (pct) => `Salud del pipeline al ${pct} % — gestión legislativa sólida`,
        propositionsThroughputGood: (n) => `Rendimiento ${n} — ritmo de procesamiento saludable`,
        propositionsHealthWeak: (pct) => `Salud del pipeline al ${pct} % — riesgo de congestión legislativa`,
        propositionsThroughputLow: (n) => `Bajo rendimiento (${n}) — el procesamiento lento retrasa la implementación de políticas`,
        propositionsPrioritisation: 'La priorización de expedientes emblemáticos puede mejorar la eficiencia del pipeline',
        propositionsTrilogueAcceleration: 'La aceleración de trílogos en expedientes maduros puede aumentar el rendimiento',
        propositionsCriticalCongestion: 'La congestión crítica del pipeline puede forzar el abandono de expedientes legislativos',
        propositionsOverlapping: 'Los calendarios de implementación superpuestos agotan la capacidad de transposición de los Estados miembros',
        committeeActive: (active, total) => `${active} de ${total} comisiones producen activamente documentos`,
        committeeDocuments: (n) => `${n} documentos producidos — fuerte producción legislativa`,
        committeeInactive: (n) => `${n} comisiones sin actividad documental reciente`,
        committeeCrossCollaboration: 'La colaboración entre comisiones en expedientes políticos horizontales puede aumentar el impacto',
        committeeHearings: 'Las audiencias de comisión proporcionan plataforma para la participación de expertos interesados',
        committeeLowActivity: 'La baja actividad de las comisiones arriesga cuellos de botella legislativos posteriores',
        committeeCompetingPriorities: 'Las prioridades políticas en competencia pueden diluir el enfoque de las comisiones',
    },
    nl: {
        votingHighCohesion: (n) => `${n} fracties met cohesie boven 80 % — gedisciplineerde stemblokken`,
        votingAdopted: (n) => `${n} teksten aangenomen — toont wetgevende productiviteit`,
        votingActiveVotes: (n) => `${n} stemmingen geregistreerd — actieve plenaire betrokkenheid`,
        votingLowCohesion: (n) => `${n} fracties met cohesie onder 50 % — interne verdeeldheid verzwakt onderhandelingspositie`,
        votingAnomalies: (n) => `${n} stemafwijkingen gedetecteerd — signaleert onvoorspelbaar coalitiegedrag`,
        votingCrossParty: 'Fractieoverstijgende allianties bij specifieke wetgeving kunnen bredere consensus opbouwen',
        votingDiverseGroups: (n) => `${n} actieve fracties — diverse coalitievormingsmogelijkheden`,
        votingHighSeverity: (n) => `${n} ernstige afwijkingen — risico op coalitiefragmentatie`,
        votingShiftingAlliances: 'Verschuivende allianties kunnen wetgevende vooruitgang bij belangrijke dossiers vertragen',
        prospectiveEvents: (n) => `${n} plenaire evenementen gepland — actieve wetgevingsagenda`,
        prospectiveCommittees: (n) => `${n} commissievergaderingen — brede politieke betrokkenheid`,
        prospectiveBottlenecks: (n) => `${n} wetgevingsprocedures met knelpuntrisico`,
        prospectiveHighDensity: (n) => `Hoge evenementendichtheid (${n}) riskeert gecomprimeerde debattijd`,
        prospectiveDocuments: (n) => `${n} documenten in behandeling — wetgevend momentum`,
        prospectiveQuestions: (n) => `${n} parlementaire vragen — EP-lid-betrokkenheid bij burgerzorgen`,
        prospectiveBottleneckRisk: 'Knelpuntprocedures kunnen procedurele shortcuts afdwingen of belangrijke dossiers uitstellen',
        prospectiveSchedulingRisk: 'Planningsdichtheid verhoogt het risico op amendementen op het laatste moment',
        breakingAdopted: (n) => `${n} teksten aangenomen — Parlement toont wetgevende capaciteit`,
        breakingEvents: (n) => `${n} parlementaire evenementen — actieve institutionele betrokkenheid`,
        breakingAnomalyWeakness: 'Stemafwijkingen gedetecteerd — potentiële coalitie-instabiliteit',
        breakingNoProcedures: 'Geen nieuwe wetgevingsprocedures — beperkt pipeline-momentum',
        breakingProceduresActive: (n) => `${n} procedures vorderen — wetgevingspipeline actief`,
        breakingCoalitionOpportunity: 'Coalitiedynamiek verschuift — nieuwe allantiemogelijkheden ontstaan',
        breakingAnomalyThreat: 'Gedetecteerde afwijkingen kunnen diepere politieke hergroepering signaleren',
        breakingRapidEvents: 'Snel evoluerende gebeurtenissen kunnen de wetgevingscapaciteit overschrijden',
        propositionsHealthStrong: (pct) => `Pipeline-gezondheid op ${pct} % — sterk wetgevingsbeheer`,
        propositionsThroughputGood: (n) => `Doorvoer ${n} — gezond verwerkingstempo`,
        propositionsHealthWeak: (pct) => `Pipeline-gezondheid op ${pct} % — risico op wetgevingscongestie`,
        propositionsThroughputLow: (n) => `Lage doorvoer (${n}) — trage verwerking vertraagt beleidsimplementatie`,
        propositionsPrioritisation: 'Prioritering van vlaggenschipdossiers kan de pipeline-efficiëntie verbeteren',
        propositionsTrilogueAcceleration: 'Trilogversnelling van rijpe dossiers kan de doorvoer verhogen',
        propositionsCriticalCongestion: 'Kritische pipeline-congestie kan leiden tot het opgeven van wetgevingsdossiers',
        propositionsOverlapping: 'Overlappende implementatietijdlijnen belasten de omzettingscapaciteit van lidstaten',
        committeeActive: (active, total) => `${active} van ${total} commissies produceren actief documenten`,
        committeeDocuments: (n) => `${n} documenten geproduceerd — sterke wetgevende productie`,
        committeeInactive: (n) => `${n} commissies zonder recente documentactiviteit`,
        committeeCrossCollaboration: 'Samenwerking tussen commissies bij horizontale beleidsdossiers kan de impact vergroten',
        committeeHearings: 'Commissiehoorzittingen bieden platform voor betrokkenheid van deskundige belanghebbenden',
        committeeLowActivity: 'Lage commissieactiviteit riskeert wetgevende knelpunten stroomafwaarts',
        committeeCompetingPriorities: 'Concurrerende politieke prioriteiten kunnen de commissiefocus verwateren',
    },
    ar: {
        votingHighCohesion: (n) => `${n} مجموعات سياسية بتماسك فوق 80% — كتل تصويت منضبطة`,
        votingAdopted: (n) => `${n} نصوص معتمدة — يُظهر إنتاجية تشريعية`,
        votingActiveVotes: (n) => `${n} تصويتات مسجلة — مشاركة نشطة في الجلسة العامة`,
        votingLowCohesion: (n) => `${n} مجموعات بتماسك أقل من 50% — انقسامات داخلية تُضعف القدرة التفاوضية`,
        votingAnomalies: (n) => `${n} شذوذات تصويت مكتشفة — تشير إلى سلوك ائتلافي غير متوقع`,
        votingCrossParty: 'التحالفات العابرة للأحزاب حول تشريعات محددة يمكن أن تبني توافقاً أوسع',
        votingDiverseGroups: (n) => `${n} مجموعات سياسية نشطة — إمكانيات متنوعة لتشكيل الائتلاف`,
        votingHighSeverity: (n) => `${n} شذوذات عالية الخطورة — خطر تفتت الائتلاف`,
        votingShiftingAlliances: 'التحالفات المتغيرة قد تؤخر التقدم التشريعي في الملفات الرئيسية',
        prospectiveEvents: (n) => `${n} فعاليات عامة مجدولة — أجندة تشريعية نشطة`,
        prospectiveCommittees: (n) => `${n} اجتماعات لجان — مشاركة سياسية واسعة`,
        prospectiveBottlenecks: (n) => `${n} إجراءات تشريعية تواجه مخاطر اختناق`,
        prospectiveHighDensity: (n) => `كثافة أحداث عالية (${n}) تخاطر بتقليص وقت النقاش`,
        prospectiveDocuments: (n) => `${n} وثائق قيد النظر — زخم تشريعي`,
        prospectiveQuestions: (n) => `${n} أسئلة برلمانية — مشاركة أعضاء البرلمان في اهتمامات المواطنين`,
        prospectiveBottleneckRisk: 'إجراءات الاختناق قد تفرض اختصارات إجرائية أو تؤجل ملفات رئيسية',
        prospectiveSchedulingRisk: 'كثافة الجدولة تزيد من خطر التعديلات في اللحظة الأخيرة',
        breakingAdopted: (n) => `${n} نصوص معتمدة — البرلمان يُظهر القدرة التشريعية`,
        breakingEvents: (n) => `${n} فعاليات برلمانية — مشاركة مؤسسية نشطة`,
        breakingAnomalyWeakness: 'شذوذات تصويت مكتشفة — عدم استقرار ائتلافي محتمل',
        breakingNoProcedures: 'لا إجراءات تشريعية جديدة — زخم محدود',
        breakingProceduresActive: (n) => `${n} إجراءات تتقدم — خط الأنابيب التشريعي نشط`,
        breakingCoalitionOpportunity: 'ديناميكيات الائتلاف تتغير — فرص تحالف جديدة تنشأ',
        breakingAnomalyThreat: 'الشذوذات المكتشفة قد تشير إلى إعادة ترتيب سياسي أعمق',
        breakingRapidEvents: 'الأحداث سريعة التطور قد تتجاوز القدرة التشريعية على الاستجابة',
        propositionsHealthStrong: (pct) => `صحة خط الأنابيب عند ${pct}% — إدارة تشريعية قوية`,
        propositionsThroughputGood: (n) => `معدل الإنتاجية ${n} — وتيرة معالجة صحية`,
        propositionsHealthWeak: (pct) => `صحة خط الأنابيب عند ${pct}% — خطر الازدحام التشريعي`,
        propositionsThroughputLow: (n) => `إنتاجية منخفضة (${n}) — المعالجة البطيئة تؤخر تنفيذ السياسات`,
        propositionsPrioritisation: 'تحديد أولويات الملفات الرائدة يمكن أن يحسن كفاءة خط الأنابيب',
        propositionsTrilogueAcceleration: 'تسريع الحوار الثلاثي للملفات الناضجة يمكن أن يزيد الإنتاجية',
        propositionsCriticalCongestion: 'الازدحام الحرج قد يفرض التخلي عن ملفات تشريعية',
        propositionsOverlapping: 'الجداول الزمنية المتداخلة للتنفيذ تُرهق قدرة الدول الأعضاء على النقل',
        committeeActive: (active, total) => `${active} من ${total} لجنة تنتج وثائق بنشاط`,
        committeeDocuments: (n) => `${n} وثائق مُنتجة — إنتاج تشريعي قوي`,
        committeeInactive: (n) => `${n} لجان بدون نشاط وثائقي حديث`,
        committeeCrossCollaboration: 'التعاون بين اللجان في ملفات السياسة الأفقية يمكن أن يزيد التأثير',
        committeeHearings: 'جلسات استماع اللجان توفر منصة لمشاركة أصحاب المصلحة الخبراء',
        committeeLowActivity: 'انخفاض نشاط اللجان يخاطر باختناقات تشريعية لاحقاً',
        committeeCompetingPriorities: 'الأولويات السياسية المتنافسة قد تُضعف تركيز اللجان',
    },
    he: {
        votingHighCohesion: (n) => `${n} קבוצות פוליטיות עם לכידות מעל 80% — גושי הצבעה ממושמעים`,
        votingAdopted: (n) => `${n} טקסטים אומצו — מדגים פרודוקטיביות חקיקתית`,
        votingActiveVotes: (n) => `${n} הצבעות נרשמו — מעורבות פעילה במליאה`,
        votingLowCohesion: (n) => `${n} קבוצות עם לכידות מתחת ל-50% — פיצולים פנימיים מחלישים כוח מיקוח`,
        votingAnomalies: (n) => `${n} חריגות הצבעה זוהו — מסמן התנהגות קואליציונית בלתי צפויה`,
        votingCrossParty: 'בריתות חוצות מפלגות בחקיקה ספציפית יכולות לבנות קונצנזוס רחב יותר',
        votingDiverseGroups: (n) => `${n} קבוצות פוליטיות פעילות — אפשרויות מגוונות ליצירת קואליציה`,
        votingHighSeverity: (n) => `${n} חריגות חמורות — סיכון לפירוק קואליציוני`,
        votingShiftingAlliances: 'בריתות משתנות עלולות לעכב התקדמות חקיקתית בתיקים מרכזיים',
        prospectiveEvents: (n) => `${n} אירועי מליאה מתוכננים — סדר יום חקיקתי פעיל`,
        prospectiveCommittees: (n) => `${n} ישיבות ועדה — מעורבות פוליטית רחבה`,
        prospectiveBottlenecks: (n) => `${n} הליכי חקיקה מתמודדים עם סיכוני צוואר בקבוק`,
        prospectiveHighDensity: (n) => `צפיפות אירועים גבוהה (${n}) מסכנת זמן דיון מצומצם`,
        prospectiveDocuments: (n) => `${n} מסמכים בבחינה — תנופה חקיקתית`,
        prospectiveQuestions: (n) => `${n} שאילתות פרלמנטריות — מעורבות חברי פרלמנט בדאגות אזרחים`,
        prospectiveBottleneckRisk: 'הליכי צוואר בקבוק עלולים לכפות קיצורי דרך פרוצדורליים או לדחות תיקים מרכזיים',
        prospectiveSchedulingRisk: 'צפיפות תזמון מגבירה סיכון לתיקונים ברגע האחרון',
        breakingAdopted: (n) => `${n} טקסטים אומצו — הפרלמנט מדגים יכולת חקיקתית`,
        breakingEvents: (n) => `${n} אירועים פרלמנטריים — מעורבות מוסדית פעילה`,
        breakingAnomalyWeakness: 'חריגות הצבעה זוהו — חוסר יציבות קואליציוני אפשרי',
        breakingNoProcedures: 'אין הליכי חקיקה חדשים — תנופה מוגבלת',
        breakingProceduresActive: (n) => `${n} הליכים מתקדמים — צינור החקיקה פעיל`,
        breakingCoalitionOpportunity: 'דינמיקת הקואליציה משתנה — הזדמנויות ברית חדשות צצות',
        breakingAnomalyThreat: 'חריגות שזוהו עשויות לסמן שינוי פוליטי עמוק יותר',
        breakingRapidEvents: 'אירועים המתפתחים במהירות עלולים לעלות על יכולת התגובה החקיקתית',
        propositionsHealthStrong: (pct) => `בריאות הצינור ב-${pct}% — ניהול חקיקתי חזק`,
        propositionsThroughputGood: (n) => `קצב תפוקה ${n} — קצב עיבוד בריא`,
        propositionsHealthWeak: (pct) => `בריאות הצינור ב-${pct}% — סיכון לעומס חקיקתי`,
        propositionsThroughputLow: (n) => `תפוקה נמוכה (${n}) — עיבוד איטי מעכב יישום מדיניות`,
        propositionsPrioritisation: 'תעדוף תיקי דגל יכול לשפר את יעילות הצינור',
        propositionsTrilogueAcceleration: 'האצת טרילוג בתיקים בשלים יכולה להגביר את התפוקה',
        propositionsCriticalCongestion: 'עומס קריטי עלול לאלץ נטישת תיקי חקיקה',
        propositionsOverlapping: 'לוחות זמנים חופפים ליישום מעמיסים על יכולת ההעברה של המדינות החברות',
        committeeActive: (active, total) => `${active} מתוך ${total} ועדות מייצרות מסמכים באופן פעיל`,
        committeeDocuments: (n) => `${n} מסמכים הופקו — תפוקה חקיקתית חזקה`,
        committeeInactive: (n) => `${n} ועדות ללא פעילות מסמכים אחרונה`,
        committeeCrossCollaboration: 'שיתוף פעולה בין ועדות בתיקי מדיניות אופקיים יכול להגביר את ההשפעה',
        committeeHearings: 'שימועי ועדות מספקים פלטפורמה למעורבות בעלי עניין מומחים',
        committeeLowActivity: 'פעילות ועדות נמוכה מסכנת צווארי בקבוק חקיקתיים בהמשך',
        committeeCompetingPriorities: 'סדרי עדיפויות פוליטיים מתחרים עלולים לדלל את מיקוד הוועדות',
    },
    ja: {
        votingHighCohesion: (n) => `${n}つの政治グループが80%以上の結束率 — 規律ある投票ブロック`,
        votingAdopted: (n) => `${n}件のテキストが採択 — 立法生産性を示す`,
        votingActiveVotes: (n) => `${n}件の投票が記録 — 活発な本会議参加`,
        votingLowCohesion: (n) => `${n}つのグループが50%未満の結束率 — 内部分裂が交渉力を弱める`,
        votingAnomalies: (n) => `${n}件の投票異常を検出 — 予測不能な連立行動を示唆`,
        votingCrossParty: '特定の法案における超党派同盟がより広い合意を構築できる',
        votingDiverseGroups: (n) => `${n}つの活動的な政治グループ — 多様な連立形成の可能性`,
        votingHighSeverity: (n) => `${n}件の重大な異常 — 連立の分裂リスク`,
        votingShiftingAlliances: '変動する同盟関係が主要案件の立法進展を遅らせる可能性',
        prospectiveEvents: (n) => `${n}件の本会議イベントが予定 — 活発な立法議題`,
        prospectiveCommittees: (n) => `${n}件の委員会会議 — 幅広い政策関与`,
        prospectiveBottlenecks: (n) => `${n}件の立法手続きがボトルネックリスクに直面`,
        prospectiveHighDensity: (n) => `高いイベント密度（${n}件）が討論時間の圧縮リスク`,
        prospectiveDocuments: (n) => `${n}件の文書が審議中 — 立法の勢い`,
        prospectiveQuestions: (n) => `${n}件の議会質問 — MEPの市民的懸念への関与`,
        prospectiveBottleneckRisk: 'ボトルネック手続きが手続き上の近道を強制するか主要案件を延期させる可能性',
        prospectiveSchedulingRisk: 'スケジュール密度が直前の修正案リスクを高める',
        breakingAdopted: (n) => `${n}件のテキストが採択 — 議会が立法能力を発揮`,
        breakingEvents: (n) => `${n}件の議会イベント — 活発な制度的関与`,
        breakingAnomalyWeakness: '投票異常を検出 — 連立の不安定性の可能性',
        breakingNoProcedures: '新しい立法手続きなし — 限定的なパイプラインの勢い',
        breakingProceduresActive: (n) => `${n}件の手続きが進行中 — 立法パイプラインが活発`,
        breakingCoalitionOpportunity: '連立力学が変化中 — 新しい同盟機会が出現',
        breakingAnomalyThreat: '検出された異常がより深い政治的再編を示唆する可能性',
        breakingRapidEvents: '急速に発展する出来事が立法対応能力を超える可能性',
        propositionsHealthStrong: (pct) => `パイプライン健全性${pct}% — 強力な立法管理`,
        propositionsThroughputGood: (n) => `スループット率${n} — 健全な処理ペース`,
        propositionsHealthWeak: (pct) => `パイプライン健全性${pct}% — 立法渋滞リスク`,
        propositionsThroughputLow: (n) => `低スループット（${n}） — 遅い処理が政策実施を遅延`,
        propositionsPrioritisation: '主要法案の優先順位付けがパイプライン効率を向上できる',
        propositionsTrilogueAcceleration: '成熟した案件のトリローグ加速がスループットを向上できる',
        propositionsCriticalCongestion: '重大なパイプライン渋滞が立法案件の放棄を強いる可能性',
        propositionsOverlapping: '重複する実施タイムラインが加盟国の国内法化能力を圧迫',
        committeeActive: (active, total) => `${total}委員会中${active}が活発に文書を作成`,
        committeeDocuments: (n) => `${n}件の文書が作成 — 強力な立法産出`,
        committeeInactive: (n) => `${n}つの委員会が最近の文書活動なし`,
        committeeCrossCollaboration: '水平的な政策案件における委員会間協力が影響力を高められる',
        committeeHearings: '委員会公聴会が専門家ステークホルダーの参加のためのプラットフォームを提供',
        committeeLowActivity: '低い委員会活動が下流の立法ボトルネックリスク',
        committeeCompetingPriorities: '競合する政策優先事項が委員会の焦点を薄める可能性',
    },
    ko: {
        votingHighCohesion: (n) => `${n}개 정치 그룹이 80% 이상 결속력 — 규율 있는 투표 블록`,
        votingAdopted: (n) => `${n}건 텍스트 채택 — 입법 생산성 입증`,
        votingActiveVotes: (n) => `${n}건 투표 기록 — 활발한 본회의 참여`,
        votingLowCohesion: (n) => `${n}개 그룹이 50% 미만 결속력 — 내부 분열이 교섭력 약화`,
        votingAnomalies: (n) => `${n}건 투표 이상 감지 — 예측 불가능한 연합 행동 신호`,
        votingCrossParty: '특정 법안에서의 초당적 동맹이 더 넓은 합의를 구축할 수 있음',
        votingDiverseGroups: (n) => `${n}개 활동 정치 그룹 — 다양한 연합 형성 가능성`,
        votingHighSeverity: (n) => `${n}건 심각한 이상 — 연합 분열 위험`,
        votingShiftingAlliances: '변화하는 동맹이 주요 안건의 입법 진전을 지연시킬 수 있음',
        prospectiveEvents: (n) => `${n}건 본회의 일정 — 활발한 입법 의제`,
        prospectiveCommittees: (n) => `${n}건 위원회 회의 — 광범위한 정책 참여`,
        prospectiveBottlenecks: (n) => `${n}건 입법 절차 병목 위험`,
        prospectiveHighDensity: (n) => `높은 일정 밀도(${n}건)로 토론 시간 압축 위험`,
        prospectiveDocuments: (n) => `${n}건 문서 검토 중 — 입법 모멘텀`,
        prospectiveQuestions: (n) => `${n}건 의회 질의 — MEP의 시민 관심사 참여`,
        prospectiveBottleneckRisk: '병목 절차가 절차적 편법을 강제하거나 주요 안건을 연기할 수 있음',
        prospectiveSchedulingRisk: '일정 밀도가 막바지 수정안 위험을 높임',
        breakingAdopted: (n) => `${n}건 텍스트 채택 — 의회가 입법 능력 입증`,
        breakingEvents: (n) => `${n}건 의회 행사 — 활발한 제도적 참여`,
        breakingAnomalyWeakness: '투표 이상 감지 — 잠재적 연합 불안정성',
        breakingNoProcedures: '새로운 입법 절차 없음 — 제한된 파이프라인 모멘텀',
        breakingProceduresActive: (n) => `${n}건 절차 진행 중 — 입법 파이프라인 활성`,
        breakingCoalitionOpportunity: '연합 역학 변화 — 새로운 동맹 기회 출현',
        breakingAnomalyThreat: '감지된 이상이 더 깊은 정치적 재편을 시사할 수 있음',
        breakingRapidEvents: '빠르게 전개되는 사건이 입법 대응 능력을 초과할 수 있음',
        propositionsHealthStrong: (pct) => `파이프라인 건전성 ${pct}% — 강력한 입법 관리`,
        propositionsThroughputGood: (n) => `처리량 ${n} — 건전한 처리 속도`,
        propositionsHealthWeak: (pct) => `파이프라인 건전성 ${pct}% — 입법 정체 위험`,
        propositionsThroughputLow: (n) => `낮은 처리량(${n}) — 느린 처리가 정책 시행 지연`,
        propositionsPrioritisation: '주력 안건 우선순위 지정이 파이프라인 효율을 개선할 수 있음',
        propositionsTrilogueAcceleration: '성숙한 안건의 3자 협의 가속이 처리량을 높일 수 있음',
        propositionsCriticalCongestion: '심각한 파이프라인 정체가 입법 안건 포기를 강제할 수 있음',
        propositionsOverlapping: '중복되는 시행 일정이 회원국 전환 역량을 압박',
        committeeActive: (active, total) => `${total}개 위원회 중 ${active}개가 활발히 문서 생산`,
        committeeDocuments: (n) => `${n}건 문서 생산 — 강력한 입법 산출`,
        committeeInactive: (n) => `${n}개 위원회가 최근 문서 활동 없음`,
        committeeCrossCollaboration: '수평적 정책 안건에서 위원회 간 협력이 영향력을 높일 수 있음',
        committeeHearings: '위원회 청문회가 전문 이해관계자 참여를 위한 플랫폼 제공',
        committeeLowActivity: '낮은 위원회 활동이 하류 입법 병목 위험',
        committeeCompetingPriorities: '경쟁하는 정책 우선순위가 위원회 초점을 희석시킬 수 있음',
    },
    zh: {
        votingHighCohesion: (n) => `${n}个政治团体凝聚力超过80%——纪律严明的投票集团`,
        votingAdopted: (n) => `${n}项文本获通过——展示立法生产力`,
        votingActiveVotes: (n) => `${n}次投票记录——积极的全会参与`,
        votingLowCohesion: (n) => `${n}个团体凝聚力低于50%——内部分歧削弱谈判力`,
        votingAnomalies: (n) => `${n}项投票异常被检测——表明不可预测的联盟行为`,
        votingCrossParty: '在特定立法上的跨党派联盟可以建立更广泛的共识',
        votingDiverseGroups: (n) => `${n}个活跃政治团体——多元化的联盟组建可能性`,
        votingHighSeverity: (n) => `${n}项严重异常——联盟分裂风险`,
        votingShiftingAlliances: '不断变化的联盟可能延缓关键文件的立法进展',
        prospectiveEvents: (n) => `${n}场全会活动已排期——积极的立法议程`,
        prospectiveCommittees: (n) => `${n}场委员会会议——广泛的政策参与`,
        prospectiveBottlenecks: (n) => `${n}项立法程序面临瓶颈风险`,
        prospectiveHighDensity: (n) => `高活动密度（${n}项）存在压缩辩论时间风险`,
        prospectiveDocuments: (n) => `${n}份文件正在审议——立法动力`,
        prospectiveQuestions: (n) => `${n}项议会质询——议员关注公民诉求`,
        prospectiveBottleneckRisk: '瓶颈程序可能迫使采取程序性捷径或推迟关键文件',
        prospectiveSchedulingRisk: '排程密度增加了最后时刻修正案的风险',
        breakingAdopted: (n) => `${n}项文本获通过——议会展示立法能力`,
        breakingEvents: (n) => `${n}场议会活动——积极的机构参与`,
        breakingAnomalyWeakness: '投票异常被检测——潜在的联盟不稳定',
        breakingNoProcedures: '无新立法程序——有限的管道动力',
        breakingProceduresActive: (n) => `${n}项程序正在推进——立法管道活跃`,
        breakingCoalitionOpportunity: '联盟动态正在转变——新的联盟机会正在出现',
        breakingAnomalyThreat: '检测到的异常可能预示更深层的政治重组',
        breakingRapidEvents: '快速发展的事件可能超出立法应对能力',
        propositionsHealthStrong: (pct) => `管道健康度${pct}%——强有力的立法管理`,
        propositionsThroughputGood: (n) => `吞吐率${n}——健康的处理节奏`,
        propositionsHealthWeak: (pct) => `管道健康度${pct}%——立法拥堵风险`,
        propositionsThroughputLow: (n) => `低吞吐量（${n}）——缓慢处理延迟政策执行`,
        propositionsPrioritisation: '优先处理旗舰文件可以提高管道效率',
        propositionsTrilogueAcceleration: '加速成熟文件的三方谈判可以提高吞吐量',
        propositionsCriticalCongestion: '严重管道拥堵可能迫使放弃立法文件',
        propositionsOverlapping: '重叠的实施时间表给成员国转化能力带来压力',
        committeeActive: (active, total) => `${total}个委员会中${active}个积极产出文件`,
        committeeDocuments: (n) => `${n}份文件已产出——强劲的立法产出`,
        committeeInactive: (n) => `${n}个委员会近期无文件活动`,
        committeeCrossCollaboration: '跨委员会在横向政策文件上的合作可以增强影响力',
        committeeHearings: '委员会听证会为专家利益相关方参与提供平台',
        committeeLowActivity: '低委员会活动存在下游立法瓶颈风险',
        committeeCompetingPriorities: '相互竞争的政策优先事项可能稀释委员会焦点',
    },
};
// ─── Dashboard Builder Strings ───────────────────────────────────────────────
/**
 * Localized strings used by the 5 Dashboard builder functions in analysis-builders.
 * Panel titles, metric labels, and chart labels.
 */
//# sourceMappingURL=swot.js.map