// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/DA
 * @description DA dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** DA dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_DA: DashboardBuilderStrings = {
  votingOverview: 'Afstemningsoversigt',
  totalVotes: 'Samlede stemmer',
  adopted: 'Vedtaget',
  rejected: 'Afvist',
  anomalies: 'Anomalier',
  politicalGroupCohesion: 'Politisk gruppesamhørighed',
  groupCohesionRates: 'Gruppesamhørighed',
  cohesionPct: 'Samhørighed %',
  scheduledActivity: 'Planlagt aktivitet',
  plenaryEvents: 'Plenarmøder',
  committeeMeetings: 'Udvalgsmøder',
  documents: 'Dokumenter',
  pipelineProcedures: 'Pipeline-procedurer',
  parliamentaryQuestions: 'Parlamentariske spørgsmål',
  questionsFiled: 'Indsendte spørgsmål',
  bottleneckProcedures: 'Flaskehalsprocedurer',
  feedActivity: 'Feed-aktivitet',
  adoptedTexts: 'Vedtagne tekster',
  events: 'Begivenheder',
  procedures: 'Procedurer',
  mepUpdates: 'MEP-opdateringer',
  activitySummary: 'Aktivitetsoversigt',
  totalItems: 'Samlede elementer',
  feedBreakdown: 'Feed-fordeling',
  items: 'Elementer',
  pipelineHealth: 'Pipeline-sundhed',
  healthScore: 'Sundhedsscore',
  throughput: 'Gennemløb',
  status: 'Status',
  pipelineStrong: 'Stærk',
  pipelineModerate: 'Moderat',
  pipelineWeak: 'Svag',
  committeeOverview: 'Udvalgsoversigt',
  totalCommittees: 'Samlede udvalg',
  activeCommittees: 'Aktive udvalg',
  activityRate: 'Aktivitetsrate',
  documentsProduced: 'Producerede dokumenter',
  documentOutputByCommittee: 'Dokumentproduktion per udvalg',
  documentsPerCommittee: 'Dokumenter per udvalg',
  coalitionAlignment: 'Koalitionsafstemning',
  alignmentScore: 'Indretningsscore',
  votingBlocs: 'Afstemningsblokke',
  coalitionShift: 'Koalitionsskift',
  coalitionStrengthening: 'Styrkelse',
  coalitionWeakening: 'Svækkelse',
  coalitionStable: 'Stabil',
  coalitionRadarChart: 'Koalitionsradar',
  pipelineStatus: 'Pipeline-status',
  onTrack: 'På sporet',
  delayed: 'Forsinket',
  blocked: 'Blokeret',
  fastTracked: 'Fremskyndet',
  pipelineStatusChart: 'Pipeline-statusdiagram',
  trendAnalysis: 'Trendanalyse',
  weekOverWeek: 'Uge-til-uge',
  monthOverMonth: 'Måned-til-måned',
  trendImproving: 'Forbedring',
  trendDeclining: 'Fald',
  trendStableLabel: 'Stabil',
  activityTrendChart: 'Aktivitetstrend',
  stakeholderImpact: 'Interessentpåvirkning',
  impactScore: 'Påvirkningsscore',
  impactPositive: 'Positiv',
  impactNegative: 'Negativ',
  impactNeutral: 'Neutral',
};
