// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/DE
 * @description DE dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** DE dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_DE: DashboardBuilderStrings = {
  votingOverview: 'Abstimmungsübersicht',
  totalVotes: 'Gesamtabstimmungen',
  adopted: 'Angenommen',
  rejected: 'Abgelehnt',
  anomalies: 'Anomalien',
  politicalGroupCohesion: 'Fraktionskohäsion',
  groupCohesionRates: 'Fraktionskohäsionsraten',
  cohesionPct: 'Kohäsion %',
  scheduledActivity: 'Geplante Aktivität',
  plenaryEvents: 'Plenarveranstaltungen',
  committeeMeetings: 'Ausschusssitzungen',
  documents: 'Dokumente',
  pipelineProcedures: 'Pipeline-Verfahren',
  parliamentaryQuestions: 'Parlamentarische Anfragen',
  questionsFiled: 'Eingereichte Anfragen',
  bottleneckProcedures: 'Engpassverfahren',
  feedActivity: 'Feed-Aktivität',
  adoptedTexts: 'Angenommene Texte',
  events: 'Veranstaltungen',
  procedures: 'Verfahren',
  mepUpdates: 'MdEP-Aktualisierungen',
  activitySummary: 'Aktivitätszusammenfassung',
  totalItems: 'Gesamtelemente',
  feedBreakdown: 'Feed-Aufschlüsselung',
  items: 'Elemente',
  pipelineHealth: 'Pipeline-Gesundheit',
  healthScore: 'Gesundheitswert',
  throughput: 'Durchsatz',
  status: 'Status',
  pipelineStrong: 'Stark',
  pipelineModerate: 'Mäßig',
  pipelineWeak: 'Schwach',
  committeeOverview: 'Ausschussübersicht',
  totalCommittees: 'Gesamtausschüsse',
  activeCommittees: 'Aktive Ausschüsse',
  activityRate: 'Aktivitätsrate',
  documentsProduced: 'Produzierte Dokumente',
  documentOutputByCommittee: 'Dokumentenproduktion je Ausschuss',
  documentsPerCommittee: 'Dokumente je Ausschuss',
  coalitionAlignment: 'Koalitionsausrichtung',
  alignmentScore: 'Ausrichtungswert',
  votingBlocs: 'Abstimmungsblöcke',
  coalitionShift: 'Koalitionswandel',
  coalitionStrengthening: 'Stärkung',
  coalitionWeakening: 'Schwächung',
  coalitionStable: 'Stabil',
  coalitionRadarChart: 'Koalitionsradar',
  pipelineStatus: 'Pipeline-Status',
  onTrack: 'Im Zeitplan',
  delayed: 'Verzögert',
  blocked: 'Blockiert',
  fastTracked: 'Beschleunigt',
  pipelineStatusChart: 'Pipeline-Statusdiagramm',
  trendAnalysis: 'Trendanalyse',
  weekOverWeek: 'Woche-zu-Woche',
  monthOverMonth: 'Monat-zu-Monat',
  trendImproving: 'Verbesserung',
  trendDeclining: 'Rückgang',
  trendStableLabel: 'Stabil',
  activityTrendChart: 'Aktivitätstrend',
  stakeholderImpact: 'Stakeholder-Einfluss',
  impactScore: 'Einflusswert',
  impactPositive: 'Positiv',
  impactNegative: 'Negativ',
  impactNeutral: 'Neutral',
};
