// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/ES
 * @description ES dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** ES dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_ES: DashboardBuilderStrings = {
  votingOverview: 'Resumen de votaciones',
  totalVotes: 'Total de votos',
  adopted: 'Adoptados',
  rejected: 'Rechazados',
  anomalies: 'Anomalías',
  politicalGroupCohesion: 'Cohesión de grupos políticos',
  groupCohesionRates: 'Tasas de cohesión de grupos',
  cohesionPct: 'Cohesión %',
  scheduledActivity: 'Actividad programada',
  plenaryEvents: 'Eventos plenarios',
  committeeMeetings: 'Reuniones de comisión',
  documents: 'Documentos',
  pipelineProcedures: 'Procedimientos en curso',
  parliamentaryQuestions: 'Preguntas parlamentarias',
  questionsFiled: 'Preguntas presentadas',
  bottleneckProcedures: 'Procedimientos con cuello de botella',
  feedActivity: 'Actividad del feed',
  adoptedTexts: 'Textos adoptados',
  events: 'Eventos',
  procedures: 'Procedimientos',
  mepUpdates: 'Actualizaciones de eurodiputados',
  activitySummary: 'Resumen de actividad',
  totalItems: 'Total de elementos',
  feedBreakdown: 'Desglose del feed',
  items: 'Elementos',
  pipelineHealth: 'Salud del pipeline',
  healthScore: 'Puntuación de salud',
  throughput: 'Rendimiento',
  status: 'Estado',
  pipelineStrong: 'Fuerte',
  pipelineModerate: 'Moderado',
  pipelineWeak: 'Débil',
  committeeOverview: 'Resumen de comisiones',
  totalCommittees: 'Total de comisiones',
  activeCommittees: 'Comisiones activas',
  activityRate: 'Tasa de actividad',
  documentsProduced: 'Documentos producidos',
  documentOutputByCommittee: 'Producción documental por comisión',
  documentsPerCommittee: 'Documentos por comisión',
  coalitionAlignment: 'Alineación de coalición',
  alignmentScore: 'Puntuación de alineación',
  votingBlocs: 'Bloques de votación',
  coalitionShift: 'Cambio de coalición',
  coalitionStrengthening: 'Fortalecimiento',
  coalitionWeakening: 'Debilitamiento',
  coalitionStable: 'Estable',
  coalitionRadarChart: 'Radar de coalición',
  pipelineStatus: 'Estado del proceso',
  onTrack: 'En plazo',
  delayed: 'Retrasado',
  blocked: 'Bloqueado',
  fastTracked: 'Acelerado',
  pipelineStatusChart: 'Diagrama de proceso',
  trendAnalysis: 'Análisis de tendencias',
  weekOverWeek: 'Semana a semana',
  monthOverMonth: 'Mes a mes',
  trendImproving: 'Mejora',
  trendDeclining: 'Declive',
  trendStableLabel: 'Estable',
  activityTrendChart: 'Tendencia de actividad',
  stakeholderImpact: 'Impacto en partes interesadas',
  impactScore: 'Puntuación de impacto',
  impactPositive: 'Positivo',
  impactNegative: 'Negativo',
  impactNeutral: 'Neutral',
};
