// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/FI
 * @description FI dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** FI dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_FI: DashboardBuilderStrings = {
  votingOverview: 'Äänestyskatsaus',
  totalVotes: 'Äänestykset yhteensä',
  adopted: 'Hyväksytyt',
  rejected: 'Hylätyt',
  anomalies: 'Poikkeamat',
  politicalGroupCohesion: 'Poliittisten ryhmien yhtenäisyys',
  groupCohesionRates: 'Ryhmäyhtenäisyys',
  cohesionPct: 'Yhtenäisyys %',
  scheduledActivity: 'Aikataulutettu toiminta',
  plenaryEvents: 'Täysistuntotapahtumat',
  committeeMeetings: 'Valiokuntakokoukset',
  documents: 'Asiakirjat',
  pipelineProcedures: 'Pipeline-menettelyt',
  parliamentaryQuestions: 'Parlamentaariset kysymykset',
  questionsFiled: 'Jätetyt kysymykset',
  bottleneckProcedures: 'Pullonkaulamenettelyt',
  feedActivity: 'Syöteaktiivisuus',
  adoptedTexts: 'Hyväksytyt tekstit',
  events: 'Tapahtumat',
  procedures: 'Menettelyt',
  mepUpdates: 'MEP-päivitykset',
  activitySummary: 'Toimintayhteenveto',
  totalItems: 'Kohteet yhteensä',
  feedBreakdown: 'Syötejakauma',
  items: 'Kohteet',
  pipelineHealth: 'Pipeline-terveys',
  healthScore: 'Terveyspisteet',
  throughput: 'Läpäisyaste',
  status: 'Tila',
  pipelineStrong: 'Vahva',
  pipelineModerate: 'Kohtalainen',
  pipelineWeak: 'Heikko',
  committeeOverview: 'Valiokuntakatsaus',
  totalCommittees: 'Valiokunnat yhteensä',
  activeCommittees: 'Aktiiviset valiokunnat',
  activityRate: 'Aktiivisuusaste',
  documentsProduced: 'Tuotetut asiakirjat',
  documentOutputByCommittee: 'Asiakirjatuotanto valiokunnittain',
  documentsPerCommittee: 'Asiakirjat per valiokunta',
  coalitionAlignment: 'Koalition suuntaus',
  alignmentScore: 'Suuntauspisteet',
  votingBlocs: 'Äänestysblokki',
  coalitionShift: 'Koalitiomuutos',
  coalitionStrengthening: 'Vahvistuminen',
  coalitionWeakening: 'Heikkeneminen',
  coalitionStable: 'Vakaa',
  coalitionRadarChart: 'Koalitiotutkataulukko',
  pipelineStatus: 'Pipeline-tila',
  onTrack: 'Aikataulussa',
  delayed: 'Viivästynyt',
  blocked: 'Estetty',
  fastTracked: 'Pikakaistalla',
  pipelineStatusChart: 'Pipeline-tila kaavio',
  trendAnalysis: 'Trendikatsaus',
  weekOverWeek: 'Viikko edelliseen',
  monthOverMonth: 'Kuukausi edelliseen',
  trendImproving: 'Paranee',
  trendDeclining: 'Heikentyy',
  trendStableLabel: 'Vakaa',
  activityTrendChart: 'Toimintakäyrä',
  stakeholderImpact: 'Sidosryhmävaikutus',
  impactScore: 'Vaikutuspisteet',
  impactPositive: 'Positiivinen',
  impactNegative: 'Negatiivinen',
  impactNeutral: 'Neutraali',
};
