// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/FR
 * @description FR dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** FR dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_FR: DashboardBuilderStrings = {
  votingOverview: 'Aperçu des votes',
  totalVotes: 'Total des votes',
  adopted: 'Adoptés',
  rejected: 'Rejetés',
  anomalies: 'Anomalies',
  politicalGroupCohesion: 'Cohésion des groupes politiques',
  groupCohesionRates: 'Taux de cohésion des groupes',
  cohesionPct: 'Cohésion %',
  scheduledActivity: 'Activité programmée',
  plenaryEvents: 'Événements pléniers',
  committeeMeetings: 'Réunions de commission',
  documents: 'Documents',
  pipelineProcedures: 'Procédures en cours',
  parliamentaryQuestions: 'Questions parlementaires',
  questionsFiled: 'Questions déposées',
  bottleneckProcedures: "Procédures en goulot d'étranglement",
  feedActivity: 'Activité du flux',
  adoptedTexts: 'Textes adoptés',
  events: 'Événements',
  procedures: 'Procédures',
  mepUpdates: 'Mises à jour des députés',
  activitySummary: "Résumé d'activité",
  totalItems: 'Total des éléments',
  feedBreakdown: 'Répartition du flux',
  items: 'Éléments',
  pipelineHealth: 'Santé du pipeline',
  healthScore: 'Score de santé',
  throughput: 'Débit',
  status: 'Statut',
  pipelineStrong: 'Fort',
  pipelineModerate: 'Modéré',
  pipelineWeak: 'Faible',
  committeeOverview: 'Aperçu des commissions',
  totalCommittees: 'Total des commissions',
  activeCommittees: 'Commissions actives',
  activityRate: "Taux d'activité",
  documentsProduced: 'Documents produits',
  documentOutputByCommittee: 'Production documentaire par commission',
  documentsPerCommittee: 'Documents par commission',
  coalitionAlignment: 'Alignement de coalition',
  alignmentScore: "Score d'alignement",
  votingBlocs: 'Blocs de vote',
  coalitionShift: 'Évolution de coalition',
  coalitionStrengthening: 'Renforcement',
  coalitionWeakening: 'Affaiblissement',
  coalitionStable: 'Stable',
  coalitionRadarChart: 'Radar de coalition',
  pipelineStatus: 'État du pipeline',
  onTrack: 'Dans les délais',
  delayed: 'Retardé',
  blocked: 'Bloqué',
  fastTracked: 'Accéléré',
  pipelineStatusChart: 'Diagramme du pipeline',
  trendAnalysis: 'Analyse des tendances',
  weekOverWeek: 'Semaine sur semaine',
  monthOverMonth: 'Mois sur mois',
  trendImproving: 'Amélioration',
  trendDeclining: 'Déclin',
  trendStableLabel: 'Stable',
  activityTrendChart: "Tendance d'activité",
  stakeholderImpact: 'Impact sur les parties prenantes',
  impactScore: "Score d'impact",
  impactPositive: 'Positif',
  impactNegative: 'Négatif',
  impactNeutral: 'Neutre',
};
