// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/HE
 * @description HE dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** HE dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_HE: DashboardBuilderStrings = {
  votingOverview: 'סקירת הצבעות',
  totalVotes: 'סך ההצבעות',
  adopted: 'אומצו',
  rejected: 'נדחו',
  anomalies: 'חריגות',
  politicalGroupCohesion: 'לכידות קבוצות פוליטיות',
  groupCohesionRates: 'שיעורי לכידות קבוצתית',
  cohesionPct: 'לכידות %',
  scheduledActivity: 'פעילות מתוכננת',
  plenaryEvents: 'אירועי מליאה',
  committeeMeetings: 'ישיבות ועדה',
  documents: 'מסמכים',
  pipelineProcedures: 'הליכי צינור',
  parliamentaryQuestions: 'שאילתות פרלמנטריות',
  questionsFiled: 'שאילתות שהוגשו',
  bottleneckProcedures: 'הליכי צוואר בקבוק',
  feedActivity: 'פעילות פיד',
  adoptedTexts: 'טקסטים שאומצו',
  events: 'אירועים',
  procedures: 'הליכים',
  mepUpdates: 'עדכוני חברי פרלמנט',
  activitySummary: 'סיכום פעילות',
  totalItems: 'סך הפריטים',
  feedBreakdown: 'פירוט פיד',
  items: 'פריטים',
  pipelineHealth: 'בריאות צינור',
  healthScore: 'ציון בריאות',
  throughput: 'תפוקה',
  status: 'מצב',
  pipelineStrong: 'חזק',
  pipelineModerate: 'בינוני',
  pipelineWeak: 'חלש',
  committeeOverview: 'סקירת ועדות',
  totalCommittees: 'סך הוועדות',
  activeCommittees: 'ועדות פעילות',
  activityRate: 'שיעור פעילות',
  documentsProduced: 'מסמכים שהופקו',
  documentOutputByCommittee: 'תפוקת מסמכים לפי ועדה',
  documentsPerCommittee: 'מסמכים לכל ועדה',
  coalitionAlignment: 'יישור קואליציה',
  alignmentScore: 'ציון יישור',
  votingBlocs: 'גושי הצבעה',
  coalitionShift: 'שינוי קואליציוני',
  coalitionStrengthening: 'התחזקות',
  coalitionWeakening: 'התחלשות',
  coalitionStable: 'יציב',
  coalitionRadarChart: 'מכ"ם קואליציוני',
  pipelineStatus: 'סטטוס צינור',
  onTrack: 'על המסלול',
  delayed: 'מאוחר',
  blocked: 'חסום',
  fastTracked: 'מסלול מהיר',
  pipelineStatusChart: 'תרשים צינור',
  trendAnalysis: 'ניתוח מגמות',
  weekOverWeek: 'שבוע לשבוע',
  monthOverMonth: 'חודש לחודש',
  trendImproving: 'שיפור',
  trendDeclining: 'ירידה',
  trendStableLabel: 'יציב',
  activityTrendChart: 'מגמת פעילות',
  stakeholderImpact: 'השפעה על בעלי עניין',
  impactScore: 'ציון השפעה',
  impactPositive: 'חיובי',
  impactNegative: 'שלילי',
  impactNeutral: 'ניטרלי',
};
