// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/JA
 * @description JA dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** JA dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_JA: DashboardBuilderStrings = {
  votingOverview: '投票概要',
  totalVotes: '総投票数',
  adopted: '採択',
  rejected: '否決',
  anomalies: '異常',
  politicalGroupCohesion: '政治グループ結束力',
  groupCohesionRates: 'グループ結束率',
  cohesionPct: '結束率 %',
  scheduledActivity: '予定された活動',
  plenaryEvents: '本会議イベント',
  committeeMeetings: '委員会会議',
  documents: '文書',
  pipelineProcedures: 'パイプライン手続き',
  parliamentaryQuestions: '議会質問',
  questionsFiled: '提出された質問',
  bottleneckProcedures: 'ボトルネック手続き',
  feedActivity: 'フィード活動',
  adoptedTexts: '採択テキスト',
  events: 'イベント',
  procedures: '手続き',
  mepUpdates: 'MEP更新',
  activitySummary: '活動サマリー',
  totalItems: '総項目数',
  feedBreakdown: 'フィード内訳',
  items: '項目',
  pipelineHealth: 'パイプライン健全性',
  healthScore: '健全性スコア',
  throughput: 'スループット',
  status: 'ステータス',
  pipelineStrong: '強い',
  pipelineModerate: '中程度',
  pipelineWeak: '弱い',
  committeeOverview: '委員会概要',
  totalCommittees: '委員会総数',
  activeCommittees: '活動中の委員会',
  activityRate: '活動率',
  documentsProduced: '作成された文書',
  documentOutputByCommittee: '委員会別文書産出',
  documentsPerCommittee: '委員会あたりの文書数',
  coalitionAlignment: '連立調整',
  alignmentScore: '調整スコア',
  votingBlocs: '投票ブロック',
  coalitionShift: '連立変化',
  coalitionStrengthening: '強化',
  coalitionWeakening: '弱体化',
  coalitionStable: '安定',
  coalitionRadarChart: '連立レーダー',
  pipelineStatus: 'パイプライン状況',
  onTrack: '予定通り',
  delayed: '遅延',
  blocked: '停滞',
  fastTracked: '加速',
  pipelineStatusChart: 'パイプライン状況図',
  trendAnalysis: 'トレンド分析',
  weekOverWeek: '週次比較',
  monthOverMonth: '月次比較',
  trendImproving: '改善',
  trendDeclining: '低下',
  trendStableLabel: '安定',
  activityTrendChart: '活動トレンド',
  stakeholderImpact: '利害関係者への影響',
  impactScore: '影響スコア',
  impactPositive: 'ポジティブ',
  impactNegative: 'ネガティブ',
  impactNeutral: '中立',
};
