// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/KO
 * @description KO dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** KO dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_KO: DashboardBuilderStrings = {
  votingOverview: '투표 개요',
  totalVotes: '총 투표 수',
  adopted: '채택',
  rejected: '거부',
  anomalies: '이상',
  politicalGroupCohesion: '정치 그룹 결속력',
  groupCohesionRates: '그룹 결속률',
  cohesionPct: '결속률 %',
  scheduledActivity: '예정된 활동',
  plenaryEvents: '본회의 일정',
  committeeMeetings: '위원회 회의',
  documents: '문서',
  pipelineProcedures: '파이프라인 절차',
  parliamentaryQuestions: '의회 질의',
  questionsFiled: '제출된 질의',
  bottleneckProcedures: '병목 절차',
  feedActivity: '피드 활동',
  adoptedTexts: '채택 텍스트',
  events: '행사',
  procedures: '절차',
  mepUpdates: 'MEP 업데이트',
  activitySummary: '활동 요약',
  totalItems: '총 항목 수',
  feedBreakdown: '피드 구성',
  items: '항목',
  pipelineHealth: '파이프라인 건전성',
  healthScore: '건전성 점수',
  throughput: '처리량',
  status: '상태',
  pipelineStrong: '강함',
  pipelineModerate: '보통',
  pipelineWeak: '약함',
  committeeOverview: '위원회 개요',
  totalCommittees: '총 위원회 수',
  activeCommittees: '활동 위원회',
  activityRate: '활동률',
  documentsProduced: '생산된 문서',
  documentOutputByCommittee: '위원회별 문서 산출',
  documentsPerCommittee: '위원회당 문서 수',
  coalitionAlignment: '연립 정렬',
  alignmentScore: '정렬 점수',
  votingBlocs: '투표 블록',
  coalitionShift: '연립 변화',
  coalitionStrengthening: '강화',
  coalitionWeakening: '약화',
  coalitionStable: '안정',
  coalitionRadarChart: '연립 레이더',
  pipelineStatus: '파이프라인 현황',
  onTrack: '정상 진행',
  delayed: '지연',
  blocked: '차단',
  fastTracked: '신속 처리',
  pipelineStatusChart: '파이프라인 현황 차트',
  trendAnalysis: '추세 분석',
  weekOverWeek: '주 대비 주',
  monthOverMonth: '월 대비 월',
  trendImproving: '개선',
  trendDeclining: '하락',
  trendStableLabel: '안정',
  activityTrendChart: '활동 추세',
  stakeholderImpact: '이해관계자 영향',
  impactScore: '영향 점수',
  impactPositive: '긍정적',
  impactNegative: '부정적',
  impactNeutral: '중립',
};
