// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/NL
 * @description NL dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** NL dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_NL: DashboardBuilderStrings = {
  votingOverview: 'Stemoverzicht',
  totalVotes: 'Totaal stemmen',
  adopted: 'Aangenomen',
  rejected: 'Verworpen',
  anomalies: 'Afwijkingen',
  politicalGroupCohesion: 'Fractiecohesie',
  groupCohesionRates: 'Fractiecohesiepercentages',
  cohesionPct: 'Cohesie %',
  scheduledActivity: 'Geplande activiteit',
  plenaryEvents: 'Plenaire evenementen',
  committeeMeetings: 'Commissievergaderingen',
  documents: 'Documenten',
  pipelineProcedures: 'Pipeline-procedures',
  parliamentaryQuestions: 'Parlementaire vragen',
  questionsFiled: 'Ingediende vragen',
  bottleneckProcedures: 'Knelpuntprocedures',
  feedActivity: 'Feedactiviteit',
  adoptedTexts: 'Aangenomen teksten',
  events: 'Evenementen',
  procedures: 'Procedures',
  mepUpdates: 'EP-lid-updates',
  activitySummary: 'Activiteitssamenvatting',
  totalItems: 'Totaal items',
  feedBreakdown: 'Feedverdeling',
  items: 'Items',
  pipelineHealth: 'Pipeline-gezondheid',
  healthScore: 'Gezondheidsscore',
  throughput: 'Doorvoer',
  status: 'Status',
  pipelineStrong: 'Sterk',
  pipelineModerate: 'Matig',
  pipelineWeak: 'Zwak',
  committeeOverview: 'Commissieoverzicht',
  totalCommittees: 'Totaal commissies',
  activeCommittees: 'Actieve commissies',
  activityRate: 'Activiteitspercentage',
  documentsProduced: 'Geproduceerde documenten',
  documentOutputByCommittee: 'Documentproductie per commissie',
  documentsPerCommittee: 'Documenten per commissie',
  coalitionAlignment: 'Coalitieafstemming',
  alignmentScore: 'Afstemmingsscore',
  votingBlocs: 'Stemblokken',
  coalitionShift: 'Coalitieverschuiving',
  coalitionStrengthening: 'Versterking',
  coalitionWeakening: 'Verzwakking',
  coalitionStable: 'Stabiel',
  coalitionRadarChart: 'Coalitieradar',
  pipelineStatus: 'Pipelinestatus',
  onTrack: 'Op schema',
  delayed: 'Vertraagd',
  blocked: 'Geblokkeerd',
  fastTracked: 'Versneld',
  pipelineStatusChart: 'Pipelinestatusdiagram',
  trendAnalysis: 'Trendanalyse',
  weekOverWeek: 'Week-op-week',
  monthOverMonth: 'Maand-op-maand',
  trendImproving: 'Verbetering',
  trendDeclining: 'Achteruitgang',
  trendStableLabel: 'Stabiel',
  activityTrendChart: 'Activiteitstrend',
  stakeholderImpact: 'Stakeholderimpact',
  impactScore: 'Impactscore',
  impactPositive: 'Positief',
  impactNegative: 'Negatief',
  impactNeutral: 'Neutraal',
};
