// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/Dashboard/SV
 * @description SV dashboard-builder strings.
 */

import type { DashboardBuilderStrings } from '../../../types/index.js';

/** SV dashboard-builder strings */
export const DASHBOARD_BUILDER_STRINGS_SV: DashboardBuilderStrings = {
  votingOverview: 'Röstningsöversikt',
  totalVotes: 'Totala röster',
  adopted: 'Antagna',
  rejected: 'Avvisade',
  anomalies: 'Anomalier',
  politicalGroupCohesion: 'Politisk gruppsammanhållning',
  groupCohesionRates: 'Gruppsammanhållning',
  cohesionPct: 'Sammanhållning %',
  scheduledActivity: 'Planerad aktivitet',
  plenaryEvents: 'Plenarsessioner',
  committeeMeetings: 'Utskottsmöten',
  documents: 'Dokument',
  pipelineProcedures: 'Pipelineförfaranden',
  parliamentaryQuestions: 'Parlamentariska frågor',
  questionsFiled: 'Inlämnade frågor',
  bottleneckProcedures: 'Flaskhalsförfaranden',
  feedActivity: 'Flödesaktivitet',
  adoptedTexts: 'Antagna texter',
  events: 'Händelser',
  procedures: 'Förfaranden',
  mepUpdates: 'MEP-uppdateringar',
  activitySummary: 'Aktivitetssammanfattning',
  totalItems: 'Totalt antal',
  feedBreakdown: 'Flödesfördelning',
  items: 'Objekt',
  pipelineHealth: 'Pipelinehälsa',
  healthScore: 'Hälsopoäng',
  throughput: 'Genomströmning',
  status: 'Status',
  pipelineStrong: 'Stark',
  pipelineModerate: 'Måttlig',
  pipelineWeak: 'Svag',
  committeeOverview: 'Utskottsöversikt',
  totalCommittees: 'Totala utskott',
  activeCommittees: 'Aktiva utskott',
  activityRate: 'Aktivitetsgrad',
  documentsProduced: 'Producerade dokument',
  documentOutputByCommittee: 'Dokumentproduktion per utskott',
  documentsPerCommittee: 'Dokument per utskott',
  coalitionAlignment: 'Koalitionsinriktning',
  alignmentScore: 'Inriktningsmätning',
  votingBlocs: 'Röstningsblock',
  coalitionShift: 'Koalitionsskifte',
  coalitionStrengthening: 'Stärks',
  coalitionWeakening: 'Försvagas',
  coalitionStable: 'Stabil',
  coalitionRadarChart: 'Koalitionsradar',
  pipelineStatus: 'Pipelinestatus',
  onTrack: 'På rätt spår',
  delayed: 'Försenad',
  blocked: 'Blockerad',
  fastTracked: 'Snabbspårad',
  pipelineStatusChart: 'Pipelinestatusdiagram',
  trendAnalysis: 'Trendanalys',
  weekOverWeek: 'Vecka-till-vecka',
  monthOverMonth: 'Månad-till-månad',
  trendImproving: 'Förbättras',
  trendDeclining: 'Försämras',
  trendStableLabel: 'Stabil',
  activityTrendChart: 'Aktivitetstrend',
  stakeholderImpact: 'Intressentpåverkan',
  impactScore: 'Påverkanspoäng',
  impactPositive: 'Positiv',
  impactNegative: 'Negativ',
  impactNeutral: 'Neutral',
};
