// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/BreakingStringsEast
 * @description East breaking-news strings.
 */

import type { LanguageMap, BreakingStrings } from '../../types/index.js';
import {
  BRK_WHY_ANOMALIES,
  BRK_WHY_NORMAL,
  BRK_NEUTRAL_REASON,
  BRK_LEGAL_CONSEQUENCE,
  BRK_PROC_CONSEQUENCE,
  BRK_IMPACT_ECONOMIC,
  BRK_IMPACT_SOCIAL,
  BRK_IMPACT_GEO_COALITION,
  BRK_IMPACT_GEO_NORMAL,
  BRK_MISTAKE_DESC,
  BRK_MISTAKE_ALT,
} from './_shared.js';

/** East breaking-news strings */
export const BREAKING_STRINGS_EAST: Pick<LanguageMap<BreakingStrings>, 'he' | 'ja' | 'ko' | 'zh'> = {
  he: {
    breakingBanner: '⚡ חדשות דחופות',
    votingAnomalyIntel: 'חריגות הצבעה — ניתוח מודיעיני',
    coalitionDynamics: 'הערכת דינמיקת קואליציה',
    analyticalReport: 'דוח אנליטי',
    keyMEPInfluence: 'ניתוח השפעת חברי פרלמנט מרכזיים',
    intelligenceBriefing: 'תדרוך מודיעיני',
    votingAnomalyAlert: 'התראת חריגות הצבעה',
    coalitionDynamicsSection: 'דינמיקת קואליציה',
    keyPlayers: 'שחקני מפתח פרלמנטריים',
    placeholderNotice: 'זהו תוכן מציין מיקום שנוצר בזמן ששרת MCP של הפרלמנט האירופי אינו זמין.',
    placeholderLede:
      'מתבצע ניטור של התפתחויות פרלמנטריות משמעותיות. חבר את שרת MCP של הפרלמנט האירופי לקבלת מודיעין בזמן אמת.',
    lede: 'ניתוח מודיעיני משרת MCP של הפרלמנט האירופי זיהה התפתחויות פרלמנטריות משמעותיות הדורשות תשומת לב מיידית',
    feedLede: 'נתוני ההזנה האחרונים של הפרלמנט האירופי מדגישים פעילות פרלמנטרית עדכנית',
    adoptedTextsHeading: 'טקסטים שאומצו לאחרונה',
    recentEventsHeading: 'אירועים פרלמנטריים אחרונים',
    procedureUpdatesHeading: 'עדכוני הליכי חקיקה',
    mepUpdatesHeading: 'עדכוני חברי פרלמנט',
    noFeedDataNotice: 'אין נתוני הזנה עדכניים זמינים מהפרלמנט האירופי.',
    asOf: 'נכון ל-',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `ההתפתחויות האחרונות ב-${date}: ${adopted} טקסטים שאומצו לאחרונה, ${events} אירועים, ${procedures} עדכוני הליכים, ${meps} שינויים בחברי פרלמנט.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'הרוב החקיקתי',
    breakingWinnerReasonFn: (count) => `${count} טקסטים חקיקתיים קודמו בתהליך הפרלמנטרי.`,
    breakingNeutralActor: 'קבוצות האופוזיציה',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'מנהיגי הסיעות',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'אומץ:',
    breakingMEPPrefix: 'חבר פרלמנט:',
    anomalyUnavailable: 'ניתוח מפורט של חריגות הצבעה אינו זמין כעת עקב מגבלות טכניות בנתוני המקור.',
    coalitionUnavailable:
      'הערכה מפורטת של דינמיקת הקואליציה אינה יכולה להיות מוצגת כעת, מכיוון שנתוני הבסיס הנחוצים אינם זמינים זמנית.',
    adoptedTextTypeLabel: 'טקסט שאומץ',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `מציג ${shown} מתוך ${total}`,
  },
  ja: {
    breakingBanner: '⚡ 速報',
    votingAnomalyIntel: '投票異常 — 情報分析',
    coalitionDynamics: '連立動態評価',
    analyticalReport: '分析レポート',
    keyMEPInfluence: '主要MEP影響力分析',
    intelligenceBriefing: 'インテリジェンスブリーフィング',
    votingAnomalyAlert: '投票異常警報',
    coalitionDynamicsSection: '連立動態',
    keyPlayers: '議会の主要人物',
    placeholderNotice:
      'これは欧州議会MCPサーバーが利用できない間に生成されたプレースホルダーコンテンツです。',
    placeholderLede:
      '重大な議会の動きを監視しています。リアルタイムの情報を受信するには、欧州議会MCPサーバーに接続してください。',
    lede: '欧州議会MCPサーバーの情報分析により、即座の注意を要する重大な議会の動きが特定されました',
    feedLede: '欧州議会の最新フィードデータが最近の議会活動を紹介しています',
    adoptedTextsHeading: '最近採択されたテキスト',
    recentEventsHeading: '最近の議会イベント',
    procedureUpdatesHeading: '立法手続きの更新',
    mepUpdatesHeading: 'MEPの更新',
    noFeedDataNotice: '欧州議会からの最新フィードデータはありません。',
    asOf: '現在',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `${date}の最新動向：新たに採択されたテキスト${adopted}件、イベント${events}件、手続き更新${procedures}件、MEP変更${meps}件。`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: '立法多数派',
    breakingWinnerReasonFn: (count) => `${count}件の立法テキストが議会プロセスで進められました。`,
    breakingNeutralActor: '野党グループ',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: '会派院内幹事',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: '採択：',
    breakingMEPPrefix: 'MEP：',
    anomalyUnavailable:
      '投票異常の詳細分析は、ソースデータの技術的な制限により現在利用できません。',
    coalitionUnavailable:
      '連立力学の詳細な評価は、必要な基礎データが一時的に利用できないため、現時点では表示できません。',
    adoptedTextTypeLabel: '採択テキスト',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `${total}件中${shown}件を表示`,
  },
  ko: {
    breakingBanner: '⚡ 속보',
    votingAnomalyIntel: '투표 이상 — 정보 분석',
    coalitionDynamics: '연합 역학 평가',
    analyticalReport: '분석 보고서',
    keyMEPInfluence: '주요 MEP 영향력 분석',
    intelligenceBriefing: '정보 브리핑',
    votingAnomalyAlert: '투표 이상 경보',
    coalitionDynamicsSection: '연합 역학',
    keyPlayers: '의회 핵심 인물',
    placeholderNotice: '유럽 의회 MCP 서버를 사용할 수 없는 동안 생성된 자리 표시자 콘텐츠입니다.',
    placeholderLede:
      '중요한 의회 동향이 모니터링되고 있습니다. 실시간 정보를 수신하려면 유럽 의회 MCP 서버에 연결하세요.',
    lede: '유럽 의회 MCP 서버의 정보 분석에서 즉각적인 주의가 필요한 중요한 의회 동향이 확인되었습니다',
    feedLede: '유럽 의회의 최신 피드 데이터가 최근 의회 활동을 조명합니다',
    adoptedTextsHeading: '최근 채택된 텍스트',
    recentEventsHeading: '최근 의회 이벤트',
    procedureUpdatesHeading: '입법 절차 업데이트',
    mepUpdatesHeading: 'MEP 업데이트',
    noFeedDataNotice: '유럽 의회의 최신 피드 데이터가 없습니다.',
    asOf: '기준',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `${date} 최신 동향: 새로 채택된 텍스트 ${adopted}건, 이벤트 ${events}건, 절차 업데이트 ${procedures}건, MEP 변경 ${meps}건.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: '입법 다수파',
    breakingWinnerReasonFn: (count) =>
      `${count}건의 입법 텍스트가 의회 절차를 통해 진행되었습니다.`,
    breakingNeutralActor: '야당 그룹',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: '정치 그룹 원내총무',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: '채택:',
    breakingMEPPrefix: 'MEP:',
    anomalyUnavailable:
      '투표 이상의 상세 분석은 소스 데이터의 기술적 제한으로 현재 이용할 수 없습니다.',
    coalitionUnavailable:
      '연합 역학의 상세 평가는 필요한 기본 데이터가 일시적으로 이용 불가능하여 현재 표시할 수 없습니다.',
    adoptedTextTypeLabel: '채택 문서',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `총 ${total}개 중 ${shown}개 표시`,
  },
  zh: {
    breakingBanner: '⚡ 突发',
    votingAnomalyIntel: '投票异常 — 情报分析',
    coalitionDynamics: '联盟动态评估',
    analyticalReport: '分析报告',
    keyMEPInfluence: '关键MEP影响力分析',
    intelligenceBriefing: '情报简报',
    votingAnomalyAlert: '投票异常警报',
    coalitionDynamicsSection: '联盟动态',
    keyPlayers: '议会关键人物',
    placeholderNotice: '这是在欧洲议会MCP服务器不可用时生成的占位符内容。',
    placeholderLede: '正在监控重大议会动态。请连接欧洲议会MCP服务器以接收实时情报。',
    lede: '欧洲议会MCP服务器的情报分析已确定需要立即关注的重大议会动态',
    feedLede: '欧洲议会的最新数据动态展示了近期议会活动',
    adoptedTextsHeading: '最近通过的文本',
    recentEventsHeading: '近期议会活动',
    procedureUpdatesHeading: '立法程序更新',
    mepUpdatesHeading: 'MEP更新',
    noFeedDataNotice: '没有来自欧洲议会的最新订阅数据。',
    asOf: '截至',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `${date}最新动态：${adopted}项新通过文本，${events}项活动，${procedures}项程序更新，${meps}项议员变更。`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: '立法多数派',
    breakingWinnerReasonFn: (count) => `${count}项立法文本已通过议会程序推进。`,
    breakingNeutralActor: '反对派团体',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: '政治团体党鞭',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: '通过：',
    breakingMEPPrefix: '议员：',
    anomalyUnavailable: '由于源数据存在技术限制，投票异常的详细分析目前不可用。',
    coalitionUnavailable: '目前无法显示联盟动态的详细评估，因为所需的基础数据暂时不可用。',
    adoptedTextTypeLabel: '通过文本',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `显示 ${shown} / ${total}`,
  },
};
