// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module breaking-strings-eu
 * @description Per-language entries (en, sv, da, no, fi, de, fr) for BREAKING_STRINGS.
 */

import type { LanguageMap, BreakingStrings } from '../../types/index.js';
import {
  BRK_WHY_ANOMALIES,
  BRK_WHY_NORMAL,
  BRK_NEUTRAL_REASON,
  BRK_LEGAL_CONSEQUENCE,
  BRK_PROC_CONSEQUENCE,
  BRK_IMPACT_ECONOMIC,
  BRK_IMPACT_SOCIAL,
  BRK_IMPACT_GEO_COALITION,
  BRK_IMPACT_GEO_NORMAL,
  BRK_MISTAKE_DESC,
  BRK_MISTAKE_ALT,
} from './_shared.js';

export const BREAKING_STRINGS_EU: Pick<
  LanguageMap<BreakingStrings>,
  'en' | 'sv' | 'da' | 'no' | 'fi' | 'de' | 'fr'
> = {
  en: {
    breakingBanner: '⚡ BREAKING',
    votingAnomalyIntel: 'Voting Anomaly Intelligence',
    coalitionDynamics: 'Coalition Dynamics Assessment',
    analyticalReport: 'Analytical Report',
    keyMEPInfluence: 'Key MEP Influence Analysis',
    intelligenceBriefing: 'Intelligence Briefing',
    votingAnomalyAlert: 'Voting Anomaly Alert',
    coalitionDynamicsSection: 'Coalition Dynamics',
    keyPlayers: 'Key Parliamentary Players',
    placeholderNotice:
      'This is placeholder content generated while the European Parliament MCP Server is unavailable. Live intelligence data will appear here when the server is connected.',
    placeholderLede:
      'Significant parliamentary developments are being monitored. Connect the European Parliament MCP Server to receive real-time intelligence on voting anomalies, coalition shifts, and MEP activities.',
    lede: 'Intelligence analysis from the European Parliament MCP Server has identified significant parliamentary developments requiring immediate attention',
    feedLede: 'The latest European Parliament feed data highlights recent parliamentary activity',
    adoptedTextsHeading: 'Recently Adopted Texts',
    recentEventsHeading: 'Recent Parliamentary Events',
    procedureUpdatesHeading: 'Legislative Procedure Updates',
    mepUpdatesHeading: 'MEP Updates',
    noFeedDataNotice: 'No recent feed data available from the European Parliament.',
    asOf: 'as of',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Breaking developments on ${date}: ${adopted} newly adopted texts, ${events} events, ${procedures} procedure updates, ${meps} MEP changes.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Legislative Majority',
    breakingWinnerReasonFn: (count) =>
      `${count} legislative texts have been advanced through the parliamentary process.`,
    breakingNeutralActor: 'Opposition Groups',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Political Group Whips',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Adopted:',
    breakingMEPPrefix: 'MEP:',
    anomalyUnavailable:
      'Detailed voting anomaly analysis is currently unavailable due to technical limitations in the source data.',
    coalitionUnavailable:
      'Detailed coalition dynamics assessment cannot be displayed at this time as the necessary underlying data is temporarily unavailable.',
    adoptedTextTypeLabel: 'Adopted text',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `Showing ${shown} of ${total}`,
  },
  sv: {
    breakingBanner: '⚡ SENASTE NYTT',
    votingAnomalyIntel: 'Röstningsanomalier — Underrättelseanalys',
    coalitionDynamics: 'Bedömning av Koalitionsdynamik',
    analyticalReport: 'Analytisk Rapport',
    keyMEPInfluence: 'Analys av Viktiga MEP-Inflytanden',
    intelligenceBriefing: 'Underrättelserapport',
    votingAnomalyAlert: 'Varning för Röstningsanomalier',
    coalitionDynamicsSection: 'Koalitionsdynamik',
    keyPlayers: 'Parlamentariska Nyckelaktörer',
    placeholderNotice:
      'Detta är platshållarinnehåll genererat medan EU-parlamentets MCP-server är otillgänglig.',
    placeholderLede:
      'Betydande parlamentariska händelser övervakas. Anslut EU-parlamentets MCP-server för att ta emot realtidsinformation.',
    lede: 'Underrättelseanalys från EU-parlamentets MCP-server har identifierat betydande parlamentariska händelser som kräver omedelbar uppmärksamhet',
    feedLede: 'De senaste flödena från Europaparlamentet belyser aktuell parlamentarisk verksamhet',
    adoptedTextsHeading: 'Nyligen Antagna Texter',
    recentEventsHeading: 'Senaste Parlamentariska Händelser',
    procedureUpdatesHeading: 'Uppdateringar av Lagstiftningsförfaranden',
    mepUpdatesHeading: 'Uppdateringar om Ledamöter',
    noFeedDataNotice: 'Inga nya flödesdata tillgängliga från Europaparlamentet.',
    asOf: 'per',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Senaste händelserna ${date}: ${adopted} nyligen antagna texter, ${events} händelser, ${procedures} proceduruppdateringar, ${meps} MEP-ändringar.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Lagstiftande majoritet',
    breakingWinnerReasonFn: (count) =>
      `${count} lagstiftningstexter har drivits fram i den parlamentariska processen.`,
    breakingNeutralActor: 'Oppositionsgrupper',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Partigruppernas piskare',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Antagen:',
    breakingMEPPrefix: 'MEP:',
    anomalyUnavailable:
      'Detaljerad analys av möjliga röstningsavvikelser är för närvarande inte tillgänglig på grund av tekniska begränsningar i källdatan.',
    coalitionUnavailable:
      'Fördjupad bedömning av koalitionsdynamik kan inte visas just nu eftersom nödvändiga underlagsdata tillfälligt saknas.',
    adoptedTextTypeLabel: 'Antagen text',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `Visar ${shown} av ${total}`,
  },
  da: {
    breakingBanner: '⚡ SENESTE NYT',
    votingAnomalyIntel: 'Afstemningsanomali — Efterretningsanalyse',
    coalitionDynamics: 'Vurdering af Koalitionsdynamik',
    analyticalReport: 'Analytisk Rapport',
    keyMEPInfluence: 'Analyse af Vigtige MEP-Indflydelse',
    intelligenceBriefing: 'Efterretningsbriefing',
    votingAnomalyAlert: 'Advarsel om Afstemningsanomalier',
    coalitionDynamicsSection: 'Koalitionsdynamik',
    keyPlayers: 'Parlamentariske Nøgleaktører',
    placeholderNotice:
      'Dette er pladsholderindhold genereret mens Europa-Parlamentets MCP-server er utilgængelig.',
    placeholderLede:
      'Betydelige parlamentariske udviklinger overvåges. Tilslut Europa-Parlamentets MCP-server for at modtage realtidsintelligens.',
    lede: 'Efterretningsanalyse fra Europa-Parlamentets MCP-server har identificeret betydelige parlamentariske udviklinger der kræver øjeblikkelig opmærksomhed',
    feedLede: 'De seneste feeds fra Europa-Parlamentet fremhæver aktuel parlamentarisk aktivitet',
    adoptedTextsHeading: 'Nyligt Vedtagne Tekster',
    recentEventsHeading: 'Seneste Parlamentariske Begivenheder',
    procedureUpdatesHeading: 'Opdateringer af Lovgivningsprocedurer',
    mepUpdatesHeading: 'MEP-Opdateringer',
    noFeedDataNotice: 'Ingen nye feeddata tilgængelige fra Europa-Parlamentet.',
    asOf: 'pr.',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Seneste begivenheder den ${date}: ${adopted} nyvedtagne tekster, ${events} begivenheder, ${procedures} procedureopdateringer, ${meps} MEP-ændringer.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Lovgivningsmæssigt flertal',
    breakingWinnerReasonFn: (count) =>
      `${count} lovgivningstekster er ført frem i den parlamentariske proces.`,
    breakingNeutralActor: 'Oppositionsgrupper',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Partigruppernes piskere',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Vedtaget:',
    breakingMEPPrefix: 'MEP:',
    anomalyUnavailable:
      'Detaljeret analyse af afstemningsanomalier er i øjeblikket ikke tilgængelig på grund af tekniske begrænsninger i kildedata.',
    coalitionUnavailable:
      'Detaljeret vurdering af koalitionsdynamik kan ikke vises i øjeblikket, da de nødvendige underliggende data midlertidigt mangler.',
    adoptedTextTypeLabel: 'Vedtaget tekst',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `Viser ${shown} af ${total}`,
  },
  no: {
    breakingBanner: '⚡ SISTE NYTT',
    votingAnomalyIntel: 'Avstemningsavvik — Etterretningsanalyse',
    coalitionDynamics: 'Vurdering av Koalisjonsdynamikk',
    analyticalReport: 'Analytisk Rapportering',
    keyMEPInfluence: 'Analyse av Viktige MEP-Innflytelse',
    intelligenceBriefing: 'Etterretningsbriefing',
    votingAnomalyAlert: 'Advarsel om Avstemningsavvik',
    coalitionDynamicsSection: 'Koalisjonsdynamikk',
    keyPlayers: 'Parlamentariske Nøkkelaktører',
    placeholderNotice:
      'Dette er plassholder-innhold generert mens Europaparlamentets MCP-server er utilgjengelig.',
    placeholderLede:
      'Betydelige parlamentariske hendelser overvåkes. Koble til Europaparlamentets MCP-server for å motta sanntidsinformasjon.',
    lede: 'Etterretningsanalyse fra Europaparlamentets MCP-server har identifisert betydelige parlamentariske hendelser som krever umiddelbar oppmerksomhet',
    feedLede: 'De siste feedene fra Europaparlamentet belyser nylig parlamentarisk aktivitet',
    adoptedTextsHeading: 'Nylig Vedtatte Tekster',
    recentEventsHeading: 'Siste Parlamentariske Hendelser',
    procedureUpdatesHeading: 'Oppdateringer av Lovgivningsprosedyrer',
    mepUpdatesHeading: 'MEP-Oppdateringer',
    noFeedDataNotice: 'Ingen nye feeddata tilgjengelige fra Europaparlamentet.',
    asOf: 'per',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Siste hendelser ${date}: ${adopted} nylig vedtatte tekster, ${events} hendelser, ${procedures} prosedyreoppdateringer, ${meps} MEP-endringer.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Lovgivningsmessig flertall',
    breakingWinnerReasonFn: (count) =>
      `${count} lovgivningstekster er fremmet i den parlamentariske prosessen.`,
    breakingNeutralActor: 'Opposisjonsgrupper',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Partigruppers innpisker',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Vedtatt:',
    breakingMEPPrefix: 'MEP:',
    anomalyUnavailable:
      'Detaljert analyse av mulige avstemningsavvik er for øyeblikket ikke tilgjengelig på grunn av tekniske begrensninger i kildedataene.',
    coalitionUnavailable:
      'Detaljert vurdering av koalisjonsdynamikk kan ikke vises for øyeblikket siden de nødvendige underliggende dataene midlertidig mangler.',
    adoptedTextTypeLabel: 'Vedtatt tekst',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `Viser ${shown} av ${total}`,
  },
  fi: {
    breakingBanner: '⚡ TUOREET UUTISET',
    votingAnomalyIntel: 'Äänestyspoikkeamat — Tiedusteluanalyysi',
    coalitionDynamics: 'Koalitiodynamiikan Arviointi',
    analyticalReport: 'Analyyttinen Raportti',
    keyMEPInfluence: 'Avain-MEP-vaikutusanalyysi',
    intelligenceBriefing: 'Tiedusteluraportti',
    votingAnomalyAlert: 'Äänestyspoikkeamavaroitus',
    coalitionDynamicsSection: 'Koalitiodynamiikka',
    keyPlayers: 'Parlamentaariset Avainpelaajat',
    placeholderNotice:
      'Tämä on paikkamerkkisisältö, joka on luotu EU-parlamentin MCP-palvelimen ollessa pois käytöstä.',
    placeholderLede:
      'Merkittäviä parlamentaarisia tapahtumia seurataan. Yhdistä EU-parlamentin MCP-palvelimeen reaaliaikaisen tiedon vastaanottamiseksi.',
    lede: 'EU-parlamentin MCP-palvelimen tiedusteluanalyysi on tunnistanut merkittäviä parlamentaarisia tapahtumia, jotka vaativat välitöntä huomiota',
    feedLede:
      'Euroopan parlamentin uusimmat syötetiedot korostavat viimeaikaista parlamentaarista toimintaa',
    adoptedTextsHeading: 'Äskettäin Hyväksytyt Tekstit',
    recentEventsHeading: 'Viimeisimmät Parlamentaariset Tapahtumat',
    procedureUpdatesHeading: 'Lainsäädäntömenettelyjen Päivitykset',
    mepUpdatesHeading: 'MEP-Päivitykset',
    noFeedDataNotice: 'Ei uusia syötetietoja saatavilla Euroopan parlamentista.',
    asOf: 'tilanne',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Uusimmat tapahtumat ${date}: ${adopted} äskettäin hyväksyttyä tekstiä, ${events} tapahtumaa, ${procedures} menettelypäivitystä, ${meps} MEP-muutosta.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Lainsäädännöllinen enemmistö',
    breakingWinnerReasonFn: (count) =>
      `${count} lainsäädäntötekstiä on edistetty parlamentaarisessa prosessissa.`,
    breakingNeutralActor: 'Oppositioryhmät',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Ryhmien parlamenttipiiskurit',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Hyväksytty:',
    breakingMEPPrefix: 'MEP:',
    anomalyUnavailable:
      'Äänestyspoikkeamien yksityiskohtainen analyysi ei ole tällä hetkellä saatavilla lähdetietojen teknisten rajoitusten vuoksi.',
    coalitionUnavailable:
      'Koalitiodynamiikan yksityiskohtaista arviointia ei voida näyttää tällä hetkellä, koska tarvittavat taustatiedot ovat tilapäisesti poissa.',
    adoptedTextTypeLabel: 'Hyväksytty teksti',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `Näytetään ${shown} / ${total}`,
  },
  de: {
    breakingBanner: '⚡ EILMELDUNG',
    votingAnomalyIntel: 'Abstimmungsanomalien — Nachrichtendienstanalyse',
    coalitionDynamics: 'Bewertung der Koalitionsdynamik',
    analyticalReport: 'Analytischer Bericht',
    keyMEPInfluence: 'Analyse des Einflusses wichtiger MdEPs',
    intelligenceBriefing: 'Nachrichtendienstbriefing',
    votingAnomalyAlert: 'Warnung vor Abstimmungsanomalien',
    coalitionDynamicsSection: 'Koalitionsdynamik',
    keyPlayers: 'Parlamentarische Schlüsselfiguren',
    placeholderNotice:
      'Dies ist Platzhalterinhalt, der generiert wurde, während der MCP-Server des EU-Parlaments nicht verfügbar ist.',
    placeholderLede:
      'Bedeutende parlamentarische Entwicklungen werden überwacht. Verbinden Sie den MCP-Server des EU-Parlaments für Echtzeit-Informationen.',
    lede: 'Die Nachrichtendienstanalyse des MCP-Servers des EU-Parlaments hat bedeutende parlamentarische Entwicklungen identifiziert, die sofortige Aufmerksamkeit erfordern',
    feedLede:
      'Die neuesten Feeds des Europäischen Parlaments beleuchten aktuelle parlamentarische Aktivitäten',
    adoptedTextsHeading: 'Kürzlich Angenommene Texte',
    recentEventsHeading: 'Aktuelle Parlamentarische Ereignisse',
    procedureUpdatesHeading: 'Aktualisierungen der Gesetzgebungsverfahren',
    mepUpdatesHeading: 'MdEP-Aktualisierungen',
    noFeedDataNotice: 'Keine neuen Feeddaten vom Europäischen Parlament verfügbar.',
    asOf: 'zum',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Neueste Entwicklungen am ${date}: ${adopted} neu angenommene Texte, ${events} Ereignisse, ${procedures} Verfahrensupdates, ${meps} MdEP-Änderungen.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Gesetzgebende Mehrheit',
    breakingWinnerReasonFn: (count) =>
      `${count} Gesetzestexte wurden im parlamentarischen Verfahren vorangebracht.`,
    breakingNeutralActor: 'Oppositionsgruppen',
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Fraktionsgeschäftsführer',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Angenommen:',
    breakingMEPPrefix: 'MdEP:',
    anomalyUnavailable:
      'Detaillierte Analyse von Abstimmungsanomalien ist aufgrund technischer Einschränkungen der Quelldaten derzeit nicht verfügbar.',
    coalitionUnavailable:
      'Eine detaillierte Bewertung der Koalitionsdynamik kann derzeit nicht angezeigt werden, da die erforderlichen Grundlagendaten vorübergehend fehlen.',
    adoptedTextTypeLabel: 'Angenommener Text',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `${shown} von ${total} angezeigt`,
  },
  fr: {
    breakingBanner: '⚡ DERNIÈRES NOUVELLES',
    votingAnomalyIntel: 'Anomalies de Vote — Analyse de Renseignement',
    coalitionDynamics: 'Évaluation des Dynamiques de Coalition',
    analyticalReport: 'Rapport Analytique',
    keyMEPInfluence: "Analyse de l'Influence des Eurodéputés Clés",
    intelligenceBriefing: 'Briefing de Renseignement',
    votingAnomalyAlert: 'Alerte Anomalie de Vote',
    coalitionDynamicsSection: 'Dynamiques de Coalition',
    keyPlayers: 'Acteurs Parlementaires Clés',
    placeholderNotice:
      'Ceci est un contenu indicatif généré pendant que le serveur MCP du Parlement européen est indisponible.',
    placeholderLede:
      'Des développements parlementaires importants sont surveillés. Connectez le serveur MCP du Parlement européen pour recevoir des renseignements en temps réel.',
    lede: "L'analyse de renseignement du serveur MCP du Parlement européen a identifié des développements parlementaires significatifs nécessitant une attention immédiate",
    feedLede:
      'Les dernières données du Parlement européen mettent en lumière les activités parlementaires récentes',
    adoptedTextsHeading: 'Textes Récemment Adoptés',
    recentEventsHeading: 'Événements Parlementaires Récents',
    procedureUpdatesHeading: 'Mises à Jour des Procédures Législatives',
    mepUpdatesHeading: 'Mises à Jour des Eurodéputés',
    noFeedDataNotice: 'Aucune donnée de flux récente disponible du Parlement européen.',
    asOf: 'au',
    breakingWhatFn: (date, adopted, events, procedures, meps) =>
      `Dernières évolutions au ${date}\u00a0: ${adopted} textes nouvellement adoptés, ${events} événements, ${procedures} mises à jour procédurales, ${meps} changements de députés.`,
    breakingWhyAnomalies: BRK_WHY_ANOMALIES,
    breakingWhyNormal: BRK_WHY_NORMAL,
    breakingWinnerActor: 'Majorité législative',
    breakingWinnerReasonFn: (count) =>
      `${count} textes législatifs ont été avancés dans le cadre du processus parlementaire.`,
    breakingNeutralActor: "Groupes d'opposition",
    breakingNeutralReason: BRK_NEUTRAL_REASON,
    breakingOutlookActiveFn: (date) => `session_date=${date}`,
    breakingOutlookTransitionalFn: (date) => `session_date=${date} transitional=true`,
    breakingLegalObligationsConsequence: BRK_LEGAL_CONSEQUENCE,
    breakingProcedureConsequence: BRK_PROC_CONSEQUENCE,
    breakingImpactPoliticalAnomalies: BRK_WHY_ANOMALIES,
    breakingImpactPoliticalNormalFn: (count) => `legislative_texts=${count}`,
    breakingImpactEconomic: BRK_IMPACT_ECONOMIC,
    breakingImpactSocial: BRK_IMPACT_SOCIAL,
    breakingImpactLegalFn: (count) => `legal_instruments=${count}`,
    breakingImpactGeopoliticalCoalition: BRK_IMPACT_GEO_COALITION,
    breakingImpactGeopoliticalNormal: BRK_IMPACT_GEO_NORMAL,
    breakingMistakeActor: 'Chefs de file des groupes politiques',
    breakingMistakeDescription: BRK_MISTAKE_DESC,
    breakingMistakeAlternative: BRK_MISTAKE_ALT,
    breakingAdoptedPrefix: 'Adopté\u00a0:',
    breakingMEPPrefix: 'Député\u00a0:',
    anomalyUnavailable:
      "L'analyse détaillée des anomalies de vote n'est pas disponible pour le moment en raison de limitations techniques des données sources.",
    coalitionUnavailable:
      "L'évaluation détaillée de la dynamique de coalition ne peut pas être affichée pour le moment, car les données sous-jacentes nécessaires sont temporairement indisponibles.",
    adoptedTextTypeLabel: 'Texte adopté',
    adoptedTextItemLabelFn: (label) => label,
    showingXofNFn: (shown, total) => `Affichage de ${shown} sur ${total}`,
  },
};
