// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module committee-reports-content-eu
 * @description Per-language entries (en, sv, da, no, fi, de, fr) for COMMITTEE_ANALYSIS_CONTENT_STRINGS.
 */

import type { LanguageMap, CommitteeAnalysisContentStrings } from '../../types/index.js';
import { BRK_IMPACT_ECONOMIC, BRK_IMPACT_SOCIAL, BRK_IMPACT_GEO_NORMAL, CMT_WHY, CMT_NO_DOCS, CMT_IMPACT_POLITICAL, CMT_IMPACT_LEGAL, CMT_ACTION_CONSEQUENCE, CMT_MISTAKE_DESC, CMT_MISTAKE_ALT, CMT_OUTLOOK_GOOD, CMT_OUTLOOK_CONCERN } from './_shared.js';

export const COMMITTEE_ANALYSIS_CONTENT_STRINGS_EU: Pick<LanguageMap<CommitteeAnalysisContentStrings>, 'en' | 'sv' | 'da' | 'no' | 'fi' | 'de' | 'fr'> = {
  en: {
    what: 'Committee activity report as of {date}: {total} committees monitored, {docs} documents processed, {active} committees with recent activity.',
    whatNoData:
      'Committee activity monitoring as of {date}: {total} committees tracked. No recent documents were available from the EP data feed for this reporting period.',
    reportDateLabel: 'Reporting date:',
    membersLabel: 'members',
    chairLabel: 'Chair:',
    productivityRobust: 'robust',
    productivityModerate: 'moderate',
    productivityLow: 'low',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} documents — highly productive period',
    stakeholderModerateActivity: '{n} document(s) — moderate activity',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} processed {n} document(s)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'European Parliament committee activity and legislative effectiveness analysis.',
    noRecentDocs: 'No recent documents available',
    committeeMetadataUnavailable:
      'Committee chair and membership data are not currently available from the EP Open Data API for this reporting period. Committee activity monitoring continues with available data sources.',
    adoptedTextsSectionHeading: 'Recent Adopted Texts by Committee Theme',
    adoptedTextsSummary:
      'The European Parliament adopted {count} texts in recent sessions, spanning environmental, economic, security, civil liberties, and agricultural policy domains.',
    adoptedTextsSummarySingular: 'The European Parliament adopted 1 text in a recent session.',
    committeeNameENVI: 'Environment, Public Health and Food Safety',
    committeeNameECON: 'Economic and Monetary Affairs',
    committeeNameAFET: 'Foreign Affairs',
    committeeNameLIBE: 'Civil Liberties, Justice and Home Affairs',
    committeeNameAGRI: 'Agriculture and Rural Development',
    committeeNameOTHER: 'Cross-Committee and Plenary',
  },
  sv: {
    what: 'Utskottsaktivitetsrapport per {date}: {total} utskott övervakade, {docs} dokument behandlade, {active} utskott med aktuell aktivitet.',
    whatNoData:
      'Utskottsaktivitetsövervakning per {date}: {total} utskott spårade. Inga aktuella dokument var tillgängliga från EP:s dataflöde för denna rapporteringsperiod.',
    reportDateLabel: 'Rapportdatum:',
    membersLabel: 'ledamöter',
    chairLabel: 'Ordförande:',
    productivityRobust: 'robust',
    productivityModerate: 'måttlig',
    productivityLow: 'låg',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} dokument — mycket produktiv period',
    stakeholderModerateActivity: '{n} dokument — måttlig aktivitet',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} behandlade {n} dokument',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analys av Europaparlamentets utskottsaktivitet och lagstiftningseffektivitet.',
    noRecentDocs: 'Inga aktuella dokument tillgängliga',
    committeeMetadataUnavailable:
      'Uppgifter om utskottsordförande och medlemskap är för närvarande inte tillgängliga från EP:s Open Data API för denna rapporteringsperiod. Utskottsaktivitetsövervakning fortsätter med tillgängliga datakällor.',
    adoptedTextsSectionHeading: 'Nyligen antagna texter efter utskottsområde',
    adoptedTextsSummary:
      'Europaparlamentet antog {count} texter under de senaste sessionerna inom miljö-, ekonomi-, säkerhets-, medborgerliga friheter- och jordbrukspolitiska områden.',
    adoptedTextsSummarySingular: 'Europaparlamentet antog 1 text under en nyligen hållen session.',
    committeeNameENVI: 'Miljö, folkhälsa och livsmedelssäkerhet',
    committeeNameECON: 'Ekonomi och valutafrågor',
    committeeNameAFET: 'Utrikesfrågor',
    committeeNameLIBE: 'Medborgerliga fri- och rättigheter samt rättsliga och inrikes frågor',
    committeeNameAGRI: 'Jordbruk och landsbygdens utveckling',
    committeeNameOTHER: 'Tvärsövergripande och plenum',
  },
  da: {
    what: 'Udvalgsaktivitetsrapport pr. {date}: {total} udvalg overvåget, {docs} dokumenter behandlet, {active} udvalg med nylig aktivitet.',
    whatNoData:
      'Udvalgsaktivitetsovervågning pr. {date}: {total} udvalg sporet. Ingen nylige dokumenter var tilgængelige fra EP-datastrømmen for denne rapporteringsperiode.',
    reportDateLabel: 'Rapportdato:',
    membersLabel: 'medlemmer',
    chairLabel: 'Formand:',
    productivityRobust: 'robust',
    productivityModerate: 'moderat',
    productivityLow: 'lav',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} dokumenter — meget produktiv periode',
    stakeholderModerateActivity: '{n} dokument(er) — moderat aktivitet',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} behandlede {n} dokument(er)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse af Europa-Parlamentets udvalgsaktivitet og lovgivningsmæssig effektivitet.',
    noRecentDocs: 'Ingen nylige dokumenter tilgængelige',
    committeeMetadataUnavailable:
      'Data om udvalgsformand og medlemskab er i øjeblikket ikke tilgængelige fra EP Open Data API for denne rapporteringsperiode. Udvalgsaktivitetsovervågning fortsætter med tilgængelige datakilder.',
    adoptedTextsSectionHeading: 'Nylig vedtagne tekster efter udvalgsemne',
    adoptedTextsSummary:
      'Europa-Parlamentet vedtog {count} tekster under de seneste sessioner inden for miljø-, økonomi-, sikkerheds-, borgerrettigheds- og landbrugspolitiske områder.',
    adoptedTextsSummarySingular: 'Europa-Parlamentet vedtog 1 tekst under en nylig session.',
    committeeNameENVI: 'Miljø, Folkesundhed og Fødevaresikkerhed',
    committeeNameECON: 'Økonomi og Valutaspørgsmål',
    committeeNameAFET: 'Udenrigsanliggender',
    committeeNameLIBE: 'Borgernes Rettigheder og Retlige og Indre Anliggender',
    committeeNameAGRI: 'Landbrug og Landdistrikternes Udvikling',
    committeeNameOTHER: 'Tværgående og Plenarmøde',
  },
  no: {
    what: 'Komitéaktivitetsrapport per {date}: {total} komiteer overvåket, {docs} dokumenter behandlet, {active} komiteer med nylig aktivitet.',
    whatNoData:
      'Komitéaktivitetsovervåkning per {date}: {total} komiteer sporet. Ingen nylige dokumenter var tilgjengelige fra EP-datastrømmen for denne rapporteringsperioden.',
    reportDateLabel: 'Rapportdato:',
    membersLabel: 'medlemmer',
    chairLabel: 'Leder:',
    productivityRobust: 'robust',
    productivityModerate: 'moderat',
    productivityLow: 'lav',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} dokumenter — svært produktiv periode',
    stakeholderModerateActivity: '{n} dokument(er) — moderat aktivitet',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} behandlet {n} dokument(er)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse av Europaparlamentets komitéaktivitet og lovgivningseffektivitet.',
    noRecentDocs: 'Ingen nylige dokumenter tilgjengelig',
    committeeMetadataUnavailable:
      'Data om komitéleder og medlemskap er for øyeblikket ikke tilgjengelige fra EP Open Data API for denne rapporteringsperioden. Overvåking av komitéaktivitet fortsetter med tilgjengelige datakilder.',
    adoptedTextsSectionHeading: 'Nylig vedtatte tekster etter komitétema',
    adoptedTextsSummary:
      'Europaparlamentet vedtok {count} tekster under de siste sesjonene innen miljø-, økonomi-, sikkerhets-, borgerrettighets- og landbrukspolitiske områder.',
    adoptedTextsSummarySingular: 'Europaparlamentet vedtok 1 tekst under en nylig sesjon.',
    committeeNameENVI: 'Miljø, Folkehelse og Mattrygghet',
    committeeNameECON: 'Økonomi og Valutaspørsmål',
    committeeNameAFET: 'Utenrikssaker',
    committeeNameLIBE: 'Borgerrettigheter og Rettslige og Indre Anliggender',
    committeeNameAGRI: 'Landbruk og Bygdeutvikling',
    committeeNameOTHER: 'Tverrgående og Plenarmøte',
  },
  fi: {
    what: 'Valiokuntatoimintaraportti {date}: {total} valiokuntaa seurannassa, {docs} asiakirjaa käsitelty, {active} valiokuntaa viimeaikaisella toiminnalla.',
    whatNoData:
      'Valiokuntatoiminnan seuranta {date}: {total} valiokuntaa seurannassa. EP:n datavirrasta ei ollut saatavilla uusia asiakirjoja tällä raportointijaksolla.',
    reportDateLabel: 'Raportointipäivä:',
    membersLabel: 'jäsentä',
    chairLabel: 'Puheenjohtaja:',
    productivityRobust: 'vankka',
    productivityModerate: 'kohtalainen',
    productivityLow: 'alhainen',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} asiakirjaa — erittäin tuottoisa kausi',
    stakeholderModerateActivity: '{n} asiakirja(a) — kohtalainen aktiivisuus',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} käsitteli {n} asiakirja(a)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyysi Euroopan parlamentin valiokuntien toiminnasta ja lainsäädäntötehokkuudesta.',
    noRecentDocs: 'Ei viimeaikaisia asiakirjoja saatavilla',
    committeeMetadataUnavailable:
      'Valiokunnan puheenjohtajan ja jäsenyyden tiedot eivät ole tällä hetkellä saatavilla EP:n Open Data -rajapinnasta tältä raportointijaksolta. Valiokuntien toiminnan seuranta jatkuu käytettävissä olevilla tietolähteillä.',
    adoptedTextsSectionHeading: 'Viimeksi hyväksytyt tekstit valiokunta-aiheen mukaan',
    adoptedTextsSummary:
      'Euroopan parlamentti hyväksyi {count} tekstiä viimeisimmissä istunnoissaan ympäristö-, talous-, turvallisuus-, kansalaisvapauksien ja maatalouspolitiikan aloilla.',
    adoptedTextsSummarySingular:
      'Euroopan parlamentti hyväksyi 1 tekstin äskettäisessä istunnossaan.',
    committeeNameENVI: 'Ympäristö, kansanterveys ja elintarvikkeiden turvallisuus',
    committeeNameECON: 'Talous- ja raha-asiat',
    committeeNameAFET: 'Ulkoasiat',
    committeeNameLIBE: 'Kansalaisvapaudet sekä oikeus- ja sisäasiat',
    committeeNameAGRI: 'Maatalous ja maaseudun kehittäminen',
    committeeNameOTHER: 'Monialatoimikunta ja täysistunto',
  },
  de: {
    what: 'Ausschussaktivitätsbericht vom {date}: {total} Ausschüsse beobachtet, {docs} Dokumente verarbeitet, {active} Ausschüsse mit aktueller Aktivität.',
    whatNoData:
      'Ausschussaktivitätsüberwachung vom {date}: {total} Ausschüsse verfolgt. Für diesen Berichtszeitraum waren keine aktuellen Dokumente aus dem EP-Datenfeed verfügbar.',
    reportDateLabel: 'Berichtsdatum:',
    membersLabel: 'Mitglieder',
    chairLabel: 'Vorsitzender:',
    productivityRobust: 'robuste',
    productivityModerate: 'moderate',
    productivityLow: 'geringe',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} Dokumente — sehr produktiver Zeitraum',
    stakeholderModerateActivity: '{n} Dokument(e) — moderate Aktivität',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} hat {n} Dokument(e) bearbeitet',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse der Ausschusstätigkeit des Europäischen Parlaments und seiner Gesetzgebungswirksamkeit.',
    noRecentDocs: 'Keine aktuellen Dokumente verfügbar',
    committeeMetadataUnavailable:
      'Daten zu Ausschussvorsitz und Mitgliedschaft sind für diesen Berichtszeitraum derzeit nicht über die EP Open Data API verfügbar. Die Überwachung der Ausschusstätigkeit wird mit den verfügbaren Datenquellen fortgesetzt.',
    adoptedTextsSectionHeading: 'Kürzlich angenommene Texte nach Ausschussthema',
    adoptedTextsSummary:
      'Das Europäische Parlament hat in den letzten Sitzungsperioden {count} Texte in den Bereichen Umwelt-, Wirtschafts-, Sicherheits-, Bürgerrechte- und Agrarpolitik verabschiedet.',
    adoptedTextsSummarySingular:
      'Das Europäische Parlament hat in einer aktuellen Sitzungsperiode 1 Text verabschiedet.',
    committeeNameENVI: 'Umweltfragen, öffentliche Gesundheit und Lebensmittelsicherheit',
    committeeNameECON: 'Wirtschaft und Währung',
    committeeNameAFET: 'Auswärtige Angelegenheiten',
    committeeNameLIBE: 'Bürgerliche Freiheiten, Justiz und Inneres',
    committeeNameAGRI: 'Landwirtschaft und ländliche Entwicklung',
    committeeNameOTHER: 'Ausschussübergreifend und Plenum',
  },
  fr: {
    what: "Rapport d'activité des commissions du {date} : {total} commissions surveillées, {docs} documents traités, {active} commissions avec activité récente.",
    whatNoData:
      "Surveillance des activités des commissions du {date} : {total} commissions suivies. Aucun document récent n'était disponible depuis le flux de données du PE pour cette période de rapport.",
    reportDateLabel: 'Date du rapport :',
    membersLabel: 'membres',
    chairLabel: 'Président(e) :',
    productivityRobust: 'robuste',
    productivityModerate: 'modérée',
    productivityLow: 'faible',
    why: "Les commissions sont le moteur législatif du Parlement européen — un taux d'activité de {pct}% signale une productivité législative {descriptor}. Les résultats des commissions façonnent directement les textes soumis aux votes en séance plénière.",
    stakeholderHighlyProductive: '{n} documents — période très productive',
    stakeholderModerateActivity: '{n} document(s) — activité modérée',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} a traité {n} document(s)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: "Analyse de l'activité des commissions du Parlement européen et de l'efficacité législative.",
    noRecentDocs: 'Aucun document récent disponible',
    committeeMetadataUnavailable:
      "Les données sur le président et les membres des commissions ne sont actuellement pas disponibles via l'API Open Data du PE pour cette période de rapport. La surveillance de l'activité des commissions se poursuit avec les sources de données disponibles.",
    adoptedTextsSectionHeading: 'Textes récemment adoptés par thème de commission',
    adoptedTextsSummary:
      'Le Parlement européen a adopté {count} textes lors des sessions récentes, couvrant les domaines de la politique environnementale, économique, sécuritaire, des libertés civiles et agricole.',
    adoptedTextsSummarySingular:
      "Le Parlement européen a adopté 1 texte lors d'une session récente.",
    committeeNameENVI: 'Environnement, santé publique et sécurité alimentaire',
    committeeNameECON: 'Affaires économiques et monétaires',
    committeeNameAFET: 'Affaires étrangères',
    committeeNameLIBE: 'Libertés civiles, justice et affaires intérieures',
    committeeNameAGRI: 'Agriculture et développement rural',
    committeeNameOTHER: 'Intercommissions et plénière',
  },
};
