// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/CommitteeReports
 * @description Committee-reports article: 14-language title generator and committee analysis content strings.
 *
 * Per-language strings live together so a translator can update one language
 * for this article type without touching any other article type.
 */

import type {
  LanguageMap,
  LangTitleSubtitle,
  CommitteeAnalysisContentStrings,
} from '../../types/index.js';
import {
  BRK_IMPACT_ECONOMIC,
  BRK_IMPACT_SOCIAL,
  BRK_IMPACT_GEO_NORMAL,
  CMT_WHY,
  CMT_NO_DOCS,
  CMT_IMPACT_POLITICAL,
  CMT_IMPACT_LEGAL,
  CMT_ACTION_CONSEQUENCE,
  CMT_MISTAKE_DESC,
  CMT_MISTAKE_ALT,
  CMT_OUTLOOK_GOOD,
  CMT_OUTLOOK_CONCERN,
} from './_shared.js';
export const COMMITTEE_REPORTS_TITLES: LanguageMap<(committee: string) => LangTitleSubtitle> = {
  en: (committee) => ({
    title: `EU Parliament Committee Activity Report: ${committee}`,
    subtitle:
      'Analysis of recent legislative output, effectiveness metrics, and key committee activities',
  }),
  sv: (committee) => ({
    title: `Aktivitetsrapport för Europaparlamentets utskott: ${committee}`,
    subtitle:
      'Analys av nylig lagstiftningsproduktion, effektivitetsmätningar och viktigaste utskottsaktiviteter',
  }),
  da: (committee) => ({
    title: `Aktivitetsrapport for Europa-Parlamentets udvalg: ${committee}`,
    subtitle:
      'Analyse af den seneste lovgivningsproduktion, effektivitetsmålinger og vigtigste udvalgsaktiviteter',
  }),
  no: (committee) => ({
    title: `Aktivitetsrapport for Europaparlamentets komiteer: ${committee}`,
    subtitle:
      'Analyse av nylig lovgivningsproduksjon, effektivitetsmålinger og viktigste komitéaktiviteter',
  }),
  fi: (committee) => ({
    title: `Euroopan parlamentin valiokuntien toimintaraportti: ${committee}`,
    subtitle:
      'Analyysi viimeaikaisesta lainsäädäntötuotannosta, tehokkuusmittareista ja tärkeimmistä valiokuntatoiminnoista',
  }),
  de: (committee) => ({
    title: `EU-Parlament Ausschussbericht: ${committee}`,
    subtitle:
      'Analyse der Gesetzgebungsleistung, Effektivitätskennzahlen und wichtiger Ausschussaktivitäten',
  }),
  fr: (committee) => ({
    title: `Rapport d'activité des commissions du Parlement européen: ${committee}`,
    subtitle:
      "Analyse de la production législative récente, des indicateurs d'efficacité et des activités clés des commissions",
  }),
  es: (committee) => ({
    title: `Informe de actividad de comisiones del Parlamento Europeo: ${committee}`,
    subtitle:
      'Análisis de la producción legislativa reciente, métricas de efectividad y actividades clave de las comisiones',
  }),
  nl: (committee) => ({
    title: `Activiteitenrapport commissies Europees Parlement: ${committee}`,
    subtitle:
      'Analyse van recente wetgevingsoutput, effectiviteitsmetrieken en belangrijkste commissieactiviteiten',
  }),
  ar: (committee) => ({
    title: `تقرير نشاط لجان البرلمان الأوروبي: ${committee}`,
    subtitle: 'تحليل الإنتاج التشريعي الأخير ومقاييس الفعالية والأنشطة الرئيسية للجان',
  }),
  he: (committee) => ({
    title: `דוח פעילות ועדות הפרלמנט האירופי: ${committee}`,
    subtitle: 'ניתוח תפוקה חקיקתית אחרונה, מדדי אפקטיביות ופעילויות ועדה מרכזיות',
  }),
  ja: (committee) => ({
    title: `EU議会委員会活動報告: ${committee}`,
    subtitle: '最近の立法成果、有効性指標、主要な委員会活動の分析',
  }),
  ko: (committee) => ({
    title: `EU 의회 위원회 활동 보고서: ${committee}`,
    subtitle: '최근 입법 산출물, 효과성 지표 및 주요 위원회 활동 분석',
  }),
  zh: (committee) => ({
    title: `EU议会委员会活动报告: ${committee}`,
    subtitle: '最近立法成果、效能指标和关键委员会活动分析',
  }),
};

/** Propositions title templates per language */
export const COMMITTEE_ANALYSIS_CONTENT_STRINGS: LanguageMap<CommitteeAnalysisContentStrings> = {
  en: {
    what: 'Committee activity report as of {date}: {total} committees monitored, {docs} documents processed, {active} committees with recent activity.',
    whatNoData:
      'Committee activity monitoring as of {date}: {total} committees tracked. No recent documents were available from the EP data feed for this reporting period.',
    reportDateLabel: 'Reporting date:',
    membersLabel: 'members',
    chairLabel: 'Chair:',
    productivityRobust: 'robust',
    productivityModerate: 'moderate',
    productivityLow: 'low',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} documents — highly productive period',
    stakeholderModerateActivity: '{n} document(s) — moderate activity',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} processed {n} document(s)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'European Parliament committee activity and legislative effectiveness analysis.',
    noRecentDocs: 'No recent documents available',
    committeeMetadataUnavailable:
      'Committee chair and membership data are not currently available from the EP Open Data API for this reporting period. Committee activity monitoring continues with available data sources.',
    adoptedTextsSectionHeading: 'Recent Adopted Texts by Committee Theme',
    adoptedTextsSummary:
      'The European Parliament adopted {count} texts in recent sessions, spanning environmental, economic, security, civil liberties, and agricultural policy domains.',
    adoptedTextsSummarySingular: 'The European Parliament adopted 1 text in a recent session.',
    committeeNameENVI: 'Environment, Public Health and Food Safety',
    committeeNameECON: 'Economic and Monetary Affairs',
    committeeNameAFET: 'Foreign Affairs',
    committeeNameLIBE: 'Civil Liberties, Justice and Home Affairs',
    committeeNameAGRI: 'Agriculture and Rural Development',
    committeeNameOTHER: 'Cross-Committee and Plenary',
  },
  sv: {
    what: 'Utskottsaktivitetsrapport per {date}: {total} utskott övervakade, {docs} dokument behandlade, {active} utskott med aktuell aktivitet.',
    whatNoData:
      'Utskottsaktivitetsövervakning per {date}: {total} utskott spårade. Inga aktuella dokument var tillgängliga från EP:s dataflöde för denna rapporteringsperiod.',
    reportDateLabel: 'Rapportdatum:',
    membersLabel: 'ledamöter',
    chairLabel: 'Ordförande:',
    productivityRobust: 'robust',
    productivityModerate: 'måttlig',
    productivityLow: 'låg',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} dokument — mycket produktiv period',
    stakeholderModerateActivity: '{n} dokument — måttlig aktivitet',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} behandlade {n} dokument',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analys av Europaparlamentets utskottsaktivitet och lagstiftningseffektivitet.',
    noRecentDocs: 'Inga aktuella dokument tillgängliga',
    committeeMetadataUnavailable:
      'Uppgifter om utskottsordförande och medlemskap är för närvarande inte tillgängliga från EP:s Open Data API för denna rapporteringsperiod. Utskottsaktivitetsövervakning fortsätter med tillgängliga datakällor.',
    adoptedTextsSectionHeading: 'Nyligen antagna texter efter utskottsområde',
    adoptedTextsSummary:
      'Europaparlamentet antog {count} texter under de senaste sessionerna inom miljö-, ekonomi-, säkerhets-, medborgerliga friheter- och jordbrukspolitiska områden.',
    adoptedTextsSummarySingular: 'Europaparlamentet antog 1 text under en nyligen hållen session.',
    committeeNameENVI: 'Miljö, folkhälsa och livsmedelssäkerhet',
    committeeNameECON: 'Ekonomi och valutafrågor',
    committeeNameAFET: 'Utrikesfrågor',
    committeeNameLIBE: 'Medborgerliga fri- och rättigheter samt rättsliga och inrikes frågor',
    committeeNameAGRI: 'Jordbruk och landsbygdens utveckling',
    committeeNameOTHER: 'Tvärsövergripande och plenum',
  },
  da: {
    what: 'Udvalgsaktivitetsrapport pr. {date}: {total} udvalg overvåget, {docs} dokumenter behandlet, {active} udvalg med nylig aktivitet.',
    whatNoData:
      'Udvalgsaktivitetsovervågning pr. {date}: {total} udvalg sporet. Ingen nylige dokumenter var tilgængelige fra EP-datastrømmen for denne rapporteringsperiode.',
    reportDateLabel: 'Rapportdato:',
    membersLabel: 'medlemmer',
    chairLabel: 'Formand:',
    productivityRobust: 'robust',
    productivityModerate: 'moderat',
    productivityLow: 'lav',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} dokumenter — meget produktiv periode',
    stakeholderModerateActivity: '{n} dokument(er) — moderat aktivitet',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} behandlede {n} dokument(er)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse af Europa-Parlamentets udvalgsaktivitet og lovgivningsmæssig effektivitet.',
    noRecentDocs: 'Ingen nylige dokumenter tilgængelige',
    committeeMetadataUnavailable:
      'Data om udvalgsformand og medlemskab er i øjeblikket ikke tilgængelige fra EP Open Data API for denne rapporteringsperiode. Udvalgsaktivitetsovervågning fortsætter med tilgængelige datakilder.',
    adoptedTextsSectionHeading: 'Nylig vedtagne tekster efter udvalgsemne',
    adoptedTextsSummary:
      'Europa-Parlamentet vedtog {count} tekster under de seneste sessioner inden for miljø-, økonomi-, sikkerheds-, borgerrettigheds- og landbrugspolitiske områder.',
    adoptedTextsSummarySingular: 'Europa-Parlamentet vedtog 1 tekst under en nylig session.',
    committeeNameENVI: 'Miljø, Folkesundhed og Fødevaresikkerhed',
    committeeNameECON: 'Økonomi og Valutaspørgsmål',
    committeeNameAFET: 'Udenrigsanliggender',
    committeeNameLIBE: 'Borgernes Rettigheder og Retlige og Indre Anliggender',
    committeeNameAGRI: 'Landbrug og Landdistrikternes Udvikling',
    committeeNameOTHER: 'Tværgående og Plenarmøde',
  },
  no: {
    what: 'Komitéaktivitetsrapport per {date}: {total} komiteer overvåket, {docs} dokumenter behandlet, {active} komiteer med nylig aktivitet.',
    whatNoData:
      'Komitéaktivitetsovervåkning per {date}: {total} komiteer sporet. Ingen nylige dokumenter var tilgjengelige fra EP-datastrømmen for denne rapporteringsperioden.',
    reportDateLabel: 'Rapportdato:',
    membersLabel: 'medlemmer',
    chairLabel: 'Leder:',
    productivityRobust: 'robust',
    productivityModerate: 'moderat',
    productivityLow: 'lav',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} dokumenter — svært produktiv periode',
    stakeholderModerateActivity: '{n} dokument(er) — moderat aktivitet',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} behandlet {n} dokument(er)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse av Europaparlamentets komitéaktivitet og lovgivningseffektivitet.',
    noRecentDocs: 'Ingen nylige dokumenter tilgjengelig',
    committeeMetadataUnavailable:
      'Data om komitéleder og medlemskap er for øyeblikket ikke tilgjengelige fra EP Open Data API for denne rapporteringsperioden. Overvåking av komitéaktivitet fortsetter med tilgjengelige datakilder.',
    adoptedTextsSectionHeading: 'Nylig vedtatte tekster etter komitétema',
    adoptedTextsSummary:
      'Europaparlamentet vedtok {count} tekster under de siste sesjonene innen miljø-, økonomi-, sikkerhets-, borgerrettighets- og landbrukspolitiske områder.',
    adoptedTextsSummarySingular: 'Europaparlamentet vedtok 1 tekst under en nylig sesjon.',
    committeeNameENVI: 'Miljø, Folkehelse og Mattrygghet',
    committeeNameECON: 'Økonomi og Valutaspørsmål',
    committeeNameAFET: 'Utenrikssaker',
    committeeNameLIBE: 'Borgerrettigheter og Rettslige og Indre Anliggender',
    committeeNameAGRI: 'Landbruk og Bygdeutvikling',
    committeeNameOTHER: 'Tverrgående og Plenarmøte',
  },
  fi: {
    what: 'Valiokuntatoimintaraportti {date}: {total} valiokuntaa seurannassa, {docs} asiakirjaa käsitelty, {active} valiokuntaa viimeaikaisella toiminnalla.',
    whatNoData:
      'Valiokuntatoiminnan seuranta {date}: {total} valiokuntaa seurannassa. EP:n datavirrasta ei ollut saatavilla uusia asiakirjoja tällä raportointijaksolla.',
    reportDateLabel: 'Raportointipäivä:',
    membersLabel: 'jäsentä',
    chairLabel: 'Puheenjohtaja:',
    productivityRobust: 'vankka',
    productivityModerate: 'kohtalainen',
    productivityLow: 'alhainen',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} asiakirjaa — erittäin tuottoisa kausi',
    stakeholderModerateActivity: '{n} asiakirja(a) — kohtalainen aktiivisuus',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} käsitteli {n} asiakirja(a)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyysi Euroopan parlamentin valiokuntien toiminnasta ja lainsäädäntötehokkuudesta.',
    noRecentDocs: 'Ei viimeaikaisia asiakirjoja saatavilla',
    committeeMetadataUnavailable:
      'Valiokunnan puheenjohtajan ja jäsenyyden tiedot eivät ole tällä hetkellä saatavilla EP:n Open Data -rajapinnasta tältä raportointijaksolta. Valiokuntien toiminnan seuranta jatkuu käytettävissä olevilla tietolähteillä.',
    adoptedTextsSectionHeading: 'Viimeksi hyväksytyt tekstit valiokunta-aiheen mukaan',
    adoptedTextsSummary:
      'Euroopan parlamentti hyväksyi {count} tekstiä viimeisimmissä istunnoissaan ympäristö-, talous-, turvallisuus-, kansalaisvapauksien ja maatalouspolitiikan aloilla.',
    adoptedTextsSummarySingular:
      'Euroopan parlamentti hyväksyi 1 tekstin äskettäisessä istunnossaan.',
    committeeNameENVI: 'Ympäristö, kansanterveys ja elintarvikkeiden turvallisuus',
    committeeNameECON: 'Talous- ja raha-asiat',
    committeeNameAFET: 'Ulkoasiat',
    committeeNameLIBE: 'Kansalaisvapaudet sekä oikeus- ja sisäasiat',
    committeeNameAGRI: 'Maatalous ja maaseudun kehittäminen',
    committeeNameOTHER: 'Monialatoimikunta ja täysistunto',
  },
  de: {
    what: 'Ausschussaktivitätsbericht vom {date}: {total} Ausschüsse beobachtet, {docs} Dokumente verarbeitet, {active} Ausschüsse mit aktueller Aktivität.',
    whatNoData:
      'Ausschussaktivitätsüberwachung vom {date}: {total} Ausschüsse verfolgt. Für diesen Berichtszeitraum waren keine aktuellen Dokumente aus dem EP-Datenfeed verfügbar.',
    reportDateLabel: 'Berichtsdatum:',
    membersLabel: 'Mitglieder',
    chairLabel: 'Vorsitzender:',
    productivityRobust: 'robuste',
    productivityModerate: 'moderate',
    productivityLow: 'geringe',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} Dokumente — sehr produktiver Zeitraum',
    stakeholderModerateActivity: '{n} Dokument(e) — moderate Aktivität',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} hat {n} Dokument(e) bearbeitet',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse der Ausschusstätigkeit des Europäischen Parlaments und seiner Gesetzgebungswirksamkeit.',
    noRecentDocs: 'Keine aktuellen Dokumente verfügbar',
    committeeMetadataUnavailable:
      'Daten zu Ausschussvorsitz und Mitgliedschaft sind für diesen Berichtszeitraum derzeit nicht über die EP Open Data API verfügbar. Die Überwachung der Ausschusstätigkeit wird mit den verfügbaren Datenquellen fortgesetzt.',
    adoptedTextsSectionHeading: 'Kürzlich angenommene Texte nach Ausschussthema',
    adoptedTextsSummary:
      'Das Europäische Parlament hat in den letzten Sitzungsperioden {count} Texte in den Bereichen Umwelt-, Wirtschafts-, Sicherheits-, Bürgerrechte- und Agrarpolitik verabschiedet.',
    adoptedTextsSummarySingular:
      'Das Europäische Parlament hat in einer aktuellen Sitzungsperiode 1 Text verabschiedet.',
    committeeNameENVI: 'Umweltfragen, öffentliche Gesundheit und Lebensmittelsicherheit',
    committeeNameECON: 'Wirtschaft und Währung',
    committeeNameAFET: 'Auswärtige Angelegenheiten',
    committeeNameLIBE: 'Bürgerliche Freiheiten, Justiz und Inneres',
    committeeNameAGRI: 'Landwirtschaft und ländliche Entwicklung',
    committeeNameOTHER: 'Ausschussübergreifend und Plenum',
  },
  fr: {
    what: "Rapport d'activité des commissions du {date} : {total} commissions surveillées, {docs} documents traités, {active} commissions avec activité récente.",
    whatNoData:
      "Surveillance des activités des commissions du {date} : {total} commissions suivies. Aucun document récent n'était disponible depuis le flux de données du PE pour cette période de rapport.",
    reportDateLabel: 'Date du rapport :',
    membersLabel: 'membres',
    chairLabel: 'Président(e) :',
    productivityRobust: 'robuste',
    productivityModerate: 'modérée',
    productivityLow: 'faible',
    why: "Les commissions sont le moteur législatif du Parlement européen — un taux d'activité de {pct}% signale une productivité législative {descriptor}. Les résultats des commissions façonnent directement les textes soumis aux votes en séance plénière.",
    stakeholderHighlyProductive: '{n} documents — période très productive',
    stakeholderModerateActivity: '{n} document(s) — activité modérée',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} a traité {n} document(s)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: "Analyse de l'activité des commissions du Parlement européen et de l'efficacité législative.",
    noRecentDocs: 'Aucun document récent disponible',
    committeeMetadataUnavailable:
      "Les données sur le président et les membres des commissions ne sont actuellement pas disponibles via l'API Open Data du PE pour cette période de rapport. La surveillance de l'activité des commissions se poursuit avec les sources de données disponibles.",
    adoptedTextsSectionHeading: 'Textes récemment adoptés par thème de commission',
    adoptedTextsSummary:
      'Le Parlement européen a adopté {count} textes lors des sessions récentes, couvrant les domaines de la politique environnementale, économique, sécuritaire, des libertés civiles et agricole.',
    adoptedTextsSummarySingular:
      "Le Parlement européen a adopté 1 texte lors d'une session récente.",
    committeeNameENVI: 'Environnement, santé publique et sécurité alimentaire',
    committeeNameECON: 'Affaires économiques et monétaires',
    committeeNameAFET: 'Affaires étrangères',
    committeeNameLIBE: 'Libertés civiles, justice et affaires intérieures',
    committeeNameAGRI: 'Agriculture et développement rural',
    committeeNameOTHER: 'Intercommissions et plénière',
  },
  es: {
    what: 'Informe de actividad de las comisiones a fecha {date}: {total} comisiones supervisadas, {docs} documentos procesados, {active} comisiones con actividad reciente.',
    whatNoData:
      'Monitoreo de actividad de las comisiones a fecha {date}: {total} comisiones rastreadas. No había documentos recientes disponibles del feed de datos del PE para este período de informe.',
    reportDateLabel: 'Fecha del informe:',
    membersLabel: 'miembros',
    chairLabel: 'Presidente/a:',
    productivityRobust: 'sólida',
    productivityModerate: 'moderada',
    productivityLow: 'baja',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} documentos — período muy productivo',
    stakeholderModerateActivity: '{n} documento(s) — actividad moderada',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} procesó {n} documento(s)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Análisis de la actividad de las comisiones del Parlamento Europeo y de su efectividad legislativa.',
    noRecentDocs: 'No hay documentos recientes disponibles',
    committeeMetadataUnavailable:
      'Los datos sobre el presidente y la membresía de las comisiones no están disponibles actualmente a través de la API Open Data del PE para este período de informe. El monitoreo de la actividad de las comisiones continúa con las fuentes de datos disponibles.',
    adoptedTextsSectionHeading: 'Textos recientemente adoptados por tema de comisión',
    adoptedTextsSummary:
      'El Parlamento Europeo adoptó {count} textos en las sesiones recientes, abarcando los dominios de la política medioambiental, económica, de seguridad, de libertades civiles y agrícola.',
    adoptedTextsSummarySingular: 'El Parlamento Europeo adoptó 1 texto en una sesión reciente.',
    committeeNameENVI: 'Medio Ambiente, Salud Pública y Seguridad Alimentaria',
    committeeNameECON: 'Asuntos Económicos y Monetarios',
    committeeNameAFET: 'Asuntos Exteriores',
    committeeNameLIBE: 'Libertades Civiles, Justicia y Asuntos de Interior',
    committeeNameAGRI: 'Agricultura y Desarrollo Rural',
    committeeNameOTHER: 'Intercomisiones y Plenario',
  },
  nl: {
    what: 'Rapport commissieactiviteiten per {date}: {total} commissies gemonitord, {docs} documenten verwerkt, {active} commissies met recente activiteit.',
    whatNoData:
      'Commissieactiviteitsbewaking per {date}: {total} commissies gevolgd. Er waren geen recente documenten beschikbaar vanuit de EP-gegevensfeed voor deze rapportageperiode.',
    reportDateLabel: 'Rapportdatum:',
    membersLabel: 'leden',
    chairLabel: 'Voorzitter:',
    productivityRobust: 'robuuste',
    productivityModerate: 'matige',
    productivityLow: 'lage',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} documenten — zeer productieve periode',
    stakeholderModerateActivity: '{n} document(en) — matige activiteit',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} verwerkte {n} document(en)',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'Analyse van commissieactiviteiten en wetgevende effectiviteit van het Europees Parlement.',
    noRecentDocs: 'Geen recente documenten beschikbaar',
    committeeMetadataUnavailable:
      'Gegevens over de voorzitter en het lidmaatschap van commissies zijn momenteel niet beschikbaar via de EP Open Data API voor deze rapportageperiode. De monitoring van commissieactiviteiten gaat door met de beschikbare gegevensbronnen.',
    adoptedTextsSectionHeading: 'Recent aangenomen teksten per commissiethema',
    adoptedTextsSummary:
      'Het Europees Parlement nam {count} teksten aan in recente plenaire vergaderingen over milieu-, economisch, veiligheids-, burgerlijke vrijheden- en landbouwbeleid.',
    adoptedTextsSummarySingular:
      'Het Europees Parlement nam 1 tekst aan in een recente plenaire vergadering.',
    committeeNameENVI: 'Milieubeheer, volksgezondheid en voedselveiligheid',
    committeeNameECON: 'Economische en monetaire zaken',
    committeeNameAFET: 'Buitenlandse zaken',
    committeeNameLIBE: 'Burgerlijke vrijheden, justitie en binnenlandse zaken',
    committeeNameAGRI: 'Landbouw en plattelandsontwikkeling',
    committeeNameOTHER: 'Commissieoverstijgend en Plenaire',
  },
  ar: {
    what: 'تقرير نشاط اللجان بتاريخ {date}: {total} لجنة مراقبة، {docs} وثيقة معالجة، {active} لجنة ذات نشاط حديث.',
    whatNoData:
      'مراقبة نشاط اللجان بتاريخ {date}: {total} لجنة متابعة. لم تكن هناك وثائق حديثة متاحة من موجز بيانات البرلمان الأوروبي لفترة التقرير هذه.',
    reportDateLabel: 'تاريخ التقرير:',
    membersLabel: 'عضو',
    chairLabel: 'الرئيس:',
    productivityRobust: 'قوية',
    productivityModerate: 'معتدلة',
    productivityLow: 'ضعيفة',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} وثيقة — فترة منتجة جداً',
    stakeholderModerateActivity: '{n} وثيقة/وثائق — نشاط معتدل',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: 'عالجت لجنة {abbr} {n} وثيقة/وثائق',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'تحليل نشاط لجان البرلمان الأوروبي وفعالية عملها التشريعية.',
    noRecentDocs: 'لا توجد وثائق حديثة متاحة',
    committeeMetadataUnavailable:
      'بيانات رئيس اللجنة والعضوية غير متاحة حالياً من خلال واجهة برمجة تطبيقات EP Open Data لفترة الإبلاغ هذه. تستمر مراقبة نشاط اللجان بمصادر البيانات المتاحة.',
    adoptedTextsSectionHeading: 'النصوص المعتمدة مؤخراً حسب موضوع اللجنة',
    adoptedTextsSummary:
      'اعتمد البرلمان الأوروبي {count} نصاً في الجلسات الأخيرة، تشمل مجالات السياسات البيئية والاقتصادية والأمنية والحريات المدنية والزراعية.',
    adoptedTextsSummarySingular: 'اعتمد البرلمان الأوروبي نصاً واحداً في جلسة أخيرة.',
    committeeNameENVI: 'البيئة والصحة العامة وسلامة الغذاء',
    committeeNameECON: 'الشؤون الاقتصادية والنقدية',
    committeeNameAFET: 'الشؤون الخارجية',
    committeeNameLIBE: 'الحريات المدنية والعدالة والشؤون الداخلية',
    committeeNameAGRI: 'الزراعة والتنمية الريفية',
    committeeNameOTHER: 'بين اللجان والجلسة العامة',
  },
  he: {
    what: 'דוח פעילות ועדות מתאריך {date}: {total} ועדות במעקב, {docs} מסמכים עובדו, {active} ועדות עם פעילות אחרונה.',
    whatNoData:
      'מעקב אחר פעילות ועדות מתאריך {date}: {total} ועדות במעקב. לא היו מסמכים אחרונים זמינים מעדכון הנתונים של הפרלמנט האירופי לחלון דיווח זה.',
    reportDateLabel: 'תאריך הדוח:',
    membersLabel: 'חברים',
    chairLabel: 'יו"ר:',
    productivityRobust: 'חזקה',
    productivityModerate: 'מתונה',
    productivityLow: 'נמוכה',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n} מסמכים — תקופה פרודוקטיבית מאוד',
    stakeholderModerateActivity: '{n} מסמך/ים — פעילות מתונה',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr} עיבד {n} מסמך/ים',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: 'ניתוח פעילות ועדות הפרלמנט האירופי ויעילותו החקיקתית.',
    noRecentDocs: 'אין מסמכים אחרונים זמינים',
    committeeMetadataUnavailable:
      'נתוני יו"ר הוועדה וחברותה אינם זמינים כרגע דרך ממשק ה-API של EP Open Data לתקופת הדיווח זו. ניטור פעילות הוועדות ממשיך עם מקורות הנתונים הזמינים.',
    adoptedTextsSectionHeading: 'טקסטים שהתקבלו לאחרונה לפי נושא ועדה',
    adoptedTextsSummary:
      'הפרלמנט האירופי אישר {count} טקסטים בפגישות האחרונות, הכוללים תחומי מדיניות סביבתית, כלכלית, ביטחונית, חירויות אזרחיות וחקלאית.',
    adoptedTextsSummarySingular: 'הפרלמנט האירופי אישר טקסט אחד בפגישה האחרונה.',
    committeeNameENVI: 'איכות הסביבה, בריאות הציבור ובטיחות המזון',
    committeeNameECON: 'ענייני כלכלה ומטבע',
    committeeNameAFET: 'ענייני חוץ',
    committeeNameLIBE: 'חירויות אזרחיות, צדק וענייני פנים',
    committeeNameAGRI: 'חקלאות ופיתוח כפרי',
    committeeNameOTHER: 'בין-ועדתי ומליאה',
  },
  ja: {
    what: '{date}付け委員会活動報告: {total}委員会を監視中、{docs}文書処理済み、{active}委員会で最近の活動あり。',
    whatNoData:
      '{date}付け委員会活動監視：{total}委員会を追跡中。このレポート期間にEPデータフィードから入手可能な最新文書はありませんでした。',
    reportDateLabel: '報告日:',
    membersLabel: '名',
    chairLabel: '委員長:',
    productivityRobust: '堅調な',
    productivityModerate: '中程度の',
    productivityLow: '低い',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n}文書 — 非常に生産的な期間',
    stakeholderModerateActivity: '{n}文書 — 中程度の活動',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr}が{n}文書を処理しました',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: '欧州議会委員会の最近の立法成果と活動の有効性を分析します。',
    noRecentDocs: '最近の文書はありません',
    committeeMetadataUnavailable:
      '委員会の委員長および構成員データは、この報告期間において EP Open Data API から現在入手できません。委員会活動の監視は利用可能なデータソースで継続します。',
    adoptedTextsSectionHeading: '委員会テーマ別の最近採択されたテキスト',
    adoptedTextsSummary:
      '欧州議会は最近の会期に{count}件のテキストを採択し、環境、経済、安全保障、市民的自由、農業政策の分野をカバーしています。',
    adoptedTextsSummarySingular: '欧州議会は最近の会期に1件のテキストを採択しました。',
    committeeNameENVI: '環境・公衆衛生・食品安全',
    committeeNameECON: '経済・通貨問題',
    committeeNameAFET: '外交問題',
    committeeNameLIBE: '市民的自由・司法・内務',
    committeeNameAGRI: '農業・農村開発',
    committeeNameOTHER: '委員会横断・本会議',
  },
  ko: {
    what: '{date} 기준 위원회 활동 보고서: {total}개 위원회 모니터링, {docs}개 문서 처리, {active}개 위원회 최근 활동.',
    whatNoData:
      '{date} 기준 위원회 활동 모니터링: {total}개 위원회 추적 중. 이 보고 기간에 EP 데이터 피드에서 사용 가능한 최근 문서가 없었습니다.',
    reportDateLabel: '보고 날짜:',
    membersLabel: '명',
    chairLabel: '의장:',
    productivityRobust: '강력한',
    productivityModerate: '보통의',
    productivityLow: '낮은',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n}개 문서 — 매우 생산적인 기간',
    stakeholderModerateActivity: '{n}개 문서 — 보통 활동',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr}에서 {n}개 문서 처리',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: '유럽 의회의 주요 위원회 활동과 입법 효율성을 종합적으로 분석합니다.',
    noRecentDocs: '최근 문서가 없습니다',
    committeeMetadataUnavailable:
      '이 보고 기간 동안 EP Open Data API에서 위원회 위원장 및 구성원 데이터를 현재 사용할 수 없습니다. 위원회 활동 모니터링은 사용 가능한 데이터 소스로 계속됩니다.',
    adoptedTextsSectionHeading: '위원회 주제별 최근 채택된 텍스트',
    adoptedTextsSummary:
      '유럽 의회는 최근 회기에서 환경, 경제, 안보, 시민 자유 및 농업 정책 분야에 걸쳐 {count}개의 텍스트를 채택했습니다.',
    adoptedTextsSummarySingular: '유럽 의회는 최근 회기에서 1개의 텍스트를 채택했습니다.',
    committeeNameENVI: '환경, 공중보건 및 식품안전',
    committeeNameECON: '경제·통화 문제',
    committeeNameAFET: '외교 문제',
    committeeNameLIBE: '시민적 자유, 사법 및 내무',
    committeeNameAGRI: '농업 및 농촌 개발',
    committeeNameOTHER: '위원회 공통 및 본회의',
  },
  zh: {
    what: '{date}委员会活动报告：监测{total}个委员会，处理{docs}份文件，{active}个委员会有近期活动。',
    whatNoData:
      '{date}委员会活动监测：追踪{total}个委员会。本报告期内EP数据feed中没有可用的近期文件。',
    reportDateLabel: '报告日期：',
    membersLabel: '名成员',
    chairLabel: '主席：',
    productivityRobust: '强劲的',
    productivityModerate: '温和的',
    productivityLow: '低',
    why: CMT_WHY,
    stakeholderHighlyProductive: '{n}份文件——非常高产的时期',
    stakeholderModerateActivity: '{n}份文件——中等活跃度',
    stakeholderNoDocs: CMT_NO_DOCS,
    impactPolitical: CMT_IMPACT_POLITICAL,
    impactPoliticalNone: 'active=0',
    impactEconomic: BRK_IMPACT_ECONOMIC,
    impactSocial: BRK_IMPACT_SOCIAL,
    impactLegal: CMT_IMPACT_LEGAL,
    impactGeopolitical: BRK_IMPACT_GEO_NORMAL,
    actionProcessed: '{abbr}处理了{n}份文件',
    actionConsequence: CMT_ACTION_CONSEQUENCE,
    mistakeDescription: CMT_MISTAKE_DESC,
    mistakeAlternative: CMT_MISTAKE_ALT,
    outlookGood: CMT_OUTLOOK_GOOD,
    outlookConcern: CMT_OUTLOOK_CONCERN,
    lede: '对欧洲议会各专门委员会近期活动和立法效率的系统分析。',
    noRecentDocs: '近期无可用文件',
    committeeMetadataUnavailable:
      '该报告期内委员会主席和成员数据目前无法通过欧洲议会开放数据API获取。委员会活动监测将继续使用可用数据源。',
    adoptedTextsSectionHeading: '按委员会主题的最新通过文本',
    adoptedTextsSummary:
      '欧洲议会在最近几届会议上通过了{count}项文本，涵盖环境、经济、安全、公民自由和农业政策领域。',
    adoptedTextsSummarySingular: '欧洲议会在最近一届会议上通过了1项文本。',
    committeeNameENVI: '环境、公共卫生和食品安全',
    committeeNameECON: '经济和货币事务',
    committeeNameAFET: '对外事务',
    committeeNameLIBE: '公民自由、司法和内政',
    committeeNameAGRI: '农业和农村发展',
    committeeNameOTHER: '跨委员会和全体会议',
  },
};
/**
 * Localized SWOT heading and label strings indexed by ISO 639-1 language code.
 *
 * Consumed by the SWOT builder in `src/aggregator/swot-builder.ts` to render
 * the four-quadrant analysis section in each of the 14 supported article
 * languages.
 */
