// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module dashboard-builder-global
 * @description Per-language entries (es, nl, ar, he, ja, ko, zh) for DASHBOARD_BUILDER_STRINGS.
 */

import type { LanguageMap, DashboardBuilderStrings } from '../../types/index.js';

export const DASHBOARD_BUILDER_STRINGS_GLOBAL: Pick<
  LanguageMap<DashboardBuilderStrings>,
  'es' | 'nl' | 'ar' | 'he' | 'ja' | 'ko' | 'zh'
> = {
  es: {
    votingOverview: 'Resumen de votaciones',
    totalVotes: 'Total de votos',
    adopted: 'Adoptados',
    rejected: 'Rechazados',
    anomalies: 'Anomalías',
    politicalGroupCohesion: 'Cohesión de grupos políticos',
    groupCohesionRates: 'Tasas de cohesión de grupos',
    cohesionPct: 'Cohesión %',
    scheduledActivity: 'Actividad programada',
    plenaryEvents: 'Eventos plenarios',
    committeeMeetings: 'Reuniones de comisión',
    documents: 'Documentos',
    pipelineProcedures: 'Procedimientos en curso',
    parliamentaryQuestions: 'Preguntas parlamentarias',
    questionsFiled: 'Preguntas presentadas',
    bottleneckProcedures: 'Procedimientos con cuello de botella',
    feedActivity: 'Actividad del feed',
    adoptedTexts: 'Textos adoptados',
    events: 'Eventos',
    procedures: 'Procedimientos',
    mepUpdates: 'Actualizaciones de eurodiputados',
    activitySummary: 'Resumen de actividad',
    totalItems: 'Total de elementos',
    feedBreakdown: 'Desglose del feed',
    items: 'Elementos',
    pipelineHealth: 'Salud del pipeline',
    healthScore: 'Puntuación de salud',
    throughput: 'Rendimiento',
    status: 'Estado',
    pipelineStrong: 'Fuerte',
    pipelineModerate: 'Moderado',
    pipelineWeak: 'Débil',
    committeeOverview: 'Resumen de comisiones',
    totalCommittees: 'Total de comisiones',
    activeCommittees: 'Comisiones activas',
    activityRate: 'Tasa de actividad',
    documentsProduced: 'Documentos producidos',
    documentOutputByCommittee: 'Producción documental por comisión',
    documentsPerCommittee: 'Documentos por comisión',
    coalitionAlignment: 'Alineación de coalición',
    alignmentScore: 'Puntuación de alineación',
    votingBlocs: 'Bloques de votación',
    coalitionShift: 'Cambio de coalición',
    coalitionStrengthening: 'Fortalecimiento',
    coalitionWeakening: 'Debilitamiento',
    coalitionStable: 'Estable',
    coalitionRadarChart: 'Radar de coalición',
    pipelineStatus: 'Estado del proceso',
    onTrack: 'En plazo',
    delayed: 'Retrasado',
    blocked: 'Bloqueado',
    fastTracked: 'Acelerado',
    pipelineStatusChart: 'Diagrama de proceso',
    trendAnalysis: 'Análisis de tendencias',
    weekOverWeek: 'Semana a semana',
    monthOverMonth: 'Mes a mes',
    trendImproving: 'Mejora',
    trendDeclining: 'Declive',
    trendStableLabel: 'Estable',
    activityTrendChart: 'Tendencia de actividad',
    stakeholderImpact: 'Impacto en partes interesadas',
    impactScore: 'Puntuación de impacto',
    impactPositive: 'Positivo',
    impactNegative: 'Negativo',
    impactNeutral: 'Neutral',
  },
  nl: {
    votingOverview: 'Stemoverzicht',
    totalVotes: 'Totaal stemmen',
    adopted: 'Aangenomen',
    rejected: 'Verworpen',
    anomalies: 'Afwijkingen',
    politicalGroupCohesion: 'Fractiecohesie',
    groupCohesionRates: 'Fractiecohesiepercentages',
    cohesionPct: 'Cohesie %',
    scheduledActivity: 'Geplande activiteit',
    plenaryEvents: 'Plenaire evenementen',
    committeeMeetings: 'Commissievergaderingen',
    documents: 'Documenten',
    pipelineProcedures: 'Pipeline-procedures',
    parliamentaryQuestions: 'Parlementaire vragen',
    questionsFiled: 'Ingediende vragen',
    bottleneckProcedures: 'Knelpuntprocedures',
    feedActivity: 'Feedactiviteit',
    adoptedTexts: 'Aangenomen teksten',
    events: 'Evenementen',
    procedures: 'Procedures',
    mepUpdates: 'EP-lid-updates',
    activitySummary: 'Activiteitssamenvatting',
    totalItems: 'Totaal items',
    feedBreakdown: 'Feedverdeling',
    items: 'Items',
    pipelineHealth: 'Pipeline-gezondheid',
    healthScore: 'Gezondheidsscore',
    throughput: 'Doorvoer',
    status: 'Status',
    pipelineStrong: 'Sterk',
    pipelineModerate: 'Matig',
    pipelineWeak: 'Zwak',
    committeeOverview: 'Commissieoverzicht',
    totalCommittees: 'Totaal commissies',
    activeCommittees: 'Actieve commissies',
    activityRate: 'Activiteitspercentage',
    documentsProduced: 'Geproduceerde documenten',
    documentOutputByCommittee: 'Documentproductie per commissie',
    documentsPerCommittee: 'Documenten per commissie',
    coalitionAlignment: 'Coalitieafstemming',
    alignmentScore: 'Afstemmingsscore',
    votingBlocs: 'Stemblokken',
    coalitionShift: 'Coalitieverschuiving',
    coalitionStrengthening: 'Versterking',
    coalitionWeakening: 'Verzwakking',
    coalitionStable: 'Stabiel',
    coalitionRadarChart: 'Coalitieradar',
    pipelineStatus: 'Pipelinestatus',
    onTrack: 'Op schema',
    delayed: 'Vertraagd',
    blocked: 'Geblokkeerd',
    fastTracked: 'Versneld',
    pipelineStatusChart: 'Pipelinestatusdiagram',
    trendAnalysis: 'Trendanalyse',
    weekOverWeek: 'Week-op-week',
    monthOverMonth: 'Maand-op-maand',
    trendImproving: 'Verbetering',
    trendDeclining: 'Achteruitgang',
    trendStableLabel: 'Stabiel',
    activityTrendChart: 'Activiteitstrend',
    stakeholderImpact: 'Stakeholderimpact',
    impactScore: 'Impactscore',
    impactPositive: 'Positief',
    impactNegative: 'Negatief',
    impactNeutral: 'Neutraal',
  },
  ar: {
    votingOverview: 'نظرة عامة على التصويت',
    totalVotes: 'إجمالي الأصوات',
    adopted: 'معتمدة',
    rejected: 'مرفوضة',
    anomalies: 'شذوذات',
    politicalGroupCohesion: 'تماسك المجموعات السياسية',
    groupCohesionRates: 'معدلات تماسك المجموعات',
    cohesionPct: 'التماسك %',
    scheduledActivity: 'النشاط المجدول',
    plenaryEvents: 'فعاليات الجلسة العامة',
    committeeMeetings: 'اجتماعات اللجان',
    documents: 'الوثائق',
    pipelineProcedures: 'إجراءات خط الأنابيب',
    parliamentaryQuestions: 'الأسئلة البرلمانية',
    questionsFiled: 'الأسئلة المقدمة',
    bottleneckProcedures: 'إجراءات الاختناق',
    feedActivity: 'نشاط التغذية',
    adoptedTexts: 'النصوص المعتمدة',
    events: 'الفعاليات',
    procedures: 'الإجراءات',
    mepUpdates: 'تحديثات الأعضاء',
    activitySummary: 'ملخص النشاط',
    totalItems: 'إجمالي العناصر',
    feedBreakdown: 'توزيع التغذية',
    items: 'العناصر',
    pipelineHealth: 'صحة خط الأنابيب',
    healthScore: 'درجة الصحة',
    throughput: 'معدل الإنتاجية',
    status: 'الحالة',
    pipelineStrong: 'قوي',
    pipelineModerate: 'معتدل',
    pipelineWeak: 'ضعيف',
    committeeOverview: 'نظرة عامة على اللجان',
    totalCommittees: 'إجمالي اللجان',
    activeCommittees: 'اللجان النشطة',
    activityRate: 'معدل النشاط',
    documentsProduced: 'الوثائق المنتجة',
    documentOutputByCommittee: 'إنتاج الوثائق حسب اللجنة',
    documentsPerCommittee: 'الوثائق لكل لجنة',
    coalitionAlignment: 'توافق التحالف',
    alignmentScore: 'درجة التوافق',
    votingBlocs: 'كتل التصويت',
    coalitionShift: 'تحول التحالف',
    coalitionStrengthening: 'تعزيز',
    coalitionWeakening: 'إضعاف',
    coalitionStable: 'مستقر',
    coalitionRadarChart: 'رادار التحالف',
    pipelineStatus: 'حالة الإجراءات',
    onTrack: 'في المسار',
    delayed: 'متأخر',
    blocked: 'محظور',
    fastTracked: 'مسار سريع',
    pipelineStatusChart: 'مخطط حالة الإجراءات',
    trendAnalysis: 'تحليل الاتجاهات',
    weekOverWeek: 'أسبوع إلى أسبوع',
    monthOverMonth: 'شهر إلى شهر',
    trendImproving: 'تحسن',
    trendDeclining: 'تراجع',
    trendStableLabel: 'مستقر',
    activityTrendChart: 'اتجاه النشاط',
    stakeholderImpact: 'تأثير أصحاب المصلحة',
    impactScore: 'درجة التأثير',
    impactPositive: 'إيجابي',
    impactNegative: 'سلبي',
    impactNeutral: 'محايد',
  },
  he: {
    votingOverview: 'סקירת הצבעות',
    totalVotes: 'סך ההצבעות',
    adopted: 'אומצו',
    rejected: 'נדחו',
    anomalies: 'חריגות',
    politicalGroupCohesion: 'לכידות קבוצות פוליטיות',
    groupCohesionRates: 'שיעורי לכידות קבוצתית',
    cohesionPct: 'לכידות %',
    scheduledActivity: 'פעילות מתוכננת',
    plenaryEvents: 'אירועי מליאה',
    committeeMeetings: 'ישיבות ועדה',
    documents: 'מסמכים',
    pipelineProcedures: 'הליכי צינור',
    parliamentaryQuestions: 'שאילתות פרלמנטריות',
    questionsFiled: 'שאילתות שהוגשו',
    bottleneckProcedures: 'הליכי צוואר בקבוק',
    feedActivity: 'פעילות פיד',
    adoptedTexts: 'טקסטים שאומצו',
    events: 'אירועים',
    procedures: 'הליכים',
    mepUpdates: 'עדכוני חברי פרלמנט',
    activitySummary: 'סיכום פעילות',
    totalItems: 'סך הפריטים',
    feedBreakdown: 'פירוט פיד',
    items: 'פריטים',
    pipelineHealth: 'בריאות צינור',
    healthScore: 'ציון בריאות',
    throughput: 'תפוקה',
    status: 'מצב',
    pipelineStrong: 'חזק',
    pipelineModerate: 'בינוני',
    pipelineWeak: 'חלש',
    committeeOverview: 'סקירת ועדות',
    totalCommittees: 'סך הוועדות',
    activeCommittees: 'ועדות פעילות',
    activityRate: 'שיעור פעילות',
    documentsProduced: 'מסמכים שהופקו',
    documentOutputByCommittee: 'תפוקת מסמכים לפי ועדה',
    documentsPerCommittee: 'מסמכים לכל ועדה',
    coalitionAlignment: 'יישור קואליציה',
    alignmentScore: 'ציון יישור',
    votingBlocs: 'גושי הצבעה',
    coalitionShift: 'שינוי קואליציוני',
    coalitionStrengthening: 'התחזקות',
    coalitionWeakening: 'התחלשות',
    coalitionStable: 'יציב',
    coalitionRadarChart: 'מכ"ם קואליציוני',
    pipelineStatus: 'סטטוס צינור',
    onTrack: 'על המסלול',
    delayed: 'מאוחר',
    blocked: 'חסום',
    fastTracked: 'מסלול מהיר',
    pipelineStatusChart: 'תרשים צינור',
    trendAnalysis: 'ניתוח מגמות',
    weekOverWeek: 'שבוע לשבוע',
    monthOverMonth: 'חודש לחודש',
    trendImproving: 'שיפור',
    trendDeclining: 'ירידה',
    trendStableLabel: 'יציב',
    activityTrendChart: 'מגמת פעילות',
    stakeholderImpact: 'השפעה על בעלי עניין',
    impactScore: 'ציון השפעה',
    impactPositive: 'חיובי',
    impactNegative: 'שלילי',
    impactNeutral: 'ניטרלי',
  },
  ja: {
    votingOverview: '投票概要',
    totalVotes: '総投票数',
    adopted: '採択',
    rejected: '否決',
    anomalies: '異常',
    politicalGroupCohesion: '政治グループ結束力',
    groupCohesionRates: 'グループ結束率',
    cohesionPct: '結束率 %',
    scheduledActivity: '予定された活動',
    plenaryEvents: '本会議イベント',
    committeeMeetings: '委員会会議',
    documents: '文書',
    pipelineProcedures: 'パイプライン手続き',
    parliamentaryQuestions: '議会質問',
    questionsFiled: '提出された質問',
    bottleneckProcedures: 'ボトルネック手続き',
    feedActivity: 'フィード活動',
    adoptedTexts: '採択テキスト',
    events: 'イベント',
    procedures: '手続き',
    mepUpdates: 'MEP更新',
    activitySummary: '活動サマリー',
    totalItems: '総項目数',
    feedBreakdown: 'フィード内訳',
    items: '項目',
    pipelineHealth: 'パイプライン健全性',
    healthScore: '健全性スコア',
    throughput: 'スループット',
    status: 'ステータス',
    pipelineStrong: '強い',
    pipelineModerate: '中程度',
    pipelineWeak: '弱い',
    committeeOverview: '委員会概要',
    totalCommittees: '委員会総数',
    activeCommittees: '活動中の委員会',
    activityRate: '活動率',
    documentsProduced: '作成された文書',
    documentOutputByCommittee: '委員会別文書産出',
    documentsPerCommittee: '委員会あたりの文書数',
    coalitionAlignment: '連立調整',
    alignmentScore: '調整スコア',
    votingBlocs: '投票ブロック',
    coalitionShift: '連立変化',
    coalitionStrengthening: '強化',
    coalitionWeakening: '弱体化',
    coalitionStable: '安定',
    coalitionRadarChart: '連立レーダー',
    pipelineStatus: 'パイプライン状況',
    onTrack: '予定通り',
    delayed: '遅延',
    blocked: '停滞',
    fastTracked: '加速',
    pipelineStatusChart: 'パイプライン状況図',
    trendAnalysis: 'トレンド分析',
    weekOverWeek: '週次比較',
    monthOverMonth: '月次比較',
    trendImproving: '改善',
    trendDeclining: '低下',
    trendStableLabel: '安定',
    activityTrendChart: '活動トレンド',
    stakeholderImpact: '利害関係者への影響',
    impactScore: '影響スコア',
    impactPositive: 'ポジティブ',
    impactNegative: 'ネガティブ',
    impactNeutral: '中立',
  },
  ko: {
    votingOverview: '투표 개요',
    totalVotes: '총 투표 수',
    adopted: '채택',
    rejected: '거부',
    anomalies: '이상',
    politicalGroupCohesion: '정치 그룹 결속력',
    groupCohesionRates: '그룹 결속률',
    cohesionPct: '결속률 %',
    scheduledActivity: '예정된 활동',
    plenaryEvents: '본회의 일정',
    committeeMeetings: '위원회 회의',
    documents: '문서',
    pipelineProcedures: '파이프라인 절차',
    parliamentaryQuestions: '의회 질의',
    questionsFiled: '제출된 질의',
    bottleneckProcedures: '병목 절차',
    feedActivity: '피드 활동',
    adoptedTexts: '채택 텍스트',
    events: '행사',
    procedures: '절차',
    mepUpdates: 'MEP 업데이트',
    activitySummary: '활동 요약',
    totalItems: '총 항목 수',
    feedBreakdown: '피드 구성',
    items: '항목',
    pipelineHealth: '파이프라인 건전성',
    healthScore: '건전성 점수',
    throughput: '처리량',
    status: '상태',
    pipelineStrong: '강함',
    pipelineModerate: '보통',
    pipelineWeak: '약함',
    committeeOverview: '위원회 개요',
    totalCommittees: '총 위원회 수',
    activeCommittees: '활동 위원회',
    activityRate: '활동률',
    documentsProduced: '생산된 문서',
    documentOutputByCommittee: '위원회별 문서 산출',
    documentsPerCommittee: '위원회당 문서 수',
    coalitionAlignment: '연립 정렬',
    alignmentScore: '정렬 점수',
    votingBlocs: '투표 블록',
    coalitionShift: '연립 변화',
    coalitionStrengthening: '강화',
    coalitionWeakening: '약화',
    coalitionStable: '안정',
    coalitionRadarChart: '연립 레이더',
    pipelineStatus: '파이프라인 현황',
    onTrack: '정상 진행',
    delayed: '지연',
    blocked: '차단',
    fastTracked: '신속 처리',
    pipelineStatusChart: '파이프라인 현황 차트',
    trendAnalysis: '추세 분석',
    weekOverWeek: '주 대비 주',
    monthOverMonth: '월 대비 월',
    trendImproving: '개선',
    trendDeclining: '하락',
    trendStableLabel: '안정',
    activityTrendChart: '활동 추세',
    stakeholderImpact: '이해관계자 영향',
    impactScore: '영향 점수',
    impactPositive: '긍정적',
    impactNegative: '부정적',
    impactNeutral: '중립',
  },
  zh: {
    votingOverview: '投票概览',
    totalVotes: '总投票数',
    adopted: '通过',
    rejected: '否决',
    anomalies: '异常',
    politicalGroupCohesion: '政治团体凝聚力',
    groupCohesionRates: '团体凝聚率',
    cohesionPct: '凝聚力 %',
    scheduledActivity: '计划活动',
    plenaryEvents: '全会活动',
    committeeMeetings: '委员会会议',
    documents: '文件',
    pipelineProcedures: '管道程序',
    parliamentaryQuestions: '议会质询',
    questionsFiled: '提交的质询',
    bottleneckProcedures: '瓶颈程序',
    feedActivity: '信息流活动',
    adoptedTexts: '通过的文本',
    events: '活动',
    procedures: '程序',
    mepUpdates: '议员更新',
    activitySummary: '活动摘要',
    totalItems: '总项目数',
    feedBreakdown: '信息流构成',
    items: '项目',
    pipelineHealth: '管道健康度',
    healthScore: '健康分数',
    throughput: '吞吐量',
    status: '状态',
    pipelineStrong: '强',
    pipelineModerate: '中等',
    pipelineWeak: '弱',
    committeeOverview: '委员会概览',
    totalCommittees: '委员会总数',
    activeCommittees: '活跃委员会',
    activityRate: '活动率',
    documentsProduced: '产出文件',
    documentOutputByCommittee: '各委员会文件产出',
    documentsPerCommittee: '每委员会文件数',
    coalitionAlignment: '联盟对齐',
    alignmentScore: '对齐分数',
    votingBlocs: '投票集团',
    coalitionShift: '联盟转变',
    coalitionStrengthening: '加强',
    coalitionWeakening: '削弱',
    coalitionStable: '稳定',
    coalitionRadarChart: '联盟雷达图',
    pipelineStatus: '流程状态',
    onTrack: '按时',
    delayed: '延误',
    blocked: '阻塞',
    fastTracked: '加速',
    pipelineStatusChart: '流程状态图',
    trendAnalysis: '趋势分析',
    weekOverWeek: '周环比',
    monthOverMonth: '月环比',
    trendImproving: '改善',
    trendDeclining: '下降',
    trendStableLabel: '稳定',
    activityTrendChart: '活动趋势',
    stakeholderImpact: '利益相关方影响',
    impactScore: '影响分数',
    impactPositive: '正面',
    impactNegative: '负面',
    impactNeutral: '中立',
  },
};
