// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module dashboard-builder-eu
 * @description Per-language entries (en, sv, da, no, fi, de, fr) for DASHBOARD_BUILDER_STRINGS.
 */

import type { LanguageMap, DashboardBuilderStrings } from '../../types/index.js';

export const DASHBOARD_BUILDER_STRINGS_EU: Pick<
  LanguageMap<DashboardBuilderStrings>,
  'en' | 'sv' | 'da' | 'no' | 'fi' | 'de' | 'fr'
> = {
  en: {
    votingOverview: 'Voting Overview',
    totalVotes: 'Total Votes',
    adopted: 'Adopted',
    rejected: 'Rejected',
    anomalies: 'Anomalies',
    politicalGroupCohesion: 'Political Group Cohesion',
    groupCohesionRates: 'Group Cohesion Rates',
    cohesionPct: 'Cohesion %',
    scheduledActivity: 'Scheduled Activity',
    plenaryEvents: 'Plenary Events',
    committeeMeetings: 'Committee Meetings',
    documents: 'Documents',
    pipelineProcedures: 'Pipeline Procedures',
    parliamentaryQuestions: 'Parliamentary Questions',
    questionsFiled: 'Questions Filed',
    bottleneckProcedures: 'Bottleneck Procedures',
    feedActivity: 'Feed Activity',
    adoptedTexts: 'Adopted Texts',
    events: 'Events',
    procedures: 'Procedures',
    mepUpdates: 'MEP Updates',
    activitySummary: 'Activity Summary',
    totalItems: 'Total Items',
    feedBreakdown: 'Feed Breakdown',
    items: 'Items',
    pipelineHealth: 'Pipeline Health',
    healthScore: 'Health Score',
    throughput: 'Throughput',
    status: 'Status',
    pipelineStrong: 'Strong',
    pipelineModerate: 'Moderate',
    pipelineWeak: 'Weak',
    committeeOverview: 'Committee Overview',
    totalCommittees: 'Total Committees',
    activeCommittees: 'Active Committees',
    activityRate: 'Activity Rate',
    documentsProduced: 'Documents Produced',
    documentOutputByCommittee: 'Document Output by Committee',
    documentsPerCommittee: 'Documents per Committee',
    coalitionAlignment: 'Coalition Alignment',
    alignmentScore: 'Alignment Score',
    votingBlocs: 'Voting Blocs',
    coalitionShift: 'Coalition Shift',
    coalitionStrengthening: 'Strengthening',
    coalitionWeakening: 'Weakening',
    coalitionStable: 'Stable',
    coalitionRadarChart: 'Coalition Radar',
    pipelineStatus: 'Pipeline Status',
    onTrack: 'On Track',
    delayed: 'Delayed',
    blocked: 'Blocked',
    fastTracked: 'Fast-Tracked',
    pipelineStatusChart: 'Pipeline Status Chart',
    trendAnalysis: 'Trend Analysis',
    weekOverWeek: 'Week-over-Week',
    monthOverMonth: 'Month-over-Month',
    trendImproving: 'Improving',
    trendDeclining: 'Declining',
    trendStableLabel: 'Stable',
    activityTrendChart: 'Activity Trend',
    stakeholderImpact: 'Stakeholder Impact',
    impactScore: 'Impact Score',
    impactPositive: 'Positive',
    impactNegative: 'Negative',
    impactNeutral: 'Neutral',
  },
  sv: {
    votingOverview: 'Röstningsöversikt',
    totalVotes: 'Totala röster',
    adopted: 'Antagna',
    rejected: 'Avvisade',
    anomalies: 'Anomalier',
    politicalGroupCohesion: 'Politisk gruppsammanhållning',
    groupCohesionRates: 'Gruppsammanhållning',
    cohesionPct: 'Sammanhållning %',
    scheduledActivity: 'Planerad aktivitet',
    plenaryEvents: 'Plenarsessioner',
    committeeMeetings: 'Utskottsmöten',
    documents: 'Dokument',
    pipelineProcedures: 'Pipelineförfaranden',
    parliamentaryQuestions: 'Parlamentariska frågor',
    questionsFiled: 'Inlämnade frågor',
    bottleneckProcedures: 'Flaskhalsförfaranden',
    feedActivity: 'Flödesaktivitet',
    adoptedTexts: 'Antagna texter',
    events: 'Händelser',
    procedures: 'Förfaranden',
    mepUpdates: 'MEP-uppdateringar',
    activitySummary: 'Aktivitetssammanfattning',
    totalItems: 'Totalt antal',
    feedBreakdown: 'Flödesfördelning',
    items: 'Objekt',
    pipelineHealth: 'Pipelinehälsa',
    healthScore: 'Hälsopoäng',
    throughput: 'Genomströmning',
    status: 'Status',
    pipelineStrong: 'Stark',
    pipelineModerate: 'Måttlig',
    pipelineWeak: 'Svag',
    committeeOverview: 'Utskottsöversikt',
    totalCommittees: 'Totala utskott',
    activeCommittees: 'Aktiva utskott',
    activityRate: 'Aktivitetsgrad',
    documentsProduced: 'Producerade dokument',
    documentOutputByCommittee: 'Dokumentproduktion per utskott',
    documentsPerCommittee: 'Dokument per utskott',
    coalitionAlignment: 'Koalitionsinriktning',
    alignmentScore: 'Inriktningsmätning',
    votingBlocs: 'Röstningsblock',
    coalitionShift: 'Koalitionsskifte',
    coalitionStrengthening: 'Stärks',
    coalitionWeakening: 'Försvagas',
    coalitionStable: 'Stabil',
    coalitionRadarChart: 'Koalitionsradar',
    pipelineStatus: 'Pipelinestatus',
    onTrack: 'På rätt spår',
    delayed: 'Försenad',
    blocked: 'Blockerad',
    fastTracked: 'Snabbspårad',
    pipelineStatusChart: 'Pipelinestatusdiagram',
    trendAnalysis: 'Trendanalys',
    weekOverWeek: 'Vecka-till-vecka',
    monthOverMonth: 'Månad-till-månad',
    trendImproving: 'Förbättras',
    trendDeclining: 'Försämras',
    trendStableLabel: 'Stabil',
    activityTrendChart: 'Aktivitetstrend',
    stakeholderImpact: 'Intressentpåverkan',
    impactScore: 'Påverkanspoäng',
    impactPositive: 'Positiv',
    impactNegative: 'Negativ',
    impactNeutral: 'Neutral',
  },
  da: {
    votingOverview: 'Afstemningsoversigt',
    totalVotes: 'Samlede stemmer',
    adopted: 'Vedtaget',
    rejected: 'Afvist',
    anomalies: 'Anomalier',
    politicalGroupCohesion: 'Politisk gruppesamhørighed',
    groupCohesionRates: 'Gruppesamhørighed',
    cohesionPct: 'Samhørighed %',
    scheduledActivity: 'Planlagt aktivitet',
    plenaryEvents: 'Plenarmøder',
    committeeMeetings: 'Udvalgsmøder',
    documents: 'Dokumenter',
    pipelineProcedures: 'Pipeline-procedurer',
    parliamentaryQuestions: 'Parlamentariske spørgsmål',
    questionsFiled: 'Indsendte spørgsmål',
    bottleneckProcedures: 'Flaskehalsprocedurer',
    feedActivity: 'Feed-aktivitet',
    adoptedTexts: 'Vedtagne tekster',
    events: 'Begivenheder',
    procedures: 'Procedurer',
    mepUpdates: 'MEP-opdateringer',
    activitySummary: 'Aktivitetsoversigt',
    totalItems: 'Samlede elementer',
    feedBreakdown: 'Feed-fordeling',
    items: 'Elementer',
    pipelineHealth: 'Pipeline-sundhed',
    healthScore: 'Sundhedsscore',
    throughput: 'Gennemløb',
    status: 'Status',
    pipelineStrong: 'Stærk',
    pipelineModerate: 'Moderat',
    pipelineWeak: 'Svag',
    committeeOverview: 'Udvalgsoversigt',
    totalCommittees: 'Samlede udvalg',
    activeCommittees: 'Aktive udvalg',
    activityRate: 'Aktivitetsrate',
    documentsProduced: 'Producerede dokumenter',
    documentOutputByCommittee: 'Dokumentproduktion per udvalg',
    documentsPerCommittee: 'Dokumenter per udvalg',
    coalitionAlignment: 'Koalitionsafstemning',
    alignmentScore: 'Indretningsscore',
    votingBlocs: 'Afstemningsblokke',
    coalitionShift: 'Koalitionsskift',
    coalitionStrengthening: 'Styrkelse',
    coalitionWeakening: 'Svækkelse',
    coalitionStable: 'Stabil',
    coalitionRadarChart: 'Koalitionsradar',
    pipelineStatus: 'Pipeline-status',
    onTrack: 'På sporet',
    delayed: 'Forsinket',
    blocked: 'Blokeret',
    fastTracked: 'Fremskyndet',
    pipelineStatusChart: 'Pipeline-statusdiagram',
    trendAnalysis: 'Trendanalyse',
    weekOverWeek: 'Uge-til-uge',
    monthOverMonth: 'Måned-til-måned',
    trendImproving: 'Forbedring',
    trendDeclining: 'Fald',
    trendStableLabel: 'Stabil',
    activityTrendChart: 'Aktivitetstrend',
    stakeholderImpact: 'Interessentpåvirkning',
    impactScore: 'Påvirkningsscore',
    impactPositive: 'Positiv',
    impactNegative: 'Negativ',
    impactNeutral: 'Neutral',
  },
  no: {
    votingOverview: 'Avstemningsoversikt',
    totalVotes: 'Totale stemmer',
    adopted: 'Vedtatt',
    rejected: 'Avvist',
    anomalies: 'Avvik',
    politicalGroupCohesion: 'Politisk gruppesamhold',
    groupCohesionRates: 'Gruppesamhold',
    cohesionPct: 'Samhold %',
    scheduledActivity: 'Planlagt aktivitet',
    plenaryEvents: 'Plenarmøter',
    committeeMeetings: 'Komitémøter',
    documents: 'Dokumenter',
    pipelineProcedures: 'Pipeline-prosedyrer',
    parliamentaryQuestions: 'Parlamentariske spørsmål',
    questionsFiled: 'Innsendte spørsmål',
    bottleneckProcedures: 'Flaskehalsprosedyrer',
    feedActivity: 'Feed-aktivitet',
    adoptedTexts: 'Vedtatte tekster',
    events: 'Hendelser',
    procedures: 'Prosedyrer',
    mepUpdates: 'MEP-oppdateringer',
    activitySummary: 'Aktivitetssammendrag',
    totalItems: 'Totale elementer',
    feedBreakdown: 'Feed-fordeling',
    items: 'Elementer',
    pipelineHealth: 'Pipeline-helse',
    healthScore: 'Helsescore',
    throughput: 'Gjennomstrømning',
    status: 'Status',
    pipelineStrong: 'Sterk',
    pipelineModerate: 'Moderat',
    pipelineWeak: 'Svak',
    committeeOverview: 'Komitéoversikt',
    totalCommittees: 'Totale komiteer',
    activeCommittees: 'Aktive komiteer',
    activityRate: 'Aktivitetsrate',
    documentsProduced: 'Produserte dokumenter',
    documentOutputByCommittee: 'Dokumentproduksjon per komité',
    documentsPerCommittee: 'Dokumenter per komité',
    coalitionAlignment: 'Koalisjonsretting',
    alignmentScore: 'Retningsscore',
    votingBlocs: 'Stemmeblokker',
    coalitionShift: 'Koalisjonsskifte',
    coalitionStrengthening: 'Styrking',
    coalitionWeakening: 'Svekkelse',
    coalitionStable: 'Stabil',
    coalitionRadarChart: 'Koalisjonsradar',
    pipelineStatus: 'Pipeline-status',
    onTrack: 'På rett spor',
    delayed: 'Forsinket',
    blocked: 'Blokkert',
    fastTracked: 'Hurtigspor',
    pipelineStatusChart: 'Pipeline-statusdiagram',
    trendAnalysis: 'Trendanalyse',
    weekOverWeek: 'Uke-til-uke',
    monthOverMonth: 'Måned-til-måned',
    trendImproving: 'Forbedring',
    trendDeclining: 'Nedgang',
    trendStableLabel: 'Stabil',
    activityTrendChart: 'Aktivitetstrend',
    stakeholderImpact: 'Interessentpåvirkning',
    impactScore: 'Påvirkningsscore',
    impactPositive: 'Positiv',
    impactNegative: 'Negativ',
    impactNeutral: 'Nøytral',
  },
  fi: {
    votingOverview: 'Äänestyskatsaus',
    totalVotes: 'Äänestykset yhteensä',
    adopted: 'Hyväksytyt',
    rejected: 'Hylätyt',
    anomalies: 'Poikkeamat',
    politicalGroupCohesion: 'Poliittisten ryhmien yhtenäisyys',
    groupCohesionRates: 'Ryhmäyhtenäisyys',
    cohesionPct: 'Yhtenäisyys %',
    scheduledActivity: 'Aikataulutettu toiminta',
    plenaryEvents: 'Täysistuntotapahtumat',
    committeeMeetings: 'Valiokuntakokoukset',
    documents: 'Asiakirjat',
    pipelineProcedures: 'Pipeline-menettelyt',
    parliamentaryQuestions: 'Parlamentaariset kysymykset',
    questionsFiled: 'Jätetyt kysymykset',
    bottleneckProcedures: 'Pullonkaulamenettelyt',
    feedActivity: 'Syöteaktiivisuus',
    adoptedTexts: 'Hyväksytyt tekstit',
    events: 'Tapahtumat',
    procedures: 'Menettelyt',
    mepUpdates: 'MEP-päivitykset',
    activitySummary: 'Toimintayhteenveto',
    totalItems: 'Kohteet yhteensä',
    feedBreakdown: 'Syötejakauma',
    items: 'Kohteet',
    pipelineHealth: 'Pipeline-terveys',
    healthScore: 'Terveyspisteet',
    throughput: 'Läpäisyaste',
    status: 'Tila',
    pipelineStrong: 'Vahva',
    pipelineModerate: 'Kohtalainen',
    pipelineWeak: 'Heikko',
    committeeOverview: 'Valiokuntakatsaus',
    totalCommittees: 'Valiokunnat yhteensä',
    activeCommittees: 'Aktiiviset valiokunnat',
    activityRate: 'Aktiivisuusaste',
    documentsProduced: 'Tuotetut asiakirjat',
    documentOutputByCommittee: 'Asiakirjatuotanto valiokunnittain',
    documentsPerCommittee: 'Asiakirjat per valiokunta',
    coalitionAlignment: 'Koalition suuntaus',
    alignmentScore: 'Suuntauspisteet',
    votingBlocs: 'Äänestysblokki',
    coalitionShift: 'Koalitiomuutos',
    coalitionStrengthening: 'Vahvistuminen',
    coalitionWeakening: 'Heikkeneminen',
    coalitionStable: 'Vakaa',
    coalitionRadarChart: 'Koalitiotutkataulukko',
    pipelineStatus: 'Pipeline-tila',
    onTrack: 'Aikataulussa',
    delayed: 'Viivästynyt',
    blocked: 'Estetty',
    fastTracked: 'Pikakaistalla',
    pipelineStatusChart: 'Pipeline-tila kaavio',
    trendAnalysis: 'Trendikatsaus',
    weekOverWeek: 'Viikko edelliseen',
    monthOverMonth: 'Kuukausi edelliseen',
    trendImproving: 'Paranee',
    trendDeclining: 'Heikentyy',
    trendStableLabel: 'Vakaa',
    activityTrendChart: 'Toimintakäyrä',
    stakeholderImpact: 'Sidosryhmävaikutus',
    impactScore: 'Vaikutuspisteet',
    impactPositive: 'Positiivinen',
    impactNegative: 'Negatiivinen',
    impactNeutral: 'Neutraali',
  },
  de: {
    votingOverview: 'Abstimmungsübersicht',
    totalVotes: 'Gesamtabstimmungen',
    adopted: 'Angenommen',
    rejected: 'Abgelehnt',
    anomalies: 'Anomalien',
    politicalGroupCohesion: 'Fraktionskohäsion',
    groupCohesionRates: 'Fraktionskohäsionsraten',
    cohesionPct: 'Kohäsion %',
    scheduledActivity: 'Geplante Aktivität',
    plenaryEvents: 'Plenarveranstaltungen',
    committeeMeetings: 'Ausschusssitzungen',
    documents: 'Dokumente',
    pipelineProcedures: 'Pipeline-Verfahren',
    parliamentaryQuestions: 'Parlamentarische Anfragen',
    questionsFiled: 'Eingereichte Anfragen',
    bottleneckProcedures: 'Engpassverfahren',
    feedActivity: 'Feed-Aktivität',
    adoptedTexts: 'Angenommene Texte',
    events: 'Veranstaltungen',
    procedures: 'Verfahren',
    mepUpdates: 'MdEP-Aktualisierungen',
    activitySummary: 'Aktivitätszusammenfassung',
    totalItems: 'Gesamtelemente',
    feedBreakdown: 'Feed-Aufschlüsselung',
    items: 'Elemente',
    pipelineHealth: 'Pipeline-Gesundheit',
    healthScore: 'Gesundheitswert',
    throughput: 'Durchsatz',
    status: 'Status',
    pipelineStrong: 'Stark',
    pipelineModerate: 'Mäßig',
    pipelineWeak: 'Schwach',
    committeeOverview: 'Ausschussübersicht',
    totalCommittees: 'Gesamtausschüsse',
    activeCommittees: 'Aktive Ausschüsse',
    activityRate: 'Aktivitätsrate',
    documentsProduced: 'Produzierte Dokumente',
    documentOutputByCommittee: 'Dokumentenproduktion je Ausschuss',
    documentsPerCommittee: 'Dokumente je Ausschuss',
    coalitionAlignment: 'Koalitionsausrichtung',
    alignmentScore: 'Ausrichtungswert',
    votingBlocs: 'Abstimmungsblöcke',
    coalitionShift: 'Koalitionswandel',
    coalitionStrengthening: 'Stärkung',
    coalitionWeakening: 'Schwächung',
    coalitionStable: 'Stabil',
    coalitionRadarChart: 'Koalitionsradar',
    pipelineStatus: 'Pipeline-Status',
    onTrack: 'Im Zeitplan',
    delayed: 'Verzögert',
    blocked: 'Blockiert',
    fastTracked: 'Beschleunigt',
    pipelineStatusChart: 'Pipeline-Statusdiagramm',
    trendAnalysis: 'Trendanalyse',
    weekOverWeek: 'Woche-zu-Woche',
    monthOverMonth: 'Monat-zu-Monat',
    trendImproving: 'Verbesserung',
    trendDeclining: 'Rückgang',
    trendStableLabel: 'Stabil',
    activityTrendChart: 'Aktivitätstrend',
    stakeholderImpact: 'Stakeholder-Einfluss',
    impactScore: 'Einflusswert',
    impactPositive: 'Positiv',
    impactNegative: 'Negativ',
    impactNeutral: 'Neutral',
  },
  fr: {
    votingOverview: 'Aperçu des votes',
    totalVotes: 'Total des votes',
    adopted: 'Adoptés',
    rejected: 'Rejetés',
    anomalies: 'Anomalies',
    politicalGroupCohesion: 'Cohésion des groupes politiques',
    groupCohesionRates: 'Taux de cohésion des groupes',
    cohesionPct: 'Cohésion %',
    scheduledActivity: 'Activité programmée',
    plenaryEvents: 'Événements pléniers',
    committeeMeetings: 'Réunions de commission',
    documents: 'Documents',
    pipelineProcedures: 'Procédures en cours',
    parliamentaryQuestions: 'Questions parlementaires',
    questionsFiled: 'Questions déposées',
    bottleneckProcedures: "Procédures en goulot d'étranglement",
    feedActivity: 'Activité du flux',
    adoptedTexts: 'Textes adoptés',
    events: 'Événements',
    procedures: 'Procédures',
    mepUpdates: 'Mises à jour des députés',
    activitySummary: "Résumé d'activité",
    totalItems: 'Total des éléments',
    feedBreakdown: 'Répartition du flux',
    items: 'Éléments',
    pipelineHealth: 'Santé du pipeline',
    healthScore: 'Score de santé',
    throughput: 'Débit',
    status: 'Statut',
    pipelineStrong: 'Fort',
    pipelineModerate: 'Modéré',
    pipelineWeak: 'Faible',
    committeeOverview: 'Aperçu des commissions',
    totalCommittees: 'Total des commissions',
    activeCommittees: 'Commissions actives',
    activityRate: "Taux d'activité",
    documentsProduced: 'Documents produits',
    documentOutputByCommittee: 'Production documentaire par commission',
    documentsPerCommittee: 'Documents par commission',
    coalitionAlignment: 'Alignement de coalition',
    alignmentScore: "Score d'alignement",
    votingBlocs: 'Blocs de vote',
    coalitionShift: 'Évolution de coalition',
    coalitionStrengthening: 'Renforcement',
    coalitionWeakening: 'Affaiblissement',
    coalitionStable: 'Stable',
    coalitionRadarChart: 'Radar de coalition',
    pipelineStatus: 'État du pipeline',
    onTrack: 'Dans les délais',
    delayed: 'Retardé',
    blocked: 'Bloqué',
    fastTracked: 'Accéléré',
    pipelineStatusChart: 'Diagramme du pipeline',
    trendAnalysis: 'Analyse des tendances',
    weekOverWeek: 'Semaine sur semaine',
    monthOverMonth: 'Mois sur mois',
    trendImproving: 'Amélioration',
    trendDeclining: 'Déclin',
    trendStableLabel: 'Stable',
    activityTrendChart: "Tendance d'activité",
    stakeholderImpact: 'Impact sur les parties prenantes',
    impactScore: "Score d'impact",
    impactPositive: 'Positif',
    impactNegative: 'Négatif',
    impactNeutral: 'Neutre',
  },
};
