// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/DeepAnalysis
 * @description Deep-analysis article strings and quality labels (14 languages).
 *
 * Per-language strings live together so a translator can update one language
 * for this article type without touching any other article type.
 */

import type { LanguageMap, DeepAnalysisStrings } from '../../types/index.js';
export const DEEP_ANALYSIS_STRINGS: LanguageMap<DeepAnalysisStrings> = {
  en: {
    sectionHeading: 'Deep Political Analysis',
    whatHeading: 'What Happened',
    whoHeading: 'Key Actors',
    whenHeading: 'Timeline',
    whyHeading: 'Why It Matters — Root Causes',
    stakeholderHeading: 'Winners & Losers',
    winnerLabel: 'Winner',
    loserLabel: 'Loser',
    neutralLabel: 'Neutral',
    impactHeading: 'Impact Assessment',
    politicalLabel: 'Political',
    economicLabel: 'Economic',
    socialLabel: 'Social',
    legalLabel: 'Legal',
    geopoliticalLabel: 'Geopolitical',
    consequencesHeading: 'Actions → Consequences',
    actionLabel: 'Action',
    consequenceLabel: 'Consequence',
    severityColumnLabel: 'Severity',
    mistakesHeading: 'Miscalculations & Missed Opportunities',
    alternativeLabel: 'Should have',
    outlookHeading: 'Strategic Outlook',
    severityLow: 'Low',
    severityMedium: 'Medium',
    severityHigh: 'High',
    severityCritical: 'Critical',

    executiveSummaryHeading: 'Executive Summary',
    confidenceHigh: 'High Confidence',
    confidenceMedium: 'Medium Confidence',
    confidenceLow: 'Low Confidence',
    evidenceRefsHeading: 'Evidence',
    counterArgumentsHeading: 'Counter-arguments',
    conclusionLabel: 'Conclusion:',
    premiseLabel: 'Premise:',
    inferenceLabel: 'Inference:',
    reasoningChainsHeading: 'Reasoning Chains',
    scenarioPlanningHeading: 'Scenario Planning',
    bestCaseLabel: 'Best Case',
    worstCaseLabel: 'Worst Case',
    mostLikelyLabel: 'Most Likely',
    wildcardsLabel: 'Wildcards',
    probabilityLabel: 'Probability',
    triggersLabel: 'Triggers',
    impliedImpactsLabel: 'Implied Impacts',
    timelineLabel: 'Timeline',
    analysisMethodologyHeading: 'Analysis Methodology',
    iterationCountLabel: 'Iterations',
    evidenceStrengthLabel: 'Evidence Strength',
    evidenceStrong: 'Strong',
    evidenceModerate: 'Moderate',
    evidenceWeak: 'Weak',
    iterationInitial: 'Initial Assessment',
    iterationStakeholderChallenge: 'Stakeholder Challenge',
    iterationEvidenceValidation: 'Evidence Validation',
    iterationSynthesis: 'Synthesis',
    overallConfidenceLabel: 'Overall Confidence',
    pendingNotice:
      'Analysis pending — this section will be completed by the editorial intelligence workflow.',
    perspectivesHeading: 'Multi-Stakeholder Perspectives',
    outcomeMatrixHeading: 'Stakeholder Outcome Matrix',
    confidenceLabel: 'Confidence',
    politicalGroupsLabel: 'Political Groups',
    civilSocietyLabel: 'Civil Society',
    industryLabel: 'Industry',
    nationalGovtsLabel: 'National Governments',
    citizensLabel: 'Citizens',
    euInstitutionsLabel: 'EU Institutions',
    positiveLabel: 'Positive',
    negativeLabel: 'Negative',
    mixedLabel: 'Mixed',
  },
  sv: {
    sectionHeading: 'Fördjupad Politisk Analys',
    whatHeading: 'Vad Hände',
    whoHeading: 'Nyckelaktörer',
    whenHeading: 'Tidslinje',
    whyHeading: 'Varför Det Spelar Roll — Grundorsaker',
    stakeholderHeading: 'Vinnare & Förlorare',
    winnerLabel: 'Vinnare',
    loserLabel: 'Förlorare',
    neutralLabel: 'Neutral',
    impactHeading: 'Konsekvensbedömning',
    politicalLabel: 'Politisk',
    economicLabel: 'Ekonomisk',
    socialLabel: 'Social',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Åtgärder → Konsekvenser',
    actionLabel: 'Åtgärd',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Allvarlighetsgrad',
    mistakesHeading: 'Felbedömningar & Missade Möjligheter',
    alternativeLabel: 'Borde ha',
    outlookHeading: 'Strategisk Utsikt',
    severityLow: 'Låg',
    severityMedium: 'Medel',
    severityHigh: 'Hög',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Sammanfattning',
    confidenceHigh: 'Hög Tillförlitlighet',
    confidenceMedium: 'Medel Tillförlitlighet',
    confidenceLow: 'Låg Tillförlitlighet',
    evidenceRefsHeading: 'Bevisning',
    counterArgumentsHeading: 'Motargument',
    conclusionLabel: 'Slutsats:',
    premiseLabel: 'Premiss:',
    inferenceLabel: 'Slutledning:',
    reasoningChainsHeading: 'Resonemangskedjor',
    scenarioPlanningHeading: 'Scenarioplanering',
    bestCaseLabel: 'Bästa Scenario',
    worstCaseLabel: 'Värsta Scenario',
    mostLikelyLabel: 'Mest Troligt',
    wildcardsLabel: 'Jokerkort',
    probabilityLabel: 'Sannolikhet',
    triggersLabel: 'Utlösare',
    impliedImpactsLabel: 'Förväntade Effekter',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysmetodik',
    iterationCountLabel: 'Iterationer',
    evidenceStrengthLabel: 'Bevisstyrka',
    evidenceStrong: 'Stark',
    evidenceModerate: 'Måttlig',
    evidenceWeak: 'Svag',
    iterationInitial: 'Inledande Bedömning',
    iterationStakeholderChallenge: 'Intressentutmaning',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntes',
    overallConfidenceLabel: 'Övergripande Tillförlitlighet',
    pendingNotice:
      'Analys väntar — denna sektion kommer att slutföras av det redaktionella analysarbetsflödet.',
    perspectivesHeading: 'Intressentperspektiv',
    outcomeMatrixHeading: 'Intressentutfallsmatris',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiska grupper',
    civilSocietyLabel: 'Civilsamhälle',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nationella regeringar',
    citizensLabel: 'Medborgare',
    euInstitutionsLabel: 'EU-institutioner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandad',
  },
  da: {
    sectionHeading: 'Dybdegående Politisk Analyse',
    whatHeading: 'Hvad Skete',
    whoHeading: 'Nøgleaktører',
    whenHeading: 'Tidslinje',
    whyHeading: 'Hvorfor Det Betyder Noget — Grundårsager',
    stakeholderHeading: 'Vindere & Tabere',
    winnerLabel: 'Vinder',
    loserLabel: 'Taber',
    neutralLabel: 'Neutral',
    impactHeading: 'Konsekvensvurdering',
    politicalLabel: 'Politisk',
    economicLabel: 'Økonomisk',
    socialLabel: 'Social',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Handlinger → Konsekvenser',
    actionLabel: 'Handling',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Alvorlighed',
    mistakesHeading: 'Fejlvurderinger & Forpassede Muligheder',
    alternativeLabel: 'Burde have',
    outlookHeading: 'Strategisk Udsigt',
    severityLow: 'Lav',
    severityMedium: 'Middel',
    severityHigh: 'Høj',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Resumé',
    confidenceHigh: 'Høj Tillid',
    confidenceMedium: 'Middel Tillid',
    confidenceLow: 'Lav Tillid',
    evidenceRefsHeading: 'Beviser',
    counterArgumentsHeading: 'Modargumenter',
    conclusionLabel: 'Konklusion:',
    premiseLabel: 'Præmis:',
    inferenceLabel: 'Slutning:',
    reasoningChainsHeading: 'Ræsonnementskæder',
    scenarioPlanningHeading: 'Scenarieplanlægning',
    bestCaseLabel: 'Bedste Scenarie',
    worstCaseLabel: 'Værste Scenarie',
    mostLikelyLabel: 'Mest Sandsynligt',
    wildcardsLabel: 'Jokere',
    probabilityLabel: 'Sandsynlighed',
    triggersLabel: 'Udløsere',
    impliedImpactsLabel: 'Forventede Konsekvenser',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysemetodik',
    iterationCountLabel: 'Iterationer',
    evidenceStrengthLabel: 'Bevisstyrke',
    evidenceStrong: 'Stærk',
    evidenceModerate: 'Moderat',
    evidenceWeak: 'Svag',
    iterationInitial: 'Indledende Vurdering',
    iterationStakeholderChallenge: 'Interessentudfordring',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntese',
    overallConfidenceLabel: 'Samlet Tillid',
    pendingNotice:
      'Analyse afventer — denne sektion vil blive udfyldt af det redaktionelle analyse-workflow.',
    perspectivesHeading: 'Interessentperspektiver',
    outcomeMatrixHeading: 'Interessentresultatmatrix',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiske grupper',
    civilSocietyLabel: 'Civilsamfund',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nationale regeringer',
    citizensLabel: 'Borgere',
    euInstitutionsLabel: 'EU-institutioner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandet',
  },
  no: {
    sectionHeading: 'Dyptgående Politisk Analyse',
    whatHeading: 'Hva Skjedde',
    whoHeading: 'Nøkkelaktører',
    whenHeading: 'Tidslinje',
    whyHeading: 'Hvorfor Det Betyr Noe — Grunnårsaker',
    stakeholderHeading: 'Vinnere & Tapere',
    winnerLabel: 'Vinner',
    loserLabel: 'Taper',
    neutralLabel: 'Nøytral',
    impactHeading: 'Konsekvensutredning',
    politicalLabel: 'Politisk',
    economicLabel: 'Økonomisk',
    socialLabel: 'Sosial',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Handlinger → Konsekvenser',
    actionLabel: 'Handling',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Alvorlighetsgrad',
    mistakesHeading: 'Feilberegninger & Tapte Muligheter',
    alternativeLabel: 'Burde ha',
    outlookHeading: 'Strategisk Utsikt',
    severityLow: 'Lav',
    severityMedium: 'Middels',
    severityHigh: 'Høy',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Sammendrag',
    confidenceHigh: 'Høy Tillit',
    confidenceMedium: 'Middels Tillit',
    confidenceLow: 'Lav Tillit',
    evidenceRefsHeading: 'Bevis',
    counterArgumentsHeading: 'Motargumenter',
    conclusionLabel: 'Konklusjon:',
    premiseLabel: 'Premiss:',
    inferenceLabel: 'Slutning:',
    reasoningChainsHeading: 'Resonnementsrekker',
    scenarioPlanningHeading: 'Scenarioplanlegging',
    bestCaseLabel: 'Beste Scenario',
    worstCaseLabel: 'Verste Scenario',
    mostLikelyLabel: 'Mest Sannsynlig',
    wildcardsLabel: 'Jokere',
    probabilityLabel: 'Sannsynlighet',
    triggersLabel: 'Utløsere',
    impliedImpactsLabel: 'Forventede Konsekvenser',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysemetodikk',
    iterationCountLabel: 'Iterasjoner',
    evidenceStrengthLabel: 'Bevisstyrke',
    evidenceStrong: 'Sterk',
    evidenceModerate: 'Moderat',
    evidenceWeak: 'Svak',
    iterationInitial: 'Innledende Vurdering',
    iterationStakeholderChallenge: 'Interessentutfordring',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntese',
    overallConfidenceLabel: 'Samlet Tillit',
    pendingNotice:
      'Analyse avventer — denne seksjonen vil bli fullført av den redaksjonelle analyse-arbeidsflyten.',
    perspectivesHeading: 'Interessentperspektiver',
    outcomeMatrixHeading: 'Interessentutfallsmatrise',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiske grupper',
    civilSocietyLabel: 'Sivilsamfunn',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nasjonale regjeringer',
    citizensLabel: 'Borgere',
    euInstitutionsLabel: 'EU-institusjoner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandet',
  },
  fi: {
    sectionHeading: 'Syvällinen Poliittinen Analyysi',
    whatHeading: 'Mitä Tapahtui',
    whoHeading: 'Keskeiset Toimijat',
    whenHeading: 'Aikajana',
    whyHeading: 'Miksi Sillä On Merkitystä — Juurisyyt',
    stakeholderHeading: 'Voittajat & Häviäjät',
    winnerLabel: 'Voittaja',
    loserLabel: 'Häviäjä',
    neutralLabel: 'Neutraali',
    impactHeading: 'Vaikutusarviointi',
    politicalLabel: 'Poliittinen',
    economicLabel: 'Taloudellinen',
    socialLabel: 'Sosiaalinen',
    legalLabel: 'Oikeudellinen',
    geopoliticalLabel: 'Geopoliittinen',
    consequencesHeading: 'Toimet → Seuraukset',
    actionLabel: 'Toimi',
    consequenceLabel: 'Seuraus',
    severityColumnLabel: 'Vakavuus',
    mistakesHeading: 'Virhearvioinnit & Menetetyt Mahdollisuudet',
    alternativeLabel: 'Olisi pitänyt',
    outlookHeading: 'Strategiset Näkymät',
    severityLow: 'Matala',
    severityMedium: 'Keskitaso',
    severityHigh: 'Korkea',
    severityCritical: 'Kriittinen',
    executiveSummaryHeading: 'Yhteenveto',
    confidenceHigh: 'Korkea Luotettavuus',
    confidenceMedium: 'Keskitason Luotettavuus',
    confidenceLow: 'Matala Luotettavuus',
    evidenceRefsHeading: 'Todisteet',
    counterArgumentsHeading: 'Vasta-argumentit',
    conclusionLabel: 'Johtopäätös:',
    premiseLabel: 'Lähtökohta:',
    inferenceLabel: 'Päätelmä:',
    reasoningChainsHeading: 'Päättelyketjut',
    scenarioPlanningHeading: 'Skenaarion Suunnittelu',
    bestCaseLabel: 'Paras Skenaario',
    worstCaseLabel: 'Pahin Skenaario',
    mostLikelyLabel: 'Todennäköisin',
    wildcardsLabel: 'Jokerikortit',
    probabilityLabel: 'Todennäköisyys',
    triggersLabel: 'Laukaisijat',
    impliedImpactsLabel: 'Odotetut Vaikutukset',
    timelineLabel: 'Aikajana',
    analysisMethodologyHeading: 'Analyysimenetelmä',
    iterationCountLabel: 'Iteraatiot',
    evidenceStrengthLabel: 'Todistusvoima',
    evidenceStrong: 'Vahva',
    evidenceModerate: 'Kohtalainen',
    evidenceWeak: 'Heikko',
    iterationInitial: 'Alustava Arviointi',
    iterationStakeholderChallenge: 'Sidosryhmähaaste',
    iterationEvidenceValidation: 'Todisteiden Validointi',
    iterationSynthesis: 'Synteesi',
    overallConfidenceLabel: 'Kokonaisluotettavuus',
    pendingNotice:
      'Analyysi odottaa — tämä osio täydennetään toimituksellisen analyysin työnkulussa.',
    perspectivesHeading: 'Sidosryhmänäkökulmat',
    outcomeMatrixHeading: 'Sidosryhmätulosmatriisi',
    confidenceLabel: 'Luotettavuus',
    politicalGroupsLabel: 'Poliittiset ryhmät',
    civilSocietyLabel: 'Kansalaisyhteiskunta',
    industryLabel: 'Teollisuus',
    nationalGovtsLabel: 'Kansalliset hallitukset',
    citizensLabel: 'Kansalaiset',
    euInstitutionsLabel: 'EU:n toimielimet',
    positiveLabel: 'Positiivinen',
    negativeLabel: 'Negatiivinen',
    mixedLabel: 'Sekalainen',
  },
  de: {
    sectionHeading: 'Vertiefte Politische Analyse',
    whatHeading: 'Was Geschah',
    whoHeading: 'Schlüsselakteure',
    whenHeading: 'Zeitachse',
    whyHeading: 'Warum Es Wichtig Ist — Grundursachen',
    stakeholderHeading: 'Gewinner & Verlierer',
    winnerLabel: 'Gewinner',
    loserLabel: 'Verlierer',
    neutralLabel: 'Neutral',
    impactHeading: 'Folgenabschätzung',
    politicalLabel: 'Politisch',
    economicLabel: 'Wirtschaftlich',
    socialLabel: 'Sozial',
    legalLabel: 'Rechtlich',
    geopoliticalLabel: 'Geopolitisch',
    consequencesHeading: 'Handlungen → Konsequenzen',
    actionLabel: 'Handlung',
    consequenceLabel: 'Konsequenz',
    severityColumnLabel: 'Schweregrad',
    mistakesHeading: 'Fehleinschätzungen & Verpasste Chancen',
    alternativeLabel: 'Hätte sollen',
    outlookHeading: 'Strategischer Ausblick',
    severityLow: 'Niedrig',
    severityMedium: 'Mittel',
    severityHigh: 'Hoch',
    severityCritical: 'Kritisch',
    executiveSummaryHeading: 'Zusammenfassung',
    confidenceHigh: 'Hohe Konfidenz',
    confidenceMedium: 'Mittlere Konfidenz',
    confidenceLow: 'Niedrige Konfidenz',
    evidenceRefsHeading: 'Belege',
    counterArgumentsHeading: 'Gegenargumente',
    conclusionLabel: 'Schlussfolgerung:',
    premiseLabel: 'Prämisse:',
    inferenceLabel: 'Ableitung:',
    reasoningChainsHeading: 'Argumentationsketten',
    scenarioPlanningHeading: 'Szenarioplanung',
    bestCaseLabel: 'Bester Fall',
    worstCaseLabel: 'Schlimmster Fall',
    mostLikelyLabel: 'Wahrscheinlichster Fall',
    wildcardsLabel: 'Unbekannte Faktoren',
    probabilityLabel: 'Wahrscheinlichkeit',
    triggersLabel: 'Auslöser',
    impliedImpactsLabel: 'Erwartete Auswirkungen',
    timelineLabel: 'Zeitachse',
    analysisMethodologyHeading: 'Analysemethodik',
    iterationCountLabel: 'Iterationen',
    evidenceStrengthLabel: 'Beweisstärke',
    evidenceStrong: 'Stark',
    evidenceModerate: 'Mäßig',
    evidenceWeak: 'Schwach',
    iterationInitial: 'Erstbewertung',
    iterationStakeholderChallenge: 'Stakeholder-Herausforderung',
    iterationEvidenceValidation: 'Beweisvalidierung',
    iterationSynthesis: 'Synthese',
    overallConfidenceLabel: 'Gesamtkonfidenz',
    pendingNotice:
      'Analyse ausstehend — dieser Abschnitt wird durch den redaktionellen Analyse-Workflow vervollständigt.',
    perspectivesHeading: 'Stakeholder-Perspektiven',
    outcomeMatrixHeading: 'Stakeholder-Ergebnismatrix',
    confidenceLabel: 'Konfidenz',
    politicalGroupsLabel: 'Politische Fraktionen',
    civilSocietyLabel: 'Zivilgesellschaft',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Nationale Regierungen',
    citizensLabel: 'Bürger',
    euInstitutionsLabel: 'EU-Institutionen',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Gemischt',
  },
  fr: {
    sectionHeading: 'Analyse Politique Approfondie',
    whatHeading: "Ce Qui S'est Passé",
    whoHeading: 'Acteurs Clés',
    whenHeading: 'Chronologie',
    whyHeading: "Pourquoi C'est Important — Causes Profondes",
    stakeholderHeading: 'Gagnants & Perdants',
    winnerLabel: 'Gagnant',
    loserLabel: 'Perdant',
    neutralLabel: 'Neutre',
    impactHeading: "Évaluation d'Impact",
    politicalLabel: 'Politique',
    economicLabel: 'Économique',
    socialLabel: 'Social',
    legalLabel: 'Juridique',
    geopoliticalLabel: 'Géopolitique',
    consequencesHeading: 'Actions → Conséquences',
    actionLabel: 'Action',
    consequenceLabel: 'Conséquence',
    severityColumnLabel: 'Gravité',
    mistakesHeading: 'Erreurs de Calcul & Opportunités Manquées',
    alternativeLabel: 'Aurait dû',
    outlookHeading: 'Perspectives Stratégiques',
    severityLow: 'Faible',
    severityMedium: 'Moyen',
    severityHigh: 'Élevé',
    severityCritical: 'Critique',
    executiveSummaryHeading: 'Synthèse',
    confidenceHigh: 'Confiance Élevée',
    confidenceMedium: 'Confiance Moyenne',
    confidenceLow: 'Confiance Faible',
    evidenceRefsHeading: 'Preuves',
    counterArgumentsHeading: 'Contre-arguments',
    conclusionLabel: 'Conclusion :',
    premiseLabel: 'Prémisse :',
    inferenceLabel: 'Inférence :',
    reasoningChainsHeading: 'Chaînes de Raisonnement',
    scenarioPlanningHeading: 'Planification de Scénarios',
    bestCaseLabel: 'Meilleur Scénario',
    worstCaseLabel: 'Pire Scénario',
    mostLikelyLabel: 'Plus Probable',
    wildcardsLabel: 'Imprévus',
    probabilityLabel: 'Probabilité',
    triggersLabel: 'Déclencheurs',
    impliedImpactsLabel: 'Impacts Attendus',
    timelineLabel: 'Chronologie',
    analysisMethodologyHeading: "Méthodologie d'Analyse",
    iterationCountLabel: 'Itérations',
    evidenceStrengthLabel: 'Force des Preuves',
    evidenceStrong: 'Fort',
    evidenceModerate: 'Modéré',
    evidenceWeak: 'Faible',
    iterationInitial: 'Évaluation Initiale',
    iterationStakeholderChallenge: 'Défi des Parties Prenantes',
    iterationEvidenceValidation: 'Validation des Preuves',
    iterationSynthesis: 'Synthèse',
    overallConfidenceLabel: 'Confiance Globale',
    pendingNotice:
      "Analyse en attente — cette section sera complétée par le flux de travail d'analyse éditoriale.",
    perspectivesHeading: 'Perspectives des Parties Prenantes',
    outcomeMatrixHeading: 'Matrice des Résultats des Parties Prenantes',
    confidenceLabel: 'Confiance',
    politicalGroupsLabel: 'Groupes politiques',
    civilSocietyLabel: 'Société civile',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Gouvernements nationaux',
    citizensLabel: 'Citoyens',
    euInstitutionsLabel: "Institutions de l'UE",
    positiveLabel: 'Positif',
    negativeLabel: 'Négatif',
    mixedLabel: 'Mixte',
  },
  es: {
    sectionHeading: 'Análisis Político Profundo',
    whatHeading: 'Qué Ocurrió',
    whoHeading: 'Actores Clave',
    whenHeading: 'Cronología',
    whyHeading: 'Por Qué Importa — Causas Raíz',
    stakeholderHeading: 'Ganadores & Perdedores',
    winnerLabel: 'Ganador',
    loserLabel: 'Perdedor',
    neutralLabel: 'Neutral',
    impactHeading: 'Evaluación de Impacto',
    politicalLabel: 'Político',
    economicLabel: 'Económico',
    socialLabel: 'Social',
    legalLabel: 'Jurídico',
    geopoliticalLabel: 'Geopolítico',
    consequencesHeading: 'Acciones → Consecuencias',
    actionLabel: 'Acción',
    consequenceLabel: 'Consecuencia',
    severityColumnLabel: 'Gravedad',
    mistakesHeading: 'Errores de Cálculo & Oportunidades Perdidas',
    alternativeLabel: 'Debería haber',
    outlookHeading: 'Perspectivas Estratégicas',
    severityLow: 'Bajo',
    severityMedium: 'Medio',
    severityHigh: 'Alto',
    severityCritical: 'Crítico',
    executiveSummaryHeading: 'Resumen Ejecutivo',
    confidenceHigh: 'Confianza Alta',
    confidenceMedium: 'Confianza Media',
    confidenceLow: 'Confianza Baja',
    evidenceRefsHeading: 'Evidencias',
    counterArgumentsHeading: 'Contraargumentos',
    conclusionLabel: 'Conclusión:',
    premiseLabel: 'Premisa:',
    inferenceLabel: 'Inferencia:',
    reasoningChainsHeading: 'Cadenas de Razonamiento',
    scenarioPlanningHeading: 'Planificación de Escenarios',
    bestCaseLabel: 'Mejor Escenario',
    worstCaseLabel: 'Peor Escenario',
    mostLikelyLabel: 'Más Probable',
    wildcardsLabel: 'Factores Imprevistos',
    probabilityLabel: 'Probabilidad',
    triggersLabel: 'Desencadenantes',
    impliedImpactsLabel: 'Impactos Previstos',
    timelineLabel: 'Cronología',
    analysisMethodologyHeading: 'Metodología de Análisis',
    iterationCountLabel: 'Iteraciones',
    evidenceStrengthLabel: 'Fuerza de la Evidencia',
    evidenceStrong: 'Fuerte',
    evidenceModerate: 'Moderada',
    evidenceWeak: 'Débil',
    iterationInitial: 'Evaluación Inicial',
    iterationStakeholderChallenge: 'Desafío de Partes Interesadas',
    iterationEvidenceValidation: 'Validación de Evidencia',
    iterationSynthesis: 'Síntesis',
    overallConfidenceLabel: 'Confianza Global',
    pendingNotice:
      'Análisis pendiente — esta sección será completada por el flujo de trabajo de análisis editorial.',
    perspectivesHeading: 'Perspectivas de las Partes Interesadas',
    outcomeMatrixHeading: 'Matriz de Resultados de Partes Interesadas',
    confidenceLabel: 'Confianza',
    politicalGroupsLabel: 'Grupos políticos',
    civilSocietyLabel: 'Sociedad civil',
    industryLabel: 'Industria',
    nationalGovtsLabel: 'Gobiernos nacionales',
    citizensLabel: 'Ciudadanos',
    euInstitutionsLabel: 'Instituciones de la UE',
    positiveLabel: 'Positivo',
    negativeLabel: 'Negativo',
    mixedLabel: 'Mixto',
  },
  nl: {
    sectionHeading: 'Diepgaande Politieke Analyse',
    whatHeading: 'Wat er Gebeurde',
    whoHeading: 'Belangrijkste Actoren',
    whenHeading: 'Tijdlijn',
    whyHeading: 'Waarom Het Belangrijk Is — Grondoorzaken',
    stakeholderHeading: 'Winnaars & Verliezers',
    winnerLabel: 'Winnaar',
    loserLabel: 'Verliezer',
    neutralLabel: 'Neutraal',
    impactHeading: 'Impactbeoordeling',
    politicalLabel: 'Politiek',
    economicLabel: 'Economisch',
    socialLabel: 'Sociaal',
    legalLabel: 'Juridisch',
    geopoliticalLabel: 'Geopolitiek',
    consequencesHeading: 'Acties → Gevolgen',
    actionLabel: 'Actie',
    consequenceLabel: 'Gevolg',
    severityColumnLabel: 'Ernst',
    mistakesHeading: 'Misrekeningen & Gemiste Kansen',
    alternativeLabel: 'Had moeten',
    outlookHeading: 'Strategisch Vooruitzicht',
    severityLow: 'Laag',
    severityMedium: 'Gemiddeld',
    severityHigh: 'Hoog',
    severityCritical: 'Kritiek',
    executiveSummaryHeading: 'Samenvatting',
    confidenceHigh: 'Hoog Vertrouwen',
    confidenceMedium: 'Gemiddeld Vertrouwen',
    confidenceLow: 'Laag Vertrouwen',
    evidenceRefsHeading: 'Bewijs',
    counterArgumentsHeading: 'Tegenargumenten',
    conclusionLabel: 'Conclusie:',
    premiseLabel: 'Premisse:',
    inferenceLabel: 'Gevolgtrekking:',
    reasoningChainsHeading: 'Redeneerketens',
    scenarioPlanningHeading: 'Scenarioplanning',
    bestCaseLabel: 'Beste Scenario',
    worstCaseLabel: 'Slechtste Scenario',
    mostLikelyLabel: 'Meest Waarschijnlijk',
    wildcardsLabel: 'Onverwachte Factoren',
    probabilityLabel: 'Waarschijnlijkheid',
    triggersLabel: 'Triggers',
    impliedImpactsLabel: 'Verwachte Effecten',
    timelineLabel: 'Tijdlijn',
    analysisMethodologyHeading: 'Analysemethodologie',
    iterationCountLabel: 'Iteraties',
    evidenceStrengthLabel: 'Bewijskracht',
    evidenceStrong: 'Sterk',
    evidenceModerate: 'Matig',
    evidenceWeak: 'Zwak',
    iterationInitial: 'Eerste Beoordeling',
    iterationStakeholderChallenge: 'Stakeholderuitdaging',
    iterationEvidenceValidation: 'Bewijsvalidatie',
    iterationSynthesis: 'Synthese',
    overallConfidenceLabel: 'Algeheel Vertrouwen',
    pendingNotice:
      'Analyse in afwachting — deze sectie wordt aangevuld door de redactionele analyse-workflow.',
    perspectivesHeading: 'Stakeholdersperspectieven',
    outcomeMatrixHeading: 'Stakeholdersresultaatmatrix',
    confidenceLabel: 'Vertrouwen',
    politicalGroupsLabel: 'Politieke fracties',
    civilSocietyLabel: 'Maatschappelijk middenveld',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Nationale regeringen',
    citizensLabel: 'Burgers',
    euInstitutionsLabel: 'EU-instellingen',
    positiveLabel: 'Positief',
    negativeLabel: 'Negatief',
    mixedLabel: 'Gemengd',
  },
  ar: {
    sectionHeading: 'تحليل سياسي معمّق',
    whatHeading: 'ماذا حدث',
    whoHeading: 'الجهات الفاعلة الرئيسية',
    whenHeading: 'الجدول الزمني',
    whyHeading: 'لماذا هذا مهم — الأسباب الجذرية',
    stakeholderHeading: 'الرابحون والخاسرون',
    winnerLabel: 'رابح',
    loserLabel: 'خاسر',
    neutralLabel: 'محايد',
    impactHeading: 'تقييم الأثر',
    politicalLabel: 'سياسي',
    economicLabel: 'اقتصادي',
    socialLabel: 'اجتماعي',
    legalLabel: 'قانوني',
    geopoliticalLabel: 'جيوسياسي',
    consequencesHeading: 'إجراءات ← عواقب',
    actionLabel: 'إجراء',
    consequenceLabel: 'عاقبة',
    severityColumnLabel: 'شدة',
    mistakesHeading: 'أخطاء في الحسابات وفرص ضائعة',
    alternativeLabel: 'كان ينبغي',
    outlookHeading: 'النظرة الاستراتيجية',
    severityLow: 'منخفض',
    severityMedium: 'متوسط',
    severityHigh: 'مرتفع',
    severityCritical: 'حرج',
    executiveSummaryHeading: 'ملخص تنفيذي',
    confidenceHigh: 'ثقة عالية',
    confidenceMedium: 'ثقة متوسطة',
    confidenceLow: 'ثقة منخفضة',
    evidenceRefsHeading: 'الأدلة',
    counterArgumentsHeading: 'حجج مضادة',
    conclusionLabel: 'استنتاج:',
    premiseLabel: 'مقدمة:',
    inferenceLabel: 'استدلال:',
    reasoningChainsHeading: 'سلاسل الاستدلال',
    scenarioPlanningHeading: 'تخطيط السيناريوهات',
    bestCaseLabel: 'أفضل سيناريو',
    worstCaseLabel: 'أسوأ سيناريو',
    mostLikelyLabel: 'الأكثر احتمالاً',
    wildcardsLabel: 'عوامل غير متوقعة',
    probabilityLabel: 'الاحتمالية',
    triggersLabel: 'المحفزات',
    impliedImpactsLabel: 'التأثيرات المتوقعة',
    timelineLabel: 'الجدول الزمني',
    analysisMethodologyHeading: 'منهجية التحليل',
    iterationCountLabel: 'التكرارات',
    evidenceStrengthLabel: 'قوة الأدلة',
    evidenceStrong: 'قوي',
    evidenceModerate: 'معتدل',
    evidenceWeak: 'ضعيف',
    iterationInitial: 'التقييم الأولي',
    iterationStakeholderChallenge: 'تحدي أصحاب المصلحة',
    iterationEvidenceValidation: 'التحقق من الأدلة',
    iterationSynthesis: 'التوليف',
    overallConfidenceLabel: 'الثقة الإجمالية',
    pendingNotice: 'التحليل معلق — سيتم استكمال هذا القسم بواسطة سير العمل التحريري التحليلي.',
    perspectivesHeading: 'وجهات نظر أصحاب المصلحة',
    outcomeMatrixHeading: 'مصفوفة نتائج أصحاب المصلحة',
    confidenceLabel: 'الثقة',
    politicalGroupsLabel: 'المجموعات السياسية',
    civilSocietyLabel: 'المجتمع المدني',
    industryLabel: 'الصناعة',
    nationalGovtsLabel: 'الحكومات الوطنية',
    citizensLabel: 'المواطنون',
    euInstitutionsLabel: 'مؤسسات الاتحاد الأوروبي',
    positiveLabel: 'إيجابي',
    negativeLabel: 'سلبي',
    mixedLabel: 'مختلط',
  },
  he: {
    sectionHeading: 'ניתוח פוליטי מעמיק',
    whatHeading: 'מה קרה',
    whoHeading: 'שחקנים מרכזיים',
    whenHeading: 'ציר זמן',
    whyHeading: 'מדוע זה חשוב — סיבות שורש',
    stakeholderHeading: 'מרוויחים ומפסידים',
    winnerLabel: 'מרוויח',
    loserLabel: 'מפסיד',
    neutralLabel: 'ניטרלי',
    impactHeading: 'הערכת השפעה',
    politicalLabel: 'פוליטי',
    economicLabel: 'כלכלי',
    socialLabel: 'חברתי',
    legalLabel: 'משפטי',
    geopoliticalLabel: 'גיאופוליטי',
    consequencesHeading: 'פעולות ← השלכות',
    actionLabel: 'פעולה',
    consequenceLabel: 'השלכה',
    severityColumnLabel: 'חומרה',
    mistakesHeading: 'טעויות חישוב והזדמנויות שהוחמצו',
    alternativeLabel: 'היה צריך',
    outlookHeading: 'תחזית אסטרטגית',
    severityLow: 'נמוך',
    severityMedium: 'בינוני',
    severityHigh: 'גבוה',
    severityCritical: 'קריטי',
    executiveSummaryHeading: 'תקציר מנהלים',
    confidenceHigh: 'ביטחון גבוה',
    confidenceMedium: 'ביטחון בינוני',
    confidenceLow: 'ביטחון נמוך',
    evidenceRefsHeading: 'ראיות',
    counterArgumentsHeading: 'טענות נגד',
    conclusionLabel: 'מסקנה:',
    premiseLabel: 'הנחה:',
    inferenceLabel: 'היסק:',
    reasoningChainsHeading: 'שרשראות היסק',
    scenarioPlanningHeading: 'תכנון תרחישים',
    bestCaseLabel: 'תרחיש אופטימי',
    worstCaseLabel: 'תרחיש גרוע',
    mostLikelyLabel: 'הסביר ביותר',
    wildcardsLabel: 'גורמים בלתי צפויים',
    probabilityLabel: 'הסתברות',
    triggersLabel: 'טריגרים',
    impliedImpactsLabel: 'השפעות צפויות',
    timelineLabel: 'ציר זמן',
    analysisMethodologyHeading: 'מתודולוגיית ניתוח',
    iterationCountLabel: 'איטרציות',
    evidenceStrengthLabel: 'עוצמת הראיות',
    evidenceStrong: 'חזק',
    evidenceModerate: 'בינוני',
    evidenceWeak: 'חלש',
    iterationInitial: 'הערכה ראשונית',
    iterationStakeholderChallenge: 'אתגר בעלי עניין',
    iterationEvidenceValidation: 'אימות ראיות',
    iterationSynthesis: 'סינתזה',
    overallConfidenceLabel: 'ביטחון כולל',
    pendingNotice: 'ניתוח ממתין — חלק זה יושלם על ידי תהליך העבודה של הניתוח העורכי.',
    perspectivesHeading: 'נקודות מבט של בעלי עניין',
    outcomeMatrixHeading: 'מטריצת תוצאות בעלי עניין',
    confidenceLabel: 'ביטחון',
    politicalGroupsLabel: 'קבוצות פוליטיות',
    civilSocietyLabel: 'חברה אזרחית',
    industryLabel: 'תעשייה',
    nationalGovtsLabel: 'ממשלות לאומיות',
    citizensLabel: 'אזרחים',
    euInstitutionsLabel: 'מוסדות האיחוד האירופי',
    positiveLabel: 'חיובי',
    negativeLabel: 'שלילי',
    mixedLabel: 'מעורב',
  },
  ja: {
    sectionHeading: '深層政治分析',
    whatHeading: '何が起きたか',
    whoHeading: '主要関係者',
    whenHeading: 'タイムライン',
    whyHeading: 'なぜ重要か — 根本原因',
    stakeholderHeading: '勝者と敗者',
    winnerLabel: '勝者',
    loserLabel: '敗者',
    neutralLabel: '中立',
    impactHeading: '影響評価',
    politicalLabel: '政治的',
    economicLabel: '経済的',
    socialLabel: '社会的',
    legalLabel: '法的',
    geopoliticalLabel: '地政学的',
    consequencesHeading: '行動 → 結果',
    actionLabel: '行動',
    consequenceLabel: '結果',
    severityColumnLabel: '重大度',
    mistakesHeading: '誤算と逃した機会',
    alternativeLabel: 'すべきだった',
    outlookHeading: '戦略的展望',
    severityLow: '低',
    severityMedium: '中',
    severityHigh: '高',
    severityCritical: '重大',
    executiveSummaryHeading: 'エグゼクティブサマリー',
    confidenceHigh: '高い信頼度',
    confidenceMedium: '中程度の信頼度',
    confidenceLow: '低い信頼度',
    evidenceRefsHeading: '証拠',
    counterArgumentsHeading: '反論',
    conclusionLabel: '結論:',
    premiseLabel: '前提:',
    inferenceLabel: '推論:',
    reasoningChainsHeading: '推論チェーン',
    scenarioPlanningHeading: 'シナリオプランニング',
    bestCaseLabel: '最良シナリオ',
    worstCaseLabel: '最悪シナリオ',
    mostLikelyLabel: '最も可能性が高い',
    wildcardsLabel: '不確定要素',
    probabilityLabel: '確率',
    triggersLabel: 'トリガー',
    impliedImpactsLabel: '予想される影響',
    timelineLabel: 'タイムライン',
    analysisMethodologyHeading: '分析手法',
    iterationCountLabel: 'イテレーション',
    evidenceStrengthLabel: '証拠の強度',
    evidenceStrong: '強い',
    evidenceModerate: '中程度',
    evidenceWeak: '弱い',
    iterationInitial: '初期評価',
    iterationStakeholderChallenge: 'ステークホルダーの検証',
    iterationEvidenceValidation: '証拠の検証',
    iterationSynthesis: '総合',
    overallConfidenceLabel: '総合信頼度',
    pendingNotice: '分析保留中 — このセクションは編集分析ワークフローによって完了されます。',
    perspectivesHeading: 'ステークホルダーの視点',
    outcomeMatrixHeading: 'ステークホルダー結果マトリックス',
    confidenceLabel: '信頼度',
    politicalGroupsLabel: '政治グループ',
    civilSocietyLabel: '市民社会',
    industryLabel: '産業界',
    nationalGovtsLabel: '各国政府',
    citizensLabel: '市民',
    euInstitutionsLabel: 'EU機関',
    positiveLabel: '肯定的',
    negativeLabel: '否定的',
    mixedLabel: '混合',
  },
  ko: {
    sectionHeading: '심층 정치 분석',
    whatHeading: '무엇이 일어났는가',
    whoHeading: '주요 행위자',
    whenHeading: '타임라인',
    whyHeading: '왜 중요한가 — 근본 원인',
    stakeholderHeading: '승자와 패자',
    winnerLabel: '승자',
    loserLabel: '패자',
    neutralLabel: '중립',
    impactHeading: '영향 평가',
    politicalLabel: '정치적',
    economicLabel: '경제적',
    socialLabel: '사회적',
    legalLabel: '법적',
    geopoliticalLabel: '지정학적',
    consequencesHeading: '행동 → 결과',
    actionLabel: '행동',
    consequenceLabel: '결과',
    severityColumnLabel: '심각도',
    mistakesHeading: '오판과 놓친 기회',
    alternativeLabel: '했어야 했다',
    outlookHeading: '전략적 전망',
    severityLow: '낮음',
    severityMedium: '보통',
    severityHigh: '높음',
    severityCritical: '위기',
    executiveSummaryHeading: '핵심 요약',
    confidenceHigh: '높은 신뢰도',
    confidenceMedium: '중간 신뢰도',
    confidenceLow: '낮은 신뢰도',
    evidenceRefsHeading: '증거',
    counterArgumentsHeading: '반론',
    conclusionLabel: '결론:',
    premiseLabel: '전제:',
    inferenceLabel: '추론:',
    reasoningChainsHeading: '추론 체인',
    scenarioPlanningHeading: '시나리오 계획',
    bestCaseLabel: '최선 시나리오',
    worstCaseLabel: '최악 시나리오',
    mostLikelyLabel: '가장 가능성 높은',
    wildcardsLabel: '불확실 요소',
    probabilityLabel: '확률',
    triggersLabel: '촉발 요인',
    impliedImpactsLabel: '예상 영향',
    timelineLabel: '타임라인',
    analysisMethodologyHeading: '분석 방법론',
    iterationCountLabel: '반복',
    evidenceStrengthLabel: '증거 강도',
    evidenceStrong: '강함',
    evidenceModerate: '보통',
    evidenceWeak: '약함',
    iterationInitial: '초기 평가',
    iterationStakeholderChallenge: '이해관계자 검증',
    iterationEvidenceValidation: '증거 검증',
    iterationSynthesis: '종합',
    overallConfidenceLabel: '종합 신뢰도',
    pendingNotice: '분석 대기 중 — 이 섹션은 편집 분석 워크플로에 의해 완성됩니다.',
    perspectivesHeading: '이해관계자 관점',
    outcomeMatrixHeading: '이해관계자 결과 매트릭스',
    confidenceLabel: '신뢰도',
    politicalGroupsLabel: '정치 그룹',
    civilSocietyLabel: '시민사회',
    industryLabel: '산업계',
    nationalGovtsLabel: '각국 정부',
    citizensLabel: '시민',
    euInstitutionsLabel: 'EU 기관',
    positiveLabel: '긍정적',
    negativeLabel: '부정적',
    mixedLabel: '혼합',
  },
  zh: {
    sectionHeading: '深度政治分析',
    whatHeading: '发生了什么',
    whoHeading: '关键参与者',
    whenHeading: '时间线',
    whyHeading: '为何重要 — 根本原因',
    stakeholderHeading: '赢家与输家',
    winnerLabel: '赢家',
    loserLabel: '输家',
    neutralLabel: '中立',
    impactHeading: '影响评估',
    politicalLabel: '政治',
    economicLabel: '经济',
    socialLabel: '社会',
    legalLabel: '法律',
    geopoliticalLabel: '地缘政治',
    consequencesHeading: '行动 → 后果',
    actionLabel: '行动',
    consequenceLabel: '后果',
    severityColumnLabel: '严重程度',
    mistakesHeading: '误判与错失机会',
    alternativeLabel: '本应',
    outlookHeading: '战略展望',
    severityLow: '低',
    severityMedium: '中',
    severityHigh: '高',
    severityCritical: '严重',
    executiveSummaryHeading: '执行摘要',
    confidenceHigh: '高置信度',
    confidenceMedium: '中等置信度',
    confidenceLow: '低置信度',
    evidenceRefsHeading: '证据',
    counterArgumentsHeading: '反驳论点',
    conclusionLabel: '结论：',
    premiseLabel: '前提：',
    inferenceLabel: '推理：',
    reasoningChainsHeading: '推理链',
    scenarioPlanningHeading: '情景规划',
    bestCaseLabel: '最佳情景',
    worstCaseLabel: '最坏情景',
    mostLikelyLabel: '最可能情景',
    wildcardsLabel: '不确定因素',
    probabilityLabel: '概率',
    triggersLabel: '触发因素',
    impliedImpactsLabel: '预期影响',
    timelineLabel: '时间线',
    analysisMethodologyHeading: '分析方法论',
    iterationCountLabel: '迭代次数',
    evidenceStrengthLabel: '证据强度',
    evidenceStrong: '强',
    evidenceModerate: '中等',
    evidenceWeak: '弱',
    iterationInitial: '初始评估',
    iterationStakeholderChallenge: '利益相关方审查',
    iterationEvidenceValidation: '证据验证',
    iterationSynthesis: '综合',
    overallConfidenceLabel: '整体置信度',
    pendingNotice: '分析待定 — 本节将由编辑分析工作流完成。',

    perspectivesHeading: '利益相关方视角',
    outcomeMatrixHeading: '利益相关方结果矩阵',
    confidenceLabel: '置信度',
    politicalGroupsLabel: '政治团体',
    civilSocietyLabel: '公民社会',
    industryLabel: '工商界',
    nationalGovtsLabel: '各国政府',
    citizensLabel: '公民',
    euInstitutionsLabel: '欧盟机构',
    positiveLabel: '积极',
    negativeLabel: '消极',
    mixedLabel: '混合',
  },
};

/** Localized section heading strings for motions articles */
export const ANALYSIS_QUALITY_LABELS: LanguageMap<{
  readonly dataCompleteness: string;
  readonly sourceReliability: string;
  readonly analyticalDepth: string;
  readonly timeliness: string;
  readonly high: string;
  readonly medium: string;
  readonly low: string;
}> = {
  en: {
    dataCompleteness: 'Data Completeness',
    sourceReliability: 'Source Reliability',
    analyticalDepth: 'Analytical Depth',
    timeliness: 'Timeliness',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  },
  sv: {
    dataCompleteness: 'Datatäckning',
    sourceReliability: 'Källtillförlitlighet',
    analyticalDepth: 'Analysdjup',
    timeliness: 'Aktualitet',
    high: 'Hög',
    medium: 'Medel',
    low: 'Låg',
  },
  da: {
    dataCompleteness: 'Datadækning',
    sourceReliability: 'Kildepålidelighed',
    analyticalDepth: 'Analysedybde',
    timeliness: 'Aktualitet',
    high: 'Høj',
    medium: 'Middel',
    low: 'Lav',
  },
  no: {
    dataCompleteness: 'Datadekning',
    sourceReliability: 'Kildepålitelighet',
    analyticalDepth: 'Analysedybde',
    timeliness: 'Aktualitet',
    high: 'Høy',
    medium: 'Middels',
    low: 'Lav',
  },
  fi: {
    dataCompleteness: 'Datan Kattavuus',
    sourceReliability: 'Lähteen Luotettavuus',
    analyticalDepth: 'Analyysin Syvyys',
    timeliness: 'Ajankohtaisuus',
    high: 'Korkea',
    medium: 'Keskitaso',
    low: 'Matala',
  },
  de: {
    dataCompleteness: 'Datenvollständigkeit',
    sourceReliability: 'Quellenzuverlässigkeit',
    analyticalDepth: 'Analysetiefe',
    timeliness: 'Aktualität',
    high: 'Hoch',
    medium: 'Mittel',
    low: 'Niedrig',
  },
  fr: {
    dataCompleteness: 'Complétude des Données',
    sourceReliability: 'Fiabilité des Sources',
    analyticalDepth: "Profondeur d'Analyse",
    timeliness: 'Actualité',
    high: 'Élevé',
    medium: 'Moyen',
    low: 'Faible',
  },
  es: {
    dataCompleteness: 'Completitud de Datos',
    sourceReliability: 'Fiabilidad de Fuentes',
    analyticalDepth: 'Profundidad Analítica',
    timeliness: 'Actualidad',
    high: 'Alto',
    medium: 'Medio',
    low: 'Bajo',
  },
  nl: {
    dataCompleteness: 'Datavolledigheid',
    sourceReliability: 'Bronbetrouwbaarheid',
    analyticalDepth: 'Analysediepte',
    timeliness: 'Actualiteit',
    high: 'Hoog',
    medium: 'Gemiddeld',
    low: 'Laag',
  },
  ar: {
    dataCompleteness: 'اكتمال البيانات',
    sourceReliability: 'موثوقية المصدر',
    analyticalDepth: 'عمق التحليل',
    timeliness: 'حداثة البيانات',
    high: 'مرتفع',
    medium: 'متوسط',
    low: 'منخفض',
  },
  he: {
    dataCompleteness: 'שלמות נתונים',
    sourceReliability: 'אמינות מקור',
    analyticalDepth: 'עומק אנליטי',
    timeliness: 'עדכניות',
    high: 'גבוה',
    medium: 'בינוני',
    low: 'נמוך',
  },
  ja: {
    dataCompleteness: 'データ完全性',
    sourceReliability: '出典の信頼性',
    analyticalDepth: '分析の深度',
    timeliness: '適時性',
    high: '高',
    medium: '中',
    low: '低',
  },
  ko: {
    dataCompleteness: '데이터 완전성',
    sourceReliability: '출처 신뢰도',
    analyticalDepth: '분석 깊이',
    timeliness: '적시성',
    high: '높음',
    medium: '보통',
    low: '낮음',
  },
  zh: {
    dataCompleteness: '数据完整性',
    sourceReliability: '来源可靠性',
    analyticalDepth: '分析深度',
    timeliness: '时效性',
    high: '高',
    medium: '中',
    low: '低',
  },
};

// ─── Analysis Insights heading ───────────────────────────────────────────────

/**
 * Localized heading for the analysis pipeline insights section.
 */
export const ANALYSIS_INSIGHTS_HEADING: LanguageMap = {
  en: 'Analysis Pipeline Insights',
  sv: 'Insikter från analyspipeline',
  da: 'Indsigter fra analysepipeline',
  no: 'Innsikter fra analysepipeline',
  fi: 'Analyysiputken tulokset',
  de: 'Erkenntnisse der Analysepipeline',
  fr: 'Résultats du pipeline d\u2019analyse',
  es: 'Resultados del pipeline de análisis',
  nl: 'Inzichten uit de analysepipeline',
  ar: '\u062A\u062D\u0644\u064A\u0644\u0627\u062A \u062E\u0637 \u0627\u0644\u062A\u062D\u0644\u064A\u0644',
  he: '\u05EA\u05D5\u05D1\u05E0\u05D5\u05EA \u05DE\u05DF \u05E6\u05D9\u05E0\u05D5\u05E8 \u05D4\u05E0\u05D9\u05EA\u05D5\u05D7',
  ja: '\u5206\u6790\u30D1\u30A4\u30D7\u30E9\u30A4\u30F3\u306E\u6D1E\u5BDF',
  ko: '\uBD84\uC11D \uD30C\uC774\uD504\uB77C\uC778 \uC778\uC0AC\uC774\uD2B8',
  zh: '\u5206\u6790\u7BA1\u9053\u6D1E\u5BDF',
};
