// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module deep-analysis-strings-eu
 * @description Per-language entries (en, sv, da, no, fi, de, fr) for DEEP_ANALYSIS_STRINGS.
 */

import type { LanguageMap, DeepAnalysisStrings } from '../../types/index.js';

export const DEEP_ANALYSIS_STRINGS_EU: Pick<LanguageMap<DeepAnalysisStrings>, 'en' | 'sv' | 'da' | 'no' | 'fi' | 'de' | 'fr'> = {
  en: {
    sectionHeading: 'Deep Political Analysis',
    whatHeading: 'What Happened',
    whoHeading: 'Key Actors',
    whenHeading: 'Timeline',
    whyHeading: 'Why It Matters — Root Causes',
    stakeholderHeading: 'Winners & Losers',
    winnerLabel: 'Winner',
    loserLabel: 'Loser',
    neutralLabel: 'Neutral',
    impactHeading: 'Impact Assessment',
    politicalLabel: 'Political',
    economicLabel: 'Economic',
    socialLabel: 'Social',
    legalLabel: 'Legal',
    geopoliticalLabel: 'Geopolitical',
    consequencesHeading: 'Actions → Consequences',
    actionLabel: 'Action',
    consequenceLabel: 'Consequence',
    severityColumnLabel: 'Severity',
    mistakesHeading: 'Miscalculations & Missed Opportunities',
    alternativeLabel: 'Should have',
    outlookHeading: 'Strategic Outlook',
    severityLow: 'Low',
    severityMedium: 'Medium',
    severityHigh: 'High',
    severityCritical: 'Critical',

    executiveSummaryHeading: 'Executive Summary',
    confidenceHigh: 'High Confidence',
    confidenceMedium: 'Medium Confidence',
    confidenceLow: 'Low Confidence',
    evidenceRefsHeading: 'Evidence',
    counterArgumentsHeading: 'Counter-arguments',
    conclusionLabel: 'Conclusion:',
    premiseLabel: 'Premise:',
    inferenceLabel: 'Inference:',
    reasoningChainsHeading: 'Reasoning Chains',
    scenarioPlanningHeading: 'Scenario Planning',
    bestCaseLabel: 'Best Case',
    worstCaseLabel: 'Worst Case',
    mostLikelyLabel: 'Most Likely',
    wildcardsLabel: 'Wildcards',
    probabilityLabel: 'Probability',
    triggersLabel: 'Triggers',
    impliedImpactsLabel: 'Implied Impacts',
    timelineLabel: 'Timeline',
    analysisMethodologyHeading: 'Analysis Methodology',
    iterationCountLabel: 'Iterations',
    evidenceStrengthLabel: 'Evidence Strength',
    evidenceStrong: 'Strong',
    evidenceModerate: 'Moderate',
    evidenceWeak: 'Weak',
    iterationInitial: 'Initial Assessment',
    iterationStakeholderChallenge: 'Stakeholder Challenge',
    iterationEvidenceValidation: 'Evidence Validation',
    iterationSynthesis: 'Synthesis',
    overallConfidenceLabel: 'Overall Confidence',
    pendingNotice:
      'Analysis pending — this section will be completed by the editorial intelligence workflow.',
    perspectivesHeading: 'Multi-Stakeholder Perspectives',
    outcomeMatrixHeading: 'Stakeholder Outcome Matrix',
    confidenceLabel: 'Confidence',
    politicalGroupsLabel: 'Political Groups',
    civilSocietyLabel: 'Civil Society',
    industryLabel: 'Industry',
    nationalGovtsLabel: 'National Governments',
    citizensLabel: 'Citizens',
    euInstitutionsLabel: 'EU Institutions',
    positiveLabel: 'Positive',
    negativeLabel: 'Negative',
    mixedLabel: 'Mixed',
  },
  sv: {
    sectionHeading: 'Fördjupad Politisk Analys',
    whatHeading: 'Vad Hände',
    whoHeading: 'Nyckelaktörer',
    whenHeading: 'Tidslinje',
    whyHeading: 'Varför Det Spelar Roll — Grundorsaker',
    stakeholderHeading: 'Vinnare & Förlorare',
    winnerLabel: 'Vinnare',
    loserLabel: 'Förlorare',
    neutralLabel: 'Neutral',
    impactHeading: 'Konsekvensbedömning',
    politicalLabel: 'Politisk',
    economicLabel: 'Ekonomisk',
    socialLabel: 'Social',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Åtgärder → Konsekvenser',
    actionLabel: 'Åtgärd',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Allvarlighetsgrad',
    mistakesHeading: 'Felbedömningar & Missade Möjligheter',
    alternativeLabel: 'Borde ha',
    outlookHeading: 'Strategisk Utsikt',
    severityLow: 'Låg',
    severityMedium: 'Medel',
    severityHigh: 'Hög',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Sammanfattning',
    confidenceHigh: 'Hög Tillförlitlighet',
    confidenceMedium: 'Medel Tillförlitlighet',
    confidenceLow: 'Låg Tillförlitlighet',
    evidenceRefsHeading: 'Bevisning',
    counterArgumentsHeading: 'Motargument',
    conclusionLabel: 'Slutsats:',
    premiseLabel: 'Premiss:',
    inferenceLabel: 'Slutledning:',
    reasoningChainsHeading: 'Resonemangskedjor',
    scenarioPlanningHeading: 'Scenarioplanering',
    bestCaseLabel: 'Bästa Scenario',
    worstCaseLabel: 'Värsta Scenario',
    mostLikelyLabel: 'Mest Troligt',
    wildcardsLabel: 'Jokerkort',
    probabilityLabel: 'Sannolikhet',
    triggersLabel: 'Utlösare',
    impliedImpactsLabel: 'Förväntade Effekter',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysmetodik',
    iterationCountLabel: 'Iterationer',
    evidenceStrengthLabel: 'Bevisstyrka',
    evidenceStrong: 'Stark',
    evidenceModerate: 'Måttlig',
    evidenceWeak: 'Svag',
    iterationInitial: 'Inledande Bedömning',
    iterationStakeholderChallenge: 'Intressentutmaning',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntes',
    overallConfidenceLabel: 'Övergripande Tillförlitlighet',
    pendingNotice:
      'Analys väntar — denna sektion kommer att slutföras av det redaktionella analysarbetsflödet.',
    perspectivesHeading: 'Intressentperspektiv',
    outcomeMatrixHeading: 'Intressentutfallsmatris',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiska grupper',
    civilSocietyLabel: 'Civilsamhälle',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nationella regeringar',
    citizensLabel: 'Medborgare',
    euInstitutionsLabel: 'EU-institutioner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandad',
  },
  da: {
    sectionHeading: 'Dybdegående Politisk Analyse',
    whatHeading: 'Hvad Skete',
    whoHeading: 'Nøgleaktører',
    whenHeading: 'Tidslinje',
    whyHeading: 'Hvorfor Det Betyder Noget — Grundårsager',
    stakeholderHeading: 'Vindere & Tabere',
    winnerLabel: 'Vinder',
    loserLabel: 'Taber',
    neutralLabel: 'Neutral',
    impactHeading: 'Konsekvensvurdering',
    politicalLabel: 'Politisk',
    economicLabel: 'Økonomisk',
    socialLabel: 'Social',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Handlinger → Konsekvenser',
    actionLabel: 'Handling',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Alvorlighed',
    mistakesHeading: 'Fejlvurderinger & Forpassede Muligheder',
    alternativeLabel: 'Burde have',
    outlookHeading: 'Strategisk Udsigt',
    severityLow: 'Lav',
    severityMedium: 'Middel',
    severityHigh: 'Høj',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Resumé',
    confidenceHigh: 'Høj Tillid',
    confidenceMedium: 'Middel Tillid',
    confidenceLow: 'Lav Tillid',
    evidenceRefsHeading: 'Beviser',
    counterArgumentsHeading: 'Modargumenter',
    conclusionLabel: 'Konklusion:',
    premiseLabel: 'Præmis:',
    inferenceLabel: 'Slutning:',
    reasoningChainsHeading: 'Ræsonnementskæder',
    scenarioPlanningHeading: 'Scenarieplanlægning',
    bestCaseLabel: 'Bedste Scenarie',
    worstCaseLabel: 'Værste Scenarie',
    mostLikelyLabel: 'Mest Sandsynligt',
    wildcardsLabel: 'Jokere',
    probabilityLabel: 'Sandsynlighed',
    triggersLabel: 'Udløsere',
    impliedImpactsLabel: 'Forventede Konsekvenser',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysemetodik',
    iterationCountLabel: 'Iterationer',
    evidenceStrengthLabel: 'Bevisstyrke',
    evidenceStrong: 'Stærk',
    evidenceModerate: 'Moderat',
    evidenceWeak: 'Svag',
    iterationInitial: 'Indledende Vurdering',
    iterationStakeholderChallenge: 'Interessentudfordring',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntese',
    overallConfidenceLabel: 'Samlet Tillid',
    pendingNotice:
      'Analyse afventer — denne sektion vil blive udfyldt af det redaktionelle analyse-workflow.',
    perspectivesHeading: 'Interessentperspektiver',
    outcomeMatrixHeading: 'Interessentresultatmatrix',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiske grupper',
    civilSocietyLabel: 'Civilsamfund',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nationale regeringer',
    citizensLabel: 'Borgere',
    euInstitutionsLabel: 'EU-institutioner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandet',
  },
  no: {
    sectionHeading: 'Dyptgående Politisk Analyse',
    whatHeading: 'Hva Skjedde',
    whoHeading: 'Nøkkelaktører',
    whenHeading: 'Tidslinje',
    whyHeading: 'Hvorfor Det Betyr Noe — Grunnårsaker',
    stakeholderHeading: 'Vinnere & Tapere',
    winnerLabel: 'Vinner',
    loserLabel: 'Taper',
    neutralLabel: 'Nøytral',
    impactHeading: 'Konsekvensutredning',
    politicalLabel: 'Politisk',
    economicLabel: 'Økonomisk',
    socialLabel: 'Sosial',
    legalLabel: 'Juridisk',
    geopoliticalLabel: 'Geopolitisk',
    consequencesHeading: 'Handlinger → Konsekvenser',
    actionLabel: 'Handling',
    consequenceLabel: 'Konsekvens',
    severityColumnLabel: 'Alvorlighetsgrad',
    mistakesHeading: 'Feilberegninger & Tapte Muligheter',
    alternativeLabel: 'Burde ha',
    outlookHeading: 'Strategisk Utsikt',
    severityLow: 'Lav',
    severityMedium: 'Middels',
    severityHigh: 'Høy',
    severityCritical: 'Kritisk',
    executiveSummaryHeading: 'Sammendrag',
    confidenceHigh: 'Høy Tillit',
    confidenceMedium: 'Middels Tillit',
    confidenceLow: 'Lav Tillit',
    evidenceRefsHeading: 'Bevis',
    counterArgumentsHeading: 'Motargumenter',
    conclusionLabel: 'Konklusjon:',
    premiseLabel: 'Premiss:',
    inferenceLabel: 'Slutning:',
    reasoningChainsHeading: 'Resonnementsrekker',
    scenarioPlanningHeading: 'Scenarioplanlegging',
    bestCaseLabel: 'Beste Scenario',
    worstCaseLabel: 'Verste Scenario',
    mostLikelyLabel: 'Mest Sannsynlig',
    wildcardsLabel: 'Jokere',
    probabilityLabel: 'Sannsynlighet',
    triggersLabel: 'Utløsere',
    impliedImpactsLabel: 'Forventede Konsekvenser',
    timelineLabel: 'Tidslinje',
    analysisMethodologyHeading: 'Analysemetodikk',
    iterationCountLabel: 'Iterasjoner',
    evidenceStrengthLabel: 'Bevisstyrke',
    evidenceStrong: 'Sterk',
    evidenceModerate: 'Moderat',
    evidenceWeak: 'Svak',
    iterationInitial: 'Innledende Vurdering',
    iterationStakeholderChallenge: 'Interessentutfordring',
    iterationEvidenceValidation: 'Bevisvalidering',
    iterationSynthesis: 'Syntese',
    overallConfidenceLabel: 'Samlet Tillit',
    pendingNotice:
      'Analyse avventer — denne seksjonen vil bli fullført av den redaksjonelle analyse-arbeidsflyten.',
    perspectivesHeading: 'Interessentperspektiver',
    outcomeMatrixHeading: 'Interessentutfallsmatrise',
    confidenceLabel: 'Konfidens',
    politicalGroupsLabel: 'Politiske grupper',
    civilSocietyLabel: 'Sivilsamfunn',
    industryLabel: 'Industri',
    nationalGovtsLabel: 'Nasjonale regjeringer',
    citizensLabel: 'Borgere',
    euInstitutionsLabel: 'EU-institusjoner',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Blandet',
  },
  fi: {
    sectionHeading: 'Syvällinen Poliittinen Analyysi',
    whatHeading: 'Mitä Tapahtui',
    whoHeading: 'Keskeiset Toimijat',
    whenHeading: 'Aikajana',
    whyHeading: 'Miksi Sillä On Merkitystä — Juurisyyt',
    stakeholderHeading: 'Voittajat & Häviäjät',
    winnerLabel: 'Voittaja',
    loserLabel: 'Häviäjä',
    neutralLabel: 'Neutraali',
    impactHeading: 'Vaikutusarviointi',
    politicalLabel: 'Poliittinen',
    economicLabel: 'Taloudellinen',
    socialLabel: 'Sosiaalinen',
    legalLabel: 'Oikeudellinen',
    geopoliticalLabel: 'Geopoliittinen',
    consequencesHeading: 'Toimet → Seuraukset',
    actionLabel: 'Toimi',
    consequenceLabel: 'Seuraus',
    severityColumnLabel: 'Vakavuus',
    mistakesHeading: 'Virhearvioinnit & Menetetyt Mahdollisuudet',
    alternativeLabel: 'Olisi pitänyt',
    outlookHeading: 'Strategiset Näkymät',
    severityLow: 'Matala',
    severityMedium: 'Keskitaso',
    severityHigh: 'Korkea',
    severityCritical: 'Kriittinen',
    executiveSummaryHeading: 'Yhteenveto',
    confidenceHigh: 'Korkea Luotettavuus',
    confidenceMedium: 'Keskitason Luotettavuus',
    confidenceLow: 'Matala Luotettavuus',
    evidenceRefsHeading: 'Todisteet',
    counterArgumentsHeading: 'Vasta-argumentit',
    conclusionLabel: 'Johtopäätös:',
    premiseLabel: 'Lähtökohta:',
    inferenceLabel: 'Päätelmä:',
    reasoningChainsHeading: 'Päättelyketjut',
    scenarioPlanningHeading: 'Skenaarion Suunnittelu',
    bestCaseLabel: 'Paras Skenaario',
    worstCaseLabel: 'Pahin Skenaario',
    mostLikelyLabel: 'Todennäköisin',
    wildcardsLabel: 'Jokerikortit',
    probabilityLabel: 'Todennäköisyys',
    triggersLabel: 'Laukaisijat',
    impliedImpactsLabel: 'Odotetut Vaikutukset',
    timelineLabel: 'Aikajana',
    analysisMethodologyHeading: 'Analyysimenetelmä',
    iterationCountLabel: 'Iteraatiot',
    evidenceStrengthLabel: 'Todistusvoima',
    evidenceStrong: 'Vahva',
    evidenceModerate: 'Kohtalainen',
    evidenceWeak: 'Heikko',
    iterationInitial: 'Alustava Arviointi',
    iterationStakeholderChallenge: 'Sidosryhmähaaste',
    iterationEvidenceValidation: 'Todisteiden Validointi',
    iterationSynthesis: 'Synteesi',
    overallConfidenceLabel: 'Kokonaisluotettavuus',
    pendingNotice:
      'Analyysi odottaa — tämä osio täydennetään toimituksellisen analyysin työnkulussa.',
    perspectivesHeading: 'Sidosryhmänäkökulmat',
    outcomeMatrixHeading: 'Sidosryhmätulosmatriisi',
    confidenceLabel: 'Luotettavuus',
    politicalGroupsLabel: 'Poliittiset ryhmät',
    civilSocietyLabel: 'Kansalaisyhteiskunta',
    industryLabel: 'Teollisuus',
    nationalGovtsLabel: 'Kansalliset hallitukset',
    citizensLabel: 'Kansalaiset',
    euInstitutionsLabel: 'EU:n toimielimet',
    positiveLabel: 'Positiivinen',
    negativeLabel: 'Negatiivinen',
    mixedLabel: 'Sekalainen',
  },
  de: {
    sectionHeading: 'Vertiefte Politische Analyse',
    whatHeading: 'Was Geschah',
    whoHeading: 'Schlüsselakteure',
    whenHeading: 'Zeitachse',
    whyHeading: 'Warum Es Wichtig Ist — Grundursachen',
    stakeholderHeading: 'Gewinner & Verlierer',
    winnerLabel: 'Gewinner',
    loserLabel: 'Verlierer',
    neutralLabel: 'Neutral',
    impactHeading: 'Folgenabschätzung',
    politicalLabel: 'Politisch',
    economicLabel: 'Wirtschaftlich',
    socialLabel: 'Sozial',
    legalLabel: 'Rechtlich',
    geopoliticalLabel: 'Geopolitisch',
    consequencesHeading: 'Handlungen → Konsequenzen',
    actionLabel: 'Handlung',
    consequenceLabel: 'Konsequenz',
    severityColumnLabel: 'Schweregrad',
    mistakesHeading: 'Fehleinschätzungen & Verpasste Chancen',
    alternativeLabel: 'Hätte sollen',
    outlookHeading: 'Strategischer Ausblick',
    severityLow: 'Niedrig',
    severityMedium: 'Mittel',
    severityHigh: 'Hoch',
    severityCritical: 'Kritisch',
    executiveSummaryHeading: 'Zusammenfassung',
    confidenceHigh: 'Hohe Konfidenz',
    confidenceMedium: 'Mittlere Konfidenz',
    confidenceLow: 'Niedrige Konfidenz',
    evidenceRefsHeading: 'Belege',
    counterArgumentsHeading: 'Gegenargumente',
    conclusionLabel: 'Schlussfolgerung:',
    premiseLabel: 'Prämisse:',
    inferenceLabel: 'Ableitung:',
    reasoningChainsHeading: 'Argumentationsketten',
    scenarioPlanningHeading: 'Szenarioplanung',
    bestCaseLabel: 'Bester Fall',
    worstCaseLabel: 'Schlimmster Fall',
    mostLikelyLabel: 'Wahrscheinlichster Fall',
    wildcardsLabel: 'Unbekannte Faktoren',
    probabilityLabel: 'Wahrscheinlichkeit',
    triggersLabel: 'Auslöser',
    impliedImpactsLabel: 'Erwartete Auswirkungen',
    timelineLabel: 'Zeitachse',
    analysisMethodologyHeading: 'Analysemethodik',
    iterationCountLabel: 'Iterationen',
    evidenceStrengthLabel: 'Beweisstärke',
    evidenceStrong: 'Stark',
    evidenceModerate: 'Mäßig',
    evidenceWeak: 'Schwach',
    iterationInitial: 'Erstbewertung',
    iterationStakeholderChallenge: 'Stakeholder-Herausforderung',
    iterationEvidenceValidation: 'Beweisvalidierung',
    iterationSynthesis: 'Synthese',
    overallConfidenceLabel: 'Gesamtkonfidenz',
    pendingNotice:
      'Analyse ausstehend — dieser Abschnitt wird durch den redaktionellen Analyse-Workflow vervollständigt.',
    perspectivesHeading: 'Stakeholder-Perspektiven',
    outcomeMatrixHeading: 'Stakeholder-Ergebnismatrix',
    confidenceLabel: 'Konfidenz',
    politicalGroupsLabel: 'Politische Fraktionen',
    civilSocietyLabel: 'Zivilgesellschaft',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Nationale Regierungen',
    citizensLabel: 'Bürger',
    euInstitutionsLabel: 'EU-Institutionen',
    positiveLabel: 'Positiv',
    negativeLabel: 'Negativ',
    mixedLabel: 'Gemischt',
  },
  fr: {
    sectionHeading: 'Analyse Politique Approfondie',
    whatHeading: "Ce Qui S'est Passé",
    whoHeading: 'Acteurs Clés',
    whenHeading: 'Chronologie',
    whyHeading: "Pourquoi C'est Important — Causes Profondes",
    stakeholderHeading: 'Gagnants & Perdants',
    winnerLabel: 'Gagnant',
    loserLabel: 'Perdant',
    neutralLabel: 'Neutre',
    impactHeading: "Évaluation d'Impact",
    politicalLabel: 'Politique',
    economicLabel: 'Économique',
    socialLabel: 'Social',
    legalLabel: 'Juridique',
    geopoliticalLabel: 'Géopolitique',
    consequencesHeading: 'Actions → Conséquences',
    actionLabel: 'Action',
    consequenceLabel: 'Conséquence',
    severityColumnLabel: 'Gravité',
    mistakesHeading: 'Erreurs de Calcul & Opportunités Manquées',
    alternativeLabel: 'Aurait dû',
    outlookHeading: 'Perspectives Stratégiques',
    severityLow: 'Faible',
    severityMedium: 'Moyen',
    severityHigh: 'Élevé',
    severityCritical: 'Critique',
    executiveSummaryHeading: 'Synthèse',
    confidenceHigh: 'Confiance Élevée',
    confidenceMedium: 'Confiance Moyenne',
    confidenceLow: 'Confiance Faible',
    evidenceRefsHeading: 'Preuves',
    counterArgumentsHeading: 'Contre-arguments',
    conclusionLabel: 'Conclusion :',
    premiseLabel: 'Prémisse :',
    inferenceLabel: 'Inférence :',
    reasoningChainsHeading: 'Chaînes de Raisonnement',
    scenarioPlanningHeading: 'Planification de Scénarios',
    bestCaseLabel: 'Meilleur Scénario',
    worstCaseLabel: 'Pire Scénario',
    mostLikelyLabel: 'Plus Probable',
    wildcardsLabel: 'Imprévus',
    probabilityLabel: 'Probabilité',
    triggersLabel: 'Déclencheurs',
    impliedImpactsLabel: 'Impacts Attendus',
    timelineLabel: 'Chronologie',
    analysisMethodologyHeading: "Méthodologie d'Analyse",
    iterationCountLabel: 'Itérations',
    evidenceStrengthLabel: 'Force des Preuves',
    evidenceStrong: 'Fort',
    evidenceModerate: 'Modéré',
    evidenceWeak: 'Faible',
    iterationInitial: 'Évaluation Initiale',
    iterationStakeholderChallenge: 'Défi des Parties Prenantes',
    iterationEvidenceValidation: 'Validation des Preuves',
    iterationSynthesis: 'Synthèse',
    overallConfidenceLabel: 'Confiance Globale',
    pendingNotice:
      "Analyse en attente — cette section sera complétée par le flux de travail d'analyse éditoriale.",
    perspectivesHeading: 'Perspectives des Parties Prenantes',
    outcomeMatrixHeading: 'Matrice des Résultats des Parties Prenantes',
    confidenceLabel: 'Confiance',
    politicalGroupsLabel: 'Groupes politiques',
    civilSocietyLabel: 'Société civile',
    industryLabel: 'Industrie',
    nationalGovtsLabel: 'Gouvernements nationaux',
    citizensLabel: 'Citoyens',
    euInstitutionsLabel: "Institutions de l'UE",
    positiveLabel: 'Positif',
    negativeLabel: 'Négatif',
    mixedLabel: 'Mixte',
  },
};
