// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/LocalizedKeywords
 * @description Per-language SEO base keywords per article category. Editing one language no longer touches any article body strings.
 *
 * Per-language strings live together so a translator can update one language
 * for this article type without touching any other article type.
 */

/* eslint-disable sonarjs/no-duplicate-string -- Localized keyword dictionaries have intentional repetition across categories */

import type { LanguageMap } from '../../types/index.js';
import { ArticleCategory } from '../../types/index.js';
export const LOCALIZED_KEYWORDS: LanguageMap<Record<string, readonly string[]>> = {
  en: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU Parliament',
      'week ahead',
      'committee meetings',
      'plenary debate',
      'European Parliament',
      'legislation',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU Parliament',
      'month ahead',
      'legislative agenda',
      'European Parliament',
      'plenary session',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU Parliament',
      'breaking news',
      'European Parliament',
      'legislation',
      'plenary vote',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU Parliament',
      'committee activity',
      'European Parliament',
      'committee report',
      'legislation',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU Parliament',
      'legislative procedures',
      'European Parliament',
      'proposal',
      'regulation',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU Parliament',
      'plenary votes',
      'resolutions',
      'European Parliament',
      'voting record',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU Parliament',
      'week in review',
      'European Parliament',
      'summary',
      'legislation',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU Parliament',
      'month in review',
      'European Parliament',
      'summary',
      'legislative review',
    ],
  },
  sv: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU-parlamentet',
      'veckan framåt',
      'utskottsmöten',
      'plenardebatt',
      'Europaparlamentet',
      'lagstiftning',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU-parlamentet',
      'månaden framåt',
      'lagstiftningsagenda',
      'Europaparlamentet',
      'plenarsession',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU-parlamentet',
      'senaste nytt',
      'Europaparlamentet',
      'lagstiftning',
      'omröstning',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU-parlamentet',
      'utskottsverksamhet',
      'Europaparlamentet',
      'utskottsrapport',
      'lagstiftning',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU-parlamentet',
      'lagstiftningsförfaranden',
      'Europaparlamentet',
      'förslag',
      'förordning',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU-parlamentet',
      'omröstningar',
      'resolutioner',
      'Europaparlamentet',
      'röstprotokoll',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU-parlamentet',
      'veckans sammanfattning',
      'Europaparlamentet',
      'sammanfattning',
      'lagstiftning',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU-parlamentet',
      'månadens sammanfattning',
      'Europaparlamentet',
      'sammanfattning',
      'lagstiftningsöversikt',
    ],
  },
  da: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU-Parlamentet',
      'ugen fremover',
      'udvalgsmøder',
      'plenardebat',
      'Europa-Parlamentet',
      'lovgivning',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU-Parlamentet',
      'måneden fremover',
      'lovgivningsdagsorden',
      'Europa-Parlamentet',
      'plenarsamling',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU-Parlamentet',
      'seneste nyt',
      'Europa-Parlamentet',
      'lovgivning',
      'afstemning',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU-Parlamentet',
      'udvalgsaktivitet',
      'Europa-Parlamentet',
      'udvalgsrapport',
      'lovgivning',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU-Parlamentet',
      'lovgivningsprocedurer',
      'Europa-Parlamentet',
      'forslag',
      'forordning',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU-Parlamentet',
      'plenar-afstemninger',
      'beslutninger',
      'Europa-Parlamentet',
      'stemmeoversigt',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU-Parlamentet',
      'ugens overblik',
      'Europa-Parlamentet',
      'sammenfatning',
      'lovgivning',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU-Parlamentet',
      'månedens overblik',
      'Europa-Parlamentet',
      'sammenfatning',
      'lovgivningsoversigt',
    ],
  },
  no: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU-parlamentet',
      'uken fremover',
      'komitémøter',
      'plenardebatt',
      'Europaparlamentet',
      'lovgivning',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU-parlamentet',
      'måneden fremover',
      'lovgivningsagenda',
      'Europaparlamentet',
      'plenarsesjon',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU-parlamentet',
      'siste nytt',
      'Europaparlamentet',
      'lovgivning',
      'avstemning',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU-parlamentet',
      'komitéaktivitet',
      'Europaparlamentet',
      'komitérapport',
      'lovgivning',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU-parlamentet',
      'lovgivningsprosedyrer',
      'Europaparlamentet',
      'forslag',
      'forordning',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU-parlamentet',
      'plenaravstemninger',
      'vedtak',
      'Europaparlamentet',
      'stemmeprotokoll',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU-parlamentet',
      'ukens oppsummering',
      'Europaparlamentet',
      'sammendrag',
      'lovgivning',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU-parlamentet',
      'månedens oppsummering',
      'Europaparlamentet',
      'sammendrag',
      'lovgivningsoversikt',
    ],
  },
  fi: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU-parlamentti',
      'tuleva viikko',
      'valiokuntakokoukset',
      'täysistuntokeskustelu',
      'Euroopan parlamentti',
      'lainsäädäntö',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU-parlamentti',
      'tuleva kuukausi',
      'lainsäädäntöohjelma',
      'Euroopan parlamentti',
      'täysistunto',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU-parlamentti',
      'uusimmat uutiset',
      'Euroopan parlamentti',
      'lainsäädäntö',
      'äänestys',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU-parlamentti',
      'valiokuntatoiminta',
      'Euroopan parlamentti',
      'valiokuntaraportti',
      'lainsäädäntö',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU-parlamentti',
      'lainsäädäntömenettelyt',
      'Euroopan parlamentti',
      'ehdotus',
      'asetus',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU-parlamentti',
      'täysistuntoäänestykset',
      'päätöslauselmat',
      'Euroopan parlamentti',
      'äänestyspöytäkirja',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU-parlamentti',
      'viikon katsaus',
      'Euroopan parlamentti',
      'yhteenveto',
      'lainsäädäntö',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU-parlamentti',
      'kuukauden katsaus',
      'Euroopan parlamentti',
      'yhteenveto',
      'lainsäädäntökatsaus',
    ],
  },
  de: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU-Parlament',
      'Woche voraus',
      'Ausschusssitzungen',
      'Plenardebatte',
      'Europäisches Parlament',
      'Gesetzgebung',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU-Parlament',
      'Monat voraus',
      'Gesetzgebungsagenda',
      'Europäisches Parlament',
      'Plenarsitzung',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU-Parlament',
      'Eilmeldung',
      'Europäisches Parlament',
      'Gesetzgebung',
      'Abstimmung',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU-Parlament',
      'Ausschusstätigkeit',
      'Europäisches Parlament',
      'Ausschussbericht',
      'Gesetzgebung',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU-Parlament',
      'Gesetzgebungsverfahren',
      'Europäisches Parlament',
      'Vorschlag',
      'Verordnung',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU-Parlament',
      'Plenar-Abstimmungen',
      'Entschließungen',
      'Europäisches Parlament',
      'Abstimmungsprotokoll',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU-Parlament',
      'Wochenrückblick',
      'Europäisches Parlament',
      'Zusammenfassung',
      'Gesetzgebung',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU-Parlament',
      'Monatsrückblick',
      'Europäisches Parlament',
      'Zusammenfassung',
      'Gesetzgebungsübersicht',
    ],
  },
  fr: {
    [ArticleCategory.WEEK_AHEAD]: [
      'Parlement européen',
      'semaine à venir',
      'réunions de commission',
      'débat en plénière',
      'législation',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'Parlement européen',
      'mois à venir',
      'agenda législatif',
      'session plénière',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'Parlement européen',
      'dernières nouvelles',
      'législation',
      'vote en plénière',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'Parlement européen',
      'travaux des commissions',
      'rapport de commission',
      'législation',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'Parlement européen',
      'procédures législatives',
      'proposition',
      'règlement',
    ],
    [ArticleCategory.MOTIONS]: [
      'Parlement européen',
      'votes en plénière',
      'résolutions',
      'protocole de vote',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'Parlement européen',
      'bilan de la semaine',
      'résumé',
      'législation',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'Parlement européen',
      'bilan du mois',
      'résumé',
      'revue législative',
    ],
  },
  es: {
    [ArticleCategory.WEEK_AHEAD]: [
      'Parlamento Europeo',
      'semana próxima',
      'reuniones de comisión',
      'debate plenario',
      'legislación',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'Parlamento Europeo',
      'mes próximo',
      'agenda legislativa',
      'sesión plenaria',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'Parlamento Europeo',
      'noticias de última hora',
      'legislación',
      'votación plenaria',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'Parlamento Europeo',
      'actividad de comisiones',
      'informe de comisión',
      'legislación',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'Parlamento Europeo',
      'procedimientos legislativos',
      'propuesta',
      'reglamento',
    ],
    [ArticleCategory.MOTIONS]: [
      'Parlamento Europeo',
      'votaciones plenarias',
      'resoluciones',
      'acta de votación',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'Parlamento Europeo',
      'resumen de la semana',
      'resumen',
      'legislación',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'Parlamento Europeo',
      'resumen del mes',
      'resumen',
      'revisión legislativa',
    ],
  },
  nl: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU-Parlement',
      'week vooruit',
      'commissievergaderingen',
      'plenair debat',
      'Europees Parlement',
      'wetgeving',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'EU-Parlement',
      'maand vooruit',
      'wetgevingsagenda',
      'Europees Parlement',
      'plenaire zitting',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'EU-Parlement',
      'laatste nieuws',
      'Europees Parlement',
      'wetgeving',
      'stemming',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU-Parlement',
      'commissieactiviteiten',
      'Europees Parlement',
      'commissieverslag',
      'wetgeving',
    ],
    [ArticleCategory.PROPOSITIONS]: [
      'EU-Parlement',
      'wetgevingsprocedures',
      'Europees Parlement',
      'voorstel',
      'verordening',
    ],
    [ArticleCategory.MOTIONS]: [
      'EU-Parlement',
      'plenaire stemmingen',
      'resoluties',
      'Europees Parlement',
      'stemprotocol',
    ],
    [ArticleCategory.WEEK_IN_REVIEW]: [
      'EU-Parlement',
      'weekoverzicht',
      'Europees Parlement',
      'samenvatting',
      'wetgeving',
    ],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU-Parlement',
      'maandoverzicht',
      'Europees Parlement',
      'samenvatting',
      'wetgevingsoverzicht',
    ],
  },
  ar: {
    [ArticleCategory.WEEK_AHEAD]: [
      'البرلمان الأوروبي',
      'الأسبوع القادم',
      'اجتماعات اللجان',
      'المناقشة العامة',
      'التشريع',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'البرلمان الأوروبي',
      'الشهر القادم',
      'جدول الأعمال التشريعي',
      'الجلسة العامة',
    ],
    [ArticleCategory.BREAKING_NEWS]: [
      'البرلمان الأوروبي',
      'أخبار عاجلة',
      'التشريع',
      'التصويت العام',
    ],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'البرلمان الأوروبي',
      'نشاط اللجان',
      'تقرير اللجنة',
      'التشريع',
    ],
    [ArticleCategory.PROPOSITIONS]: ['البرلمان الأوروبي', 'الإجراءات التشريعية', 'مقترح', 'تنظيم'],
    [ArticleCategory.MOTIONS]: ['البرلمان الأوروبي', 'التصويتات العامة', 'القرارات', 'سجل التصويت'],
    [ArticleCategory.WEEK_IN_REVIEW]: ['البرلمان الأوروبي', 'مراجعة الأسبوع', 'ملخص', 'التشريع'],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'البرلمان الأوروبي',
      'مراجعة الشهر',
      'ملخص',
      'مراجعة تشريعية',
    ],
  },
  he: {
    [ArticleCategory.WEEK_AHEAD]: [
      'הפרלמנט האירופי',
      'השבוע הקרוב',
      'ישיבות ועדות',
      'דיון מליאה',
      'חקיקה',
    ],
    [ArticleCategory.MONTH_AHEAD]: [
      'הפרלמנט האירופי',
      'החודש הקרוב',
      'סדר יום חקיקתי',
      'ישיבת מליאה',
    ],
    [ArticleCategory.BREAKING_NEWS]: ['הפרלמנט האירופי', 'חדשות דחופות', 'חקיקה', 'הצבעת מליאה'],
    [ArticleCategory.COMMITTEE_REPORTS]: ['הפרלמנט האירופי', 'פעילות ועדות', 'דוח ועדה', 'חקיקה'],
    [ArticleCategory.PROPOSITIONS]: ['הפרלמנט האירופי', 'הליכי חקיקה', 'הצעה', 'תקנה'],
    [ArticleCategory.MOTIONS]: ['הפרלמנט האירופי', 'הצבעות מליאה', 'החלטות', 'פרוטוקול הצבעה'],
    [ArticleCategory.WEEK_IN_REVIEW]: ['הפרלמנט האירופי', 'סיכום השבוע', 'סיכום', 'חקיקה'],
    [ArticleCategory.MONTH_IN_REVIEW]: ['הפרלמנט האירופי', 'סיכום החודש', 'סיכום', 'סקירה חקיקתית'],
  },
  ja: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU議会',
      '今週の予定',
      '委員会会議',
      '本会議討論',
      '欧州議会',
      '立法',
    ],
    [ArticleCategory.MONTH_AHEAD]: ['EU議会', '今月の予定', '立法議題', '欧州議会', '本会議'],
    [ArticleCategory.BREAKING_NEWS]: ['EU議会', '速報', '欧州議会', '立法', '本会議投票'],
    [ArticleCategory.COMMITTEE_REPORTS]: ['EU議会', '委員会活動', '欧州議会', '委員会報告', '立法'],
    [ArticleCategory.PROPOSITIONS]: ['EU議会', '立法手続', '欧州議会', '提案', '規則'],
    [ArticleCategory.MOTIONS]: ['EU議会', '本会議投票', '決議', '欧州議会', '投票記録'],
    [ArticleCategory.WEEK_IN_REVIEW]: ['EU議会', '週間レビュー', '欧州議会', '要約', '立法'],
    [ArticleCategory.MONTH_IN_REVIEW]: [
      'EU議会',
      '月間レビュー',
      '欧州議会',
      '要約',
      '立法レビュー',
    ],
  },
  ko: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU 의회',
      '다음 주 일정',
      '위원회 회의',
      '본회의 토론',
      '유럽 의회',
      '입법',
    ],
    [ArticleCategory.MONTH_AHEAD]: ['EU 의회', '다음 달 일정', '입법 의제', '유럽 의회', '본회의'],
    [ArticleCategory.BREAKING_NEWS]: ['EU 의회', '속보', '유럽 의회', '입법', '본회의 투표'],
    [ArticleCategory.COMMITTEE_REPORTS]: [
      'EU 의회',
      '위원회 활동',
      '유럽 의회',
      '위원회 보고서',
      '입법',
    ],
    [ArticleCategory.PROPOSITIONS]: ['EU 의회', '입법 절차', '유럽 의회', '제안', '규정'],
    [ArticleCategory.MOTIONS]: ['EU 의회', '본회의 투표', '결의', '유럽 의회', '투표 기록'],
    [ArticleCategory.WEEK_IN_REVIEW]: ['EU 의회', '주간 리뷰', '유럽 의회', '요약', '입법'],
    [ArticleCategory.MONTH_IN_REVIEW]: ['EU 의회', '월간 리뷰', '유럽 의회', '요약', '입법 리뷰'],
  },
  zh: {
    [ArticleCategory.WEEK_AHEAD]: [
      'EU议会',
      '下周预告',
      '委员会会议',
      '全会辩论',
      '欧洲议会',
      '立法',
    ],
    [ArticleCategory.MONTH_AHEAD]: ['EU议会', '下月预告', '立法议程', '欧洲议会', '全会'],
    [ArticleCategory.BREAKING_NEWS]: ['EU议会', '突发新闻', '欧洲议会', '立法', '全会投票'],
    [ArticleCategory.COMMITTEE_REPORTS]: ['EU议会', '委员会活动', '欧洲议会', '委员会报告', '立法'],
    [ArticleCategory.PROPOSITIONS]: ['EU议会', '立法程序', '欧洲议会', '提案', '条例'],
    [ArticleCategory.MOTIONS]: ['EU议会', '全体投票', '决议', '欧洲议会', '投票记录'],
    [ArticleCategory.WEEK_IN_REVIEW]: ['EU议会', '每周回顾', '欧洲议会', '摘要', '立法'],
    [ArticleCategory.MONTH_IN_REVIEW]: ['EU议会', '每月回顾', '欧洲议会', '摘要', '立法审查'],
  },
};
/* eslint-enable sonarjs/no-duplicate-string */

/** Week ahead title templates per language */
