// SPDX-FileCopyrightText: 2024-2026 Hack23 AB
// SPDX-License-Identifier: Apache-2.0

/**
 * @module Constants/Articles/WeekAhead
 * @description Week-Ahead article: 14-language title generator, body strings, and per-stakeholder strings.
 *
 * Per-language strings live together so a translator can update one language
 * for this article type without touching any other article type.
 */

import type { LanguageMap, LangTitleSubtitle, WeekAheadStrings, WeekAheadStakeholderStrings } from '../../types/index.js';
export const WEEK_AHEAD_TITLES: LanguageMap<(start: string, end: string) => LangTitleSubtitle> = {
  en: (start, end) => ({
    title: `Week Ahead: ${start} to ${end}`,
    subtitle:
      'European Parliament calendar, committee meetings, and plenary debates for the coming week',
  }),
  sv: (start, end) => ({
    title: `Vecka Framåt: ${start} till ${end}`,
    subtitle: 'Europaparlamentets kalender, utskottsmöten och plenardebatter för kommande vecka',
  }),
  da: (start, end) => ({
    title: `Ugen Fremover: ${start} til ${end}`,
    subtitle: 'Europa-Parlamentets kalender, udvalgsmøder og plenardebatter for den kommende uge',
  }),
  no: (start, end) => ({
    title: `Uken Fremover: ${start} til ${end}`,
    subtitle: 'Europaparlamentets kalender, komitémøter og plenardebatter for kommende uke',
  }),
  fi: (start, end) => ({
    title: `Tuleva Viikko: ${start} - ${end}`,
    subtitle:
      'Euroopan parlamentin kalenteri, valiokuntien kokoukset ja täysistuntokeskustelut tulevalle viikolle',
  }),
  de: (start, end) => ({
    title: `Woche Voraus: ${start} bis ${end}`,
    subtitle:
      'Europäischer Parlamentskalender, Ausschusssitzungen und Plenardebatten für die kommende Woche',
  }),
  fr: (start, end) => ({
    title: `Semaine à Venir: ${start} au ${end}`,
    subtitle:
      'Calendrier du Parlement européen, réunions de commission et débats pléniers pour la semaine à venir',
  }),
  es: (start, end) => ({
    title: `Semana Próxima: ${start} a ${end}`,
    subtitle:
      'Calendario del Parlamento Europeo, reuniones de comisión y debates plenarios para la próxima semana',
  }),
  nl: (start, end) => ({
    title: `Week Vooruit: ${start} tot ${end}`,
    subtitle:
      'Europees Parlement kalender, commissievergaderingen en plenaire debatten voor de komende week',
  }),
  ar: (start, end) => ({
    title: `الأسبوع القادم: ${start} إلى ${end}`,
    subtitle: 'جدول أعمال البرلمان الأوروبي واجتماعات اللجان والنقاشات العامة للأسبوع القادم',
  }),
  he: (start, end) => ({
    title: `השבוע הקרוב: ${start} עד ${end}`,
    subtitle: 'לוח הזמנים של הפרלמנט האירופי, ישיבות ועדות ודיוני מליאה לשבוע הקרוב',
  }),
  ja: (start, end) => ({
    title: `今週の予定: ${start} ～ ${end}`,
    subtitle: '欧州議会のカレンダー、委員会会合、本会議の討論',
  }),
  ko: (start, end) => ({
    title: `다음 주 일정: ${start} ~ ${end}`,
    subtitle: '유럽 의회 일정, 위원회 회의 및 본회의 토론',
  }),
  zh: (start, end) => ({
    title: `下周预告: ${start} 至 ${end}`,
    subtitle: '欧洲议会日历、委员会会议和全体辩论',
  }),
};

/** Month ahead title templates per language */
export const WEEK_AHEAD_STRINGS: LanguageMap<WeekAheadStrings> = {
  en: {
    lede: 'The European Parliament prepares for an active week ahead with multiple committee meetings and plenary sessions scheduled',
    plenarySessions: 'Plenary Sessions',
    committeeMeetings: 'Committee Meetings',
    legislativeDocuments: 'Upcoming Legislative Documents',
    legislativePipeline: 'Legislative Pipeline',
    parliamentaryQuestions: 'Parliamentary Questions',
    noPlenary: 'No plenary sessions scheduled for this period.',
    bottleneckIndicator: '⚠ Bottleneck',
    whatToWatch: 'What to Watch',
  },
  sv: {
    lede: 'Europaparlamentet förbereder sig för en aktiv vecka framåt med flera utskottsmöten och plenarsammanträden planerade',
    plenarySessions: 'Plenarsammanträden',
    committeeMeetings: 'Utskottsmöten',
    legislativeDocuments: 'Kommande Lagstiftningsdokument',
    legislativePipeline: 'Lagstiftnings-Pipeline',
    parliamentaryQuestions: 'Parlamentariska Frågor',
    noPlenary: 'Inga plenarsammanträden planerade för denna period.',
    bottleneckIndicator: '⚠ Flaskhals',
    whatToWatch: 'Att Bevaka',
  },
  da: {
    lede: 'Europa-Parlamentet forbereder sig på en aktiv uge med flere udvalgsmøder og plenarforsamlinger planlagt',
    plenarySessions: 'Plenarforsamlinger',
    committeeMeetings: 'Udvalgsmøder',
    legislativeDocuments: 'Kommende Lovgivningsdokumenter',
    legislativePipeline: 'Lovgivningspipeline',
    parliamentaryQuestions: 'Parlamentariske Spørgsmål',
    noPlenary: 'Ingen plenarforsamlinger planlagt for denne periode.',
    bottleneckIndicator: '⚠ Flaskehals',
    whatToWatch: 'Hvad Man Skal Holde Øje Med',
  },
  no: {
    lede: 'Europaparlamentet forbereder seg på en aktiv uke fremover med flere komitémøter og plenarrsamlinger planlagt',
    plenarySessions: 'Plenarsamlinger',
    committeeMeetings: 'Komitémøter',
    legislativeDocuments: 'Kommende Lovgivningsdokumenter',
    legislativePipeline: 'Lovgivningspipeline',
    parliamentaryQuestions: 'Parlamentariske Spørsmål',
    noPlenary: 'Ingen plenarsamlinger planlagt for denne perioden.',
    bottleneckIndicator: '⚠ Flaskehals',
    whatToWatch: 'Hva Man Bør Følge Med På',
  },
  fi: {
    lede: 'Euroopan parlamentti valmistautuu aktiiviseen viikkoon useilla valiokuntakokouksilla ja täysistunnoilla suunnitelmissa',
    plenarySessions: 'Täysistunnot',
    committeeMeetings: 'Valiokuntakokoukset',
    legislativeDocuments: 'Tulevat Lainsäädäntöasiakirjat',
    legislativePipeline: 'Lainsäädäntöputki',
    parliamentaryQuestions: 'Parlamentaariset Kysymykset',
    noPlenary: 'Ei täysistuntoja suunniteltu tälle jaksolle.',
    bottleneckIndicator: '⚠ Pullonkaula',
    whatToWatch: 'Mitä Seurata',
  },
  de: {
    lede: 'Das Europäische Parlament bereitet sich auf eine aktive Woche mit mehreren Ausschusssitzungen und Plenarsitzungen vor',
    plenarySessions: 'Plenarsitzungen',
    committeeMeetings: 'Ausschusssitzungen',
    legislativeDocuments: 'Anstehende Gesetzgebungsdokumente',
    legislativePipeline: 'Gesetzgebungspipeline',
    parliamentaryQuestions: 'Parlamentarische Anfragen',
    noPlenary: 'Keine Plenarsitzungen für diesen Zeitraum geplant.',
    bottleneckIndicator: '⚠ Engpass',
    whatToWatch: 'Was Zu Beachten Ist',
  },
  fr: {
    lede: 'Le Parlement européen se prépare pour une semaine active avec plusieurs réunions de commission et sessions plénières programmées',
    plenarySessions: 'Sessions Plénières',
    committeeMeetings: 'Réunions de Commission',
    legislativeDocuments: 'Documents Législatifs à Venir',
    legislativePipeline: 'Pipeline Législatif',
    parliamentaryQuestions: 'Questions Parlementaires',
    noPlenary: 'Aucune session plénière prévue pour cette période.',
    bottleneckIndicator: "⚠ Goulot d'étranglement",
    whatToWatch: 'À Suivre',
  },
  es: {
    lede: 'El Parlamento Europeo se prepara para una semana activa con múltiples reuniones de comisión y sesiones plenarias programadas',
    plenarySessions: 'Sesiones Plenarias',
    committeeMeetings: 'Reuniones de Comisión',
    legislativeDocuments: 'Documentos Legislativos Próximos',
    legislativePipeline: 'Pipeline Legislativo',
    parliamentaryQuestions: 'Preguntas Parlamentarias',
    noPlenary: 'No hay sesiones plenarias programadas para este período.',
    bottleneckIndicator: '⚠ Cuello de botella',
    whatToWatch: 'Qué Observar',
  },
  nl: {
    lede: 'Het Europees Parlement bereidt zich voor op een actieve week met meerdere commissievergaderingen en plenaire vergaderingen gepland',
    plenarySessions: 'Plenaire Vergaderingen',
    committeeMeetings: 'Commissievergaderingen',
    legislativeDocuments: 'Aankomende Wetgevende Documenten',
    legislativePipeline: 'Wetgevende Pipeline',
    parliamentaryQuestions: 'Parlementaire Vragen',
    noPlenary: 'Geen plenaire vergaderingen gepland voor deze periode.',
    bottleneckIndicator: '⚠ Knelpunt',
    whatToWatch: 'Wat Te Volgen',
  },
  ar: {
    lede: 'يستعد البرلمان الأوروبي لأسبوع نشط مع العديد من اجتماعات اللجان والجلسات العامة المجدولة',
    plenarySessions: 'الجلسات العامة',
    committeeMeetings: 'اجتماعات اللجان',
    legislativeDocuments: 'الوثائق التشريعية القادمة',
    legislativePipeline: 'خط الأنابيب التشريعي',
    parliamentaryQuestions: 'الأسئلة البرلمانية',
    noPlenary: 'لا توجد جلسات عامة مجدولة لهذه الفترة.',
    bottleneckIndicator: '⚠ عنق زجاجة',
    whatToWatch: 'ما يجب متابعته',
  },
  he: {
    lede: 'הפרלמנט האירופי מתכונן לשבוע פעיל עם מספר ישיבות ועדות וישיבות מליאה מתוכננות',
    plenarySessions: 'ישיבות מליאה',
    committeeMeetings: 'ישיבות ועדות',
    legislativeDocuments: 'מסמכים חקיקתיים קרובים',
    legislativePipeline: 'צינור חקיקה',
    parliamentaryQuestions: 'שאילתות פרלמנטריות',
    noPlenary: 'אין ישיבות מליאה מתוכננות לתקופה זו.',
    bottleneckIndicator: '⚠ צוואר בקבוק',
    whatToWatch: 'מה לעקוב',
  },
  ja: {
    lede: '欧州議会は、複数の委員会会合と本会議が予定されている活発な一週間に備えています',
    plenarySessions: '本会議',
    committeeMeetings: '委員会会合',
    legislativeDocuments: '今後の立法文書',
    legislativePipeline: '立法パイプライン',
    parliamentaryQuestions: '議会質問',
    noPlenary: 'この期間に本会議は予定されていません。',
    bottleneckIndicator: '⚠ ボトルネック',
    whatToWatch: '注目すべきポイント',
  },
  ko: {
    lede: '유럽 의회는 다수의 위원회 회의와 본회의가 예정된 활발한 한 주를 준비하고 있습니다',
    plenarySessions: '본회의',
    committeeMeetings: '위원회 회의',
    legislativeDocuments: '예정된 입법 문서',
    legislativePipeline: '입법 파이프라인',
    parliamentaryQuestions: '의회 질문',
    noPlenary: '이 기간에 예정된 본회의가 없습니다.',
    bottleneckIndicator: '⚠ 병목 현상',
    whatToWatch: '주목할 사항',
  },
  zh: {
    lede: '欧洲议会正在为活跃的一周做准备，多场委员会会议和全体会议已排定日程',
    plenarySessions: '全体会议',
    committeeMeetings: '委员会会议',
    legislativeDocuments: '即将发布的立法文件',
    legislativePipeline: '立法管道',
    parliamentaryQuestions: '议会质询',
    noPlenary: '该时段没有预定的全体会议。',
    bottleneckIndicator: '⚠ 瓶颈',
    whatToWatch: '值得关注',
  },
};

/** Localized strings for the week-ahead stakeholder impact section */
export const WEEK_AHEAD_STAKEHOLDER_STRINGS: LanguageMap<WeekAheadStakeholderStrings> = {
  en: {
    heading: 'Stakeholder Impact Analysis',
    temperatureLabel: 'Political Temperature',
    impactHeader: 'Impact',
    stakeholderHeader: 'Stakeholder',
    reasonHeader: 'Reason',
    tempLow: 'Low',
    tempModerate: 'Moderate',
    tempHigh: 'High',
    tempVeryHigh: 'Very High',
    stakeholderPoliticalGroups: 'Political Groups',
    stakeholderCivilSociety: 'Civil Society',
    stakeholderIndustry: 'Industry',
    stakeholderEuCitizens: 'EU Citizens',
    stakeholderNationalGovernments: 'National Governments',
    stakeholderEuInstitutions: 'EU Institutions',
    reasonEventsScheduled: '{count} parliamentary event(s) scheduled',
    reasonDocumentsUnderReview: '{count} legislative document(s) under review',
    reasonIndustryRegulatoryAgenda: 'Regulatory agenda may affect business environment',
    reasonCitizensDecisionsShapePolicy: 'Parliamentary decisions shape EU-wide policy',
    reasonDocumentsRequireTransposition: '{count} document(s) may require national transposition',
    reasonInstitutionsCoordination: 'Cross-institutional coordination required',
  },
  sv: {
    heading: 'Intressentanalys',
    temperatureLabel: 'Politisk Temperatur',
    impactHeader: 'Påverkan',
    stakeholderHeader: 'Intressent',
    reasonHeader: 'Anledning',
    tempLow: 'Låg',
    tempModerate: 'Måttlig',
    tempHigh: 'Hög',
    tempVeryHigh: 'Mycket hög',
    stakeholderPoliticalGroups: 'Politiska grupper',
    stakeholderCivilSociety: 'Civilsamhället',
    stakeholderIndustry: 'Industri',
    stakeholderEuCitizens: 'EU-medborgare',
    stakeholderNationalGovernments: 'Nationella regeringar',
    stakeholderEuInstitutions: 'EU-institutioner',
    reasonEventsScheduled: '{count} parlamentarisk(a) händelse(r) planerad(e)',
    reasonDocumentsUnderReview: '{count} lagstiftningsdokument under granskning',
    reasonIndustryRegulatoryAgenda: 'Regleringsagendan kan påverka företagsmiljön',
    reasonCitizensDecisionsShapePolicy: 'Parlamentariska beslut formar EU-omfattande politik',
    reasonDocumentsRequireTransposition: '{count} dokument kan kräva nationell införlivning',
    reasonInstitutionsCoordination: 'Interinstitutionell samordning krävs',
  },
  da: {
    heading: 'Interessentanalyse',
    temperatureLabel: 'Politisk Temperatur',
    impactHeader: 'Indvirkning',
    stakeholderHeader: 'Interessent',
    reasonHeader: 'Begrundelse',
    tempLow: 'Lav',
    tempModerate: 'Moderat',
    tempHigh: 'Høj',
    tempVeryHigh: 'Meget høj',
    stakeholderPoliticalGroups: 'Politiske grupper',
    stakeholderCivilSociety: 'Civilsamfundet',
    stakeholderIndustry: 'Industri',
    stakeholderEuCitizens: 'EU-borgere',
    stakeholderNationalGovernments: 'Nationale regeringer',
    stakeholderEuInstitutions: 'EU-institutioner',
    reasonEventsScheduled: '{count} parlamentarisk(e) begivenhed(er) planlagt',
    reasonDocumentsUnderReview: '{count} lovgivningsdokument(er) under gennemgang',
    reasonIndustryRegulatoryAgenda: 'Reguleringsagendaen kan påvirke erhvervsmiljøet',
    reasonCitizensDecisionsShapePolicy: 'Parlamentariske beslutninger former EU-dækkende politik',
    reasonDocumentsRequireTransposition: '{count} dokument(er) kan kræve national gennemførelse',
    reasonInstitutionsCoordination: 'Tværinstitutionel koordinering påkrævet',
  },
  no: {
    heading: 'Interessentanalyse',
    temperatureLabel: 'Politisk temperatur',
    impactHeader: 'Innvirkning',
    stakeholderHeader: 'Interessent',
    reasonHeader: 'Begrunnelse',
    tempLow: 'Lav',
    tempModerate: 'Moderat',
    tempHigh: 'Høy',
    tempVeryHigh: 'Svært høy',
    stakeholderPoliticalGroups: 'Politiske grupper',
    stakeholderCivilSociety: 'Sivilsamfunnet',
    stakeholderIndustry: 'Industri',
    stakeholderEuCitizens: 'EU-borgere',
    stakeholderNationalGovernments: 'Nasjonale regjeringer',
    stakeholderEuInstitutions: 'EU-institusjoner',
    reasonEventsScheduled: '{count} parlamentarisk(e) hendelse(r) planlagt',
    reasonDocumentsUnderReview: '{count} lovgivningsdokument(er) under behandling',
    reasonIndustryRegulatoryAgenda: 'Reguleringsagendaen kan påvirke næringslivet',
    reasonCitizensDecisionsShapePolicy: 'Parlamentariske beslutninger former EU-politikk',
    reasonDocumentsRequireTransposition: '{count} dokument(er) kan kreve nasjonal gjennomføring',
    reasonInstitutionsCoordination: 'Tverrinstitusjonell koordinering nødvendig',
  },
  fi: {
    heading: 'Sidosryhmäanalyysi',
    temperatureLabel: 'Poliittinen Lämpötila',
    impactHeader: 'Vaikutus',
    stakeholderHeader: 'Sidosryhmä',
    reasonHeader: 'Perustelu',
    tempLow: 'Matala',
    tempModerate: 'Kohtalainen',
    tempHigh: 'Korkea',
    tempVeryHigh: 'Erittäin korkea',
    stakeholderPoliticalGroups: 'Poliittiset ryhmät',
    stakeholderCivilSociety: 'Kansalaisyhteiskunta',
    stakeholderIndustry: 'Teollisuus',
    stakeholderEuCitizens: 'EU-kansalaiset',
    stakeholderNationalGovernments: 'Kansalliset hallitukset',
    stakeholderEuInstitutions: 'EU-toimielimet',
    reasonEventsScheduled: '{count} parlamentaarista tapahtumaa ajoitettu',
    reasonDocumentsUnderReview: '{count} lainsäädäntöasiakirjaa käsittelyssä',
    reasonIndustryRegulatoryAgenda: 'Sääntelyohjelma voi vaikuttaa liiketoimintaympäristöön',
    reasonCitizensDecisionsShapePolicy:
      'Parlamentaariset päätökset muovaavat EU-laajuista politiikkaa',
    reasonDocumentsRequireTransposition:
      '{count} asiakirjaa voi edellyttää kansallista täytäntöönpanoa',
    reasonInstitutionsCoordination: 'Toimielinten välinen koordinointi tarpeen',
  },
  de: {
    heading: 'Stakeholder-Auswirkungsanalyse',
    temperatureLabel: 'Politische Temperatur',
    impactHeader: 'Auswirkung',
    stakeholderHeader: 'Stakeholder',
    reasonHeader: 'Begründung',
    tempLow: 'Niedrig',
    tempModerate: 'Mäßig',
    tempHigh: 'Hoch',
    tempVeryHigh: 'Sehr hoch',
    stakeholderPoliticalGroups: 'Politische Gruppen',
    stakeholderCivilSociety: 'Zivilgesellschaft',
    stakeholderIndustry: 'Industrie',
    stakeholderEuCitizens: 'EU-Bürger',
    stakeholderNationalGovernments: 'Nationale Regierungen',
    stakeholderEuInstitutions: 'EU-Institutionen',
    reasonEventsScheduled: '{count} parlamentarische(s) Ereignis(se) geplant',
    reasonDocumentsUnderReview: '{count} Gesetzgebungsdokument(e) in Prüfung',
    reasonIndustryRegulatoryAgenda: 'Regulierungsagenda kann Geschäftsumfeld beeinflussen',
    reasonCitizensDecisionsShapePolicy:
      'Parlamentarische Entscheidungen gestalten EU-weite Politik',
    reasonDocumentsRequireTransposition: '{count} Dokument(e) können nationale Umsetzung erfordern',
    reasonInstitutionsCoordination: 'Interinstitutionelle Koordinierung erforderlich',
  },
  fr: {
    heading: 'Analyse d\u2019Impact des Parties Prenantes',
    temperatureLabel: 'Température Politique',
    impactHeader: 'Impact',
    stakeholderHeader: 'Partie Prenante',
    reasonHeader: 'Raison',
    tempLow: 'Faible',
    tempModerate: 'Modéré',
    tempHigh: 'Élevé',
    tempVeryHigh: 'Très élevé',
    stakeholderPoliticalGroups: 'Groupes politiques',
    stakeholderCivilSociety: 'Société civile',
    stakeholderIndustry: 'Industrie',
    stakeholderEuCitizens: 'Citoyens de l\u2019UE',
    stakeholderNationalGovernments: 'Gouvernements nationaux',
    stakeholderEuInstitutions: 'Institutions de l\u2019UE',
    reasonEventsScheduled: '{count} événement(s) parlementaire(s) prévu(s)',
    reasonDocumentsUnderReview: '{count} document(s) législatif(s) en cours d\u2019examen',
    reasonIndustryRegulatoryAgenda:
      'L\u2019agenda réglementaire peut affecter l\u2019environnement commercial',
    reasonCitizensDecisionsShapePolicy:
      'Les décisions parlementaires façonnent la politique à l\u2019échelle de l\u2019UE',
    reasonDocumentsRequireTransposition:
      '{count} document(s) peuvent nécessiter une transposition nationale',
    reasonInstitutionsCoordination: 'Coordination interinstitutionnelle requise',
  },
  es: {
    heading: 'Análisis de Impacto en Partes Interesadas',
    temperatureLabel: 'Temperatura Política',
    impactHeader: 'Impacto',
    stakeholderHeader: 'Parte Interesada',
    reasonHeader: 'Razón',
    tempLow: 'Baja',
    tempModerate: 'Moderada',
    tempHigh: 'Alta',
    tempVeryHigh: 'Muy alta',
    stakeholderPoliticalGroups: 'Grupos políticos',
    stakeholderCivilSociety: 'Sociedad civil',
    stakeholderIndustry: 'Industria',
    stakeholderEuCitizens: 'Ciudadanos de la UE',
    stakeholderNationalGovernments: 'Gobiernos nacionales',
    stakeholderEuInstitutions: 'Instituciones de la UE',
    reasonEventsScheduled: '{count} evento(s) parlamentario(s) programado(s)',
    reasonDocumentsUnderReview: '{count} documento(s) legislativo(s) en revisión',
    reasonIndustryRegulatoryAgenda: 'La agenda regulatoria puede afectar el entorno empresarial',
    reasonCitizensDecisionsShapePolicy:
      'Las decisiones parlamentarias configuran la política a nivel de la UE',
    reasonDocumentsRequireTransposition:
      '{count} documento(s) pueden requerir transposición nacional',
    reasonInstitutionsCoordination: 'Se requiere coordinación interinstitucional',
  },
  nl: {
    heading: 'Stakeholder-Impactanalyse',
    temperatureLabel: 'Politieke Temperatuur',
    impactHeader: 'Impact',
    stakeholderHeader: 'Stakeholder',
    reasonHeader: 'Reden',
    tempLow: 'Laag',
    tempModerate: 'Gematigd',
    tempHigh: 'Hoog',
    tempVeryHigh: 'Zeer hoog',
    stakeholderPoliticalGroups: 'Politieke groepen',
    stakeholderCivilSociety: 'Maatschappelijk middenveld',
    stakeholderIndustry: 'Industrie',
    stakeholderEuCitizens: 'EU-burgers',
    stakeholderNationalGovernments: 'Nationale regeringen',
    stakeholderEuInstitutions: 'EU-instellingen',
    reasonEventsScheduled: '{count} parlementaire evenement(en) gepland',
    reasonDocumentsUnderReview: '{count} wetgevingsdocument(en) in behandeling',
    reasonIndustryRegulatoryAgenda: 'Regelgevingsagenda kan het bedrijfsklimaat beïnvloeden',
    reasonCitizensDecisionsShapePolicy: 'Parlementaire beslissingen vormen EU-breed beleid',
    reasonDocumentsRequireTransposition: '{count} document(en) kunnen nationale omzetting vereisen',
    reasonInstitutionsCoordination: 'Interinstitutionele coördinatie vereist',
  },
  ar: {
    heading: 'تحليل تأثير أصحاب المصلحة',
    temperatureLabel: 'الحرارة السياسية',
    impactHeader: 'التأثير',
    stakeholderHeader: 'صاحب المصلحة',
    reasonHeader: 'السبب',
    tempLow: 'منخفضة',
    tempModerate: 'معتدلة',
    tempHigh: 'مرتفعة',
    tempVeryHigh: 'مرتفعة جداً',
    stakeholderPoliticalGroups: 'المجموعات السياسية',
    stakeholderCivilSociety: 'المجتمع المدني',
    stakeholderIndustry: 'الصناعة',
    stakeholderEuCitizens: 'مواطنو الاتحاد الأوروبي',
    stakeholderNationalGovernments: 'الحكومات الوطنية',
    stakeholderEuInstitutions: 'مؤسسات الاتحاد الأوروبي',
    reasonEventsScheduled: '{count} حدث/أحداث برلمانية مجدولة',
    reasonDocumentsUnderReview: '{count} وثيقة/وثائق تشريعية قيد المراجعة',
    reasonIndustryRegulatoryAgenda: 'قد يؤثر جدول الأعمال التنظيمي على بيئة الأعمال',
    reasonCitizensDecisionsShapePolicy:
      'القرارات البرلمانية تشكل السياسة على مستوى الاتحاد الأوروبي',
    reasonDocumentsRequireTransposition: '{count} وثيقة/وثائق قد تتطلب نقلاً وطنياً',
    reasonInstitutionsCoordination: 'التنسيق بين المؤسسات مطلوب',
  },
  he: {
    heading: 'ניתוח השפעה על בעלי עניין',
    temperatureLabel: 'טמפרטורה פוליטית',
    impactHeader: 'השפעה',
    stakeholderHeader: 'בעל עניין',
    reasonHeader: 'סיבה',
    tempLow: 'נמוכה',
    tempModerate: 'מתונה',
    tempHigh: 'גבוהה',
    tempVeryHigh: 'גבוהה מאוד',
    stakeholderPoliticalGroups: 'קבוצות פוליטיות',
    stakeholderCivilSociety: 'חברה אזרחית',
    stakeholderIndustry: 'תעשייה',
    stakeholderEuCitizens: 'אזרחי האיחוד האירופי',
    stakeholderNationalGovernments: 'ממשלות לאומיות',
    stakeholderEuInstitutions: 'מוסדות האיחוד האירופי',
    reasonEventsScheduled: '{count} אירוע/ים פרלמנטרי/ים מתוכנן/ים',
    reasonDocumentsUnderReview: '{count} מסמך/ים חקיקתי/ים בבדיקה',
    reasonIndustryRegulatoryAgenda: 'סדר היום הרגולטורי עשוי להשפיע על סביבת העסקים',
    reasonCitizensDecisionsShapePolicy: 'החלטות פרלמנטריות מעצבות מדיניות ברחבי האיחוד האירופי',
    reasonDocumentsRequireTransposition: '{count} מסמך/ים עשויים לדרוש אימוץ לאומי',
    reasonInstitutionsCoordination: 'נדרש תיאום בין-מוסדי',
  },
  ja: {
    heading: 'ステークホルダー影響分析',
    temperatureLabel: '政治的温度',
    impactHeader: '影響度',
    stakeholderHeader: 'ステークホルダー',
    reasonHeader: '理由',
    tempLow: '低い',
    tempModerate: '中程度',
    tempHigh: '高い',
    tempVeryHigh: '非常に高い',
    stakeholderPoliticalGroups: '政治グループ',
    stakeholderCivilSociety: '市民社会',
    stakeholderIndustry: '産業界',
    stakeholderEuCitizens: 'EU市民',
    stakeholderNationalGovernments: '各国政府',
    stakeholderEuInstitutions: 'EU機関',
    reasonEventsScheduled: '{count}件の議会イベントが予定',
    reasonDocumentsUnderReview: '{count}件の立法文書が審査中',
    reasonIndustryRegulatoryAgenda: '規制アジェンダがビジネス環境に影響する可能性',
    reasonCitizensDecisionsShapePolicy: '議会の決定がEU全体の政策を形成',
    reasonDocumentsRequireTransposition: '{count}件の文書が国内法化を必要とする可能性',
    reasonInstitutionsCoordination: '機関間の調整が必要',
  },
  ko: {
    heading: '이해관계자 영향 분석',
    temperatureLabel: '정치적 온도',
    impactHeader: '영향',
    stakeholderHeader: '이해관계자',
    reasonHeader: '사유',
    tempLow: '낮음',
    tempModerate: '보통',
    tempHigh: '높음',
    tempVeryHigh: '매우 높음',
    stakeholderPoliticalGroups: '정치 그룹',
    stakeholderCivilSociety: '시민사회',
    stakeholderIndustry: '산업계',
    stakeholderEuCitizens: 'EU 시민',
    stakeholderNationalGovernments: '각국 정부',
    stakeholderEuInstitutions: 'EU 기관',
    reasonEventsScheduled: '{count}건의 의회 행사 예정',
    reasonDocumentsUnderReview: '{count}건의 입법 문서 검토 중',
    reasonIndustryRegulatoryAgenda: '규제 의제가 비즈니스 환경에 영향을 줄 수 있음',
    reasonCitizensDecisionsShapePolicy: '의회 결정이 EU 전체 정책을 형성',
    reasonDocumentsRequireTransposition: '{count}건의 문서가 국내 이행을 요구할 수 있음',
    reasonInstitutionsCoordination: '기관 간 조정 필요',
  },
  zh: {
    heading: '利益相关方影响分析',
    temperatureLabel: '政治温度',
    impactHeader: '影响',
    stakeholderHeader: '利益相关方',
    reasonHeader: '原因',
    tempLow: '低',
    tempModerate: '中等',
    tempHigh: '高',
    tempVeryHigh: '非常高',
    stakeholderPoliticalGroups: '政治团体',
    stakeholderCivilSociety: '公民社会',
    stakeholderIndustry: '产业界',
    stakeholderEuCitizens: '欧盟公民',
    stakeholderNationalGovernments: '各国政府',
    stakeholderEuInstitutions: '欧盟机构',
    reasonEventsScheduled: '{count}项议会活动已安排',
    reasonDocumentsUnderReview: '{count}份立法文件正在审查',
    reasonIndustryRegulatoryAgenda: '监管议程可能影响商业环境',
    reasonCitizensDecisionsShapePolicy: '议会决定塑造欧盟范围的政策',
    reasonDocumentsRequireTransposition: '{count}份文件可能需要国内转化',
    reasonInstitutionsCoordination: '需要机构间协调',
  },
};

/** Localized section heading strings for breaking news articles */
